In [414]:
import pandas as pd
import geopandas as gpd
from haversine import haversine
import numpy as np
import math
from datetime import timedelta
import itertools
from shapely.geometry import shape, Point
import random

# Reading city df and getting SP as test

In [ ]:
df_muns = gpd.read_file(r"municipios_2010-20240620T030303Z-001\municipios_2010")
df_sp = df_muns[df_muns['nome']=='São Paulo']

# Defining SP centroid
df_sp['centroid'] =df_sp.centroid

# Get the bounding box (minx, miny, maxx, maxy)
bounds = df_sp.geometry.bounds

# Extract longitude (x) and latitude (y)
center_lon = df_sp['centroid'].x
center_lat = df_sp['centroid'].y

# Extract min/max longitude and latitude
min_lon_sp = bounds.minx.values[0]
max_lon_sp = bounds.maxx.values[0]
min_lat_sp = bounds.miny.values[0]
max_lat_sp = bounds.maxy.values[0]

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\2239167489.py:5: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  df_sp['centroid'] =df_sp.centroid
C:\Users\EduardoMontez\anaconda3\envs\geo\Lib\site-packages\geopandas\geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

# Parameters

In [416]:
seed=1
np.random.seed(seed)  # Set the seed for reproducibility
num_samples = 1000  # Number of order samples
lambda_ = 5  # rate of occurence poisson distribution
long_mean = center_lon  # long center sp
lat_mean = center_lat  # lat center sp
max_lat = max_lat_sp
min_lat = min_lat_sp
max_lon = max_lon_sp
min_lon = min_lon_sp
long_stddev = 0.05  # Standard deviation of longitude distribution
lat_stddev = 0.05  # Standard deviation of the latitude distribution

# Generating timestamps following a Poisson Process

In [417]:
num_samples = 1000  # Number of order samples
lambda_ = 0.5  # rate of occurrence (lambda) for the Poisson process

# Generate random intervals between events following an exponential distribution
intervals = np.random.exponential(scale=1/lambda_, size=num_samples)

# Convert the intervals to timestamps starting from a given timestamp
start_timestamp = pd.Timestamp("2024-04-01 00:00:00")  # Define your start time
timestamps = [start_timestamp]
for interval in intervals:
    timestamps.append(timestamps[-1] + pd.Timedelta(minutes=interval))

# Remove the first element, which is the initial start time
timestamps = timestamps[1:]

In [418]:
def generate_normal_distribution(mean, std_dev, n, min_val=None, max_val=None):
    samples = np.random.normal(mean, std_dev, n)
    if min_val is not None or max_val is not None:
        samples = np.clip(samples, a_min=min_val, a_max=max_val)
    return samples.tolist()

# Generate samples for the first distribution
long_samples = generate_normal_distribution(long_mean, long_stddev, num_samples,min_val=min_lon,max_val=max_lon)

# Generate samples for the second distribution
lat_samples = generate_normal_distribution(lat_mean, lat_stddev, num_samples,min_val=min_lat,max_val=max_lat)

# Define the SLA time choices and their probabilities
sla_choices = [1, 2, 3]
sla_probs = [0.25, 0.5, 0.25]

# Randomly assign SLA hours to each order
sla_hours = np.random.choice(sla_choices, size=num_samples, p=sla_probs)

# Generate order weights from a normal distribution
order_weights = generate_normal_distribution(mean=7, std_dev=3, n=num_samples, min_val=0.01, max_val=20)

# Creating df_orders

In [419]:
df_orders = pd.DataFrame(columns=["order_id"])
df_orders['order_id'] = [i for i in range(1, num_samples+1)]
df_orders['order_longitude'] = long_samples
df_orders['order_latitude'] = lat_samples
df_orders['ordered_at_brt'] = timestamps
df_orders['sla_hours'] = sla_hours
df_orders['sla_max_delivery_time_brt'] = df_orders['ordered_at_brt'] + pd.to_timedelta(df_orders['sla_hours'], unit='h')
df_orders['order_weight'] = order_weights
df_orders

,order_id,order_longitude,order_latitude,ordered_at_brt,sla_hours,sla_max_delivery_time_brt,order_weight
0,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968
1,2,-46.664223,-23.565863,2024-04-01 00:03:37.647730832,1,2024-04-01 01:03:37.647730832,10.086003
2,3,-46.607296,-23.715624,2024-04-01 00:03:37.661456595,2,2024-04-01 02:03:37.661456595,2.240132
3,4,-46.608989,-23.576606,2024-04-01 00:04:20.862987177,1,2024-04-01 01:04:20.862987177,4.106139
4,5,-46.721215,-23.646482,2024-04-01 00:04:39.908138600,2,2024-04-01 02:04:39.908138600,3.509114
...,...,...,...,...,...,...,...
995,996,-46.601350,-23.659473,2024-04-02 08:58:13.839793951,2,2024-04-02 10:58:13.839793951,3.718150
996,997,-46.658821,-23.617170,2024-04-02 08:58:58.663961384,2,2024-04-02 10:58:58.663961384,3.636059
997,998,-46.606329,-23.730086,2024-04-02 09:01:11.266674428,1,2024-04-02 10:01:11.266674428,1.127828
998,999,-46.539990,-23.627175,2024-04-02 09:01:58.603856277,1,2024-04-02 10:01:58.603856277,4.962055
999,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094

# Generate Hub df

In [420]:
# Extract the geometry from the DataFrame
geometry = df_sp['geometry'].iloc[0]

# Define the bounding box of the geometry
min_x, min_y, max_x, max_y = geometry.bounds

# Method two to define hub location
#min_x, min_y, max_x, max_y = (-46.7726,-23.5413,-46.4986,-23.7456)


# Generate 20 random points within the geometry
latitude_values = []
longitude_values = []
for _ in range(20):
    while True:
        # Generate a random point within the bounding box
        random_point = Point(random.uniform(min_x, max_x), random.uniform(min_y, max_y))
        
        # Check if the random point is inside the geometry
        if geometry.contains(random_point):
            # Extract latitude and longitude values
            latitude_values.append(random_point.y)
            longitude_values.append(random_point.x)
            break

In [421]:
num_hubs = 15
# Generate samples for the first distribution
longitude_values = generate_normal_distribution(long_mean, long_stddev, num_hubs,min_val=min_lon,max_val=max_lon)

# Generate samples for the second distribution
latitude_values = generate_normal_distribution(lat_mean, lat_stddev, num_hubs,min_val=min_lat,max_val=max_lat)

In [422]:
n_hubs = 15
unique_hubs =  pd.DataFrame(columns=["hub_id", "hub_longitude", "hub_latitude"])
unique_hubs['hub_id'] = [i for i in range(1, n_hubs+1)]
unique_hubs['hub_longitude'] = longitude_values
unique_hubs['hub_latitude'] = latitude_values
unique_hubs

    hub_id  hub_longitude  hub_latitude
0        1     -46.628005    -23.712645
1        2     -46.512143    -23.655454
2        3     -46.575586    -23.615431
3        4     -46.700040    -23.571423
4        5     -46.655904    -23.672282
5        6     -46.576099    -23.725495
6        7     -46.611407    -23.620241
7        8     -46.636713    -23.600547
8        9     -46.703117    -23.652369
9       10     -46.654509    -23.618115
10      11     -46.762302    -23.557874
11      12     -46.577398    -23.668775
12      13     -46.613073    -23.618987
13      14     -46.616519    -23.625545
14      15     -46.659818    -23.615621

In [423]:
# Distância de haversine
def calculate_distance(row):
    order_coords = (row['order_latitude'], row['order_longitude'])
    hub_coords = (row['hub_latitude'], row['hub_longitude'])
    return haversine(order_coords, hub_coords)

def calculate_distance_order_with_order(row):
    order_coords = (row['order_latitude'], row['order_longitude'])
    order2_coords = (row['order_latitude_open_order'], row['order_longitude_open_order'])
    return haversine(order_coords, order2_coords)

def assign_route_id(df, hub_col, minutes_wait, max_orders_per_route,max_weight_per_route):
    # Ordena por hub e horário
    df = df.sort_values(by=[hub_col, 'ordered_at_brt']).copy()

    # Inicializa contador de rotas, contagem de pedidos por rota e pesos
    current_route_id = 0
    orders_count_per_route = {}
    total_weight_per_route = {}
    vehicle_type_per_route = {}

    # Inicializa dicionário para manter o horário do último pedido para cada hub
    last_order_time = {}

    # Itera nas linhas
    for index, row in df.iterrows():
        hub_id = row[hub_col]
        ordered_at = row['ordered_at_brt']
        order_weight = row['order_weight']

        # Verifica se é necessário iniciar uma nova rota
        new_route_needed = False

        if hub_id not in last_order_time or ordered_at > last_order_time[hub_id] + timedelta(minutes=minutes_wait):
            new_route_needed = True

        if not new_route_needed and orders_count_per_route[current_route_id] >= max_orders_per_route:
            new_route_needed = True

        if not new_route_needed:
            max_weight = max_weight_per_route
            if total_weight_per_route[current_route_id] + order_weight > max_weight:
                new_route_needed = True

        # Inicia uma nova rota se necessário
        if new_route_needed:
            current_route_id += 1
            last_order_time[hub_id] = ordered_at
            orders_count_per_route[current_route_id] = 0
            total_weight_per_route[current_route_id] = 0
            # Define o veículo com base no primeiro pedido

        # Atualiza as informações da rota atual
        df.at[index, 'route_id_moving_window'] = current_route_id
        orders_count_per_route[current_route_id] += 1
        total_weight_per_route[current_route_id] += order_weight

    return df.reset_index(drop=True)

def assign_route_id_fixed_window(df, hub_col, minutes_wait, max_orders_per_route,max_weight_per_route):
    # Ordena por hub e horário
    df = df.sort_values(by=[hub_col, 'ordered_at_brt']).copy()

    # Inicializa contador de rotas, contagem de pedidos por rota e pesos
    current_route_id = 0
    orders_count_per_route = {}
    total_weight_per_route = {}

    # Inicializa dicionário para manter o horário do final da janela fixa para cada hub
    last_route_time = {}

    # Itera nas linhas
    for index, row in df.iterrows():
        hub_id = row[hub_col]
        ordered_at = row['ordered_at_brt']
        order_weight = row['order_weight']

        # Define o início e o fim da janela fixa (alinhado ao intervalo de minutos)
        interval_start_time = ordered_at - timedelta(minutes=(ordered_at.minute % minutes_wait))
        interval_end_time = interval_start_time + timedelta(minutes=minutes_wait)

        # Verifica se uma nova rota precisa ser iniciada
        new_route_needed = False

        if hub_id not in last_route_time or ordered_at > last_route_time[hub_id]:
            new_route_needed = True
            last_route_time[hub_id] = interval_end_time

        if not new_route_needed and orders_count_per_route[current_route_id] >= max_orders_per_route:
            new_route_needed = True
            last_route_time[hub_id] = interval_end_time

        if not new_route_needed:
            max_weight = max_weight_per_route
            if total_weight_per_route[current_route_id] + order_weight > max_weight:
                new_route_needed = True
                last_route_time[hub_id] = interval_end_time

        # Inicia uma nova rota, se necessário
        if new_route_needed:
            current_route_id += 1
            orders_count_per_route[current_route_id] = 0
            total_weight_per_route[current_route_id] = 0
            # Define o veículo com base no peso do primeiro pedido

        # Atualiza as informações da rota atual
        df.at[index, 'route_id_fixed_interval'] = current_route_id
        orders_count_per_route[current_route_id] += 1
        total_weight_per_route[current_route_id] += order_weight

    return df.reset_index(drop=True)


def new_assign_route_id(df,hub_col,minutes_wait, max_orders_per_route):
    # ordena por hub e horário
    df = df.sort_values(by=[hub_col, 'ordered_at_brt'])

    # inicializa contador de rotas e contagem de orders por rota
    current_route_id = 0
    orders_count_per_route = {}

    # incicializa dicionário para manter a par horário do último pedido para cada hub
    last_order_time = {}

    # Itera nas linhas
    for index, row in df.iterrows():
        hub_id = row[hub_col]
        ordered_at = row['ordered_at_brt']

        # Checa se é a primeira order do dia para o hub ou se o horário do pedido excede o max da rota
        if hub_id not in last_order_time or ordered_at > last_order_time[hub_id] + timedelta(minutes=minutes_wait):
            current_route_id += 1
            last_order_time[hub_id] = ordered_at
            orders_count_per_route[current_route_id] = 0

        # Checa se o max de orders por rota foi atingido
        if orders_count_per_route[current_route_id] >= max_orders_per_route:
            current_route_id += 1
            last_order_time[hub_id] = ordered_at
            orders_count_per_route[current_route_id] = 0

        # Faz a atribuição do route_id para aquela row
        df.at[index, 'route_id_new_model'] = current_route_id
        orders_count_per_route[current_route_id] += 1

    return df.reset_index(drop=True)

import itertools

def filter_one_route(df_routes,route_id_col,hub_id_col,n_routes,route_id_counter):
    route = df_routes[df_routes[route_id_col]==route_id_counter].reset_index(drop=True).rename(columns={'order_id':'id','order_latitude':'latitude','order_longitude':'longitude'})
    route['id'] = route['id'].astype(str)
    route[hub_id_col] = route[hub_id_col].astype(str)

    # New row to add
    new_row = {route_id_col: route[route_id_col][0],
               'id': route[hub_id_col][0],
               'latitude': route['hub_latitude'][0],
               'longitude': route['hub_longitude'][0],
               hub_id_col: route[hub_id_col][0],
               'hub_latitude': route['hub_latitude'][0],
               'hub_longitude': route['hub_longitude'][0],           
               }

    # Create a DataFrame from the new row dictionary
    new_row_pd = pd.DataFrame([new_row])

    # Concatenate the new row DataFrame with the existing DataFrame
    route = pd.concat([new_row_pd, route]).reset_index(drop=True)
    return route
    
def get_distance_matrix(route_df):
    # Cria matriz de distâncias com zeros
    n = len(route_df)
    dist_matrix = np.zeros((n, n))

    # Itera para montar a matriz quadrada de distâncias (todos com todos)
    for i in range(n):
        for j in range(n):
            dist_matrix[i][j] = haversine((route_df['latitude'][i],route_df['longitude'][i]),
                                           (route_df['latitude'][j],route_df['longitude'][j]))

    return dist_matrix


def solve_tsp_nearest(distances):
    num_cities = len(distances)
    visited = [False] * num_cities
    tour = []
    total_distance = 0
    partial_distances = []  # List to store partial distances
    
    # Start at the first city
    current_city = 0
    tour.append(current_city)
    visited[current_city] = True
    
    # Repeat until all cities have been visited
    while len(tour) < num_cities:
        nearest_city = None
        nearest_distance = math.inf

        # Find the nearest unvisited city
        for city in range(num_cities):
            if not visited[city]:
                distance = distances[current_city][city]
                if distance < nearest_distance:
                    nearest_city = city
                    nearest_distance = distance
        
        # Move to the nearest city
        current_city = nearest_city
        tour.append(current_city)
        visited[current_city] = True
        total_distance += nearest_distance
        partial_distances.append(nearest_distance)  # Store the partial distance
    
    return tour, total_distance, partial_distances


def solve_tsp_brute_force_without_return(distances):
    num_cities = len(distances)
    cities = list(range(num_cities))
    min_distance = float('inf')
    optimal_tour = None
    partial_distances = []
    
    # Generate all permutations of cities
    for permutation in itertools.permutations(cities):
        tour_distance = 0
        partial_distance = []
        for i in range(num_cities - 1):
            tour_distance += distances[permutation[i]][permutation[i+1]]
            partial_distance.append(distances[permutation[i]][permutation[i+1]])
        
        # Check if the current permutation gives a shorter tour
        if tour_distance < min_distance:
            min_distance = tour_distance
            optimal_tour = list(permutation)
            partial_distances = partial_distance
        
    return optimal_tour, min_distance, partial_distances

def get_route_reindexed_df(route_df,route_id_col,tour,total_distances,partial_distances):
    route_reindex = route_df.reindex(index=route_df.index[tour]).drop([0]).reset_index(drop=True).rename(columns={'id':'order_id'})
    route_reindex['order_id_delivery_order'] = route_reindex.index+1
    route_reindex['route_total_distance'] = total_distance
    route_reindex['order_partial_distance'] = partial_distances
    route_reindex_final = route_reindex[[route_id_col,'order_id','order_id_delivery_order','route_total_distance','order_partial_distance']]
    return route_reindex_final

# Cross join orders and hubs

In [424]:
# Cross join dos DataFrames
df_final_order_hub = pd.merge(df_orders.assign(key=1), unique_hubs.assign(key=1), on='key').drop('key', axis=1)
df_final_order_hub

,order_id,order_longitude,order_latitude,ordered_at_brt,sla_hours,sla_max_delivery_time_brt,order_weight,hub_id,hub_longitude,hub_latitude
0,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968,1,-46.628005,-23.712645
1,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968,2,-46.512143,-23.655454
2,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968,3,-46.575586,-23.615431
3,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968,4,-46.700040,-23.571423
4,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968,5,-46.655904,-23.672282
...,...,...,...,...,...,...,...,...,...,...
14995,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094,11,-46.762302,-23.557874
14996,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094,12,-46.577398,-23.668775
14997,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094,13,-46.613073,-23.618987
14998,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094,14,-46.616519,-23.625545
14999,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094,15,-46.659818,-23.615621

In [425]:
df_final_order_hub['distance'] = df_final_order_hub.apply(calculate_distance, axis=1).round(2)
df_final_order_hub = df_final_order_hub.drop_duplicates(subset=['order_id','hub_id'])
df_final_order_hub

,order_id,order_longitude,order_latitude,ordered_at_brt,sla_hours,sla_max_delivery_time_brt,order_weight,hub_id,hub_longitude,hub_latitude,distance
0,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968,1,-46.628005,-23.712645,11.31
1,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968,2,-46.512143,-23.655454,11.24
2,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968,3,-46.575586,-23.615431,3.70
3,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968,4,-46.700040,-23.571423,10.07
4,1,-46.611735,-23.612023,2024-04-01 00:01:04.752700471,2,2024-04-01 02:01:04.752700471,8.331968,5,-46.655904,-23.672282,8.07
...,...,...,...,...,...,...,...,...,...,...,...
14995,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094,11,-46.762302,-23.557874,22.03
14996,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094,12,-46.577398,-23.668775,9.85
14997,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094,13,-46.613073,-23.618987,7.66
14998,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094,14,-46.616519,-23.625545,8.34
14999,1000,-46.548063,-23.584400,2024-04-02 09:04:57.323973383,2,2024-04-02 11:04:57.323973383,8.433094,15,-46.659818,-23.615621,11.90

# Allocating based on nearest hub

In [426]:
sorted_result = df_final_order_hub.sort_values(by=['distance','hub_id'],ascending=[True, False])
top_hubs = sorted_result.groupby(['order_id']).head(1).reset_index(drop=True)
top_hubs

,order_id,order_longitude,order_latitude,ordered_at_brt,sla_hours,sla_max_delivery_time_brt,order_weight,hub_id,hub_longitude,hub_latitude,distance
0,20,-46.659225,-23.615591,2024-04-01 00:22:28.750843212,3,2024-04-01 03:22:28.750843212,7.677302,15,-46.659818,-23.615621,0.06
1,602,-46.659587,-23.614084,2024-04-01 20:14:42.227964548,3,2024-04-01 23:14:42.227964548,11.230012,15,-46.659818,-23.615621,0.17
2,187,-46.657166,-23.671119,2024-04-01 05:58:53.910662138,2,2024-04-01 07:58:53.910662138,4.791629,5,-46.655904,-23.672282,0.18
3,997,-46.658821,-23.617170,2024-04-02 08:58:58.663961384,2,2024-04-02 10:58:58.663961384,3.636059,15,-46.659818,-23.615621,0.20
4,843,-46.618488,-23.625687,2024-04-02 03:56:33.098763940,1,2024-04-02 04:56:33.098763940,8.231306,14,-46.616519,-23.625545,0.20
...,...,...,...,...,...,...,...,...,...,...,...
995,437,-46.582368,-23.508028,2024-04-01 14:45:46.868245763,2,2024-04-01 16:45:46.868245763,0.899243,8,-46.636713,-23.600547,11.68
996,836,-46.476380,-23.554294,2024-04-02 03:50:36.488467610,2,2024-04-02 05:50:36.488467610,1.981767,2,-46.512143,-23.655454,11.82
997,666,-46.805681,-23.702693,2024-04-01 22:06:00.380049462,2,2024-04-02 00:06:00.380049462,5.111195,9,-46.703117,-23.652369,11.85
998,598,-46.702920,-23.463213,2024-04-01 20:08:57.171798136,1,2024-04-01 21:08:57.171798136,6.975383,4,-46.700040,-23.571423,12.04
999,735,-46.778877,-23.754643,2024-04-02 00:25:03.630238530,2,2024-04-02 02:25:03.630238530,11.696730,9,-46.703117,-23.652369,13.74

# Assigning both fixed window and moving window

In [427]:
hubs_with_moving_route =assign_route_id(top_hubs,'hub_id',30,4,20) 
hubs_with_both_routes = assign_route_id_fixed_window(hubs_with_moving_route,'hub_id',30,4,20)
hubs_with_both_routes

,order_id,order_longitude,order_latitude,ordered_at_brt,sla_hours,sla_max_delivery_time_brt,order_weight,hub_id,hub_longitude,hub_latitude,distance,route_id_moving_window,route_id_fixed_interval
0,3,-46.607296,-23.715624,2024-04-01 00:03:37.661456595,2,2024-04-01 02:03:37.661456595,2.240132,1,-46.628005,-23.712645,2.13,1.0,1.0
1,6,-46.655737,-23.739572,2024-04-01 00:04:51.534203198,3,2024-04-01 03:04:51.534203198,5.795681,1,-46.628005,-23.712645,4.12,1.0,1.0
2,18,-46.635742,-23.711039,2024-04-01 00:21:44.105305969,3,2024-04-01 03:21:44.105305969,3.578536,1,-46.628005,-23.712645,0.81,1.0,1.0
3,27,-46.701407,-23.732633,2024-04-01 00:44:34.473570777,3,2024-04-01 03:44:34.473570777,6.392867,1,-46.628005,-23.712645,7.80,2.0,2.0
4,28,-46.651847,-23.718389,2024-04-01 00:44:39.254116151,1,2024-04-01 01:44:39.254116151,5.822331,1,-46.628005,-23.712645,2.51,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,927,-46.669266,-23.611914,2024-04-02 06:55:21.973160720,1,2024-04-02 07:55:21.973160720,5.893437,15,-46.659818,-23.615621,1.05,576.0,660.0
996,945,-46.666616,-23.616746,2024-04-02 07:20:38.978320443,2,2024-04-02 09:20:38.978320443,10.730955,15,-46.659818,-23.615621,0.70,576.0,661.0
997,965,-46.662569,-23.616411,2024-04-02 07:56:21.687656360,2,2024-04-02 09:56:21.687656360,8.351173,15,-46.659818,-23.615621,0.29,577.0,662.0
998,986,-46.680794,-23.634527,2024-04-02 08:31:06.218722203,3,2024-04-02 11:31:06.218722203,8.009104,15,-46.659818,-23.615621,3.00,578.0,663.0
999,997,-46.658821,-23.617170,2024-04-02 08:58:58.663961384,2,2024-04-02 10:58:58.663961384,3.636059,15,-46.659818,-23.615621,0.20,578.0,663.0

In [428]:
hubs_with_both_routes['route_id_moving_window'].nunique(),hubs_with_both_routes['route_id_fixed_interval'].nunique()

(578, 663)

In [429]:
hubs_with_both_routes.head(20)

,order_id,order_longitude,order_latitude,ordered_at_brt,sla_hours,sla_max_delivery_time_brt,order_weight,hub_id,hub_longitude,hub_latitude,distance,route_id_moving_window,route_id_fixed_interval
0,3,-46.607296,-23.715624,2024-04-01 00:03:37.661456595,2,2024-04-01 02:03:37.661456595,2.240132,1,-46.628005,-23.712645,2.13,1.0,1.0
1,6,-46.655737,-23.739572,2024-04-01 00:04:51.534203198,3,2024-04-01 03:04:51.534203198,5.795681,1,-46.628005,-23.712645,4.12,1.0,1.0
2,18,-46.635742,-23.711039,2024-04-01 00:21:44.105305969,3,2024-04-01 03:21:44.105305969,3.578536,1,-46.628005,-23.712645,0.81,1.0,1.0
3,27,-46.701407,-23.732633,2024-04-01 00:44:34.473570777,3,2024-04-01 03:44:34.473570777,6.392867,1,-46.628005,-23.712645,7.80,2.0,2.0
4,28,-46.651847,-23.718389,2024-04-01 00:44:39.254116151,1,2024-04-01 01:44:39.254116151,5.822331,1,-46.628005,-23.712645,2.51,2.0,2.0
5,29,-46.619365,-23.682018,2024-04-01 00:45:01.589150384,3,2024-04-01 03:45:01.589150384,13.439207,1,-46.628005,-23.712645,3.52,3.0,3.0
6,35,-46.649854,-23.701948,2024-04-01 01:00:44.976652065,1,2024-04-01 02:00:44.976652065,7.095774,1,-46.628005,-23.712645,2.52,4.0,4.0
7,68,-46.666476,-23.740190,2024-04-01 01:54:40.373012470,3,2024-04-01 04:54:40.373012470,7.579177,1,-46.628005,-23.712645,4.97,5.0,5.0
8,69,-46.634731,-23.698523,2024-04-01 02:00:27.542736370,3,2024-04-01 05:00:27.542736370,7.834239,1,-46.628005,-23.712645,1.71,5.0,5.0
9,78,-46.615497,-23.678827,2024-04-01 02:18:16.111791507,1,2024-04-01 03:18:16.111791507,8.473382,1,-46.628005,-23.712645,3.97,6.0,6.0
10,79,-46.617685,-23.727808,2024-04-01 02:21:02.857558852,3,2024-04-01 05:21:02.857558852,6.779940,1,-46.628005,-23.712645,1.99,6.0,6.0
11,86,-46.643975,-23.724258,2024-04-01 02:38:40.796649436,2,2024-04-01 04:38:40.796649436,6.571014,1,-46.628005,-23.712645,2.08,7.0,7.0
12,97,-46.725648,-23.750164,2024-04-01 03:06:01.009536767,1,2024-04-01 04:06:01.009536767,7.952866,1,-46.628005,-23.712645,10.78,7.0,8.0
13,104,-46.637794,-23.738414,2024-04-01 03:17:09.755309755,2,2024-04-01 05:17:09.755309755,10.316006,1,-46.628005,-23.712645,3.03,8.0,8.0
14,112,-46.670639,-23.712823,2024-04-01 03:44:06.059449507,1,2024-04-01 04:44:06.059449507,6.357911,1,-46.628005,-23.712645,4.34,8.0,9.0
15,117,-46.610243,-23.698408,2024-04-01 03:57:38.345922245,2,2024-04-01 05:57:38.345922245,8.242702,1,-46.628005,-23.712645,2.40,9.0,9.0
16,137,-46.659351,-23.710874,2024-04-01 04:35:24.978869265,3,2024-04-01 07:35:24.978869265,7.915086,1,-46.628005,-23.712645,3.20,10.0,10.0
17,144,-46.658500,-23.719599,2024-04-01 04:45:25.904052295,2,2024-04-01 06:45:25.904052295,5.734863,1,-46.628005,-23.712645,3.20,10.0,10.0
18,158,-46.669187,-23.715323,2024-04-01 05:05:01.708407503,1,2024-04-01 06:05:01.708407503,8.756478,1,-46.628005,-23.712645,4.20,11.0,11.0
19,160,-46.628396,-23.748379,2024-04-01 05:15:47.719222819,3,2024-04-01 08:15:47.719222819,2.310889,1,-46.628005,-23.712645,3.97,11.0,11.0

# Allocating based on open routes

In [430]:
sample_pedidos = sorted_result.sort_values(by=['ordered_at_brt']).drop_duplicates(subset=['order_id']).tail(50)[['order_id','order_latitude','order_longitude','ordered_at_brt','order_weight','sla_max_delivery_time_brt']].drop_duplicates(subset=['order_id']).sort_values(by=['ordered_at_brt']).reset_index(drop=True)
sample_pedidos

,order_id,order_latitude,order_longitude,ordered_at_brt,order_weight,sla_max_delivery_time_brt
0,951,-23.686146,-46.537221,2024-04-02 07:26:45.300383789,10.268791,2024-04-02 08:26:45.300383789
1,952,-23.646501,-46.606689,2024-04-02 07:28:54.526566598,6.577929,2024-04-02 09:28:54.526566598
2,953,-23.545738,-46.696081,2024-04-02 07:29:03.353611575,10.551756,2024-04-02 10:29:03.353611575
3,954,-23.626359,-46.719364,2024-04-02 07:29:23.224069074,11.665605,2024-04-02 09:29:23.224069074
4,955,-23.620569,-46.582671,2024-04-02 07:29:25.229845086,13.146954,2024-04-02 09:29:25.229845086
5,956,-23.702035,-46.632177,2024-04-02 07:29:39.726866140,9.057804,2024-04-02 08:29:39.726866140
6,957,-23.677769,-46.678536,2024-04-02 07:31:46.320560591,8.322078,2024-04-02 08:31:46.320560591
7,958,-23.666099,-46.700821,2024-04-02 07:32:48.152185839,8.644178,2024-04-02 08:32:48.152185839
8,959,-23.692159,-46.688399,2024-04-02 07:33:34.612934615,6.744110,2024-04-02 08:33:34.612934615
9,960,-23.710680,-46.586342,2024-04-02 07:35:12.562491656,7.094357,2024-04-02 10:35:12.562491656
10,961,-23.728514,-46.649131,2024-04-02 07:45:16.149162823,7.056997,2024-04-02 10:45:16.149162823
11,962,-23.660619,-46.718036,2024-04-02 07:48:51.993474965,5.501054,2024-04-02 08:48:51.993474965
12,963,-23.608584,-46.604384,2024-04-02 07:51:16.319579025,6.981411,2024-04-02 09:51:16.319579025
13,964,-23.619386,-46.632508,2024-04-02 07:56:16.822923892,6.521095,2024-04-02 09:56:16.822923892
14,965,-23.616411,-46.662569,2024-04-02 07:56:21.687656360,8.351173,2024-04-02 09:56:21.687656360
15,966,-23.604621,-46.617627,2024-04-02 07:56:30.439171939,6.638503,2024-04-02 09:56:30.439171939
16,967,-23.693166,-46.689397,2024-04-02 07:57:47.535094875,8.156696,2024-04-02 09:57:47.535094875
17,968,-23.684389,-46.599818,2024-04-02 07:58:39.075434787,8.368279,2024-04-02 08:58:39.075434787
18,969,-23.662005,-46.719256,2024-04-02 08:04:11.310982480,7.851197,2024-04-02 10:04:11.310982480
19,970,-23.694788,-46.693185,2024-04-02 08:05:32.010010421,14.096804,2024-04-02 09:05:32.010010421
20,971,-23.637742,-46.716857,2024-04-02 08:07:05.101963557,9.948052,2024-04-02 11:07:05.101963557
21,972,-23.683383,-46.668841,2024-04-02 08:11:35.855285389,2.253118,2024-04-02 10:11:35.855285389
22,973,-23.594528,-46.685885,2024-04-02 08:12:46.863790408,3.194231,2024-04-02 09:12:46.863790408
23,974,-23.694118,-46.666145,2024-04-02 08:16:58.365856439,9.829610,2024-04-02 10:16:58.365856439
24,975,-23.622098,-46.647774,2024-04-02 08:17:33.462157824,10.288049,2024-04-02 09:17:33.462157824
25,976,-23.566287,-46.620300,2024-04-02 08:18:11.855339786,6.110959,2024-04-02 09:18:11.855339786
26,977,-23.710987,-46.640686,2024-04-02 08:18:59.619523704,7.685111,2024-04-02 10:18:59.619523704
27,978,-23.677791,-46.635420,2024-04-02 08:20:34.792670921,6.864422,2024-04-02 11:20:34.792670921
28,979,-23.688633,-46.567797,2024-04-02 08:21:04.627831673,6.490096,2024-04-02 10:21:04.627831673
29,980,-23.703239,-46.661337,2024-04-02 08:23:18.188173811,9.308653,2024-04-02 10:23:18.188173811
30,981,-23.637191,-46.720930,2024-04-02 08:23:36.677315315,4.034446,2024-04-02 10:23:36.677315315
31,982,-23.625209,-46.600444,2024-04-02 08:23:48.536514193,4.852462,2024-04-02 10:23:48.536514193
32,983,-23.686866,-46.556219,2024-04-02 08:27:53.540140774,9.065069,2024-04-02 11:27:53.540140774
33,984,-23.675849,-46.638648,2024-04-02 08:28:25.979162768,4.830992,2024-04-02 09:28:25.979162768
34,985,-23.638105,-46.606036,2024-04-02 08:29:24.511188783,7.096745,2024-04-02 10:29:24.511188783
35,986,-23.634527,-46.680794,2024-04-02 08:31:06.218722203,8.009104,2024-04-02 11:31:06.218722203
36,987,-23.705794,-46.638729,2024-04-02 08:32:35.754353357,0.971960,2024-04-02 10:32:35.754353357
37,988,-23.535144,-46.616162,2024-04-02 08:32:45.242639504,9.139321,2024-04-02 09:32:45.242639504
38,989,-23.661897,-46.629084,2024-04-02 08:36:53.939442791,6.993411,2024-04-02 09:36:53.939442791
39,990,-23.645819,-46.674998,2024-04-02 08:42:56.184227702,12.684295,2024-04-02 10:42:56.184227702
40,991,-23.681629,-46.566481,2024-04-02 08:46:17.066074493,14.496830,2024-04-02 09:46:17.066074493
41,992,-23.663160,-46.639372,2024-04-02 08:46:57.121880510,2.405048,2024-04-02 11:46:57.121880510
42,993,-23.695440,-46.601503,2024-04-02 08:48:27.176091898,7.087706,2024-04-02 10:48:27.176091898
43,994,-23.568813,-46.627724,2024-04-02 08:49:16.931941828,5.667831,2024-04-02 10:49:16.931941828
44,995,-23.742585,-46.604329,2024-04-02 08:50:54.003981020,6.632764,2024-04-02 10:50:54.003981020
45,996,-23.659473,-46.601350,2024-04-02 08:58:13.839793951,3.718150,2024-04-02 10:58:13.839793951
46,997,-23.617170,-46.658821,2024-04-02 08:58:58.663961384,3.636059,2024-04-02 10:58:58.663961384
47,998,-23.730086,-46.606329,2024-04-02 09:01:11.266674428,1.127828,2024-04-02 10:01:11.266674428
48,999,-23.627175,-46.539990,2024-04-02 09:01:58.603856277,4.962055,2024-04-02 10:01:58.603856277
49,1000,-23.584400,-46.548063,2024-04-02 09:04:57.323973383,8.433094,2024-04-02 11:04:57.323973383

In [431]:
df_pedidos = sorted_result.sort_values(by=['ordered_at_brt']).drop_duplicates(subset=['order_id'])[['order_id','order_latitude','order_longitude','ordered_at_brt','order_weight','sla_max_delivery_time_brt']].drop_duplicates(subset=['order_id']).sort_values(by=['ordered_at_brt']).reset_index(drop=True)
df = df_pedidos

#df = sample_pedidos

In [432]:
km_correct = 2
minutes_wait = 30
order_allocated_hub = pd.DataFrame(columns=['route_id','order_id','hub_id'])
open_routes = pd.DataFrame(columns=['route_id','order_id_waiting','order_latitude_open_order','order_longitude_open_order','hub_id_waiting','waiting_ordered_at_brt','order_waiting_weight','max_time_order','max_time_route','max_weight_route'])
route_id_count = 0

In [433]:
for i in range(len(df)):
    print(df.order_id[i])
    print(df[df.index==i])
    time_of_current_order = df[df.index==i]['ordered_at_brt'][i]
    open_routes['route_id_orders'] = open_routes.groupby(['route_id'])['order_id_waiting'].transform('count')    
    open_routes['max_time_route'] = open_routes.groupby(['order_id_waiting', 'route_id'])['max_time_route'].transform('min')
    open_routes['max_weight_route'] = 20
    open_routes['route_weight'] = open_routes.groupby(['route_id'])['order_waiting_weight'].transform('sum')
    open_routes = open_routes[(open_routes['max_time_route']>time_of_current_order)&(open_routes['route_id_orders']<4)] # São os que de fato ainda estão em aberto e as rotas não fechadas
    print(time_of_current_order)    
    if not open_routes.empty:
        print('tem rota aberta')
        pedido = df[df.index==i]
        orders_hub = open_routes.groupby(['hub_id_waiting']).agg(orders_hub_waiting=('order_id_waiting','count')).reset_index(drop=False)    
        distances_order_hub_df = pd.merge(pedido.assign(key=1), unique_hubs.assign(key=1), on='key').drop('key', axis=1)
        distances_order_hub_df['distance'] = distances_order_hub_df.apply(calculate_distance, axis=1)
        distances_order_hub_df_filtered =distances_order_hub_df.merge(orders_hub,left_on='hub_id',right_on='hub_id_waiting',how='left').fillna(0).sort_values(by=['distance']).reset_index(drop=True)
        distances_order_order_df = pd.merge(pedido.assign(key=1), open_routes.assign(key=1), on='key').drop('key', axis=1)
        distances_order_order_df['distance_order_to_order'] = distances_order_order_df.apply(calculate_distance_order_with_order, axis=1)
        distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
        distance_order_to_order_filtered = distance_order_to_order[distance_order_to_order['orders_hub_waiting']<4].sort_values(by=['distance_order_to_order']).reset_index(drop=True)
        
        print('dist order to order é ',distance_order_to_order_filtered['distance_order_to_order'][0],'hub em questão',distance_order_to_order_filtered['hub_id_waiting'][0])
        print('dist order to hub é ',distances_order_hub_df_filtered['distance'][0],'hub em questão',distances_order_hub_df_filtered['hub_id'][0])        
        if distance_order_to_order_filtered['distance_order_to_order'][0] <= distances_order_hub_df_filtered['distance'][0]+km_correct: # vamos alocar em uma rota existente
            print('distancia pro pedido menor que distancia pro hub +',km_correct,"km")
            print('hub alocado',(distance_order_to_order_filtered['hub_id_waiting'][0]),2)
            chosen_route = distance_order_to_order_filtered['route_id'][0]
            print('route_id',chosen_route)
            new_row_open_routes = [{'route_id':chosen_route,
                                    'order_id_waiting':distances_order_hub_df_filtered['order_id'][0],
                                    'order_latitude_open_order':distances_order_hub_df_filtered['order_latitude'][0],
                                    'order_longitude_open_order':distances_order_hub_df_filtered['order_longitude'][0],
                                    'hub_id_waiting':distance_order_to_order_filtered['hub_id_waiting'][0],
                                    'waiting_ordered_at_brt':distances_order_hub_df_filtered['ordered_at_brt'][0],
                                    'order_waiting_weight':distances_order_hub_df_filtered['order_weight'][0],
                                    'max_time_order':distances_order_hub_df_filtered['ordered_at_brt'][0]+timedelta(minutes=minutes_wait),
                                    'max_time_route':distance_order_to_order_filtered['max_time_route'][0]}]
            open_routes = pd.concat([open_routes, pd.DataFrame(new_row_open_routes)], ignore_index=True)
            new_row_order_allocated_hub = [{'route_id':chosen_route,'order_id': distances_order_hub_df_filtered['order_id'][0], 'hub_id': distance_order_to_order_filtered['hub_id_waiting'][0]}]
            order_allocated_hub = pd.concat([order_allocated_hub, pd.DataFrame(new_row_order_allocated_hub)], ignore_index=True)

        else:
            print('distancia pro pedido maior que distancia pro hub +',km_correct,"km")
            print('hub alocado',distances_order_hub_df_filtered['hub_id'][0])            
            print('hub_order',distance_order_to_order_filtered['hub_id_waiting'][0]) 
            hub_allocated = distances_order_hub_df_filtered['hub_id'][0]
            # Existe rota ja aberta nesse hub?
            try:
                print('passou aqui1')
                chosen_route = open_routes[open_routes.hub_id_waiting==hub_allocated]['route_id'].reset_index(drop=True)[0]
                print('rota em aberto, route_id: ',chosen_route)
                print('rota_escolhida:',chosen_route)
                print('orders no hub:',len(open_routes[open_routes.route_id==chosen_route]))
                if len(open_routes[open_routes.route_id==chosen_route])>=4: #inicia nova rota
                    print('passou aqui2')
                    chosen_route = max(order_allocated_hub['route_id']) + 1 
                    route_id_count = max(order_allocated_hub['route_id']) + 1
                    print('route_id',existing_route)
                    print('caiu aqui')
                    new_row_open_routes = [{'route_id':chosen_route,
                                            'order_id_waiting':distances_order_hub_df_filtered['order_id'][0] ,
                                            'order_latitude_open_order':distances_order_hub_df_filtered['order_latitude'][0] ,
                                            'order_longitude_open_order':distances_order_hub_df_filtered['order_longitude'][0],
                                            'hub_id_waiting':distances_order_hub_df_filtered['hub_id'][0],
                                            'waiting_ordered_at_brt':distances_order_hub_df_filtered['ordered_at_brt'][0],
                                            'order_waiting_weight':distances_order_hub_df_filtered['order_weight'][0],
                                            'max_time_order':distances_order_hub_df_filtered['ordered_at_brt'][0]+timedelta(minutes=minutes_wait),
                                            'max_time_route':distances_order_hub_df_filtered['ordered_at_brt'][0]+timedelta(minutes=minutes_wait)}]
                    open_routes = pd.concat([open_routes, pd.DataFrame(new_row_open_routes)], ignore_index=True)
                    new_row_order_allocated_hub = [{'route_id':chosen_route,'order_id': distances_order_hub_df_filtered['order_id'][0], 'hub_id':distances_order_hub_df_filtered['hub_id'][0] }]
                    order_allocated_hub = pd.concat([order_allocated_hub, pd.DataFrame(new_row_order_allocated_hub)], ignore_index=True)
                else:
                    print('passou aqui3')
                    new_row_open_routes = [{'route_id':chosen_route,
                                            'order_id_waiting':distances_order_hub_df_filtered['order_id'][0] ,
                                            'order_latitude_open_order':distances_order_hub_df_filtered['order_latitude'][0] ,
                                            'order_longitude_open_order':distances_order_hub_df_filtered['order_longitude'][0],
                                            'hub_id_waiting':distances_order_hub_df_filtered['hub_id'][0],
                                            'waiting_ordered_at_brt':distances_order_hub_df_filtered['ordered_at_brt'][0],
                                            'order_waiting_weight':distances_order_hub_df_filtered['order_weight'][0],
                                            'max_time_order':distances_order_hub_df_filtered['ordered_at_brt'][0]+timedelta(minutes=minutes_wait),
                                            'max_time_route':open_routes[open_routes['route_id']==chosen_route].reset_index()['max_time_route'][0]}]
                    open_routes = pd.concat([open_routes, pd.DataFrame(new_row_open_routes)], ignore_index=True)
                    new_row_order_allocated_hub = [{'route_id':chosen_route,'order_id': distances_order_hub_df_filtered['order_id'][0], 'hub_id':distances_order_hub_df_filtered['hub_id'][0]}]
                    order_allocated_hub = pd.concat([order_allocated_hub, pd.DataFrame(new_row_order_allocated_hub)], ignore_index=True)
                    print('passou aqui4')
            except: #Nãio tem rota aberta nesse pdv
                print('passou aqui5')
                route_id_count = max(order_allocated_hub['route_id']) + 1
                print('route_id',route_id_count)
                print('caiu aqui tb')
                new_row_open_routes = [{'route_id':route_id_count, #iniciando nova rota
                                        'order_id_waiting':distances_order_hub_df_filtered['order_id'][0] ,
                                        'order_latitude_open_order':distances_order_hub_df_filtered['order_latitude'][0] ,
                                        'order_longitude_open_order':distances_order_hub_df_filtered['order_longitude'][0],
                                        'hub_id_waiting':distances_order_hub_df_filtered['hub_id'][0],
                                        'waiting_ordered_at_brt':distances_order_hub_df_filtered['ordered_at_brt'][0],
                                        'order_waiting_weight':distances_order_hub_df_filtered['order_weight'][0],
                                        'max_time_order':distances_order_hub_df_filtered['ordered_at_brt'][0]+timedelta(minutes=minutes_wait),
                                        'max_time_route':distance_order_to_order_filtered['ordered_at_brt'][0]+timedelta(minutes=minutes_wait)}]
                open_routes = pd.concat([open_routes, pd.DataFrame(new_row_open_routes)], ignore_index=True)
                new_row_order_allocated_hub = [{'route_id':route_id_count,'order_id': distances_order_hub_df_filtered['order_id'][0], 'hub_id':distances_order_hub_df_filtered['hub_id'][0] }]
                order_allocated_hub = pd.concat([order_allocated_hub, pd.DataFrame(new_row_order_allocated_hub)], ignore_index=True)

    else:
        if i==0:
            route_id_count = route_id_count + 1
        else:            
            route_id_count = max(order_allocated_hub['route_id']) + 1
        print('não tem rota aberta')
        print('route_id',route_id_count)
        pedido = df[df.index==i]
        distances_order_hub_df = pd.merge(pedido.assign(key=1), unique_hubs.assign(key=1), on='key').drop('key', axis=1)
        distances_order_hub_df['distance'] = distances_order_hub_df.apply(calculate_distance, axis=1)
        distances_order_hub_df = distances_order_hub_df.sort_values(by=['distance']).reset_index(drop=True)
        print('dist pro hub mais próximo é',round(distances_order_hub_df['distance'][0],2))
        print('hub alocado',distances_order_hub_df['hub_id'][0])
        new_row_open_routes = [{'route_id':route_id_count,
                                'order_id_waiting':distances_order_hub_df['order_id'][0] ,
                                'order_latitude_open_order':distances_order_hub_df['order_latitude'][0] ,
                                'order_longitude_open_order':distances_order_hub_df['order_longitude'][0],
                                'hub_id_waiting':distances_order_hub_df['hub_id'][0],
                                'waiting_ordered_at_brt':distances_order_hub_df['ordered_at_brt'][0],
                                'order_waiting_weight':distances_order_hub_df['order_weight'][0],
                                'max_time_order':distances_order_hub_df['ordered_at_brt'][0]+timedelta(minutes=minutes_wait),
                                'max_time_route':distances_order_hub_df['ordered_at_brt'][0]+timedelta(minutes=minutes_wait)},                              ]
        open_routes = pd.concat([open_routes, pd.DataFrame(new_row_open_routes)], ignore_index=True)
        new_row_order_allocated_hub = [{'route_id':route_id_count,'order_id': distances_order_hub_df['order_id'][0], 'hub_id':distances_order_hub_df['hub_id'][0] }]
        order_allocated_hub = pd.concat([order_allocated_hub, pd.DataFrame(new_row_order_allocated_hub)], ignore_index=True)

1
   order_id  order_latitude  order_longitude                ordered_at_brt  \
0         1      -23.612023       -46.611735 2024-04-01 00:01:04.752700471

   order_weight     sla_max_delivery_time_brt
0      8.331968 2024-04-01 02:01:04.752700471
2024-04-01 00:01:04.752700471
não tem rota aberta
route_id 1
dist pro hub mais próximo é 0.79
hub alocado 13
2
   order_id  order_latitude  order_longitude                ordered_at_brt  \
1         2      -23.565863       -46.664223 2024-04-01 00:03:37.647730832

   order_weight     sla_max_delivery_time_brt
1     10.086003 2024-04-01 01:03:37.647730832
2024-04-01 00:03:37.647730832
tem rota aberta
dist order to order é  7.413133443835677 hub em questão 13
dist order to hub é  3.7024245986023563 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 13
passou aqui1
passou aqui5
route_id 2
caiu aqui tb
3
   order_id  order_latitude  order_longitude                ordered_at_brt  \
2         3      -23.715624       -46.607296 2024-04-01 00:03:37.661456595

   order_weight     sla_max_delivery_time_brt
2      2.240132 2024-04-01 02:03:37.661456595
2024-04-01 00:03:37.661456595
tem rota aberta
dist order to order é  11.528751424703673 hub em questão 13
dist order to hub é  2.134217462566802 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 13
passou aqui1
passou aqui5
route_id 3
caiu aqui tb
4
   order_id  order_latitude  order_longitude                ordered_at_brt  \
3         4      -23.576606       -46.608989 2024-04-01 00:04:20.862987177

   order_weight     sla_max_delivery_time_brt
3      4.106139 2024-04-01 01:04:20.862987177
2024-04-01 00:04:20.862987177
tem rota aberta
dist order to order é  3.948206696280916 hub em questão 13
dist order to hub é  3.8818090411200203 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 1
5
   order_id  order_latitude  order_longitude                ordered_at_brt  \
4         5      -23.646482       -46.721215 2024-04-01 00:04:39.908138600

   order_weight     sla_max_delivery_time_brt
4      3.509114 2024-04-01 02:04:39.908138600
2024-04-01 00:04:39.908138600
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:128: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  open_routes = pd.concat([open_routes, pd.DataFrame(new_row_open_routes)], ignore_index=True)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  10.680916927202906 hub em questão 4
dist order to hub é  1.9562549812443975 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 4
passou aqui1
passou aqui5
route_id 4
caiu aqui tb
6
   order_id  order_latitude  order_longitude                ordered_at_brt  \
5         6      -23.739572       -46.655737 2024-04-01 00:04:51.534203198

   order_weight     sla_max_delivery_time_brt
5      5.795681 2024-04-01 03:04:51.534203198
2024-04-01 00:04:51.534203198
tem rota aberta
dist order to order é  5.60423473977609 hub em questão 1
dist order to hub é  4.115191264753022 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 3
7
   order_id  order_latitude  order_longitude                ordered_at_brt  \
6         7      -23.641965       -46.652634 2024-04-01 00:05:16.267959287

   order_weight     sla_max_delivery_time_brt
6     11.068059 2024-04-01 01:05:16.267959287
2024-04-01 00:05:16.267959287
tem rota aberta
dist order to order é  5.333368044540868 hub em questão 13
dist order to hub é  2.658890550269822 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 13
passou aqui1
passou aqui5
route_id 5
caiu aqui tb
8
   order_id  order_latitude  order_longitude                ordered_at_brt  \
7         8      -23.601411       -46.659907 2024-04-01 00:06:07.145137103

   order_weight     sla_max_delivery_time_brt
7      6.711525 2024-04-01 02:06:07.145137103
2024-04-01 00:06:07.145137103
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.97715723904327 hub em questão 4
dist order to hub é  1.5801261587143738 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 4
passou aqui1
passou aqui5
route_id 6
caiu aqui tb
9
   order_id  order_latitude  order_longitude                ordered_at_brt  \
8         9      -23.685027       -46.685796 2024-04-01 00:07:07.799442108

   order_weight     sla_max_delivery_time_brt
8     10.885753 2024-04-01 01:07:07.799442108
2024-04-01 00:07:07.799442108
tem rota aberta
dist order to order é  5.602003675897812 hub em questão 9
dist order to hub é  3.3576903835662137 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 9
passou aqui1
passou aqui5
route_id 7
caiu aqui tb
10
   order_id  order_latitude  order_longitude                ordered_at_brt  \
9        10      -23.553369       -46.555441 2024-04-01 00:08:40.674615091

   order_weight     sla_max_delivery_time_brt
9      6.110153 2024-04-01 02:08:40.674615091
2024-04-01 00:08:40.674615091
tem rota aberta
dist order to order é  6.0384898132927365 hub em questão 13
dist order to hub é  7.199839669770902 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 1
11
    order_id  order_latitude  order_longitude                ordered_at_brt  \
10        11      -23.582764       -46.637558 2024-04-01 00:09:45.875339565

    order_weight     sla_max_delivery_time_brt
10     10.504864 2024-04-01 01:09:45.875339565
2024-04-01 00:09:45.875339565
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.990903908200463 hub em questão 13
dist order to hub é  1.9792544062660864 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 1
12
    order_id  order_latitude  order_longitude                ordered_at_brt  \
11        12      -23.713981       -46.570262 2024-04-01 00:12:04.580904730

    order_weight     sla_max_delivery_time_brt
11      4.851812 2024-04-01 02:12:04.580904730
2024-04-01 00:12:04.580904730
tem rota aberta
dist order to order é  3.774656294528166 hub em questão 1
dist order to hub é  1.411480096452944 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 1
passou aqui1
passou aqui5
route_id 8
caiu aqui tb
13
    order_id  order_latitude  order_longitude                ordered_at_brt  \
12        13      -23.599771        -46.67647 2024-04-01 00:12:32.027833633

    order_weight     sla_max_delivery_time_brt
12      5.495854 2024-04-01 01:12:32.027833633
2024-04-01 00:12:32.027833633
tem rota aberta
dist order to order é  1.6975676787089347 hub em questão 15
dist order to hub é  2.446422910328442 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 6
14
    order_id  order_latitude  order_longitude                ordered_at_brt  \
13        14      -23.644627       -46.701103 2024-04-01 00:16:44.591508577

    order_weight     sla_max_delivery_time_brt
13       1.73976 2024-04-01 03:16:44.591508577
2024-04-01 00:16:44.591508577
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.059041572430634 hub em questão 9
dist order to hub é  0.884961096033704 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 4
15
    order_id  order_latitude  order_longitude                ordered_at_brt  \
14        15      -23.677809         -46.6414 2024-04-01 00:16:47.923863549

    order_weight     sla_max_delivery_time_brt
14      9.100387 2024-04-01 01:16:47.923863549
2024-04-01 00:16:47.923863549
tem rota aberta
dist order to order é  4.146711023296368 hub em questão 10
dist order to hub é  1.5997953218162224 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 10
passou aqui1
rota em aberto, route_id:  7
rota_escolhida: 7
orders no hub: 1
passou aqui3
passou aqui4
16
    order_id  order_latitude  order_longitude                ordered_at_brt  \
15        16      -23.666057       -46.676175 2024-04-01 00:19:01.133502728

    order_weight     sla_max_delivery_time_brt
15      6.189893 2024-04-01 02:19:01.133502728
2024-04-01 00:19:01.133502728
tem rota aberta
dist order to order é  2.325802091695424 hub em questão 5
dist order to hub é  2.177318538250394 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 7
17
    order_id  order_latitude  order_longitude                ordered_at_brt  \
16        17      -23.672475       -46.528505 2024-04-01 00:20:05.944428301

    order_weight     sla_max_delivery_time_brt
16       5.26243 2024-04-01 01:20:05.944428301
2024-04-01 00:20:05.944428301
tem rota aberta
dist order to order é  6.275186428714357 hub em questão 6
dist order to hub é  2.521700285196229 hub em questão 2
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 2
hub_order 6
passou aqui1
passou aqui5
route_id 9
caiu aqui tb
18
    order_id  order_latitude  order_longitude                ordered_at_brt  \
17        18      -23.711039       -46.635742 2024-04-01 00:21:44.105305969

    order_weight     sla_max_delivery_time_brt
17      3.578536 2024-04-01 03:21:44.105305969
2024-04-01 00:21:44.105305969
tem rota aberta
dist order to order é  2.940531566634785 hub em questão 1
dist order to hub é  0.8076286921391518 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 1
passou aqui1
rota em aberto, route_id:  3
rota_escolhida: 3
orders no hub: 2
passou aqui3
passou aqui4
19
    order_id  order_latitude  order_longitude                ordered_at_brt  \
18        19      -23.672641       -46.590383 2024-04-01 00:22:02.258056318

    order_weight     sla_max_delivery_time_brt
18      8.503049 2024-04-01 02:22:02.258056318
2024-04-01 00:22:02.258056318
tem rota aberta
dist order to order é  5.032646050329315 hub em questão 6
dist order to hub é  1.3905031046844525 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 6
passou aqui1
passou aqui5
route_id 10
caiu aqui tb
20
    order_id  order_latitude  order_longitude                ordered_at_brt  \
19        20      -23.615591       -46.659225 2024-04-01 00:22:28.750843212

    order_weight     sla_max_delivery_time_brt
19      7.677302 2024-04-01 03:22:28.750843212
2024-04-01 00:22:28.750843212
tem rota aberta
dist order to order é  1.5783175896231696 hub em questão 15
dist order to hub é  0.060515562115006735 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 6

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

21
    order_id  order_latitude  order_longitude                ordered_at_brt  \
20        21      -23.578928       -46.664316 2024-04-01 00:25:42.330967552

    order_weight     sla_max_delivery_time_brt
20      3.732739 2024-04-01 01:25:42.330967552
2024-04-01 00:25:42.330967552
tem rota aberta
dist order to order é  1.452867908478758 hub em questão 4
dist order to hub é  3.7001082651466604 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 2
22
    order_id  order_latitude  order_longitude                ordered_at_brt  \
21        22      -23.577308       -46.649558 2024-04-01 00:32:36.358232717

    order_weight     sla_max_delivery_time_brt
21     10.840174 2024-04-01 02:32:36.358232717
2024-04-01 00:32:36.358232717
tem rota aberta
dist order to order é  1.5147130320289923 hub em questão 4
dist order to hub é  2.896658867328614 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 2
23
    order_id  order_latitude  order_longitude                ordered_at_brt  \
22        23      -23.678893       -46.630227 2024-04-01 00:33:21.482866266

    order_weight     sla_max_delivery_time_brt
22      6.703543 2024-04-01 03:33:21.482866266
2024-04-01 00:33:21.482866266
tem rota aberta
dist order to order é  1.1442070353667835 hub em questão 5
dist order to hub é  2.7162580043832607 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 7

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

24
    order_id  order_latitude  order_longitude                ordered_at_brt  \
23        24      -23.656088       -46.605533 2024-04-01 00:35:42.927286079

    order_weight     sla_max_delivery_time_brt
23      6.189553 2024-04-01 03:35:42.927286079
2024-04-01 00:35:42.927286079
tem rota aberta
dist order to order é  2.401886754843964 hub em questão 12
dist order to hub é  3.1939659699120173 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 10
25
    order_id  order_latitude  order_longitude                ordered_at_brt  \
24        25      -23.693194        -46.65412 2024-04-01 00:39:53.801322864

    order_weight     sla_max_delivery_time_brt
24     12.235205 2024-04-01 02:39:53.801322864
2024-04-01 00:39:53.801322864
tem rota aberta
dist order to order é  6.442542182728469 hub em questão 12
dist order to hub é  2.33237128371229 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
passou aqui5
route_id 11
caiu aqui tb
26
    order_id  order_latitude  order_longitude                ordered_at_brt  \
25        26      -23.598725       -46.682055 2024-04-01 00:44:23.808026780

    order_weight     sla_max_delivery_time_brt
25      6.458326 2024-04-01 01:44:23.808026780
2024-04-01 00:44:23.808026780
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  10.072502166802845 hub em questão 12
dist order to hub é  2.943345751140907 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 12
passou aqui1
passou aqui5
route_id 12
caiu aqui tb
27
    order_id  order_latitude  order_longitude                ordered_at_brt  \
26        27      -23.732633       -46.701407 2024-04-01 00:44:34.473570777

    order_weight     sla_max_delivery_time_brt
26      6.392867 2024-04-01 03:44:34.473570777
2024-04-01 00:44:34.473570777
tem rota aberta
dist order to order é  6.512082398666592 hub em questão 5
dist order to hub é  7.795784353707131 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 11
28
    order_id  order_latitude  order_longitude                ordered_at_brt  \
27        28      -23.718389       -46.651847 2024-04-01 00:44:39.254116151

    order_weight     sla_max_delivery_time_brt
27      5.822331 2024-04-01 01:44:39.254116151
2024-04-01 00:44:39.254116151
tem rota aberta
dist order to order é  2.8111370933619857 hub em questão 5
dist order to hub é  2.5098418534194753 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 11
29
    order_id  order_latitude  order_longitude                ordered_at_brt  \
28        29      -23.682018       -46.619365 2024-04-01 00:45:01.589150384

    order_weight     sla_max_delivery_time_brt
28     13.439207 2024-04-01 03:45:01.589150384
2024-04-01 00:45:01.589150384
tem rota aberta
dist order to order é  3.1300967720542165 hub em questão 12
dist order to hub é  3.517380798424392 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 10
30
    order_id  order_latitude  order_longitude                ordered_at_brt  \
29        30      -23.637652       -46.625115 2024-04-01 00:49:14.177507727

    order_weight     sla_max_delivery_time_brt
29     13.409216 2024-04-01 03:49:14.177507727
2024-04-01 00:49:14.177507727
tem rota aberta
dist order to order é  2.860226895507713 hub em questão 12
dist order to hub é  1.6059496294607893 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 10
31
    order_id  order_latitude  order_longitude                ordered_at_brt  \
30        31      -23.666283       -46.648904 2024-04-01 00:49:26.600549644

    order_weight     sla_max_delivery_time_brt
30      9.922689 2024-04-01 02:49:26.600549644
2024-04-01 00:49:26.600549644
tem rota aberta
dist order to order é  3.0391799739358647 hub em questão 5
dist order to hub é  0.9763840104331442 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 5
passou aqui1
rota em aberto, route_id:  11
rota_escolhida: 11
orders no hub: 3
passou aqui3
passou aqui4
32
    order_id  order_latitude  order_longitude                ordered_at_brt  \
31        32      -23.648572        -46.67802 2024-04-01 00:50:32.197193586

    order_weight     sla_max_delivery_time_brt
31       6.43063 2024-04-01 02:50:32.197193586
2024-04-01 00:50:32.197193586
tem rota aberta
dist order to order é  5.557960611741813 hub em questão 15
dist order to hub é  2.5908906292903136 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 13
caiu aqui tb
33
    order_id  order_latitude  order_longitude                ordered_at_brt  \
32        33      -23.647849       -46.640675 2024-04-01 00:56:52.292259090

    order_weight     sla_max_delivery_time_brt
32      5.011456 2024-04-01 03:56:52.292259090
2024-04-01 00:56:52.292259090
tem rota aberta
dist order to order é  3.80474097952284 hub em questão 9
dist order to hub é  3.128492601413962 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 13
34
    order_id  order_latitude  order_longitude                ordered_at_brt  \
33        34      -23.638561       -46.619423 2024-04-01 00:58:23.705860678

    order_weight     sla_max_delivery_time_brt
33        8.2419 2024-04-01 01:58:23.705860678
2024-04-01 00:58:23.705860678
tem rota aberta
dist order to order é  2.3984654968132215 hub em questão 9
dist order to hub é  1.4772469349680784 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 13
35
    order_id  order_latitude  order_longitude                ordered_at_brt  \
34        35      -23.701948       -46.649854 2024-04-01 01:00:44.976652065

    order_weight     sla_max_delivery_time_brt
34      7.095774 2024-04-01 02:00:44.976652065

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 01:00:44.976652065
tem rota aberta
dist order to order é  6.087834904735697 hub em questão 9
dist order to hub é  2.522442842319633 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 9
passou aqui1
passou aqui5
route_id 14
caiu aqui tb
36
    order_id  order_latitude  order_longitude                ordered_at_brt  \
35        36      -23.667193       -46.642394 2024-04-01 01:01:30.467388485

    order_weight     sla_max_delivery_time_brt
35      2.219022 2024-04-01 03:01:30.467388485
2024-04-01 01:01:30.467388485
tem rota aberta
dist order to order é  2.1581580410805357 hub em questão 9
dist order to hub é  1.4876762785698694 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 13
37
    order_id  order_latitude  order_longitude                ordered_at_brt  \
36        37      -23.621345       -46.655538 2024-04-01 01:03:49.662453848

    order_weight     sla_max_delivery_time_brt
36     10.431443 2024-04-01 03:03:49.662453848
2024-04-01 01:03:49.662453848
tem rota aberta
dist order to order é  3.6913057717668156 hub em questão 15
dist order to hub é  0.3741554328473724 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 15
passou aqui1
passou aqui5
route_id 15
caiu aqui tb
38
    order_id  order_latitude  order_longitude                ordered_at_brt  \
37        38      -23.636214       -46.602238 2024-04-01 01:07:25.607700179

    order_weight     sla_max_delivery_time_brt
37       5.47139 2024-04-01 03:07:25.607700179
2024-04-01 01:07:25.607700179
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  5.67597727481843 hub em questão 10
dist order to hub é  1.8772094910963437 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 10
passou aqui1
passou aqui5
route_id 16
caiu aqui tb
39
    order_id  order_latitude  order_longitude                ordered_at_brt  \
38        39       -23.59556       -46.669923 2024-04-01 01:07:27.822609200

    order_weight     sla_max_delivery_time_brt
38      8.946384 2024-04-01 03:07:27.822609200
2024-04-01 01:07:27.822609200
tem rota aberta
dist order to order é  1.2853982068033392 hub em questão 15
dist order to hub é  2.456809262592647 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 12
40
    order_id  order_latitude  order_longitude                ordered_at_brt  \
39        40      -23.687537       -46.638736 2024-04-01 01:10:14.247223709

    order_weight     sla_max_delivery_time_brt
39      6.644113 2024-04-01 03:10:14.247223709
2024-04-01 01:10:14.247223709
tem rota aberta
dist order to order é  1.962034638330168 hub em questão 1
dist order to hub é  2.435916833886123 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 14
41
    order_id  order_latitude  order_longitude                ordered_at_brt  \
40        41      -23.604912       -46.628291 2024-04-01 01:19:13.924519313

    order_weight     sla_max_delivery_time_brt
40      6.781537 2024-04-01 02:19:13.924519313
2024-04-01 01:19:13.924519313
tem rota aberta
dist order to order é  3.323395656534493 hub em questão 10
dist order to hub é  0.9858505931073998 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 10
passou aqui1
passou aqui5
route_id 17
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

42
    order_id  order_latitude  order_longitude                ordered_at_brt  \
41        42      -23.576894       -46.611737 2024-04-01 01:21:59.402571266

    order_weight     sla_max_delivery_time_brt
41      2.969712 2024-04-01 04:21:59.402571266
2024-04-01 01:21:59.402571266
tem rota aberta
dist order to order é  3.5428897755644493 hub em questão 8
dist order to hub é  3.659932262286219 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 17
43
    order_id  order_latitude  order_longitude                ordered_at_brt  \
42        43      -23.657355       -46.573219 2024-04-01 01:22:38.897080805

    order_weight     sla_max_delivery_time_brt
42      4.359864 2024-04-01 03:22:38.897080805
2024-04-01 01:22:38.897080805
tem rota aberta
dist order to order é  3.7766732986110525 hub em questão 14
dist order to hub é  1.3393359795896786 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 14
passou aqui1
passou aqui5
route_id 18
caiu aqui tb
44
    order_id  order_latitude  order_longitude                ordered_at_brt  \
43        44      -23.636929        -46.61424 2024-04-01 01:25:45.763703293

    order_weight     sla_max_delivery_time_brt
43      5.039013 2024-04-01 03:25:45.763703293
2024-04-01 01:25:45.763703293
tem rota aberta
dist order to order é  1.2252125391749 hub em questão 14
dist order to hub é  1.2869214884501026 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 16
45

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

    order_id  order_latitude  order_longitude                ordered_at_brt  \
44        45      -23.638966       -46.618052 2024-04-01 01:25:58.837872127

    order_weight     sla_max_delivery_time_brt
44      6.933962 2024-04-01 04:25:58.837872127
2024-04-01 01:25:58.837872127
tem rota aberta
dist order to order é  0.44954867216193595 hub em questão 14
dist order to hub é  1.5004636766832833 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 16
46
    order_id  order_latitude  order_longitude                ordered_at_brt  \
45        46      -23.623442       -46.721525 2024-04-01 01:27:10.119595800

    order_weight     sla_max_delivery_time_brt
45      8.014899 2024-04-01 03:27:10.119595800
2024-04-01 01:27:10.119595800
tem rota aberta
dist order to order é  6.7266046789305625 hub em questão 10
dist order to hub é  3.7231822469086273 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 10
passou aqui1
passou aqui5
route_id 19
caiu aqui tb
47
    order_id  order_latitude  order_longitude                ordered_at_brt  \
46        47      -23.630829       -46.617693 2024-04-01 01:31:57.214867972

    order_weight     sla_max_delivery_time_brt
46      6.133735 2024-04-01 03:31:57.214867972
2024-04-01 01:31:57.214867972
tem rota aberta
dist order to order é  0.7640044302131608 hub em questão 14
dist order to hub é  0.5996043885307807 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 16

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

48
    order_id  order_latitude  order_longitude                ordered_at_brt  \
47        48      -23.576751       -46.533327 2024-04-01 01:32:38.926107020

    order_weight     sla_max_delivery_time_brt
47      4.713739 2024-04-01 02:32:38.926107020
2024-04-01 01:32:38.926107020
tem rota aberta
dist order to order é  7.990990997454782 hub em questão 8
dist order to hub é  6.086112471183128 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 17
49
    order_id  order_latitude  order_longitude                ordered_at_brt  \
48        49      -23.624557       -46.689513 2024-04-01 01:33:19.649532817

    order_weight     sla_max_delivery_time_brt
48     10.159498 2024-04-01 03:33:19.649532817
2024-04-01 01:33:19.649532817
tem rota aberta
dist order to order é  3.2635527089730365 hub em questão 9
dist order to hub é  3.1843873648581376 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 19
50
    order_id  order_latitude  order_longitude                ordered_at_brt  \
49        50         -23.607       -46.698989 2024-04-01 01:33:36.364921943

    order_weight     sla_max_delivery_time_brt
49      6.972445 2024-04-01 03:33:36.364921943
2024-04-01 01:33:36.364921943
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.1778853772983138 hub em questão 9
dist order to hub é  3.957423676081615 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 19
51
    order_id  order_latitude  order_longitude                ordered_at_brt  \
50        51      -23.633649       -46.658745 2024-04-01 01:33:38.711756483

    order_weight     sla_max_delivery_time_brt
50      8.427281 2024-04-01 04:33:38.711756483
2024-04-01 01:33:38.711756483
tem rota aberta
dist order to order é  1.4066535913523932 hub em questão 10
dist order to hub é  1.780446278459047 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 15
52
    order_id  order_latitude  order_longitude                ordered_at_brt  \
51        52      -23.702314        -46.59695 2024-04-01 01:35:55.007987917

    order_weight     sla_max_delivery_time_brt
51       8.12183 2024-04-01 03:35:55.007987917
2024-04-01 01:35:55.007987917
tem rota aberta
dist order to order é  5.5527060120965155 hub em questão 12
dist order to hub é  3.3392666131949382 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 12
passou aqui1
passou aqui5
route_id 20
caiu aqui tb
53
    order_id  order_latitude  order_longitude                ordered_at_brt  \
52        53      -23.628557       -46.621775 2024-04-01 01:36:23.542231889

    order_weight     sla_max_delivery_time_brt
52      4.362209 2024-04-01 02:36:23.542231889
2024-04-01 01:36:23.542231889
tem rota aberta
dist order to order é  2.711732852700588 hub em questão 8
dist order to hub é  0.6315880175465978 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 8
passou aqui1
passou aqui5
route_id 21
caiu aqui tb
54
    order_id  order_latitude  order_longitude                ordered_at_brt  \
53        54      -23.661723       -46.671869 2024-04-01 01:37:00.577689177

    order_weight     sla_max_delivery_time_brt
53      5.083457 2024-04-01 02:37:00.577689177
2024-04-01 01:37:00.577689177
tem rota aberta
dist order to order é  4.506580479075184 hub em questão 9
dist order to hub é  2.0055052150478994 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 9
passou aqui1
passou aqui5
route_id 22
caiu aqui tb
55
    order_id  order_latitude  order_longitude                ordered_at_brt  \
54        55       -23.68198       -46.649812 2024-04-01 01:38:21.749762765

    order_weight     sla_max_delivery_time_brt
54       9.56676 2024-04-01 02:38:21.749762765
2024-04-01 01:38:21.749762765
tem rota aberta
dist order to order é  3.181040219074291 hub em questão 5
dist order to hub é  1.2440466253148577 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 22
56
    order_id  order_latitude  order_longitude                ordered_at_brt  \
55        56      -23.694944       -46.596161 2024-04-01 01:38:28.330454103

    order_weight     sla_max_delivery_time_brt
55     12.867261 2024-04-01 02:38:28.330454103
2024-04-01 01:38:28.330454103
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  0.8234392333225738 hub em questão 6
dist order to hub é  3.4810358005238697 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 20
57
    order_id  order_latitude  order_longitude                ordered_at_brt  \
56        57      -23.653745       -46.614382 2024-04-01 01:40:10.761498909

    order_weight     sla_max_delivery_time_brt
56      8.419875 2024-04-01 03:40:10.761498909
2024-04-01 01:40:10.761498909
tem rota aberta
dist order to order é  2.9002566355247508 hub em questão 14
dist order to hub é  3.1432521381614644 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 21
58
    order_id  order_latitude  order_longitude                ordered_at_brt  \
57        58      -23.680599       -46.526569 2024-04-01 01:40:29.802808692

    order_weight     sla_max_delivery_time_brt
57      4.974752 2024-04-01 03:40:29.802808692
2024-04-01 01:40:29.802808692
tem rota aberta
dist order to order é  5.408395569050089 hub em questão 12
dist order to hub é  3.1584100281425247 hub em questão 2
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 2
hub_order 12
passou aqui1
passou aqui5
route_id 23
caiu aqui tb
59
    order_id  order_latitude  order_longitude                ordered_at_brt  \
58        59      -23.548242       -46.597728 2024-04-01 01:42:16.591497460

    order_weight     sla_max_delivery_time_brt
58     10.685516 2024-04-01 04:42:16.591497460
2024-04-01 01:42:16.591497460
tem rota aberta
dist order to order é  3.491296951248513 hub em questão 8
dist order to hub é  7.04358691637561 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 17
60
    order_id  order_latitude  order_longitude                ordered_at_brt  \
59        60      -23.570387       -46.630334 2024-04-01 01:44:40.971616893

    order_weight     sla_max_delivery_time_brt
59      2.073939 2024-04-01 04:44:40.971616893
2024-04-01 01:44:40.971616893
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  6.526813907355566 hub em questão 14
dist order to hub é  3.416071328257379 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 14
passou aqui1
passou aqui5
route_id 24
caiu aqui tb
61
    order_id  order_latitude  order_longitude                ordered_at_brt  \
60        61      -23.663572       -46.617276 2024-04-01 01:44:53.926540319

    order_weight     sla_max_delivery_time_brt
60      4.479004 2024-04-01 02:44:53.926540319
2024-04-01 01:44:53.926540319
tem rota aberta
dist order to order é  1.1317512304875563 hub em questão 14
dist order to hub é  4.0514148977551026 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 21
62
    order_id  order_latitude  order_longitude                ordered_at_brt  \
61        62      -23.614767       -46.665462 2024-04-01 01:45:58.070264677

    order_weight     sla_max_delivery_time_brt
61     10.813145 2024-04-01 04:45:58.070264677
2024-04-01 01:45:58.070264677
tem rota aberta
dist order to order é  2.6812577245891016 hub em questão 9
dist order to hub é  0.582836868943207 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 9
passou aqui1
passou aqui5
route_id 25
caiu aqui tb
63
    order_id  order_latitude  order_longitude                ordered_at_brt  \
62        63      -23.592377       -46.696901 2024-04-01 01:48:20.327713214

    order_weight     sla_max_delivery_time_brt
62      5.721077 2024-04-01 02:48:20.327713214
2024-04-01 01:48:20.327713214
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.6398615544529649 hub em questão 9
dist order to hub é  2.351812558329302 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 19
64
    order_id  order_latitude  order_longitude                ordered_at_brt  \
63        64      -23.658867       -46.639415 2024-04-01 01:49:24.496688042

    order_weight     sla_max_delivery_time_brt
63     11.541467 2024-04-01 03:49:24.496688042
2024-04-01 01:49:24.496688042
tem rota aberta
dist order to order é  2.314633719490025 hub em questão 14
dist order to hub é  2.246162647976695 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 21
65
    order_id  order_latitude  order_longitude                ordered_at_brt  \
64        65      -23.557814       -46.623485 2024-04-01 01:49:30.646004642

    order_weight     sla_max_delivery_time_brt
64      1.849916 2024-04-01 03:49:30.646004642
2024-04-01 01:49:30.646004642
tem rota aberta
dist order to order é  1.5626844675554616 hub em questão 8
dist order to hub é  4.939253805809282 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 24
66
    order_id  order_latitude  order_longitude                ordered_at_brt  \
65        66       -23.60412       -46.717777 2024-04-01 01:51:02.763703269

    order_weight     sla_max_delivery_time_brt
65       5.02875 2024-04-01 02:51:02.763703269
2024-04-01 01:51:02.763703269
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  5.4601581676122075 hub em questão 15
dist order to hub é  4.060201342723556 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 25
67
    order_id  order_latitude  order_longitude                ordered_at_brt  \
66        67      -23.655311       -46.674131 2024-04-01 01:53:13.567678961

    order_weight     sla_max_delivery_time_brt
66      8.002103 2024-04-01 04:53:13.567678961
2024-04-01 01:53:13.567678961
tem rota aberta
dist order to order é  0.749304851512851 hub em questão 5
dist order to hub é  2.647069755843663 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 22
68
    order_id  order_latitude  order_longitude                ordered_at_brt  \
67        68       -23.74019       -46.666476 2024-04-01 01:54:40.373012470

    order_weight     sla_max_delivery_time_brt
67      7.579177 2024-04-01 04:54:40.373012470
2024-04-01 01:54:40.373012470
tem rota aberta
dist order to order é  6.691355228971182 hub em questão 5
dist order to hub é  4.971705562693513 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 22
69
    order_id  order_latitude  order_longitude                ordered_at_brt  \
68        69      -23.698523       -46.634731 2024-04-01 02:00:27.542736370

    order_weight     sla_max_delivery_time_brt
68      7.834239 2024-04-01 05:00:27.542736370
2024-04-01 02:00:27.542736370
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.869695208094333 hub em questão 6
dist order to hub é  1.7130655864501918 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 6
passou aqui1
passou aqui5
route_id 26
caiu aqui tb
70
    order_id  order_latitude  order_longitude                ordered_at_brt  \
69        70      -23.634291       -46.661036 2024-04-01 02:02:13.530442235

    order_weight     sla_max_delivery_time_brt
69      6.902528 2024-04-01 04:02:13.530442235
2024-04-01 02:02:13.530442235
tem rota aberta
dist order to order é  2.2172182000485687 hub em questão 15
dist order to hub é  1.917672335134027 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 25
71
    order_id  order_latitude  order_longitude                ordered_at_brt  \
70        71      -23.672139       -46.625758 2024-04-01 02:06:53.994006029

    order_weight     sla_max_delivery_time_brt
70      5.120095 2024-04-01 03:06:53.994006029
2024-04-01 02:06:53.994006029
tem rota aberta
dist order to order é  3.0728145388433292 hub em questão 1
dist order to hub é  3.0701100487613138 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 26
72
    order_id  order_latitude  order_longitude                ordered_at_brt  \
71        72      -23.651263       -46.643107 2024-04-01 02:07:11.740902266

    order_weight     sla_max_delivery_time_brt
71      9.982593 2024-04-01 05:07:11.740902266
2024-04-01 02:07:11.740902266
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.6261991536926144 hub em questão 15
dist order to hub é  2.6760654697070283 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 25
73
    order_id  order_latitude  order_longitude                ordered_at_brt  \
72        73      -23.689591       -46.594996 2024-04-01 02:07:29.738716691

    order_weight     sla_max_delivery_time_brt
72      5.008428 2024-04-01 05:07:29.738716691
2024-04-01 02:07:29.738716691
tem rota aberta
dist order to order é  3.684925543158686 hub em questão 1
dist order to hub é  2.927295021334214 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 26
74
    order_id  order_latitude  order_longitude                ordered_at_brt  \
73        74      -23.637879       -46.733571 2024-04-01 02:10:47.390062772

    order_weight     sla_max_delivery_time_brt
73      3.231923 2024-04-01 03:10:47.390062772
2024-04-01 02:10:47.390062772
tem rota aberta
dist order to order é  11.623028796620494 hub em questão 1
dist order to hub é  3.495535248859093 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 1
passou aqui1
passou aqui5
route_id 27
caiu aqui tb
75
    order_id  order_latitude  order_longitude                ordered_at_brt  \
74        75       -23.67314       -46.565157 2024-04-01 02:11:48.225402220

    order_weight     sla_max_delivery_time_brt
74      6.668063 2024-04-01 04:11:48.225402220
2024-04-01 02:11:48.225402220
tem rota aberta
dist order to order é  3.5467465421130764 hub em questão 1
dist order to hub é  1.3378225177621048 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 1
passou aqui1
passou aqui5
route_id 28
caiu aqui tb
76
    order_id  order_latitude  order_longitude                ordered_at_brt  \
75        76      -23.727861       -46.577129 2024-04-01 02:12:09.915142094

    order_weight     sla_max_delivery_time_brt
75          0.01 2024-04-01 05:12:09.915142094
2024-04-01 02:12:09.915142094
tem rota aberta
dist order to order é  4.627895676001441 hub em questão 1
dist order to hub é  0.28316705721785257 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 1
passou aqui1
passou aqui5
route_id 29
caiu aqui tb
77
    order_id  order_latitude  order_longitude                ordered_at_brt  \
76        77      -23.667308       -46.645497 2024-04-01 02:17:24.829591023

    order_weight     sla_max_delivery_time_brt
76      9.492986 2024-04-01 04:17:24.829591023
2024-04-01 02:17:24.829591023
tem rota aberta
dist order to order é  2.0807709731574193 hub em questão 1
dist order to hub é  1.1955552186090939 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 26
78
    order_id  order_latitude  order_longitude                ordered_at_brt  \
77        78      -23.678827       -46.615497 2024-04-01 02:18:16.111791507

    order_weight     sla_max_delivery_time_brt
77      8.473382 2024-04-01 03:18:16.111791507
2024-04-01 02:18:16.111791507
tem rota aberta
dist order to order é  5.165270775302979 hub em questão 12
dist order to hub é  3.970237087194653 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 28
79
    order_id  order_latitude  order_longitude                ordered_at_brt  \
78        79      -23.727808       -46.617685 2024-04-01 02:21:02.857558852

    order_weight     sla_max_delivery_time_brt
78       6.77994 2024-04-01 05:21:02.857558852

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 02:21:02.857558852
tem rota aberta
dist order to order é  4.128448967709588 hub em questão 6
dist order to hub é  1.986611536268733 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 6
passou aqui1
passou aqui5
route_id 30
caiu aqui tb
80
    order_id  order_latitude  order_longitude                ordered_at_brt  \
79        80      -23.579066       -46.684877 2024-04-01 02:23:38.211937238

    order_weight     sla_max_delivery_time_brt
79      4.932358 2024-04-01 04:23:38.211937238
2024-04-01 02:23:38.211937238
tem rota aberta
dist order to order é  8.208680415085194 hub em questão 9
dist order to hub é  1.7635685160970143 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 9
passou aqui1
passou aqui5
route_id 31
caiu aqui tb
81
    order_id  order_latitude  order_longitude                ordered_at_brt  \
80        81      -23.654028        -46.63978 2024-04-01 02:27:55.996049614

    order_weight     sla_max_delivery_time_brt
80      1.575084 2024-04-01 03:27:55.996049614
2024-04-01 02:27:55.996049614
tem rota aberta
dist order to order é  3.7040231010814013 hub em questão 12
dist order to hub é  2.6109320527228927 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 28
82
    order_id  order_latitude  order_longitude                ordered_at_brt  \
81        82      -23.666569       -46.609104 2024-04-01 02:29:53.271416690

    order_weight     sla_max_delivery_time_brt
81      1.826699 2024-04-01 03:29:53.271416690
2024-04-01 02:29:53.271416690
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.510515285405778 hub em questão 12
dist order to hub é  3.238333693167662 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 28
83
    order_id  order_latitude  order_longitude                ordered_at_brt  \
82        83      -23.612707       -46.632522 2024-04-01 02:32:40.079963161

    order_weight     sla_max_delivery_time_brt
82      9.039027 2024-04-01 05:32:40.079963161
2024-04-01 02:32:40.079963161
tem rota aberta
dist order to order é  6.5156359357590405 hub em questão 4
dist order to hub é  1.4179156480385195 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 4
passou aqui1
passou aqui5
route_id 32
caiu aqui tb
84
    order_id  order_latitude  order_longitude                ordered_at_brt  \
83        84      -23.654355       -46.595447 2024-04-01 02:33:31.570702230

    order_weight     sla_max_delivery_time_brt
83      7.295222 2024-04-01 04:33:31.570702230
2024-04-01 02:33:31.570702230
tem rota aberta
dist order to order é  5.9759078504095715 hub em questão 8
dist order to hub é  2.43928278086696 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 8
passou aqui1
passou aqui5
route_id 33
caiu aqui tb
85
    order_id  order_latitude  order_longitude                ordered_at_brt  \
84        85      -23.611861       -46.643263 2024-04-01 02:34:09.324138787

    order_weight     sla_max_delivery_time_brt
84      8.135093 2024-04-01 03:34:09.324138787
2024-04-01 02:34:09.324138787
tem rota aberta
dist order to order é  1.098390433028213 hub em questão 8
dist order to hub é  1.3403103054822005 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 32
86

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

    order_id  order_latitude  order_longitude                ordered_at_brt  \
85        86      -23.724258       -46.643975 2024-04-01 02:38:40.796649436

    order_weight     sla_max_delivery_time_brt
85      6.571014 2024-04-01 04:38:40.796649436
2024-04-01 02:38:40.796649436
tem rota aberta
dist order to order é  2.705184210628465 hub em questão 1
dist order to hub é  2.0762480336849194 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 30
87
    order_id  order_latitude  order_longitude                ordered_at_brt  \
86        87      -23.702058       -46.686403 2024-04-01 02:39:47.849736215

    order_weight     sla_max_delivery_time_brt
86      7.911408 2024-04-01 04:39:47.849736215
2024-04-01 02:39:47.849736215
tem rota aberta
dist order to order é  4.975052059981755 hub em questão 1
dist order to hub é  4.539502105307337 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 30
88
    order_id  order_latitude  order_longitude                ordered_at_brt  \
87        88      -23.622964        -46.66624 2024-04-01 02:46:29.591441870

    order_weight     sla_max_delivery_time_brt
87      2.215311 2024-04-01 04:46:29.591441870
2024-04-01 02:46:29.591441870
tem rota aberta
dist order to order é  2.646532919663636 hub em questão 8
dist order to hub é  1.0463311844066732 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 32
89
    order_id  order_latitude  order_longitude                ordered_at_brt  \
88        89       -23.57563       -46.670999 2024-04-01 02:48:40.269436680

    order_weight     sla_max_delivery_time_brt
88      8.930985 2024-04-01 03:48:40.269436680

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 02:48:40.269436680
tem rota aberta
dist order to order é  1.4650988468099582 hub em questão 4
dist order to hub é  2.996486037498548 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 31
90
    order_id  order_latitude  order_longitude                ordered_at_brt  \
89        90      -23.648725       -46.562739 2024-04-01 02:50:36.916208782

    order_weight     sla_max_delivery_time_brt
89      8.082634 2024-04-01 03:50:36.916208782
2024-04-01 02:50:36.916208782
tem rota aberta
dist order to order é  3.389801409234121 hub em questão 12
dist order to hub é  2.6832716344707968 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 33
91
    order_id  order_latitude  order_longitude                ordered_at_brt  \
90        91      -23.639404       -46.635988 2024-04-01 02:50:51.541885456

    order_weight     sla_max_delivery_time_brt
90      9.673971 2024-04-01 05:50:51.541885456
2024-04-01 02:50:51.541885456
tem rota aberta
dist order to order é  2.9894986983336 hub em questão 8
dist order to hub é  2.511552449075599 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 32
92

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

    order_id  order_latitude  order_longitude                ordered_at_brt  \
91        92      -23.691398       -46.697984 2024-04-01 02:56:49.810197429

    order_weight     sla_max_delivery_time_brt
91      7.337312 2024-04-01 04:56:49.810197429
2024-04-01 02:56:49.810197429
tem rota aberta
dist order to order é  11.225233077195607 hub em questão 12
dist order to hub é  4.371194834007623 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 12
passou aqui1
passou aqui5
route_id 34
caiu aqui tb
93
    order_id  order_latitude  order_longitude                ordered_at_brt  \
92        93      -23.651722       -46.628083 2024-04-01 02:58:01.531468173

    order_weight     sla_max_delivery_time_brt
92      3.955287 2024-04-01 03:58:01.531468173
2024-04-01 02:58:01.531468173
tem rota aberta
dist order to order é  3.336980066619884 hub em questão 12
dist order to hub é  3.140064005177727 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 33
94
    order_id  order_latitude  order_longitude                ordered_at_brt  \
93        94      -23.685672       -46.657613 2024-04-01 02:59:45.172305963

    order_weight     sla_max_delivery_time_brt
93      8.422912 2024-04-01 04:59:45.172305963
2024-04-01 02:59:45.172305963
tem rota aberta
dist order to order é  4.159840894859866 hub em questão 9
dist order to hub é  1.499040600049786 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 9
passou aqui1
passou aqui5
route_id 35
caiu aqui tb
95
    order_id  order_latitude  order_longitude                ordered_at_brt  \
94        95      -23.658237       -46.800701 2024-04-01 03:00:48.109876748

    order_weight     sla_max_delivery_time_brt
94      3.460525 2024-04-01 05:00:48.109876748
2024-04-01 03:00:48.109876748
tem rota aberta
dist order to order é  11.091214202357822 hub em questão 9
dist order to hub é  9.96056003479962 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 34
96
    order_id  order_latitude  order_longitude                ordered_at_brt  \
95        96      -23.614111        -46.62402 2024-04-01 03:01:20.573789835

    order_weight     sla_max_delivery_time_brt
95      9.969871 2024-04-01 06:01:20.573789835
2024-04-01 03:01:20.573789835
tem rota aberta
dist order to order é  4.202564101234262 hub em questão 12
dist order to hub é  1.2401268260629876 hub em questão 13
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 13
hub_order 12
passou aqui1
passou aqui5
route_id 36
caiu aqui tb
97
    order_id  order_latitude  order_longitude                ordered_at_brt  \
96        97      -23.750164       -46.725648 2024-04-01 03:06:01.009536767

    order_weight     sla_max_delivery_time_brt
96      7.952866 2024-04-01 04:06:01.009536767
2024-04-01 03:06:01.009536767
tem rota aberta
dist order to order é  7.115507427321226 hub em questão 9
dist order to hub é  10.779355544047345 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 34
98
    order_id  order_latitude  order_longitude                ordered_at_brt  \
97        98      -23.639574        -46.61909 2024-04-01 03:07:43.317197195

    order_weight     sla_max_delivery_time_brt
97      5.018511 2024-04-01 04:07:43.317197195

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 03:07:43.317197195
tem rota aberta
dist order to order é  2.8755401556421396 hub em questão 13
dist order to hub é  1.5817662156654388 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 36
99
    order_id  order_latitude  order_longitude                ordered_at_brt  \
98        99      -23.690452       -46.696076 2024-04-01 03:07:43.662131713

    order_weight     sla_max_delivery_time_brt
98      8.116332 2024-04-01 05:07:43.662131713
2024-04-01 03:07:43.662131713
tem rota aberta
dist order to order é  0.22089613428771931 hub em questão 9
dist order to hub é  4.295012597610766 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 34
100
    order_id  order_latitude  order_longitude                ordered_at_brt  \
99       100      -23.682554       -46.720929 2024-04-01 03:09:38.873978826

    order_weight     sla_max_delivery_time_brt
99     11.778005 2024-04-01 06:09:38.873978826
2024-04-01 03:09:38.873978826
tem rota aberta
dist order to order é  6.456758085526521 hub em questão 5
dist order to hub é  3.8153690655842314 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 37
caiu aqui tb
101
     order_id  order_latitude  order_longitude                ordered_at_brt  \
100       101      -23.593317       -46.623296 2024-04-01 03:10:26.331873267

     order_weight     sla_max_delivery_time_brt
100      4.045153 2024-04-01 05:10:26.331873267

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 03:10:26.331873267
tem rota aberta
dist order to order é  2.3134387840782775 hub em questão 13
dist order to hub é  1.5860245104941133 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 36
102
     order_id  order_latitude  order_longitude                ordered_at_brt  \
101       102      -23.635453       -46.722722 2024-04-01 03:11:56.185801561

     order_weight     sla_max_delivery_time_brt
101     12.089182 2024-04-01 04:11:56.185801561
2024-04-01 03:11:56.185801561
tem rota aberta
dist order to order é  5.240594285195236 hub em questão 9
dist order to hub é  2.7433554069165993 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 9
passou aqui1
rota em aberto, route_id:  37
rota_escolhida: 37
orders no hub: 1
passou aqui3
passou aqui4
103
     order_id  order_latitude  order_longitude                ordered_at_brt  \
102       103      -23.603544       -46.670348 2024-04-01 03:16:16.711688610

     order_weight     sla_max_delivery_time_brt
102      7.293489 2024-04-01 04:16:16.711688610
2024-04-01 03:16:16.711688610
tem rota aberta
dist order to order é  4.864291948695731 hub em questão 13
dist order to hub é  1.7188428238293647 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 13
passou aqui1
passou aqui5
route_id 38
caiu aqui tb
104
     order_id  order_latitude  order_longitude                ordered_at_brt  \
103       104      -23.738414       -46.637794 2024-04-01 03:17:09.755309755

     order_weight     sla_max_delivery_time_brt
103     10.316006 2024-04-01 05:17:09.755309755

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 03:17:09.755309755
tem rota aberta
dist order to order é  6.202035946234934 hub em questão 5
dist order to hub é  3.0337435983054624 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 39
caiu aqui tb
105
     order_id  order_latitude  order_longitude                ordered_at_brt  \
104       105      -23.670736       -46.617401 2024-04-01 03:21:56.771374983

     order_weight     sla_max_delivery_time_brt
104      7.876521 2024-04-01 04:21:56.771374983
2024-04-01 03:21:56.771374983
tem rota aberta
dist order to order é  3.4693398963129622 hub em questão 13
dist order to hub é  3.9249016797770064 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 36
106
     order_id  order_latitude  order_longitude                ordered_at_brt  \
105       106      -23.672909       -46.610769 2024-04-01 03:23:53.947266464

     order_weight     sla_max_delivery_time_brt
105      8.443767 2024-04-01 05:23:53.947266464
2024-04-01 03:23:53.947266464
tem rota aberta
dist order to order é  4.976967361262798 hub em questão 5
dist order to hub é  3.4293957577792336 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 35
107
     order_id  order_latitude  order_longitude                ordered_at_brt  \
106       107      -23.679697       -46.649827 2024-04-01 03:23:55.860994622

     order_weight     sla_max_delivery_time_brt
106     12.394488 2024-04-01 05:23:55.860994622
2024-04-01 03:23:55.860994622
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.0344579601374875 hub em questão 5
dist order to hub é  1.0309235780849777 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 35
108
     order_id  order_latitude  order_longitude                ordered_at_brt  \
107       108      -23.628214       -46.689633 2024-04-01 03:29:14.011314270

     order_weight     sla_max_delivery_time_brt
107       7.56244 2024-04-01 05:29:14.011314270
2024-04-01 03:29:14.011314270
tem rota aberta
dist order to order é  3.37421010423386 hub em questão 15
dist order to hub é  3.0167417544016315 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 38
109
     order_id  order_latitude  order_longitude                ordered_at_brt  \
108       109      -23.605429       -46.551822 2024-04-01 03:31:34.900969163

     order_weight     sla_max_delivery_time_brt
108      6.553491 2024-04-01 05:31:34.900969163
2024-04-01 03:31:34.900969163
tem rota aberta
dist order to order é  12.07858865133019 hub em questão 15
dist order to hub é  2.6643875841874523 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 15
passou aqui1
passou aqui5
route_id 40
caiu aqui tb
110
     order_id  order_latitude  order_longitude                ordered_at_brt  \
109       110      -23.705564       -46.678312 2024-04-01 03:43:25.661287376

     order_weight     sla_max_delivery_time_brt
109      7.565277 2024-04-01 05:43:25.661287376
2024-04-01 03:43:25.661287376
tem rota aberta
dist order to order é  5.509613660333405 hub em questão 1
dist order to hub é  4.347645395029423 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 39
111
     order_id  order_latitude  order_longitude                ordered_at_brt  \
110       111      -23.698358       -46.557833 2024-04-01 03:43:48.359701513

     order_weight     sla_max_delivery_time_brt
110     10.287063 2024-04-01 05:43:48.359701513

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 03:43:48.359701513
tem rota aberta
dist order to order é  9.279065619305086 hub em questão 1
dist order to hub é  3.544444906735762 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 1
passou aqui1
passou aqui5
route_id 41
caiu aqui tb
112
     order_id  order_latitude  order_longitude                ordered_at_brt  \
111       112      -23.712823       -46.670639 2024-04-01 03:44:06.059449507

     order_weight     sla_max_delivery_time_brt
111      6.357911 2024-04-01 04:44:06.059449507
2024-04-01 03:44:06.059449507
tem rota aberta
dist order to order é  1.1232668642820278 hub em questão 1
dist order to hub é  4.340488303889867 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 39
113
     order_id  order_latitude  order_longitude                ordered_at_brt  \
112       113      -23.592845       -46.589948 2024-04-01 03:49:29.704603427

     order_weight     sla_max_delivery_time_brt
112      4.231667 2024-04-01 05:49:29.704603427
2024-04-01 03:49:29.704603427
tem rota aberta
dist order to order é  4.129249802459439 hub em questão 3
dist order to hub é  2.906691550543136 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 40
114
     order_id  order_latitude  order_longitude                ordered_at_brt  \
113       114      -23.675962       -46.594515 2024-04-01 03:51:52.915306592

     order_weight     sla_max_delivery_time_brt
113      6.324036 2024-04-01 05:51:52.915306592
2024-04-01 03:51:52.915306592
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.48923218008364 hub em questão 6
dist order to hub é  1.9175782012045721 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 6
passou aqui1
passou aqui5
route_id 42
caiu aqui tb
115
     order_id  order_latitude  order_longitude                ordered_at_brt  \
114       115      -23.655294       -46.700289 2024-04-01 03:52:01.108789673

     order_weight     sla_max_delivery_time_brt
114      8.723073 2024-04-01 05:52:01.108789673
2024-04-01 03:52:01.108789673
tem rota aberta
dist order to order é  11.014953252554442 hub em questão 12
dist order to hub é  0.43446938295171916 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 12
passou aqui1
passou aqui5
route_id 43
caiu aqui tb
116
     order_id  order_latitude  order_longitude                ordered_at_brt  \
115       116      -23.666836       -46.630249 2024-04-01 03:54:50.115453759

     order_weight     sla_max_delivery_time_brt
115      6.959069 2024-04-01 05:54:50.115453759
2024-04-01 03:54:50.115453759
tem rota aberta
dist order to order é  3.7779778377228443 hub em questão 12
dist order to hub é  2.682067551951231 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 42
117
     order_id  order_latitude  order_longitude                ordered_at_brt  \
116       117      -23.698408       -46.610243 2024-04-01 03:57:38.345922245

     order_weight     sla_max_delivery_time_brt
116      8.242702 2024-04-01 05:57:38.345922245
2024-04-01 03:57:38.345922245
tem rota aberta
dist order to order é  2.9655741903985393 hub em questão 12
dist order to hub é  2.403391798722633 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 42

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

118
     order_id  order_latitude  order_longitude                ordered_at_brt  \
117       118      -23.631562       -46.612964 2024-04-01 04:02:46.058148409

     order_weight     sla_max_delivery_time_brt
117      4.741855 2024-04-01 05:02:46.058148409
2024-04-01 04:02:46.058148409
tem rota aberta
dist order to order é  4.299265626563668 hub em questão 12
dist order to hub é  0.7608220467058739 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 12
passou aqui1
passou aqui5
route_id 44
caiu aqui tb
119
     order_id  order_latitude  order_longitude                ordered_at_brt  \
118       119      -23.631074        -46.65796 2024-04-01 04:05:15.235670231

     order_weight     sla_max_delivery_time_brt
118      11.08113 2024-04-01 06:05:15.235670231
2024-04-01 04:05:15.235670231
tem rota aberta
dist order to order é  4.5840924316876 hub em questão 14
dist order to hub é  1.4832759181022823 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 14
passou aqui1
passou aqui5
route_id 45
caiu aqui tb
120
     order_id  order_latitude  order_longitude                ordered_at_brt  \
119       120      -23.603159       -46.632915 2024-04-01 04:05:31.159496616

     order_weight     sla_max_delivery_time_brt
119      8.159125 2024-04-01 05:05:31.159496616
2024-04-01 04:05:31.159496616
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.7558644524047247 hub em questão 14
dist order to hub é  0.4838584669680798 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 14
passou aqui1
passou aqui5
route_id 46
caiu aqui tb
121
     order_id  order_latitude  order_longitude                ordered_at_brt  \
120       121      -23.661496       -46.667747 2024-04-01 04:05:33.569144902

     order_weight     sla_max_delivery_time_brt
120      8.165546 2024-04-01 05:05:33.569144902
2024-04-01 04:05:33.569144902
tem rota aberta
dist order to order é  3.385398132387367 hub em questão 9
dist order to hub é  1.7009167602840847 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 43
122
     order_id  order_latitude  order_longitude                ordered_at_brt  \
121       122       -23.66508       -46.706603 2024-04-01 04:05:36.756419035

     order_weight     sla_max_delivery_time_brt
121      7.091566 2024-04-01 06:05:36.756419035
2024-04-01 04:05:36.756419035
tem rota aberta
dist order to order é  1.2639037064855658 hub em questão 9
dist order to hub é  1.4573492179324248 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 43
123
     order_id  order_latitude  order_longitude                ordered_at_brt  \
122       123      -23.679501       -46.598812 2024-04-01 04:05:40.202199971

     order_weight     sla_max_delivery_time_brt
122      8.841156 2024-04-01 06:05:40.202199971
2024-04-01 04:05:40.202199971
tem rota aberta
dist order to order é  0.5885792609436471 hub em questão 12
dist order to hub é  2.4856093329913462 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 42
124
     order_id  order_latitude  order_longitude                ordered_at_brt  \
123       124      -23.575818       -46.675997 2024-04-01 04:06:14.119345651

     order_weight     sla_max_delivery_time_brt
123      6.753241 2024-04-01 06:06:14.119345651

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 04:06:14.119345651
tem rota aberta
dist order to order é  5.340079548889944 hub em questão 8
dist order to hub é  2.4986051660549458 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 8
passou aqui1
passou aqui5
route_id 47
caiu aqui tb
125
     order_id  order_latitude  order_longitude                ordered_at_brt  \
124       125      -23.599847       -46.579025 2024-04-01 04:10:10.076846821

     order_weight     sla_max_delivery_time_brt
124      6.567341 2024-04-01 05:10:10.076846821
2024-04-01 04:10:10.076846821
tem rota aberta
dist order to order é  4.9389324598021656 hub em questão 14
dist order to hub é  1.767893083209168 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 14
passou aqui1
passou aqui5
route_id 48
caiu aqui tb
126
     order_id  order_latitude  order_longitude                ordered_at_brt  \
125       126      -23.652245        -46.61789 2024-04-01 04:11:42.955748619

     order_weight     sla_max_delivery_time_brt
125      9.377133 2024-04-01 06:11:42.955748619
2024-04-01 04:11:42.955748619
tem rota aberta
dist order to order é  2.3538864925002225 hub em questão 14
dist order to hub é  2.9721279123311177 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 44
127
     order_id  order_latitude  order_longitude                ordered_at_brt  \
126       127      -23.617777       -46.692645 2024-04-01 04:13:19.531569300

     order_weight     sla_max_delivery_time_brt
126      6.093184 2024-04-01 07:13:19.531569300

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 04:13:19.531569300
tem rota aberta
dist order to order é  3.8304967557087597 hub em questão 10
dist order to hub é  3.353110233812561 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 45
128
     order_id  order_latitude  order_longitude                ordered_at_brt  \
127       128      -23.679518       -46.656073 2024-04-01 04:17:00.974263660

     order_weight     sla_max_delivery_time_brt
127      6.830977 2024-04-01 06:17:00.974263660
2024-04-01 04:17:00.974263660
tem rota aberta
dist order to order é  2.330034524020159 hub em questão 9
dist order to hub é  0.8047239582679874 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 43
129
     order_id  order_latitude  order_longitude                ordered_at_brt  \
128       129      -23.547502       -46.662332 2024-04-01 04:17:16.884710371

     order_weight     sla_max_delivery_time_brt
128      2.841821 2024-04-01 05:17:16.884710371
2024-04-01 04:17:16.884710371
tem rota aberta
dist order to order é  3.442962656350371 hub em questão 4
dist order to hub é  4.674119722980853 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 47
130
     order_id  order_latitude  order_longitude                ordered_at_brt  \
129       130      -23.679804       -46.691557 2024-04-01 04:17:56.169221978

     order_weight     sla_max_delivery_time_brt
129      6.287499 2024-04-01 07:17:56.169221978

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 04:17:56.169221978
tem rota aberta
dist order to order é  6.408588065467183 hub em questão 10
dist order to hub é  3.269923602183297 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 10
passou aqui1
passou aqui5
route_id 49
caiu aqui tb
131
     order_id  order_latitude  order_longitude                ordered_at_brt  \
130       131       -23.66921       -46.622941 2024-04-01 04:19:41.926182486

     order_weight     sla_max_delivery_time_brt
130      3.267581 2024-04-01 05:19:41.926182486
2024-04-01 04:19:41.926182486
tem rota aberta
dist order to order é  1.9553323239498248 hub em questão 14
dist order to hub é  3.374288492830136 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 44
132
     order_id  order_latitude  order_longitude                ordered_at_brt  \
131       132      -23.668777       -46.671943 2024-04-01 04:26:41.106921179

     order_weight     sla_max_delivery_time_brt
131      4.184189 2024-04-01 06:26:41.106921179
2024-04-01 04:26:41.106921179
tem rota aberta
dist order to order é  2.343711655305106 hub em questão 9
dist order to hub é  1.6792920837578404 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 49
133
     order_id  order_latitude  order_longitude                ordered_at_brt  \
132       133      -23.565164       -46.566428 2024-04-01 04:28:19.905885760

     order_weight     sla_max_delivery_time_brt
132      4.991078 2024-04-01 07:28:19.905885760
2024-04-01 04:28:19.905885760
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.064658871788627 hub em questão 3
dist order to hub é  5.666799650044013 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 48
134
     order_id  order_latitude  order_longitude                ordered_at_brt  \
133       134      -23.642845       -46.604968 2024-04-01 04:28:22.164686813

     order_weight     sla_max_delivery_time_brt
133     12.715107 2024-04-01 06:28:22.164686813
2024-04-01 04:28:22.164686813
tem rota aberta
dist order to order é  1.4957910412994493 hub em questão 14
dist order to hub é  2.2550164540104056 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 44
135
     order_id  order_latitude  order_longitude                ordered_at_brt  \
134       135      -23.596004       -46.692022 2024-04-01 04:31:35.677441594

     order_weight     sla_max_delivery_time_brt
134     10.331213 2024-04-01 05:31:35.677441594
2024-04-01 04:31:35.677441594
tem rota aberta
dist order to order é  2.4217985672088296 hub em questão 10
dist order to hub é  2.852796742997844 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 45
136
     order_id  order_latitude  order_longitude                ordered_at_brt  \
135       136       -23.65573       -46.648963 2024-04-01 04:32:07.505634022

     order_weight     sla_max_delivery_time_brt
135      7.972148 2024-04-01 07:32:07.505634022
2024-04-01 04:32:07.505634022
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.7536487449184506 hub em questão 9
dist order to hub é  1.971599772929481 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 49
137
     order_id  order_latitude  order_longitude                ordered_at_brt  \
136       137      -23.710874       -46.659351 2024-04-01 04:35:24.978869265

     order_weight     sla_max_delivery_time_brt
136      7.915086 2024-04-01 07:35:24.978869265
2024-04-01 04:35:24.978869265
tem rota aberta
dist order to order é  4.763387830726466 hub em questão 9
dist order to hub é  3.197310316082827 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 49
138
     order_id  order_latitude  order_longitude                ordered_at_brt  \
137       138      -23.611451       -46.726238 2024-04-01 04:36:23.874307258

     order_weight     sla_max_delivery_time_brt
137     10.559193 2024-04-01 06:36:23.874307258
2024-04-01 04:36:23.874307258
tem rota aberta
dist order to order é  15.055055212766595 hub em questão 3
dist order to hub é  5.123328607084039 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 3
passou aqui1
passou aqui5
route_id 50
caiu aqui tb
139
     order_id  order_latitude  order_longitude                ordered_at_brt  \
138       139      -23.681548        -46.60145 2024-04-01 04:40:22.882787840

     order_weight     sla_max_delivery_time_brt
138      0.773008 2024-04-01 05:40:22.882787840
2024-04-01 04:40:22.882787840
tem rota aberta
dist order to order é  14.910297534589068 hub em questão 9
dist order to hub é  2.8313665852249055 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 9
passou aqui1
passou aqui5
route_id 51
caiu aqui tb
140
     order_id  order_latitude  order_longitude                ordered_at_brt  \
139       140      -23.716151       -46.600522 2024-04-01 04:43:07.864392705

     order_weight     sla_max_delivery_time_brt
139      3.281956 2024-04-01 05:43:07.864392705
2024-04-01 04:43:07.864392705
tem rota aberta
dist order to order é  3.848875639090599 hub em questão 12
dist order to hub é  2.694698949642741 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 51
141
     order_id  order_latitude  order_longitude                ordered_at_brt  \
140       141      -23.671029       -46.601738 2024-04-01 04:44:45.361024368

     order_weight     sla_max_delivery_time_brt
140      6.823442 2024-04-01 07:44:45.361024368
2024-04-01 04:44:45.361024368
tem rota aberta
dist order to order é  1.1700335559782193 hub em questão 12
dist order to hub é  2.4914123819776597 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 51
142
     order_id  order_latitude  order_longitude                ordered_at_brt  \
141       142      -23.618642       -46.670862 2024-04-01 04:45:02.966168037

     order_weight     sla_max_delivery_time_brt
141      4.678552 2024-04-01 06:45:02.966168037
2024-04-01 04:45:02.966168037
tem rota aberta
dist order to order é  5.698274466805093 hub em questão 9
dist order to hub é  1.1743320165502393 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 9
passou aqui1
passou aqui5
route_id 52
caiu aqui tb
143
     order_id  order_latitude  order_longitude                ordered_at_brt  \
142       143      -23.562011       -46.594563 2024-04-01 04:45:10.380709221

     order_weight     sla_max_delivery_time_brt
142       3.10545 2024-04-01 07:45:10.380709221
2024-04-01 04:45:10.380709221
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  10.00524728308836 hub em questão 15
dist order to hub é  6.067264764085611 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 15
passou aqui1
passou aqui5
route_id 53
caiu aqui tb
144
     order_id  order_latitude  order_longitude                ordered_at_brt  \
143       144      -23.719599         -46.6585 2024-04-01 04:45:25.904052295

     order_weight     sla_max_delivery_time_brt
143      5.734863 2024-04-01 06:45:25.904052295
2024-04-01 04:45:25.904052295
tem rota aberta
dist order to order é  5.9147939016898885 hub em questão 12
dist order to hub é  3.199425109081949 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 12
passou aqui1
passou aqui5
route_id 54
caiu aqui tb
145
     order_id  order_latitude  order_longitude                ordered_at_brt  \
144       145      -23.760178       -46.601255 2024-04-01 04:45:31.373029666

     order_weight     sla_max_delivery_time_brt
144      8.868943 2024-04-01 05:45:31.373029666
2024-04-01 04:45:31.373029666
tem rota aberta
dist order to order é  4.896129255310688 hub em questão 12
dist order to hub é  4.629212474278492 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 51
146
     order_id  order_latitude  order_longitude                ordered_at_brt  \
145       146      -23.603717       -46.557386 2024-04-01 04:45:45.019692144

     order_weight     sla_max_delivery_time_brt
145       9.85532 2024-04-01 06:45:45.019692144
2024-04-01 04:45:45.019692144
tem rota aberta
dist order to order é  5.988384672855039 hub em questão 8
dist order to hub é  2.265980999062519 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 8
passou aqui1
passou aqui5
route_id 55
caiu aqui tb
147
     order_id  order_latitude  order_longitude                ordered_at_brt  \
146       147      -23.635223       -46.641007 2024-04-01 04:46:15.716645468

     order_weight     sla_max_delivery_time_brt
146      6.790472 2024-04-01 05:46:15.716645468

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 04:46:15.716645468
tem rota aberta
dist order to order é  3.5565977713027572 hub em questão 15
dist order to hub é  2.347523192282442 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 52
148
     order_id  order_latitude  order_longitude                ordered_at_brt  \
147       148      -23.678399        -46.71897 2024-04-01 04:48:45.504805637

     order_weight     sla_max_delivery_time_brt
147      7.870088 2024-04-01 06:48:45.504805637
2024-04-01 04:48:45.504805637
tem rota aberta
dist order to order é  7.480970538177876 hub em questão 9
dist order to hub é  3.314330053337852 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 9
passou aqui1
rota em aberto, route_id:  50
rota_escolhida: 50
orders no hub: 1
passou aqui3
passou aqui4
149
     order_id  order_latitude  order_longitude                ordered_at_brt  \
148       149      -23.629307       -46.663858 2024-04-01 04:50:23.945309986

     order_weight     sla_max_delivery_time_brt
148      8.843661 2024-04-01 06:50:23.945309986
2024-04-01 04:50:23.945309986
tem rota aberta
dist order to order é  1.3840071016313265 hub em questão 15
dist order to hub é  1.5671772158021922 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 52

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

150
     order_id  order_latitude  order_longitude                ordered_at_brt  \
149       150      -23.613753       -46.615963 2024-04-01 04:50:25.461566695

     order_weight     sla_max_delivery_time_brt
149          0.01 2024-04-01 06:50:25.461566695
2024-04-01 04:50:25.461566695
tem rota aberta
dist order to order é  3.494096454932812 hub em questão 15
dist order to hub é  0.6522467175561861 hub em questão 13
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 13
hub_order 15
passou aqui1
passou aqui5
route_id 56
caiu aqui tb
151
     order_id  order_latitude  order_longitude                ordered_at_brt  \
150       151      -23.554622       -46.587019 2024-04-01 04:50:34.425066382

     order_weight     sla_max_delivery_time_brt
150      8.921393 2024-04-01 06:50:34.425066382
2024-04-01 04:50:34.425066382
tem rota aberta
dist order to order é  1.1253571824090198 hub em questão 8
dist order to hub é  6.861275753611068 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 53
152
     order_id  order_latitude  order_longitude                ordered_at_brt  \
151       152      -23.656742       -46.704702 2024-04-01 04:57:24.783859549

     order_weight     sla_max_delivery_time_brt
151      0.769926 2024-04-01 05:57:24.783859549
2024-04-01 04:57:24.783859549
tem rota aberta
dist order to order é  2.8125381294231544 hub em questão 9
dist order to hub é  0.5124705239235016 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 9
passou aqui1
rota em aberto, route_id:  50
rota_escolhida: 50
orders no hub: 2
passou aqui3
passou aqui4
153

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
152       153      -23.586235        -46.65754 2024-04-01 04:59:05.531331771

     order_weight     sla_max_delivery_time_brt
152      7.961607 2024-04-01 06:59:05.531331771
2024-04-01 04:59:05.531331771
tem rota aberta
dist order to order é  3.850702735196352 hub em questão 15
dist order to hub é  2.6526900515526113 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 52
154
     order_id  order_latitude  order_longitude                ordered_at_brt  \
153       154      -23.672813       -46.636346 2024-04-01 04:59:32.803562682

     order_weight     sla_max_delivery_time_brt
153      8.625845 2024-04-01 06:59:32.803562682
2024-04-01 04:59:32.803562682
tem rota aberta
dist order to order é  5.670393671556927 hub em questão 1
dist order to hub é  1.9926810449528 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 1
passou aqui1
passou aqui5
route_id 57
caiu aqui tb
155
     order_id  order_latitude  order_longitude                ordered_at_brt  \
154       155      -23.675709       -46.626263 2024-04-01 05:00:07.698108672

     order_weight     sla_max_delivery_time_brt
154      8.793837 2024-04-01 07:00:07.698108672
2024-04-01 05:00:07.698108672
tem rota aberta
dist order to order é  1.0761193019142072 hub em questão 5
dist order to hub é  3.0425596334204448 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 57

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

156
     order_id  order_latitude  order_longitude                ordered_at_brt  \
155       156      -23.629037       -46.602492 2024-04-01 05:02:51.125845662

     order_weight     sla_max_delivery_time_brt
155      5.245995 2024-04-01 08:02:51.125845662
2024-04-01 05:02:51.125845662
tem rota aberta
dist order to order é  2.1844596593840357 hub em questão 13
dist order to hub é  1.3347537593583452 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 56
157
     order_id  order_latitude  order_longitude                ordered_at_brt  \
156       157      -23.705974       -46.695435 2024-04-01 05:03:17.219444962

     order_weight     sla_max_delivery_time_brt
156      8.778979 2024-04-01 07:03:17.219444962
2024-04-01 05:03:17.219444962
tem rota aberta
dist order to order é  3.891584651794146 hub em questão 9
dist order to hub é  5.498856690672387 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 50
158
     order_id  order_latitude  order_longitude                ordered_at_brt  \
157       158      -23.715323       -46.669187 2024-04-01 05:05:01.708407503

     order_weight     sla_max_delivery_time_brt
157      8.756478 2024-04-01 06:05:01.708407503
2024-04-01 05:05:01.708407503
tem rota aberta
dist order to order é  1.1872626374627238 hub em questão 1
dist order to hub é  4.203110668938151 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 54
159
     order_id  order_latitude  order_longitude                ordered_at_brt  \
158       159      -23.602066       -46.597614 2024-04-01 05:12:02.575338184

     order_weight     sla_max_delivery_time_brt
158      9.891102 2024-04-01 08:12:02.575338184
2024-04-01 05:12:02.575338184
tem rota aberta
dist order to order é  2.276884661359246 hub em questão 13
dist order to hub é  2.4537504376729693 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 56
160
     order_id  order_latitude  order_longitude                ordered_at_brt  \
159       160      -23.748379       -46.628396 2024-04-01 05:15:47.719222819

     order_weight     sla_max_delivery_time_brt
159      2.310889 2024-04-01 08:15:47.719222819
2024-04-01 05:15:47.719222819
tem rota aberta
dist order to order é  8.083499502581025 hub em questão 5
dist order to hub é  3.9736814867671324 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 58
caiu aqui tb
161
     order_id  order_latitude  order_longitude                ordered_at_brt  \
160       161      -23.644558       -46.625594 2024-04-01 05:16:20.627608681

     order_weight     sla_max_delivery_time_brt
160      4.506555 2024-04-01 07:16:20.627608681
2024-04-01 05:16:20.627608681
tem rota aberta
dist order to order é  2.9183666826044887 hub em questão 13
dist order to hub é  2.3073923123224462 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 56
162

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
161       162      -23.666462       -46.591747 2024-04-01 05:17:42.319241051

     order_weight     sla_max_delivery_time_brt
161      7.999879 2024-04-01 07:17:42.319241051
2024-04-01 05:17:42.319241051
tem rota aberta
dist order to order é  3.6624028505411053 hub em questão 5
dist order to hub é  1.4837573494212275 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 5
passou aqui1
passou aqui5
route_id 59
caiu aqui tb
163
     order_id  order_latitude  order_longitude                ordered_at_brt  \
162       163      -23.668876        -46.64281 2024-04-01 05:19:38.415341348

     order_weight     sla_max_delivery_time_brt
162      6.349562 2024-04-01 08:19:38.415341348
2024-04-01 05:19:38.415341348
tem rota aberta
dist order to order é  0.7905786581567846 hub em questão 5
dist order to hub é  1.386244199106413 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 57
164
     order_id  order_latitude  order_longitude                ordered_at_brt  \
163       164      -23.716841       -46.621613 2024-04-01 05:23:10.332944969

     order_weight     sla_max_delivery_time_brt
163      9.065172 2024-04-01 07:23:10.332944969
2024-04-01 05:23:10.332944969
tem rota aberta
dist order to order é  3.5742561354949283 hub em questão 1
dist order to hub é  0.8007530146222614 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 1
passou aqui1
rota em aberto, route_id:  58
rota_escolhida: 58
orders no hub: 1
passou aqui3

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

passou aqui4
165
     order_id  order_latitude  order_longitude                ordered_at_brt  \
164       165       -23.75202       -46.663741 2024-04-01 05:23:30.797852447

     order_weight     sla_max_delivery_time_brt
164      8.414068 2024-04-01 07:23:30.797852447
2024-04-01 05:23:30.797852447
tem rota aberta
dist order to order é  3.6200517464399966 hub em questão 1
dist order to hub é  5.692324566644069 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 58
166
     order_id  order_latitude  order_longitude                ordered_at_brt  \
165       166      -23.683271       -46.715263 2024-04-01 05:23:33.047961259

     order_weight     sla_max_delivery_time_brt
165      7.621886 2024-04-01 08:23:33.047961259
2024-04-01 05:23:33.047961259
tem rota aberta
dist order to order é  7.549941498512425 hub em questão 5
dist order to hub é  3.6520620259471923 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 60
caiu aqui tb
167
     order_id  order_latitude  order_longitude                ordered_at_brt  \
166       167      -23.708486       -46.712776 2024-04-01 05:23:41.759301687

     order_weight     sla_max_delivery_time_brt
166      8.336359 2024-04-01 06:23:41.759301687
2024-04-01 05:23:41.759301687
tem rota aberta
dist order to order é  2.8152543011643645 hub em questão 9
dist order to hub é  6.317056802125415 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 60
168
     order_id  order_latitude  order_longitude                ordered_at_brt  \
167       168      -23.671496       -46.644297 2024-04-01 05:25:01.703741017

     order_weight     sla_max_delivery_time_brt
167      7.532962 2024-04-01 07:25:01.703741017

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 05:25:01.703741017
tem rota aberta
dist order to order é  0.32831701338438 hub em questão 5
dist order to hub é  1.1853259234702858 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 57
169
     order_id  order_latitude  order_longitude                ordered_at_brt  \
168       169      -23.645824       -46.657991 2024-04-01 05:26:53.572651006

     order_weight     sla_max_delivery_time_brt
168      4.371247 2024-04-01 06:26:53.572651006
2024-04-01 05:26:53.572651006
tem rota aberta
dist order to order é  7.126684525849176 hub em questão 12
dist order to hub é  2.9497300390875503 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
passou aqui5
route_id 61
caiu aqui tb
170
     order_id  order_latitude  order_longitude                ordered_at_brt  \
169       170      -23.687313       -46.680743 2024-04-01 05:28:34.528957574

     order_weight     sla_max_delivery_time_brt
169      8.590209 2024-04-01 08:28:34.528957574
2024-04-01 05:28:34.528957574
tem rota aberta
dist order to order é  3.5437850291781086 hub em questão 9
dist order to hub é  3.0317321924822287 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 60

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

171
     order_id  order_latitude  order_longitude                ordered_at_brt  \
170       171      -23.703852       -46.632112 2024-04-01 05:29:20.343898475

     order_weight     sla_max_delivery_time_brt
170      5.084198 2024-04-01 07:29:20.343898475
2024-04-01 05:29:20.343898475
tem rota aberta
dist order to order é  1.7968508041036042 hub em questão 1
dist order to hub é  1.0634102261581382 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 58
172
     order_id  order_latitude  order_longitude                ordered_at_brt  \
171       172      -23.635723       -46.692526 2024-04-01 05:38:17.411096348

     order_weight     sla_max_delivery_time_brt
171     11.651446 2024-04-01 06:38:17.411096348
2024-04-01 05:38:17.411096348
tem rota aberta
dist order to order é  3.692832003512354 hub em questão 5
dist order to hub é  2.142289637727095 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 61
173
     order_id  order_latitude  order_longitude                ordered_at_brt  \
172       173      -23.688317       -46.642446 2024-04-01 05:40:01.438392041

     order_weight     sla_max_delivery_time_brt
172     10.198428 2024-04-01 08:40:01.438392041
2024-04-01 05:40:01.438392041
tem rota aberta
dist order to order é  3.9012553078515686 hub em questão 9
dist order to hub é  2.2488632570657487 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 60
174
     order_id  order_latitude  order_longitude                ordered_at_brt  \
173       174      -23.698202       -46.648989 2024-04-01 05:40:58.830014998

     order_weight     sla_max_delivery_time_brt
173      4.932343 2024-04-01 07:40:58.830014998
2024-04-01 05:40:58.830014998
tem rota aberta
dist order to order é  5.895927382677218 hub em questão 5
dist order to hub é  2.6727233217309507 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 62
caiu aqui tb
175
     order_id  order_latitude  order_longitude                ordered_at_brt  \
174       175      -23.665183       -46.690012 2024-04-01 05:42:34.904063756

     order_weight     sla_max_delivery_time_brt
174      7.471229 2024-04-01 07:42:34.904063756
2024-04-01 05:42:34.904063756
tem rota aberta
dist order to order é  3.285771278792293 hub em questão 5
dist order to hub é  1.9523620697855926 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 61
176
     order_id  order_latitude  order_longitude                ordered_at_brt  \
175       176      -23.635951       -46.762923 2024-04-01 05:45:19.040554356

     order_weight     sla_max_delivery_time_brt
175      2.718031 2024-04-01 08:45:19.040554356
2024-04-01 05:45:19.040554356
tem rota aberta
dist order to order é  7.171158343768023 hub em questão 5
dist order to hub é  6.3595785653882135 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 61

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

177
     order_id  order_latitude  order_longitude                ordered_at_brt  \
176       177      -23.544788       -46.575186 2024-04-01 05:47:31.801445178

     order_weight     sla_max_delivery_time_brt
176      7.280238 2024-04-01 08:47:31.801445178
2024-04-01 05:47:31.801445178
tem rota aberta
dist order to order é  13.63442022809075 hub em questão 12
dist order to hub é  7.855218730824368 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 12
passou aqui1
passou aqui5
route_id 63
caiu aqui tb
178
     order_id  order_latitude  order_longitude                ordered_at_brt  \
177       178      -23.569547       -46.632181 2024-04-01 05:48:08.734486026

     order_weight     sla_max_delivery_time_brt
177     11.664486 2024-04-01 08:48:08.734486026
2024-04-01 05:48:08.734486026
tem rota aberta
dist order to order é  6.428703139457301 hub em questão 3
dist order to hub é  3.4778090489843416 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 3
passou aqui1
passou aqui5
route_id 64
caiu aqui tb
179
     order_id  order_latitude  order_longitude                ordered_at_brt  \
178       179      -23.713394       -46.781219 2024-04-01 05:48:16.970974042

     order_weight     sla_max_delivery_time_brt
178      7.560454 2024-04-01 06:48:16.970974042
2024-04-01 05:48:16.970974042
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  13.568279663091108 hub em questão 1
dist order to hub é  10.454675592400006 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 1
passou aqui1
passou aqui5
route_id 65
caiu aqui tb
180
     order_id  order_latitude  order_longitude                ordered_at_brt  \
179       180      -23.716438       -46.669334 2024-04-01 05:49:12.431267963

     order_weight     sla_max_delivery_time_brt
179      9.828449 2024-04-01 06:49:12.431267963
2024-04-01 05:49:12.431267963
tem rota aberta
dist order to order é  2.898682732336457 hub em questão 1
dist order to hub é  4.228631075316171 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 62
181
     order_id  order_latitude  order_longitude                ordered_at_brt  \
180       181      -23.646989       -46.628323 2024-04-01 05:51:11.649956377

     order_weight     sla_max_delivery_time_brt
180     10.673328 2024-04-01 06:51:11.649956377
2024-04-01 05:51:11.649956377
tem rota aberta
dist order to order é  6.071019758112444 hub em questão 1
dist order to hub é  2.670535523991594 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 1
passou aqui1
passou aqui5
route_id 66
caiu aqui tb
182
     order_id  order_latitude  order_longitude                ordered_at_brt  \
181       182      -23.622375        -46.65942 2024-04-01 05:51:39.963071196

     order_weight     sla_max_delivery_time_brt
181      7.411094 2024-04-01 06:51:39.963071196
2024-04-01 05:51:39.963071196
tem rota aberta
dist order to order é  4.186346959044486 hub em questão 14
dist order to hub é  0.6890332898804564 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 14
passou aqui1
passou aqui5
route_id 67
caiu aqui tb
183
     order_id  order_latitude  order_longitude                ordered_at_brt  \
182       183      -23.656811       -46.618996 2024-04-01 05:54:27.648403688

     order_weight     sla_max_delivery_time_brt
182     10.351738 2024-04-01 07:54:27.648403688

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 05:54:27.648403688
tem rota aberta
dist order to order é  1.4474536512974832 hub em questão 14
dist order to hub é  3.4857082136547555 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 66
184
     order_id  order_latitude  order_longitude                ordered_at_brt  \
183       184      -23.541609       -46.696676 2024-04-01 05:54:35.910811322

     order_weight     sla_max_delivery_time_brt
183      6.366734 2024-04-01 07:54:35.910811322
2024-04-01 05:54:35.910811322
tem rota aberta
dist order to order é  7.271053041348543 hub em questão 8
dist order to hub é  3.332926161836502 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 8
passou aqui1
passou aqui5
route_id 68
caiu aqui tb
185
     order_id  order_latitude  order_longitude                ordered_at_brt  \
184       185      -23.591372       -46.639254 2024-04-01 05:55:12.094530404

     order_weight     sla_max_delivery_time_brt
184      7.672778 2024-04-01 07:55:12.094530404
2024-04-01 05:55:12.094530404
tem rota aberta
dist order to order é  2.5315846410064204 hub em questão 8
dist order to hub é  1.0525876518117045 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 64
186
     order_id  order_latitude  order_longitude                ordered_at_brt  \
185       186      -23.568222       -46.650687 2024-04-01 05:58:28.114274129

     order_weight     sla_max_delivery_time_brt
185      2.443619 2024-04-01 06:58:28.114274129

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 05:58:28.114274129
tem rota aberta
dist order to order é  1.8918650959784493 hub em questão 8
dist order to hub é  3.866154054514807 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 64
187
     order_id  order_latitude  order_longitude                ordered_at_brt  \
186       187      -23.671119       -46.657166 2024-04-01 05:58:53.910662138

     order_weight     sla_max_delivery_time_brt
186      4.791629 2024-04-01 07:58:53.910662138
2024-04-01 05:58:53.910662138
tem rota aberta
dist order to order é  3.1244940790980014 hub em questão 1
dist order to hub é  0.1823127879309985 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 1
passou aqui1
passou aqui5
route_id 69
caiu aqui tb
188
     order_id  order_latitude  order_longitude                ordered_at_brt  \
187       188      -23.695069       -46.659064 2024-04-01 06:00:56.329239894

     order_weight     sla_max_delivery_time_brt
187      5.926778 2024-04-01 09:00:56.329239894
2024-04-01 06:00:56.329239894
tem rota aberta
dist order to order é  1.0833915017340474 hub em questão 1
dist order to hub é  2.5541737838358283 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 62

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

189
     order_id  order_latitude  order_longitude                ordered_at_brt  \
188       189       -23.70374       -46.638025 2024-04-01 06:02:25.578835453

     order_weight     sla_max_delivery_time_brt
188      8.644474 2024-04-01 08:02:25.578835453
2024-04-01 06:02:25.578835453
tem rota aberta
dist order to order é  1.2748988585448198 hub em questão 1
dist order to hub é  1.421658984455383 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 62
190
     order_id  order_latitude  order_longitude                ordered_at_brt  \
189       190      -23.655914       -46.601377 2024-04-01 06:07:36.104040612

     order_weight     sla_max_delivery_time_brt
189      3.654149 2024-04-01 08:07:36.104040612
2024-04-01 06:07:36.104040612
tem rota aberta
dist order to order é  1.7973383462827879 hub em questão 14
dist order to hub é  2.8300511989865877 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 66
191
     order_id  order_latitude  order_longitude                ordered_at_brt  \
190       191      -23.713143       -46.674519 2024-04-01 06:08:12.772457597

     order_weight     sla_max_delivery_time_brt
190      7.468518 2024-04-01 08:08:12.772457597
2024-04-01 06:08:12.772457597
tem rota aberta
dist order to order é  4.995762262183437 hub em questão 5
dist order to hub é  4.735746759221844 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 69

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

192
     order_id  order_latitude  order_longitude                ordered_at_brt  \
191       192      -23.681915       -46.668375 2024-04-01 06:08:20.960919535

     order_weight     sla_max_delivery_time_brt
191      2.201083 2024-04-01 08:08:20.960919535
2024-04-01 06:08:20.960919535
tem rota aberta
dist order to order é  1.6565229715119163 hub em questão 5
dist order to hub é  1.6613346131796103 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 69
193
     order_id  order_latitude  order_longitude                ordered_at_brt  \
192       193      -23.671764       -46.639985 2024-04-01 06:11:00.353847781

     order_weight     sla_max_delivery_time_brt
192      5.803546 2024-04-01 07:11:00.353847781
2024-04-01 06:11:00.353847781
tem rota aberta
dist order to order é  1.7512080444195615 hub em questão 5
dist order to hub é  1.6222758615294863 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 69
194
     order_id  order_latitude  order_longitude                ordered_at_brt  \
193       194      -23.603011        -46.65402 2024-04-01 06:13:57.856742144

     order_weight     sla_max_delivery_time_brt
193      4.900171 2024-04-01 08:13:57.856742144
2024-04-01 06:13:57.856742144
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.9846561746019287 hub em questão 8
dist order to hub é  1.521464886150388 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 64
195
     order_id  order_latitude  order_longitude                ordered_at_brt  \
194       195      -23.673869       -46.628733 2024-04-01 06:18:43.932794053

     order_weight     sla_max_delivery_time_brt
194     11.772533 2024-04-01 08:18:43.932794053
2024-04-01 06:18:43.932794053
tem rota aberta
dist order to order é  2.1403717683002936 hub em questão 14
dist order to hub é  2.7727292221842563 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 66
196
     order_id  order_latitude  order_longitude                ordered_at_brt  \
195       196      -23.720579       -46.612098 2024-04-01 06:24:06.473223377

     order_weight     sla_max_delivery_time_brt
195      4.702957 2024-04-01 08:24:06.473223377
2024-04-01 06:24:06.473223377
tem rota aberta
dist order to order é  21.68567085728129 hub em questão 4
dist order to hub é  1.8440933050146755 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 4
passou aqui1
passou aqui5
route_id 70
caiu aqui tb
197
     order_id  order_latitude  order_longitude                ordered_at_brt  \
196       197      -23.672599       -46.583453 2024-04-01 06:24:08.159200691

     order_weight     sla_max_delivery_time_brt
196      6.523876 2024-04-01 09:24:08.159200691
2024-04-01 06:24:08.159200691
tem rota aberta
dist order to order é  6.080283337037952 hub em questão 1
dist order to hub é  0.7490452637591483 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 1
passou aqui1
passou aqui5
route_id 71
caiu aqui tb
198
     order_id  order_latitude  order_longitude                ordered_at_brt  \
197       198      -23.640796       -46.653835 2024-04-01 06:24:40.204710885

     order_weight     sla_max_delivery_time_brt
197      9.673638 2024-04-01 08:24:40.204710885
2024-04-01 06:24:40.204710885
tem rota aberta
dist order to order é  7.993247659384388 hub em questão 12
dist order to hub é  2.5230134918698672 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 12
passou aqui1
passou aqui5
route_id 72
caiu aqui tb
199
     order_id  order_latitude  order_longitude                ordered_at_brt  \
198       199      -23.622179       -46.761878 2024-04-01 06:26:35.301721465

     order_weight     sla_max_delivery_time_brt
198      4.837158 2024-04-01 08:26:35.301721465
2024-04-01 06:26:35.301721465
tem rota aberta
dist order to order é  11.19934877166234 hub em questão 10
dist order to hub é  6.862789161702758 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 10
passou aqui1
passou aqui5
route_id 73
caiu aqui tb
200
     order_id  order_latitude  order_longitude                ordered_at_brt  \
199       200      -23.696308       -46.651494 2024-04-01 06:32:32.451686779

     order_weight     sla_max_delivery_time_brt
199      8.281368 2024-04-01 07:32:32.451686779
2024-04-01 06:32:32.451686779
tem rota aberta
dist order to order é  4.834306947452149 hub em questão 1
dist order to hub é  2.709075405047197 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 1
passou aqui1
passou aqui5
route_id 74
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

201
     order_id  order_latitude  order_longitude                ordered_at_brt  \
200       201      -23.617857       -46.630319 2024-04-01 06:38:32.362991982

     order_weight     sla_max_delivery_time_brt
200      6.640573 2024-04-01 08:38:32.362991982
2024-04-01 06:38:32.362991982
tem rota aberta
dist order to order é  3.4993334334599746 hub em questão 10
dist order to hub é  1.6454663941702612 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 72
202
     order_id  order_latitude  order_longitude                ordered_at_brt  \
201       202      -23.580884       -46.657361 2024-04-01 06:40:09.971345301

     order_weight     sla_max_delivery_time_brt
201       4.23332 2024-04-01 08:40:09.971345301
2024-04-01 06:40:09.971345301
tem rota aberta
dist order to order é  4.949121333782971 hub em questão 10
dist order to hub é  3.034384546660813 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 72
203
     order_id  order_latitude  order_longitude                ordered_at_brt  \
202       203       -23.62575       -46.655675 2024-04-01 06:45:06.642919029

     order_weight     sla_max_delivery_time_brt
202      4.680338 2024-04-01 08:45:06.642919029
2024-04-01 06:45:06.642919029
tem rota aberta
dist order to order é  1.6835795153969073 hub em questão 10
dist order to hub é  0.8572250165167853 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 72
204
     order_id  order_latitude  order_longitude                ordered_at_brt  \
203       204      -23.638286       -46.769638 2024-04-01 06:47:09.764277339

     order_weight     sla_max_delivery_time_brt
203      9.251567 2024-04-01 08:47:09.764277339
2024-04-01 06:47:09.764277339
tem rota aberta
dist order to order é  1.9576533118939592 hub em questão 9
dist order to hub é  6.9544687236519405 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 73
205
     order_id  order_latitude  order_longitude                ordered_at_brt  \
204       205      -23.672631       -46.622614 2024-04-01 06:48:09.081353502

     order_weight     sla_max_delivery_time_brt
204      5.189334 2024-04-01 08:48:09.081353502
2024-04-01 06:48:09.081353502
tem rota aberta
dist order to order é  3.947203317804741 hub em questão 5
dist order to hub é  3.390504142960017 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 74
206
     order_id  order_latitude  order_longitude                ordered_at_brt  \
205       206      -23.680765       -46.664214 2024-04-01 06:49:28.943016257

     order_weight     sla_max_delivery_time_brt
205      9.260717 2024-04-01 09:49:28.943016257
2024-04-01 06:49:28.943016257
tem rota aberta
dist order to order é  2.159822974474998 hub em questão 5
dist order to hub é  1.2672449870160925 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 74
207
     order_id  order_latitude  order_longitude                ordered_at_brt  \
206       207      -23.751723       -46.723567 2024-04-01 06:51:20.198067020

     order_weight     sla_max_delivery_time_brt
206      7.080127 2024-04-01 07:51:20.198067020
2024-04-01 06:51:20.198067020
tem rota aberta
dist order to order é  9.581102342936338 hub em questão 5
dist order to hub é  10.653809935748061 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 74
208
     order_id  order_latitude  order_longitude                ordered_at_brt  \
207       208      -23.619828       -46.691584 2024-04-01 06:52:55.898496816

     order_weight     sla_max_delivery_time_brt
207      4.434839 2024-04-01 07:52:55.898496816
2024-04-01 06:52:55.898496816
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  7.166212167303326 hub em questão 9
dist order to hub é  3.2700225098300653 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 9
passou aqui1
passou aqui5
route_id 75
caiu aqui tb
209
     order_id  order_latitude  order_longitude                ordered_at_brt  \
208       209      -23.667931       -46.691254 2024-04-01 06:58:08.635885823

     order_weight     sla_max_delivery_time_brt
208      6.775154 2024-04-01 07:58:08.635885823
2024-04-01 06:58:08.635885823
tem rota aberta
dist order to order é  5.348897126552863 hub em questão 15
dist order to hub é  2.1104726188526612 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 76
caiu aqui tb
210
     order_id  order_latitude  order_longitude                ordered_at_brt  \
209       210      -23.642596       -46.617575 2024-04-01 07:03:09.838358954

     order_weight     sla_max_delivery_time_brt
209      13.34361 2024-04-01 09:03:09.838358954
2024-04-01 07:03:09.838358954
tem rota aberta
dist order to order é  7.953034618590882 hub em questão 15
dist order to hub é  1.8990474581033838 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 15
passou aqui1
passou aqui5
route_id 77
caiu aqui tb
211
     order_id  order_latitude  order_longitude                ordered_at_brt  \
210       211      -23.625162       -46.619931 2024-04-01 07:04:10.116908187

     order_weight     sla_max_delivery_time_brt
210      7.190036 2024-04-01 09:04:10.116908187
2024-04-01 07:04:10.116908187
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.9534432000658595 hub em questão 14
dist order to hub é  0.3501812386393359 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 77
212
     order_id  order_latitude  order_longitude                ordered_at_brt  \
211       212      -23.689545       -46.572275 2024-04-01 07:10:46.591870754

     order_weight     sla_max_delivery_time_brt
211       4.63736 2024-04-01 10:10:46.591870754
2024-04-01 07:10:46.591870754
tem rota aberta
dist order to order é  6.966953107515797 hub em questão 14
dist order to hub é  2.3677248426100337 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 14
passou aqui1
passou aqui5
route_id 78
caiu aqui tb
213
     order_id  order_latitude  order_longitude                ordered_at_brt  \
212       213      -23.599376       -46.615617 2024-04-01 07:11:09.524690906

     order_weight     sla_max_delivery_time_brt
212       7.98334 2024-04-01 09:11:09.524690906
2024-04-01 07:11:09.524690906
tem rota aberta
dist order to order é  2.9007792916837243 hub em questão 14
dist order to hub é  2.1535341597614077 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 77
214
     order_id  order_latitude  order_longitude                ordered_at_brt  \
213       214       -23.64457       -46.715595 2024-04-01 07:11:25.730930779

     order_weight     sla_max_delivery_time_brt
213      5.835266 2024-04-01 10:11:25.730930779
2024-04-01 07:11:25.730930779
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.590805825290508 hub em questão 9
dist order to hub é  1.5386793333530384 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 9
passou aqui1
rota em aberto, route_id:  76
rota_escolhida: 76
orders no hub: 1
passou aqui3
passou aqui4
215
     order_id  order_latitude  order_longitude                ordered_at_brt  \
214       215      -23.575376       -46.718473 2024-04-01 07:11:43.145005390

     order_weight     sla_max_delivery_time_brt
214      2.814613 2024-04-01 09:11:43.145005390
2024-04-01 07:11:43.145005390
tem rota aberta
dist order to order é  5.651500929441211 hub em questão 15
dist order to hub é  1.929374022051996 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 15
passou aqui1
passou aqui5
route_id 79
caiu aqui tb
216
     order_id  order_latitude  order_longitude                ordered_at_brt  \
215       216      -23.641778       -46.591477 2024-04-01 07:13:07.689339835

     order_weight     sla_max_delivery_time_brt
215      8.110164 2024-04-01 09:13:07.689339835
2024-04-01 07:13:07.689339835
tem rota aberta
dist order to order é  2.660037962511747 hub em questão 14
dist order to hub é  3.1250853543001758 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 77
217
     order_id  order_latitude  order_longitude                ordered_at_brt  \
216       217      -23.634294       -46.569678 2024-04-01 07:13:10.300520967

     order_weight     sla_max_delivery_time_brt
216      4.007693 2024-04-01 10:13:10.300520967
2024-04-01 07:13:10.300520967
tem rota aberta
dist order to order é  6.149370850706214 hub em questão 12
dist order to hub é  2.182156140629107 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 12
passou aqui1
passou aqui5
route_id 80
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

218
     order_id  order_latitude  order_longitude                ordered_at_brt  \
217       218      -23.663894         -46.6599 2024-04-01 07:19:05.013184553

     order_weight     sla_max_delivery_time_brt
217     10.710204 2024-04-01 09:19:05.013184553
2024-04-01 07:19:05.013184553
tem rota aberta
dist order to order é  3.2246097347073563 hub em questão 9
dist order to hub é  1.0176104814894584 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 9
passou aqui1
passou aqui5
route_id 81
caiu aqui tb
219
     order_id  order_latitude  order_longitude                ordered_at_brt  \
218       219      -23.576405       -46.620073 2024-04-01 07:22:35.628949043

     order_weight     sla_max_delivery_time_brt
218     10.348897 2024-04-01 09:22:35.628949043
2024-04-01 07:22:35.628949043
tem rota aberta
dist order to order é  8.234103751216736 hub em questão 3
dist order to hub é  3.1752028972539996 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 3
passou aqui1
passou aqui5
route_id 82
caiu aqui tb
220
     order_id  order_latitude  order_longitude                ordered_at_brt  \
219       220        -23.7554       -46.723257 2024-04-01 07:22:37.444897977

     order_weight     sla_max_delivery_time_brt
219      9.025721 2024-04-01 08:22:37.444897977
2024-04-01 07:22:37.444897977
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  10.257365763146236 hub em questão 9
dist order to hub é  10.798628306840163 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 76
221
     order_id  order_latitude  order_longitude                ordered_at_brt  \
220       221      -23.676867       -46.745209 2024-04-01 07:23:00.703652178

     order_weight     sla_max_delivery_time_brt
220      7.067356 2024-04-01 09:23:00.703652178
2024-04-01 07:23:00.703652178
tem rota aberta
dist order to order é  4.689781705389895 hub em questão 9
dist order to hub é  5.079170772378748 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 76
222
     order_id  order_latitude  order_longitude                ordered_at_brt  \
221       222      -23.665478       -46.706714 2024-04-01 07:23:49.131125919

     order_weight     sla_max_delivery_time_brt
221      4.386888 2024-04-01 09:23:49.131125919
2024-04-01 07:23:49.131125919
tem rota aberta
dist order to order é  4.770987068446317 hub em questão 5
dist order to hub é  1.5030489438724859 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 83
caiu aqui tb
223
     order_id  order_latitude  order_longitude                ordered_at_brt  \
222       223      -23.726746       -46.665872 2024-04-01 07:24:05.980148666

     order_weight     sla_max_delivery_time_brt
222      7.862301 2024-04-01 09:24:05.980148666
2024-04-01 07:24:05.980148666
tem rota aberta
dist order to order é  7.015256169067269 hub em questão 5
dist order to hub é  4.1616395842837335 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 84
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

224
     order_id  order_latitude  order_longitude                ordered_at_brt  \
223       224       -23.68996       -46.674082 2024-04-01 07:27:24.946655711

     order_weight     sla_max_delivery_time_brt
223      4.713446 2024-04-01 09:27:24.946655711
2024-04-01 07:27:24.946655711
tem rota aberta
dist order to order é  3.2382991106803027 hub em questão 5
dist order to hub é  2.70008658455596 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 81
225
     order_id  order_latitude  order_longitude                ordered_at_brt  \
224       225      -23.758831       -46.659518 2024-04-01 07:28:15.672823772

     order_weight     sla_max_delivery_time_brt
224     10.212177 2024-04-01 09:28:15.672823772
2024-04-01 07:28:15.672823772
tem rota aberta
dist order to order é  3.6258435995588507 hub em questão 1
dist order to hub é  6.055186123644061 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 84
226
     order_id  order_latitude  order_longitude                ordered_at_brt  \
225       226      -23.640706       -46.672564 2024-04-01 07:33:53.497267221

     order_weight     sla_max_delivery_time_brt
225      2.870045 2024-04-01 08:33:53.497267221
2024-04-01 07:33:53.497267221
tem rota aberta
dist order to order é  2.8830275947012374 hub em questão 5
dist order to hub é  3.0767729812425 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 81

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

227
     order_id  order_latitude  order_longitude                ordered_at_brt  \
226       227      -23.720487       -46.614048 2024-04-01 07:35:38.174199663

     order_weight     sla_max_delivery_time_brt
226     11.355159 2024-04-01 09:35:38.174199663
2024-04-01 07:35:38.174199663
tem rota aberta
dist order to order é  5.3213802981799185 hub em questão 1
dist order to hub é  1.6671458098928094 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 1
passou aqui1
rota em aberto, route_id:  84
rota_escolhida: 84
orders no hub: 2
passou aqui3
passou aqui4
228
     order_id  order_latitude  order_longitude                ordered_at_brt  \
227       228      -23.631732       -46.576635 2024-04-01 07:39:51.443456218

     order_weight     sla_max_delivery_time_brt
227       6.67597 2024-04-01 08:39:51.443456218
2024-04-01 07:39:51.443456218
tem rota aberta
dist order to order é  0.7638074511415753 hub em questão 3
dist order to hub é  1.815828421082005 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 80
229
     order_id  order_latitude  order_longitude                ordered_at_brt  \
228       229      -23.663314       -46.646203 2024-04-01 07:43:34.957660915

     order_weight     sla_max_delivery_time_brt
228      4.923475 2024-04-01 10:43:34.957660915
2024-04-01 07:43:34.957660915
tem rota aberta
dist order to order é  1.3964956014200134 hub em questão 5
dist order to hub é  1.40374541988808 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 81
230
     order_id  order_latitude  order_longitude                ordered_at_brt  \
229       230      -23.691861       -46.546513 2024-04-01 07:48:17.919653951

     order_weight     sla_max_delivery_time_brt
229      3.560274 2024-04-01 08:48:17.919653951
2024-04-01 07:48:17.919653951
tem rota aberta
dist order to order é  7.576901466674005 hub em questão 1
dist order to hub é  4.05971276698491 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 1
passou aqui1
passou aqui5
route_id 85
caiu aqui tb
231
     order_id  order_latitude  order_longitude                ordered_at_brt  \
230       231      -23.727914       -46.679733 2024-04-01 07:49:31.835386035

     order_weight     sla_max_delivery_time_brt
230      8.703792 2024-04-01 09:49:31.835386035
2024-04-01 07:49:31.835386035
tem rota aberta
dist order to order é  1.4169435384638516 hub em questão 1
dist order to hub é  5.532936105719862 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 84
232
     order_id  order_latitude  order_longitude                ordered_at_brt  \
231       232      -23.684368       -46.674268 2024-04-01 07:51:06.686060212

     order_weight     sla_max_delivery_time_brt
231      8.271614 2024-04-01 10:51:06.686060212
2024-04-01 07:51:06.686060212
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.9152984869977834 hub em questão 9
dist order to hub é  2.3028318560468555 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 83
233
     order_id  order_latitude  order_longitude                ordered_at_brt  \
232       233      -23.634694       -46.628626 2024-04-01 07:54:18.983675788

     order_weight     sla_max_delivery_time_brt
232      9.217346 2024-04-01 10:54:18.983675788
2024-04-01 07:54:18.983675788
tem rota aberta
dist order to order é  10.504524550238111 hub em questão 12
dist order to hub é  1.5987806114407717 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 12
passou aqui1
passou aqui5
route_id 86
caiu aqui tb
234
     order_id  order_latitude  order_longitude                ordered_at_brt  \
233       234      -23.656498       -46.665753 2024-04-01 07:54:59.361111276

     order_weight     sla_max_delivery_time_brt
233      6.676022 2024-04-01 10:54:59.361111276
2024-04-01 07:54:59.361111276
tem rota aberta
dist order to order é  4.492132158369181 hub em questão 14
dist order to hub é  2.021531037298316 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 14
passou aqui1
passou aqui5
route_id 87
caiu aqui tb
235
     order_id  order_latitude  order_longitude                ordered_at_brt  \
234       235      -23.616913        -46.58916 2024-04-01 07:56:20.222124880

     order_weight     sla_max_delivery_time_brt
234      5.247154 2024-04-01 09:56:20.222124880
2024-04-01 07:56:20.222124880
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.480431394024908 hub em questão 14
dist order to hub é  1.3928006732354945 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 14
passou aqui1
passou aqui5
route_id 88
caiu aqui tb
236
     order_id  order_latitude  order_longitude                ordered_at_brt  \
235       236      -23.689642       -46.680068 2024-04-01 07:58:09.910401391

     order_weight     sla_max_delivery_time_brt
235      7.309494 2024-04-01 10:58:09.910401391
2024-04-01 07:58:09.910401391
tem rota aberta
dist order to order é  3.963334465243824 hub em questão 5
dist order to hub é  3.12745186498027 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 87
237
     order_id  order_latitude  order_longitude                ordered_at_brt  \
236       237      -23.569926       -46.581878 2024-04-01 07:58:11.789023100

     order_weight     sla_max_delivery_time_brt
236      3.349525 2024-04-01 10:58:11.789023100
2024-04-01 07:58:11.789023100
tem rota aberta
dist order to order é  5.277208483346436 hub em questão 3
dist order to hub é  5.100385795710247 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 88
238
     order_id  order_latitude  order_longitude                ordered_at_brt  \
237       238      -23.662123       -46.638304 2024-04-01 07:59:59.804096869

     order_weight     sla_max_delivery_time_brt
237      6.493291 2024-04-01 09:59:59.804096869
2024-04-01 07:59:59.804096869
tem rota aberta
dist order to order é  2.8647411308144286 hub em questão 5
dist order to hub é  2.118726448587959 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 87
239
     order_id  order_latitude  order_longitude                ordered_at_brt  \
238       239      -23.692485        -46.51974 2024-04-01 08:01:08.034841984

     order_weight     sla_max_delivery_time_brt
238      4.482652 2024-04-01 11:01:08.034841984
2024-04-01 08:01:08.034841984
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.726973859244045 hub em questão 12
dist order to hub é  4.189704926275895 hub em questão 2
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 85
240
     order_id  order_latitude  order_longitude                ordered_at_brt  \
239       240      -23.584717       -46.671219 2024-04-01 08:04:25.667025462

     order_weight     sla_max_delivery_time_brt
239      10.83957 2024-04-01 11:04:25.667025462
2024-04-01 08:04:25.667025462
tem rota aberta
dist order to order é  7.050860037140819 hub em questão 14
dist order to hub é  3.288237617665969 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 14
passou aqui1
passou aqui5
route_id 89
caiu aqui tb
241
     order_id  order_latitude  order_longitude                ordered_at_brt  \
240       241      -23.582347       -46.658147 2024-04-01 08:05:11.110291227

     order_weight     sla_max_delivery_time_brt
240      8.392966 2024-04-01 10:05:11.110291227
2024-04-01 08:05:11.110291227
tem rota aberta
dist order to order é  1.3578685063583453 hub em questão 4
dist order to hub é  2.9776571279474098 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 89
242
     order_id  order_latitude  order_longitude                ordered_at_brt  \
241       242      -23.654734        -46.64073 2024-04-01 08:09:39.176716564

     order_weight     sla_max_delivery_time_brt
241      5.785694 2024-04-01 10:09:39.176716564
2024-04-01 08:09:39.176716564
tem rota aberta
dist order to order é  0.8579963199608196 hub em questão 5
dist order to hub é  2.489142114803574 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 87
243
     order_id  order_latitude  order_longitude                ordered_at_brt  \
242       243       -23.67444       -46.757064 2024-04-01 08:11:22.666116936

     order_weight     sla_max_delivery_time_brt
242      5.444641 2024-04-01 10:11:22.666116936
2024-04-01 08:11:22.666116936
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  13.267085335670759 hub em questão 4
dist order to hub é  6.0175656408995195 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 4
passou aqui1
passou aqui5
route_id 90
caiu aqui tb
244
     order_id  order_latitude  order_longitude                ordered_at_brt  \
243       244      -23.604722         -46.6179 2024-04-01 08:11:47.068528066

     order_weight     sla_max_delivery_time_brt
243      10.16135 2024-04-01 09:11:47.068528066
2024-04-01 08:11:47.068528066
tem rota aberta
dist order to order é  3.2267406700923913 hub em questão 3
dist order to hub é  1.6607196425145376 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 88
245
     order_id  order_latitude  order_longitude                ordered_at_brt  \
244       245      -23.694932        -46.62397 2024-04-01 08:14:53.168758941

     order_weight     sla_max_delivery_time_brt
244       5.09457 2024-04-01 10:14:53.168758941
2024-04-01 08:14:53.168758941
tem rota aberta
dist order to order é  6.7149343497803295 hub em questão 14
dist order to hub é  2.0119323083119993 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 14
passou aqui1
passou aqui5
route_id 91
caiu aqui tb
246
     order_id  order_latitude  order_longitude                ordered_at_brt  \
245       246      -23.603466       -46.642547 2024-04-01 08:16:46.788394436

     order_weight     sla_max_delivery_time_brt
245      6.582067 2024-04-01 10:16:46.788394436
2024-04-01 08:16:46.788394436
tem rota aberta
dist order to order é  2.515242226913609 hub em questão 3
dist order to hub é  0.6772951662191421 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 88
247
     order_id  order_latitude  order_longitude                ordered_at_brt  \
246       247      -23.719584       -46.725233 2024-04-01 08:16:53.438411351

     order_weight     sla_max_delivery_time_brt
246      8.692516 2024-04-01 11:16:53.438411351
2024-04-01 08:16:53.438411351
tem rota aberta
dist order to order é  5.975182005756754 hub em questão 9
dist order to hub é  7.805977725388067 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 90
248
     order_id  order_latitude  order_longitude                ordered_at_brt  \
247       248      -23.654395       -46.725341 2024-04-01 08:17:58.845750820

     order_weight     sla_max_delivery_time_brt
247      4.696273 2024-04-01 11:17:58.845750820
2024-04-01 08:17:58.845750820
tem rota aberta
dist order to order é  3.9251374231131018 hub em questão 9
dist order to hub é  2.2747969133661505 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 90

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

249
     order_id  order_latitude  order_longitude                ordered_at_brt  \
248       249      -23.649638       -46.618682 2024-04-01 08:20:15.229185577

     order_weight     sla_max_delivery_time_brt
248     10.790077 2024-04-01 11:20:15.229185577
2024-04-01 08:20:15.229185577
tem rota aberta
dist order to order é  1.946039927791983 hub em questão 14
dist order to hub é  2.6879983372473255 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 86
250
     order_id  order_latitude  order_longitude                ordered_at_brt  \
249       250       -23.58982       -46.589254 2024-04-01 08:25:16.237407419

     order_weight     sla_max_delivery_time_brt
249      7.775404 2024-04-01 10:25:16.237407419
2024-04-01 08:25:16.237407419
tem rota aberta
dist order to order é  7.069672442630691 hub em questão 4
dist order to hub é  3.170040087467215 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 4
passou aqui1
passou aqui5
route_id 92
caiu aqui tb
251
     order_id  order_latitude  order_longitude                ordered_at_brt  \
250       251      -23.741686        -46.56829 2024-04-01 08:25:16.285660106

     order_weight     sla_max_delivery_time_brt
250     11.740053 2024-04-01 10:25:16.285660106
2024-04-01 08:25:16.285660106
tem rota aberta
dist order to order é  7.691520060194136 hub em questão 1
dist order to hub é  1.9680478307139702 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 1
passou aqui1
passou aqui5
route_id 93
caiu aqui tb
252
     order_id  order_latitude  order_longitude                ordered_at_brt  \
251       252      -23.638504       -46.692785 2024-04-01 08:32:47.706907838

     order_weight     sla_max_delivery_time_brt
251      7.020352 2024-04-01 10:32:47.706907838

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 08:32:47.706907838
tem rota aberta
dist order to order é  3.757540992398099 hub em questão 9
dist order to hub é  1.866668463315514 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 90
253
     order_id  order_latitude  order_longitude                ordered_at_brt  \
252       253      -23.656261       -46.699553 2024-04-01 08:33:44.411148026

     order_weight     sla_max_delivery_time_brt
252     15.362084 2024-04-01 09:33:44.411148026
2024-04-01 08:33:44.411148026
tem rota aberta
dist order to order é  8.462820513583601 hub em questão 4
dist order to hub é  0.5648817180426636 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 4
passou aqui1
passou aqui5
route_id 94
caiu aqui tb
254
     order_id  order_latitude  order_longitude                ordered_at_brt  \
253       254       -23.65008        -46.66161 2024-04-01 08:41:01.375279055

     order_weight     sla_max_delivery_time_brt
253      8.218398 2024-04-01 11:41:01.375279055
2024-04-01 08:41:01.375279055
tem rota aberta
dist order to order é  3.9252683735820884 hub em questão 9
dist order to hub é  2.5362393045783347 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 94
255
     order_id  order_latitude  order_longitude                ordered_at_brt  \
254       255      -23.694431       -46.746799 2024-04-01 08:42:52.753403919

     order_weight     sla_max_delivery_time_brt
254      7.561744 2024-04-01 09:42:52.753403919
2024-04-01 08:42:52.753403919
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  6.4159012336330985 hub em questão 9
dist order to hub é  6.454826523296543 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 94
256
     order_id  order_latitude  order_longitude                ordered_at_brt  \
255       256       -23.71532       -46.677459 2024-04-01 08:46:24.576254446

     order_weight     sla_max_delivery_time_brt
255      3.009911 2024-04-01 10:46:24.576254446
2024-04-01 08:46:24.576254446
tem rota aberta
dist order to order é  6.941757639277648 hub em questão 9
dist order to hub é  5.043532555307877 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 94
257
     order_id  order_latitude  order_longitude                ordered_at_brt  \
256       257      -23.673382       -46.605423 2024-04-01 08:48:07.174757793

     order_weight     sla_max_delivery_time_brt
256       7.78163 2024-04-01 09:48:07.174757793
2024-04-01 08:48:07.174757793
tem rota aberta
dist order to order é  8.484013597742287 hub em questão 6
dist order to hub é  2.8996989306140355 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 6
passou aqui1
passou aqui5
route_id 95
caiu aqui tb
258
     order_id  order_latitude  order_longitude                ordered_at_brt  \
257       258      -23.662309       -46.566283 2024-04-01 08:50:05.862711374

     order_weight     sla_max_delivery_time_brt
257      2.843383 2024-04-01 09:50:05.862711374
2024-04-01 08:50:05.862711374
tem rota aberta
dist order to order é  4.172019735649134 hub em questão 12
dist order to hub é  1.341101518254172 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 12
passou aqui1
rota em aberto, route_id:  95
rota_escolhida: 95
orders no hub: 1
passou aqui3
passou aqui4
259
     order_id  order_latitude  order_longitude                ordered_at_brt  \
258       259      -23.576466       -46.634055 2024-04-01 08:50:46.216197332

     order_weight     sla_max_delivery_time_brt
258      6.134738 2024-04-01 10:50:46.216197332

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 08:50:46.216197332
tem rota aberta
dist order to order é  4.8010118128406605 hub em questão 3
dist order to hub é  2.691323778310085 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 3
passou aqui1
passou aqui5
route_id 96
caiu aqui tb
260
     order_id  order_latitude  order_longitude                ordered_at_brt  \
259       260      -23.644656       -46.565985 2024-04-01 08:52:32.284705399

     order_weight     sla_max_delivery_time_brt
259       6.01192 2024-04-01 10:52:32.284705399
2024-04-01 08:52:32.284705399
tem rota aberta
dist order to order é  1.963079700615676 hub em questão 12
dist order to hub é  2.922992061622285 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 95
261
     order_id  order_latitude  order_longitude                ordered_at_brt  \
260       261      -23.650439       -46.627469 2024-04-01 08:55:18.650475765

     order_weight     sla_max_delivery_time_brt
260      9.681041 2024-04-01 10:55:18.650475765
2024-04-01 08:55:18.650475765
tem rota aberta
dist order to order é  3.3984924645411585 hub em questão 12
dist order to hub é  2.984374244112015 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 95
262
     order_id  order_latitude  order_longitude                ordered_at_brt  \
261       262      -23.615308       -46.638445 2024-04-01 08:59:13.147369723

     order_weight     sla_max_delivery_time_brt
261      6.072781 2024-04-01 11:59:13.147369723
2024-04-01 08:59:13.147369723
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.342123188187883 hub em questão 8
dist order to hub é  1.650819606812665 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 8
passou aqui1
rota em aberto, route_id:  96
rota_escolhida: 96
orders no hub: 1
passou aqui3
passou aqui4
263
     order_id  order_latitude  order_longitude                ordered_at_brt  \
262       263      -23.730818       -46.656585 2024-04-01 09:02:01.967280265

     order_weight     sla_max_delivery_time_brt
262      6.159714 2024-04-01 11:02:01.967280265
2024-04-01 09:02:01.967280265
tem rota aberta
dist order to order é  12.976322173471813 hub em questão 8
dist order to hub é  3.542359674268308 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 8
passou aqui1
passou aqui5
route_id 97
caiu aqui tb
264
     order_id  order_latitude  order_longitude                ordered_at_brt  \
263       264      -23.614097       -46.638666 2024-04-01 09:04:25.669421541

     order_weight     sla_max_delivery_time_brt
263      4.639492 2024-04-01 12:04:25.669421541
2024-04-01 09:04:25.669421541
tem rota aberta
dist order to order é  0.13653338059000758 hub em questão 8
dist order to hub é  1.519789898974991 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 96
265
     order_id  order_latitude  order_longitude                ordered_at_brt  \
264       265      -23.604457       -46.660755 2024-04-01 09:08:25.505242637

     order_weight     sla_max_delivery_time_brt
264      5.899187 2024-04-01 12:08:25.505242637
2024-04-01 09:08:25.505242637
tem rota aberta
dist order to order é  2.492901686327596 hub em questão 8
dist order to hub é  1.245070721024514 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 96
266
     order_id  order_latitude  order_longitude                ordered_at_brt  \
265       266      -23.604868       -46.655058 2024-04-01 09:09:12.258792547

     order_weight     sla_max_delivery_time_brt
265      5.323682 2024-04-01 12:09:12.258792547
2024-04-01 09:09:12.258792547
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  14.00587491178998 hub em questão 1
dist order to hub é  1.2902218114008994 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 1
passou aqui1
passou aqui5
route_id 98
caiu aqui tb
267
     order_id  order_latitude  order_longitude                ordered_at_brt  \
266       267      -23.666875       -46.681107 2024-04-01 09:11:25.585483855

     order_weight     sla_max_delivery_time_brt
266     12.441924 2024-04-01 11:11:25.585483855
2024-04-01 09:11:25.585483855
tem rota aberta
dist order to order é  7.3878553455272975 hub em questão 15
dist order to hub é  2.6361835108309943 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 15
passou aqui1
passou aqui5
route_id 99
caiu aqui tb
268
     order_id  order_latitude  order_longitude                ordered_at_brt  \
267       268      -23.711988       -46.635061 2024-04-01 09:12:37.516752632

     order_weight     sla_max_delivery_time_brt
267      4.428356 2024-04-01 11:12:37.516752632
2024-04-01 09:12:37.516752632
tem rota aberta
dist order to order é  3.0306962135260824 hub em questão 1
dist order to hub é  0.722067464272822 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 1
passou aqui1
rota em aberto, route_id:  97
rota_escolhida: 97
orders no hub: 1
passou aqui3
passou aqui4
269
     order_id  order_latitude  order_longitude                ordered_at_brt  \
268       269      -23.699472        -46.64729 2024-04-01 09:13:35.288724724

     order_weight     sla_max_delivery_time_brt
268       3.54874 2024-04-01 11:13:35.288724724
2024-04-01 09:13:35.288724724
tem rota aberta
dist order to order é  1.8673881392035918 hub em questão 1
dist order to hub é  2.4496551292911413 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 97
270
     order_id  order_latitude  order_longitude                ordered_at_brt  \
269       270      -23.637853       -46.721992 2024-04-01 09:14:38.769787666

     order_weight     sla_max_delivery_time_brt
269      5.129265 2024-04-01 12:14:38.769787666
2024-04-01 09:14:38.769787666
tem rota aberta
dist order to order é  5.268347398226327 hub em questão 5
dist order to hub é  2.510332712054625 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 100
caiu aqui tb
271
     order_id  order_latitude  order_longitude                ordered_at_brt  \
270       271      -23.623387       -46.660048 2024-04-01 09:15:40.365144673

     order_weight     sla_max_delivery_time_brt
270     10.264332 2024-04-01 11:15:40.365144673
2024-04-01 09:15:40.365144673
tem rota aberta
dist order to order é  2.121035235160221 hub em questão 15
dist order to hub é  0.8137122685738728 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 98
272
     order_id  order_latitude  order_longitude                ordered_at_brt  \
271       272      -23.586398       -46.690796 2024-04-01 09:16:26.183871532

     order_weight     sla_max_delivery_time_brt
271      1.180709 2024-04-01 12:16:26.183871532
2024-04-01 09:16:26.183871532
tem rota aberta
dist order to order é  4.180876240306422 hub em questão 15
dist order to hub é  1.9130881490225853 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 15
passou aqui1
passou aqui5
route_id 101
caiu aqui tb
273
     order_id  order_latitude  order_longitude                ordered_at_brt  \
272       273      -23.574154       -46.750423 2024-04-01 09:18:22.901606779

     order_weight     sla_max_delivery_time_brt
272       11.1771 2024-04-01 12:18:22.901606779
2024-04-01 09:18:22.901606779
tem rota aberta
dist order to order é  6.227211394808148 hub em questão 4
dist order to hub é  2.177782982165987 hub em questão 11
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 11
hub_order 4
passou aqui1
passou aqui5
route_id 102
caiu aqui tb
274
     order_id  order_latitude  order_longitude                ordered_at_brt  \
273       274      -23.606663       -46.623819 2024-04-01 09:19:30.407945267

     order_weight     sla_max_delivery_time_brt
273      4.209059 2024-04-01 11:19:30.407945267
2024-04-01 09:19:30.407945267
tem rota aberta
dist order to order é  3.1892823951839206 hub em questão 15
dist order to hub é  1.479384752136872 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 98
275
     order_id  order_latitude  order_longitude                ordered_at_brt  \
274       275      -23.648529       -46.570078 2024-04-01 09:26:47.456967054

     order_weight     sla_max_delivery_time_brt
274      4.018057 2024-04-01 11:26:47.456967054
2024-04-01 09:26:47.456967054
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  7.186387701481324 hub em questão 15
dist order to hub é  2.3715211529373903 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 15
passou aqui1
passou aqui5
route_id 103
caiu aqui tb
276
     order_id  order_latitude  order_longitude                ordered_at_brt  \
275       276      -23.636979       -46.529526 2024-04-01 09:29:03.367236048

     order_weight     sla_max_delivery_time_brt
275      3.010877 2024-04-01 11:29:03.367236048
2024-04-01 09:29:03.367236048
tem rota aberta
dist order to order é  4.325744228965178 hub em questão 12
dist order to hub é  2.712045650505264 hub em questão 2
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 103
277
     order_id  order_latitude  order_longitude                ordered_at_brt  \
276       277      -23.661991       -46.569892 2024-04-01 09:29:29.930136980

     order_weight     sla_max_delivery_time_brt
276      8.341526 2024-04-01 11:29:29.930136980
2024-04-01 09:29:29.930136980
tem rota aberta
dist order to order é  1.497035265314574 hub em questão 12
dist order to hub é  1.0740081747663395 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 103
278
     order_id  order_latitude  order_longitude                ordered_at_brt  \
277       278      -23.597482       -46.691553 2024-04-01 09:30:36.691884939

     order_weight     sla_max_delivery_time_brt
277      4.911616 2024-04-01 12:30:36.691884939
2024-04-01 09:30:36.691884939
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.2349021320254705 hub em questão 4
dist order to hub é  3.0239041658921377 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 101
279
     order_id  order_latitude  order_longitude                ordered_at_brt  \
278       279      -23.620512       -46.589251 2024-04-01 09:31:27.163693009

     order_weight     sla_max_delivery_time_brt
278      7.474957 2024-04-01 11:31:27.163693009
2024-04-01 09:31:27.163693009
tem rota aberta
dist order to order é  3.6769357680289905 hub em questão 12
dist order to hub é  1.5024791593491866 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 12
passou aqui1
passou aqui5
route_id 104
caiu aqui tb
280
     order_id  order_latitude  order_longitude                ordered_at_brt  \
279       280      -23.639432       -46.592018 2024-04-01 09:34:38.887822502

     order_weight     sla_max_delivery_time_brt
279      7.038114 2024-04-01 12:34:38.887822502
2024-04-01 09:34:38.887822502
tem rota aberta
dist order to order é  2.1226801999028764 hub em questão 3
dist order to hub é  2.9078342164255373 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 104
281
     order_id  order_latitude  order_longitude                ordered_at_brt  \
280       281      -23.713005       -46.747404 2024-04-01 09:38:53.317735421

     order_weight     sla_max_delivery_time_brt
280          0.01 2024-04-01 11:38:53.317735421
2024-04-01 09:38:53.317735421
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  8.47839080103214 hub em questão 5
dist order to hub é  8.111727825338173 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 99
282
     order_id  order_latitude  order_longitude                ordered_at_brt  \
281       282      -23.597892       -46.604948 2024-04-01 09:43:34.329193144

     order_weight     sla_max_delivery_time_brt
281      6.726697 2024-04-01 11:43:34.329193144
2024-04-01 09:43:34.329193144
tem rota aberta
dist order to order é  2.9806457375757227 hub em questão 3
dist order to hub é  2.487404067034284 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 104
283
     order_id  order_latitude  order_longitude                ordered_at_brt  \
282       283       -23.72657       -46.616654 2024-04-01 09:45:44.750146357

     order_weight     sla_max_delivery_time_brt
282      8.139566 2024-04-01 11:45:44.750146357
2024-04-01 09:45:44.750146357
tem rota aberta
dist order to order é  8.615988701595137 hub em questão 12
dist order to hub é  1.932051787117637 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 12
passou aqui1
passou aqui5
route_id 105
caiu aqui tb
284
     order_id  order_latitude  order_longitude                ordered_at_brt  \
283       284      -23.588636       -46.639872 2024-04-01 09:46:22.549675476

     order_weight     sla_max_delivery_time_brt
283      3.137355 2024-04-01 12:46:22.549675476
2024-04-01 09:46:22.549675476
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.7046082066738024 hub em questão 3
dist order to hub é  1.3629857603045448 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 3
passou aqui1
passou aqui5
route_id 106
caiu aqui tb
285
     order_id  order_latitude  order_longitude                ordered_at_brt  \
284       285      -23.600994       -46.633582 2024-04-01 09:46:57.450795140

     order_weight     sla_max_delivery_time_brt
284      2.970824 2024-04-01 11:46:57.450795140
2024-04-01 09:46:57.450795140
tem rota aberta
dist order to order é  1.5162582199134453 hub em questão 8
dist order to hub é  0.3228515498725301 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 106
286
     order_id  order_latitude  order_longitude                ordered_at_brt  \
285       286      -23.729579       -46.645097 2024-04-01 09:50:49.088948021

     order_weight     sla_max_delivery_time_brt
285      6.719917 2024-04-01 11:50:49.088948021
2024-04-01 09:50:49.088948021
tem rota aberta
dist order to order é  2.914681189627474 hub em questão 1
dist order to hub é  2.563834408457807 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 105
287
     order_id  order_latitude  order_longitude                ordered_at_brt  \
286       287      -23.652649       -46.566416 2024-04-01 09:52:19.109577600

     order_weight     sla_max_delivery_time_brt
286     11.678037 2024-04-01 11:52:19.109577600
2024-04-01 09:52:19.109577600
tem rota aberta
dist order to order é  0.590759579652179 hub em questão 12
dist order to hub é  2.113441649710847 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 103
288
     order_id  order_latitude  order_longitude                ordered_at_brt  \
287       288      -23.712295       -46.668102 2024-04-01 09:55:33.545833797

     order_weight     sla_max_delivery_time_brt
287     11.291769 2024-04-01 11:55:33.545833797
2024-04-01 09:55:33.545833797
tem rota aberta
dist order to order é  3.0295386957331165 hub em questão 1
dist order to hub é  4.08237109876948 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 105
289
     order_id  order_latitude  order_longitude                ordered_at_brt  \
288       289      -23.657456        -46.65801 2024-04-01 09:57:15.518729468

     order_weight     sla_max_delivery_time_brt
288     12.131589 2024-04-01 10:57:15.518729468
2024-04-01 09:57:15.518729468
tem rota aberta
dist order to order é  6.183795812743724 hub em questão 1
dist order to hub é  1.6624451880832598 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 1
passou aqui1
passou aqui5
route_id 107
caiu aqui tb
290
     order_id  order_latitude  order_longitude                ordered_at_brt  \
289       290      -23.622467       -46.647643 2024-04-01 09:59:54.043597349

     order_weight     sla_max_delivery_time_brt
289       4.38303 2024-04-01 11:59:54.043597349
2024-04-01 09:59:54.043597349
tem rota aberta
dist order to order é  2.7845227573556572 hub em questão 8
dist order to hub é  0.8505706481507332 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 106
291
     order_id  order_latitude  order_longitude                ordered_at_brt  \
290       291      -23.657057        -46.63423 2024-04-01 10:01:21.873059271

     order_weight     sla_max_delivery_time_brt
290      8.662046 2024-04-01 11:01:21.873059271
2024-04-01 10:01:21.873059271
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.422428756253193 hub em questão 5
dist order to hub é  2.781883181155476 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 107
292
     order_id  order_latitude  order_longitude                ordered_at_brt  \
291       292      -23.718419       -46.736175 2024-04-01 10:04:18.696234811

     order_weight     sla_max_delivery_time_brt
291      5.382403 2024-04-01 13:04:18.696234811
2024-04-01 10:04:18.696234811
tem rota aberta
dist order to order é  6.963561374905084 hub em questão 1
dist order to hub é  8.079175703512432 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 105
293
     order_id  order_latitude  order_longitude                ordered_at_brt  \
292       293      -23.637184       -46.578614 2024-04-01 10:05:59.654365437

     order_weight     sla_max_delivery_time_brt
292      9.074908 2024-04-01 12:05:59.654365437
2024-04-01 10:05:59.654365437
tem rota aberta
dist order to order é  6.080656993951432 hub em questão 5
dist order to hub é  2.4384703692681886 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 5
passou aqui1
passou aqui5
route_id 108
caiu aqui tb
294
     order_id  order_latitude  order_longitude                ordered_at_brt  \
293       294      -23.637251       -46.636703 2024-04-01 10:07:14.872320121

     order_weight     sla_max_delivery_time_brt
293      6.722988 2024-04-01 12:07:14.872320121
2024-04-01 10:07:14.872320121
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.9861162844157056 hub em questão 8
dist order to hub é  2.433489412169875 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 106
295
     order_id  order_latitude  order_longitude                ordered_at_brt  \
294       295      -23.651587       -46.619557 2024-04-01 10:08:05.224064363

     order_weight     sla_max_delivery_time_brt
294      1.437819 2024-04-01 11:08:05.224064363
2024-04-01 10:08:05.224064363
tem rota aberta
dist order to order é  1.6135272642978884 hub em questão 5
dist order to hub é  2.9122146043447388 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 107
296
     order_id  order_latitude  order_longitude                ordered_at_brt  \
295       296      -23.702482       -46.638147 2024-04-01 10:08:13.701717838

     order_weight     sla_max_delivery_time_brt
295      8.706201 2024-04-01 13:08:13.701717838
2024-04-01 10:08:13.701717838
tem rota aberta
dist order to order é  5.066769866690115 hub em questão 5
dist order to hub é  1.5307233460387861 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 109
caiu aqui tb
297
     order_id  order_latitude  order_longitude                ordered_at_brt  \
296       297      -23.667714       -46.657335 2024-04-01 10:09:10.664913296

     order_weight     sla_max_delivery_time_brt
296       0.76642 2024-04-01 12:09:10.664913296
2024-04-01 10:09:10.664913296
tem rota aberta
dist order to order é  1.1427213459328711 hub em questão 5
dist order to hub é  0.5283877869039147 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 107
298
     order_id  order_latitude  order_longitude                ordered_at_brt  \
297       298      -23.636799       -46.665775 2024-04-01 10:09:20.621943803

     order_weight     sla_max_delivery_time_brt
297     14.042848 2024-04-01 13:09:20.621943803
2024-04-01 10:09:20.621943803
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  7.8268806954982635 hub em questão 1
dist order to hub é  2.3735293077296284 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 1
passou aqui1
passou aqui5
route_id 110
caiu aqui tb
299
     order_id  order_latitude  order_longitude                ordered_at_brt  \
298       299      -23.657978       -46.643207 2024-04-01 10:17:28.282908780

     order_weight     sla_max_delivery_time_brt
298     15.118375 2024-04-01 11:17:28.282908780
2024-04-01 10:17:28.282908780
tem rota aberta
dist order to order é  3.290901238581794 hub em questão 10
dist order to hub é  2.049905733354964 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 110
300
     order_id  order_latitude  order_longitude                ordered_at_brt  \
299       300      -23.544594        -46.64041 2024-04-01 10:17:52.333280875

     order_weight     sla_max_delivery_time_brt
299      5.045915 2024-04-01 11:17:52.333280875
2024-04-01 10:17:52.333280875
tem rota aberta
dist order to order é  10.573500956083542 hub em questão 10
dist order to hub é  6.2330662277875435 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 10
passou aqui1
passou aqui5
route_id 111
caiu aqui tb
301
     order_id  order_latitude  order_longitude                ordered_at_brt  \
300       301      -23.637421        -46.59025 2024-04-01 10:21:12.800719746

     order_weight     sla_max_delivery_time_brt
300      6.850872 2024-04-01 11:21:12.800719746
2024-04-01 10:21:12.800719746
tem rota aberta
dist order to order é  1.1855664708384381 hub em questão 3
dist order to hub é  2.8654970909554542 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 108
302
     order_id  order_latitude  order_longitude                ordered_at_brt  \
301       302      -23.660563        -46.63071 2024-04-01 10:25:22.296889553

     order_weight     sla_max_delivery_time_brt
301      7.239369 2024-04-01 12:25:22.296889553
2024-04-01 10:25:22.296889553
tem rota aberta
dist order to order é  1.3048907627167248 hub em questão 10
dist order to hub é  2.877798275798686 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 110
303
     order_id  order_latitude  order_longitude                ordered_at_brt  \
302       303      -23.626095       -46.654687 2024-04-01 10:27:42.226189074

     order_weight     sla_max_delivery_time_brt
302      8.103768 2024-04-01 11:27:42.226189074
2024-04-01 10:27:42.226189074
tem rota aberta
dist order to order é  1.6408263254530155 hub em questão 10
dist order to hub é  0.8876130529389875 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 110
304
     order_id  order_latitude  order_longitude                ordered_at_brt  \
303       304      -23.705497       -46.548685 2024-04-01 10:29:23.361586274

     order_weight     sla_max_delivery_time_brt
303      8.775203 2024-04-01 13:29:23.361586274
2024-04-01 10:29:23.361586274
tem rota aberta
dist order to order é  8.184779740751383 hub em questão 3
dist order to hub é  3.5684741405963356 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 3
passou aqui1
passou aqui5
route_id 112
caiu aqui tb
305
     order_id  order_latitude  order_longitude                ordered_at_brt  \
304       305      -23.629188       -46.711984 2024-04-01 10:29:44.422849726

     order_weight     sla_max_delivery_time_brt
304       2.03899 2024-04-01 12:29:44.422849726
2024-04-01 10:29:44.422849726
tem rota aberta
dist order to order é  11.089221961146261 hub em questão 1
dist order to hub é  2.7312927862783725 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 1
passou aqui1
passou aqui5
route_id 113
caiu aqui tb
306
     order_id  order_latitude  order_longitude                ordered_at_brt  \
305       306      -23.569386       -46.715023 2024-04-01 10:30:59.903903583

     order_weight     sla_max_delivery_time_brt
305      3.908662 2024-04-01 12:30:59.903903583
2024-04-01 10:30:59.903903583
tem rota aberta
dist order to order é  6.656889690406154 hub em questão 9
dist order to hub é  1.5438016299394166 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 9
passou aqui1
passou aqui5
route_id 114
caiu aqui tb
307
     order_id  order_latitude  order_longitude                ordered_at_brt  \
306       307      -23.694414       -46.630283 2024-04-01 10:31:50.709833747

     order_weight     sla_max_delivery_time_brt
306      9.522583 2024-04-01 11:31:50.709833747
2024-04-01 10:31:50.709833747
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.2025280250673245 hub em questão 1
dist order to hub é  2.0404010875072593 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 109
308
     order_id  order_latitude  order_longitude                ordered_at_brt  \
307       308      -23.635284       -46.658631 2024-04-01 10:32:21.303090878

     order_weight     sla_max_delivery_time_brt
307      8.350078 2024-04-01 12:32:21.303090878
2024-04-01 10:32:21.303090878
tem rota aberta
dist order to order é  5.477138604003828 hub em questão 9
dist order to hub é  1.954750158819116 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 9
passou aqui1
passou aqui5
route_id 115
caiu aqui tb
309
     order_id  order_latitude  order_longitude                ordered_at_brt  \
308       309       -23.61187       -46.736743 2024-04-01 10:34:09.032307581

     order_weight     sla_max_delivery_time_brt
308      5.020482 2024-04-01 11:34:09.032307581
2024-04-01 10:34:09.032307581
tem rota aberta
dist order to order é  3.1734122879062947 hub em questão 9
dist order to hub é  5.658034181311416 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 113
310
     order_id  order_latitude  order_longitude                ordered_at_brt  \
309       310      -23.734893       -46.663624 2024-04-01 10:34:53.955354454

     order_weight     sla_max_delivery_time_brt
309      3.028232 2024-04-01 11:34:53.955354454
2024-04-01 10:34:53.955354454
tem rota aberta
dist order to order é  4.440161808696735 hub em questão 1
dist order to hub é  4.389507885342192 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 109
311
     order_id  order_latitude  order_longitude                ordered_at_brt  \
310       311      -23.568281       -46.683546 2024-04-01 10:39:51.625272858

     order_weight     sla_max_delivery_time_brt
310      8.091541 2024-04-01 13:39:51.625272858
2024-04-01 10:39:51.625272858
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.210530764470616 hub em questão 4
dist order to hub é  1.7169980763379058 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 114
312
     order_id  order_latitude  order_longitude                ordered_at_brt  \
311       312      -23.702475       -46.591456 2024-04-01 10:44:40.093760531

     order_weight     sla_max_delivery_time_brt
311      5.742745 2024-04-01 13:44:40.093760531
2024-04-01 10:44:40.093760531
tem rota aberta
dist order to order é  4.367716466552315 hub em questão 6
dist order to hub é  2.9994392952243096 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 112
313
     order_id  order_latitude  order_longitude                ordered_at_brt  \
312       313      -23.666978       -46.679075 2024-04-01 10:45:15.759975485

     order_weight     sla_max_delivery_time_brt
312      9.953055 2024-04-01 11:45:15.759975485
2024-04-01 10:45:15.759975485
tem rota aberta
dist order to order é  4.093473064035468 hub em questão 10
dist order to hub é  2.4323506735056366 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 115
314
     order_id  order_latitude  order_longitude                ordered_at_brt  \
313       314      -23.631192       -46.595482 2024-04-01 10:45:29.864269032

     order_weight     sla_max_delivery_time_brt
313     10.196772 2024-04-01 13:45:29.864269032
2024-04-01 10:45:29.864269032
tem rota aberta
dist order to order é  6.449048010609562 hub em questão 10
dist order to hub é  2.0285161640568083 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 10
passou aqui1
passou aqui5
route_id 116
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

315
     order_id  order_latitude  order_longitude                ordered_at_brt  \
314       315      -23.661855       -46.625024 2024-04-01 10:45:55.590520738

     order_weight     sla_max_delivery_time_brt
314      9.104963 2024-04-01 13:45:55.590520738
2024-04-01 10:45:55.590520738
tem rota aberta
dist order to order é  4.52197851537358 hub em questão 10
dist order to hub é  3.351866253813011 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 115
316
     order_id  order_latitude  order_longitude                ordered_at_brt  \
315       316      -23.610079       -46.658329 2024-04-01 10:47:18.668424844

     order_weight     sla_max_delivery_time_brt
315      7.960304 2024-04-01 12:47:18.668424844
2024-04-01 10:47:18.668424844
tem rota aberta
dist order to order é  2.802850162874088 hub em questão 10
dist order to hub é  0.6346451922326701 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 10
passou aqui1
passou aqui5
route_id 117
caiu aqui tb
317
     order_id  order_latitude  order_longitude                ordered_at_brt  \
316       317      -23.642679       -46.646954 2024-04-01 10:49:55.161471870

     order_weight     sla_max_delivery_time_brt
316      7.866635 2024-04-01 12:49:55.161471870
2024-04-01 10:49:55.161471870
tem rota aberta
dist order to order é  1.446082911076804 hub em questão 10
dist order to hub é  2.8378016349279727 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 115

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

318
     order_id  order_latitude  order_longitude                ordered_at_brt  \
317       318      -23.621738        -46.62658 2024-04-01 10:50:23.174202311

     order_weight     sla_max_delivery_time_brt
317      9.647793 2024-04-01 13:50:23.174202311
2024-04-01 10:50:23.174202311
tem rota aberta
dist order to order é  3.3379282453773422 hub em questão 7
dist order to hub é  1.1089483027999851 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 7
passou aqui1
passou aqui5
route_id 118
caiu aqui tb
319
     order_id  order_latitude  order_longitude                ordered_at_brt  \
318       319      -23.646477       -46.763415 2024-04-01 10:50:57.381832094

     order_weight     sla_max_delivery_time_brt
318      4.810104 2024-04-01 12:50:57.381832094
2024-04-01 10:50:57.381832094
tem rota aberta
dist order to order é  4.710731518012735 hub em questão 9
dist order to hub é  6.176596491317733 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 113
320
     order_id  order_latitude  order_longitude                ordered_at_brt  \
319       320      -23.576625       -46.631659 2024-04-01 10:54:46.381239857

     order_weight     sla_max_delivery_time_brt
319      2.226351 2024-04-01 12:54:46.381239857
2024-04-01 10:54:46.381239857
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.606836109373159 hub em questão 15
dist order to hub é  2.709359264899013 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 117
321
     order_id  order_latitude  order_longitude                ordered_at_brt  \
320       321         -23.751       -46.666969 2024-04-01 10:55:50.892674133

     order_weight     sla_max_delivery_time_brt
320      8.785568 2024-04-01 12:55:50.892674133
2024-04-01 10:55:50.892674133
tem rota aberta
dist order to order é  9.391602633451043 hub em questão 6
dist order to hub é  5.8241292139031575 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 6
passou aqui1
passou aqui5
route_id 119
caiu aqui tb
322
     order_id  order_latitude  order_longitude                ordered_at_brt  \
321       322      -23.632021       -46.558117 2024-04-01 10:57:45.960475979

     order_weight     sla_max_delivery_time_brt
321      7.820001 2024-04-01 12:57:45.960475979
2024-04-01 10:57:45.960475979
tem rota aberta
dist order to order é  3.8075293003897417 hub em questão 7
dist order to hub é  2.5632478964731016 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 116
323
     order_id  order_latitude  order_longitude                ordered_at_brt  \
322       323      -23.665256       -46.682576 2024-04-01 10:58:17.896958535

     order_weight     sla_max_delivery_time_brt
322      7.894337 2024-04-01 13:58:17.896958535
2024-04-01 10:58:17.896958535
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  5.005784097020535 hub em questão 9
dist order to hub é  2.535776898748754 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 9
passou aqui1
rota em aberto, route_id:  113
rota_escolhida: 113
orders no hub: 3
passou aqui3
passou aqui4
324
     order_id  order_latitude  order_longitude                ordered_at_brt  \
323       324      -23.698177       -46.590885 2024-04-01 10:58:30.802808763

     order_weight     sla_max_delivery_time_brt
323       6.60209 2024-04-01 11:58:30.802808763
2024-04-01 10:58:30.802808763
tem rota aberta
dist order to order é  0.4814797905800643 hub em questão 6
dist order to hub é  3.390180023955283 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 112
325
     order_id  order_latitude  order_longitude                ordered_at_brt  \
324       325      -23.690806       -46.773759 2024-04-01 10:59:57.847808331

     order_weight     sla_max_delivery_time_brt
324       0.24677 2024-04-01 13:59:57.847808331
2024-04-01 10:59:57.847808331
tem rota aberta
dist order to order é  12.766618634628749 hub em questão 1
dist order to hub é  8.368002047987872 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 1
passou aqui1
passou aqui5
route_id 120
caiu aqui tb
326
     order_id  order_latitude  order_longitude                ordered_at_brt  \
325       326      -23.678824       -46.607282 2024-04-01 11:01:15.661019327

     order_weight     sla_max_delivery_time_brt
325     15.680778 2024-04-01 14:01:15.661019327
2024-04-01 11:01:15.661019327
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  5.431147898303661 hub em questão 7
dist order to hub é  3.2419261870423255 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 7
passou aqui1
passou aqui5
route_id 121
caiu aqui tb
327
     order_id  order_latitude  order_longitude                ordered_at_brt  \
326       327      -23.621305       -46.634208 2024-04-01 11:01:35.541058144

     order_weight     sla_max_delivery_time_brt
326     15.226466 2024-04-01 14:01:35.541058144
2024-04-01 11:01:35.541058144
tem rota aberta
dist order to order é  0.7785970700933675 hub em questão 14
dist order to hub é  1.8627147791317955 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 118
328
     order_id  order_latitude  order_longitude                ordered_at_brt  \
327       328      -23.695032       -46.660364 2024-04-01 11:03:32.222890175

     order_weight     sla_max_delivery_time_brt
327      5.469346 2024-04-01 14:03:32.222890175
2024-04-01 11:03:32.222890175
tem rota aberta
dist order to order é  5.697735291201463 hub em questão 12
dist order to hub é  2.5700921079233043 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
passou aqui5
route_id 122
caiu aqui tb
329
     order_id  order_latitude  order_longitude                ordered_at_brt  \
328       329      -23.658385       -46.654057 2024-04-01 11:05:06.457049386

     order_weight     sla_max_delivery_time_brt
328      9.500053 2024-04-01 14:05:06.457049386
2024-04-01 11:05:06.457049386
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.125299201463398 hub em questão 5
dist order to hub é  1.556752360471124 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 5
passou aqui1
rota em aberto, route_id:  122
rota_escolhida: 122
orders no hub: 1
passou aqui3
passou aqui4
330
     order_id  order_latitude  order_longitude                ordered_at_brt  \
329       330      -23.636463       -46.661041 2024-04-01 11:07:13.862674101

     order_weight     sla_max_delivery_time_brt
329      7.266766 2024-04-01 13:07:13.862674101
2024-04-01 11:07:13.862674101
tem rota aberta
dist order to order é  2.539246720883481 hub em questão 5
dist order to hub é  2.1460062504484987 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 122
331
     order_id  order_latitude  order_longitude                ordered_at_brt  \
330       331      -23.708015       -46.626863 2024-04-01 11:07:32.597364409

     order_weight     sla_max_delivery_time_brt
330      7.760166 2024-04-01 13:07:32.597364409
2024-04-01 11:07:32.597364409
tem rota aberta
dist order to order é  3.703864981183304 hub em questão 5
dist order to hub é  0.527791208217998 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
rota em aberto, route_id:  119
rota_escolhida: 119
orders no hub: 1
passou aqui3
passou aqui4
332
     order_id  order_latitude  order_longitude                ordered_at_brt  \
331       332      -23.594608       -46.654725 2024-04-01 11:10:19.688289996

     order_weight     sla_max_delivery_time_brt
331      8.029877 2024-04-01 14:10:19.688289996
2024-04-01 11:10:19.688289996
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.75901598595922 hub em questão 15
dist order to hub é  1.950612317749341 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 117
333
     order_id  order_latitude  order_longitude                ordered_at_brt  \
332       333      -23.529146         -46.7374 2024-04-01 11:10:49.819320215

     order_weight     sla_max_delivery_time_brt
332     10.220509 2024-04-01 14:10:49.819320215
2024-04-01 11:10:49.819320215
tem rota aberta
dist order to order é  11.13515183634929 hub em questão 15
dist order to hub é  4.080200056223106 hub em questão 11
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 11
hub_order 15
passou aqui1
passou aqui5
route_id 123
caiu aqui tb
334
     order_id  order_latitude  order_longitude                ordered_at_brt  \
333       334      -23.683926       -46.657303 2024-04-01 11:12:17.733686627

     order_weight     sla_max_delivery_time_brt
333      4.992852 2024-04-01 14:12:17.733686627
2024-04-01 11:12:17.733686627
tem rota aberta
dist order to order é  1.2736041707400934 hub em questão 5
dist order to hub é  1.3025792619707803 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 122
335
     order_id  order_latitude  order_longitude                ordered_at_brt  \
334       335      -23.604253       -46.536277 2024-04-01 11:15:22.353095635

     order_weight     sla_max_delivery_time_brt
334      9.146061 2024-04-01 14:15:22.353095635
2024-04-01 11:15:22.353095635
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.8058461712294602 hub em questão 7
dist order to hub é  4.193502190313752 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 116
336
     order_id  order_latitude  order_longitude                ordered_at_brt  \
335       336      -23.665709        -46.64567 2024-04-01 11:15:25.063118871

     order_weight     sla_max_delivery_time_brt
335      9.122985 2024-04-01 13:15:25.063118871
2024-04-01 11:15:25.063118871
tem rota aberta
dist order to order é  4.17262228554419 hub em questão 12
dist order to hub é  1.272948083766966 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
passou aqui5
route_id 124
caiu aqui tb
337
     order_id  order_latitude  order_longitude                ordered_at_brt  \
336       337      -23.623557       -46.633473 2024-04-01 11:16:12.114942442

     order_weight     sla_max_delivery_time_brt
336          0.01 2024-04-01 13:16:12.114942442
2024-04-01 11:16:12.114942442
tem rota aberta
dist order to order é  0.2613620770178606 hub em questão 14
dist order to hub é  1.7413230256885217 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 118
338
     order_id  order_latitude  order_longitude                ordered_at_brt  \
337       338      -23.659311       -46.669916 2024-04-01 11:20:19.669802816

     order_weight     sla_max_delivery_time_brt
337     11.405021 2024-04-01 14:20:19.669802816
2024-04-01 11:20:19.669802816
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.5697338915448418 hub em questão 5
dist order to hub é  2.028949188637571 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 124
339
     order_id  order_latitude  order_longitude                ordered_at_brt  \
338       339      -23.539792        -46.63931 2024-04-01 11:24:03.164812679

     order_weight     sla_max_delivery_time_brt
338      8.972258 2024-04-01 12:24:03.164812679
2024-04-01 11:24:03.164812679
tem rota aberta
dist order to order é  10.06966036934781 hub em questão 11
dist order to hub é  6.760805225748725 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 11
passou aqui1
passou aqui5
route_id 125
caiu aqui tb
340
     order_id  order_latitude  order_longitude                ordered_at_brt  \
339       340      -23.666442       -46.639116 2024-04-01 11:25:35.942153465

     order_weight     sla_max_delivery_time_brt
339      5.253348 2024-04-01 14:25:35.942153465
2024-04-01 11:25:35.942153465
tem rota aberta
dist order to order é  0.6725336648325646 hub em questão 5
dist order to hub é  1.8289601086438 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 124
341
     order_id  order_latitude  order_longitude                ordered_at_brt  \
340       341      -23.610529       -46.661073 2024-04-01 11:29:37.677974184

     order_weight     sla_max_delivery_time_brt
340       7.14364 2024-04-01 12:29:37.677974184
2024-04-01 11:29:37.677974184
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  5.4985788490173535 hub em questão 5
dist order to hub é  0.580454490150937 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 5
passou aqui1
passou aqui5
route_id 126
caiu aqui tb
342
     order_id  order_latitude  order_longitude                ordered_at_brt  \
341       342      -23.619857        -46.60485 2024-04-01 11:35:36.701127273

     order_weight     sla_max_delivery_time_brt
341      8.537403 2024-04-01 13:35:36.701127273
2024-04-01 11:35:36.701127273
tem rota aberta
dist order to order é  5.821361446660465 hub em questão 15
dist order to hub é  0.6694659541598185 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 15
passou aqui1
passou aqui5
route_id 127
caiu aqui tb
343
     order_id  order_latitude  order_longitude                ordered_at_brt  \
342       343      -23.704423       -46.694167 2024-04-01 11:39:06.826141652

     order_weight     sla_max_delivery_time_brt
342      6.147042 2024-04-01 13:39:06.826141652
2024-04-01 11:39:06.826141652
tem rota aberta
dist order to order é  5.591242567735956 hub em questão 5
dist order to hub é  5.28704161390337 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 124
344
     order_id  order_latitude  order_longitude                ordered_at_brt  \
343       344      -23.758239       -46.654523 2024-04-01 11:42:57.818903403

     order_weight     sla_max_delivery_time_brt
343      8.576231 2024-04-01 13:42:57.818903403
2024-04-01 11:42:57.818903403
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  16.197357978542378 hub em questão 7
dist order to hub é  5.743595268877225 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 7
passou aqui1
passou aqui5
route_id 128
caiu aqui tb
345
     order_id  order_latitude  order_longitude                ordered_at_brt  \
344       345      -23.621271        -46.62276 2024-04-01 11:43:10.294735715

     order_weight     sla_max_delivery_time_brt
344      0.847372 2024-04-01 14:43:10.294735715
2024-04-01 11:43:10.294735715
tem rota aberta
dist order to order é  1.8314638073207006 hub em questão 7
dist order to hub é  0.793811634054782 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 127
346
     order_id  order_latitude  order_longitude                ordered_at_brt  \
345       346      -23.607999       -46.661363 2024-04-01 11:45:16.721425672

     order_weight     sla_max_delivery_time_brt
345      7.635726 2024-04-01 13:45:16.721425672
2024-04-01 11:45:16.721425672
tem rota aberta
dist order to order é  0.2828060049092692 hub em questão 15
dist order to hub é  0.8619498725041032 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 126
347
     order_id  order_latitude  order_longitude                ordered_at_brt  \
346       347      -23.677061       -46.709207 2024-04-01 11:47:42.613268609

     order_weight     sla_max_delivery_time_brt
346     10.331524 2024-04-01 13:47:42.613268609
2024-04-01 11:47:42.613268609
tem rota aberta
dist order to order é  8.875222588124727 hub em questão 15
dist order to hub é  2.8148210448907514 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 129
caiu aqui tb
348
     order_id  order_latitude  order_longitude                ordered_at_brt  \
347       348      -23.681894         -46.6201 2024-04-01 11:49:35.680412476

     order_weight     sla_max_delivery_time_brt
347      9.254063 2024-04-01 13:49:35.680412476

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 11:49:35.680412476
tem rota aberta
dist order to order é  6.746434457203443 hub em questão 7
dist order to hub é  3.512791441635562 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 7
passou aqui1
rota em aberto, route_id:  128
rota_escolhida: 128
orders no hub: 1
passou aqui3
passou aqui4
349
     order_id  order_latitude  order_longitude                ordered_at_brt  \
348       349      -23.601385       -46.697121 2024-04-01 11:52:48.582340760

     order_weight     sla_max_delivery_time_brt
348      7.653601 2024-04-01 12:52:48.582340760
2024-04-01 11:52:48.582340760
tem rota aberta
dist order to order é  3.7169066111534366 hub em questão 15
dist order to hub é  3.3448579137252343 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 126
350
     order_id  order_latitude  order_longitude                ordered_at_brt  \
349       350      -23.607584       -46.670378 2024-04-01 11:52:52.804294110

     order_weight     sla_max_delivery_time_brt
349      4.658449 2024-04-01 13:52:52.804294110
2024-04-01 11:52:52.804294110
tem rota aberta
dist order to order é  0.9197119662224096 hub em questão 15
dist order to hub é  1.3987038475470654 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 126
351
     order_id  order_latitude  order_longitude                ordered_at_brt  \
350       351      -23.602432        -46.68942 2024-04-01 11:55:49.290032364

     order_weight     sla_max_delivery_time_brt
350      7.211074 2024-04-01 12:55:49.290032364
2024-04-01 11:55:49.290032364
tem rota aberta
dist order to order é  7.107448244449641 hub em questão 7
dist order to hub é  3.3537947476004177 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 7
passou aqui1
passou aqui5
route_id 130
caiu aqui tb
352
     order_id  order_latitude  order_longitude                ordered_at_brt  \
351       352      -23.637155       -46.653549 2024-04-01 11:58:27.180767613

     order_weight     sla_max_delivery_time_brt
351      3.441091 2024-04-01 13:58:27.180767613
2024-04-01 11:58:27.180767613
tem rota aberta
dist order to order é  3.599672040877956 hub em questão 7
dist order to hub é  2.1194793317284204 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 127
353
     order_id  order_latitude  order_longitude                ordered_at_brt  \
352       353      -23.689639       -46.669482 2024-04-01 11:59:03.264479516

     order_weight     sla_max_delivery_time_brt
352      7.361821 2024-04-01 13:59:03.264479516

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 11:59:03.264479516
tem rota aberta
dist order to order é  4.280151145087566 hub em questão 9
dist order to hub é  2.374173298666087 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 129
354
     order_id  order_latitude  order_longitude                ordered_at_brt  \
353       354      -23.711124       -46.671742 2024-04-01 11:59:38.922780422

     order_weight     sla_max_delivery_time_brt
353      6.476756 2024-04-01 14:59:38.922780422
2024-04-01 11:59:38.922780422
tem rota aberta
dist order to order é  2.4000672405088777 hub em questão 9
dist order to hub é  4.45599996741031 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 129
355
     order_id  order_latitude  order_longitude                ordered_at_brt  \
354       355      -23.749882       -46.613964 2024-04-01 12:01:38.982409961

     order_weight     sla_max_delivery_time_brt
354      8.498326 2024-04-01 14:01:38.982409961
2024-04-01 12:01:38.982409961
tem rota aberta
dist order to order é  4.231155808338805 hub em questão 1
dist order to hub é  4.380365492749943 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 128
356
     order_id  order_latitude  order_longitude                ordered_at_brt  \
355       356      -23.653109       -46.559882 2024-04-01 12:02:29.811324320

     order_weight     sla_max_delivery_time_brt
355     11.166527 2024-04-01 13:02:29.811324320

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 12:02:29.811324320
tem rota aberta
dist order to order é  5.886767201382382 hub em questão 7
dist order to hub é  2.493359044113532 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 7
passou aqui1
passou aqui5
route_id 131
caiu aqui tb
357
     order_id  order_latitude  order_longitude                ordered_at_brt  \
356       357      -23.554267       -46.665888 2024-04-01 12:05:40.914340308

     order_weight     sla_max_delivery_time_brt
356      9.551626 2024-04-01 15:05:40.914340308
2024-04-01 12:05:40.914340308
tem rota aberta
dist order to order é  5.86807644776591 hub em questão 15
dist order to hub é  3.9693296005066734 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 130
358
     order_id  order_latitude  order_longitude                ordered_at_brt  \
357       358      -23.626331        -46.62188 2024-04-01 12:06:51.816890359

     order_weight     sla_max_delivery_time_brt
357      4.505392 2024-04-01 14:06:51.816890359
2024-04-01 12:06:51.816890359
tem rota aberta
dist order to order é  6.181044306199067 hub em questão 1
dist order to hub é  0.5530805705903142 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 1
passou aqui1
passou aqui5
route_id 132
caiu aqui tb
359
     order_id  order_latitude  order_longitude                ordered_at_brt  \
358       359      -23.654212       -46.665783 2024-04-01 12:09:55.021348890

     order_weight     sla_max_delivery_time_brt
358      4.097506 2024-04-01 13:09:55.021348890

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 12:09:55.021348890
tem rota aberta
dist order to order é  3.9572539417741726 hub em questão 9
dist order to hub é  2.2471108093886683 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 129
360
     order_id  order_latitude  order_longitude                ordered_at_brt  \
359       360      -23.726263       -46.643066 2024-04-01 12:19:13.441077411

     order_weight     sla_max_delivery_time_brt
359      4.402815 2024-04-01 13:19:13.441077411
2024-04-01 12:19:13.441077411
tem rota aberta
dist order to order é  11.319455069537966 hub em questão 14
dist order to hub é  2.1549063203724224 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 14
passou aqui1
passou aqui5
route_id 133
caiu aqui tb
361
     order_id  order_latitude  order_longitude                ordered_at_brt  \
360       361      -23.683622       -46.591625 2024-04-01 12:19:56.284650728

     order_weight     sla_max_delivery_time_brt
360      4.388651 2024-04-01 14:19:56.284650728
2024-04-01 12:19:56.284650728
tem rota aberta
dist order to order é  4.686362142732234 hub em questão 12
dist order to hub é  2.1964729055155328 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 12
passou aqui1
rota em aberto, route_id:  131
rota_escolhida: 131
orders no hub: 1
passou aqui3

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

passou aqui4
362
     order_id  order_latitude  order_longitude                ordered_at_brt  \
361       362      -23.649978       -46.645498 2024-04-01 12:20:14.803550069

     order_weight     sla_max_delivery_time_brt
361      3.884397 2024-04-01 14:20:14.803550069
2024-04-01 12:20:14.803550069
tem rota aberta
dist order to order é  3.564064331620553 hub em questão 14
dist order to hub é  2.6970324354959367 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 132
363
     order_id  order_latitude  order_longitude                ordered_at_brt  \
362       363      -23.661336        -46.68879 2024-04-01 12:24:52.694247372

     order_weight     sla_max_delivery_time_brt
362     12.974546 2024-04-01 15:24:52.694247372
2024-04-01 12:24:52.694247372
tem rota aberta
dist order to order é  4.586671601233885 hub em questão 14
dist order to hub é  1.767348297202682 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 14
passou aqui1
passou aqui5
route_id 134
caiu aqui tb
364
     order_id  order_latitude  order_longitude                ordered_at_brt  \
363       364      -23.604808       -46.684509 2024-04-01 12:26:26.285187673

     order_weight     sla_max_delivery_time_brt
363     10.898888 2024-04-01 15:26:26.285187673
2024-04-01 12:26:26.285187673
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  6.300741540376109 hub em questão 9
dist order to hub é  2.788265770496585 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 9
passou aqui1
passou aqui5
route_id 135
caiu aqui tb
365
     order_id  order_latitude  order_longitude                ordered_at_brt  \
364       365      -23.658156        -46.67885 2024-04-01 12:33:47.710928914

     order_weight     sla_max_delivery_time_brt
364      5.223782 2024-04-01 15:33:47.710928914
2024-04-01 12:33:47.710928914
tem rota aberta
dist order to order é  1.0723782224971732 hub em questão 9
dist order to hub é  2.5539959308495366 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 134
366
     order_id  order_latitude  order_longitude                ordered_at_brt  \
365       366       -23.61546       -46.648678 2024-04-01 12:35:49.182516630

     order_weight     sla_max_delivery_time_brt
365      7.148978 2024-04-01 14:35:49.182516630
2024-04-01 12:35:49.182516630
tem rota aberta
dist order to order é  2.9857622284072867 hub em questão 14
dist order to hub é  0.6633725280060696 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 14
passou aqui1
passou aqui5
route_id 136
caiu aqui tb
367
     order_id  order_latitude  order_longitude                ordered_at_brt  \
366       367      -23.655936       -46.605112 2024-04-01 12:46:01.374993341

     order_weight     sla_max_delivery_time_brt
366     14.434016 2024-04-01 14:46:01.374993341
2024-04-01 12:46:01.374993341
tem rota aberta
dist order to order é  6.320759541059393 hub em questão 10
dist order to hub é  3.163101503198454 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 10
passou aqui1
passou aqui5
route_id 137
caiu aqui tb
368
     order_id  order_latitude  order_longitude                ordered_at_brt  \
367       368      -23.659714       -46.715953 2024-04-01 12:47:36.152679264

     order_weight     sla_max_delivery_time_brt
367      1.663916 2024-04-01 13:47:36.152679264
2024-04-01 12:47:36.152679264
tem rota aberta
dist order to order é  2.7723196518625084 hub em questão 9
dist order to hub é  1.5415131463582965 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 134
369
     order_id  order_latitude  order_longitude                ordered_at_brt  \
368       369      -23.587269       -46.699877 2024-04-01 12:49:05.846313984

     order_weight     sla_max_delivery_time_brt
368      8.187259 2024-04-01 15:49:05.846313984
2024-04-01 12:49:05.846313984
tem rota aberta
dist order to order é  2.501215751875043 hub em questão 15
dist order to hub é  1.7619961102277941 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 135
370
     order_id  order_latitude  order_longitude                ordered_at_brt  \
369       370      -23.687824        -46.69424 2024-04-01 12:49:23.308783593

     order_weight     sla_max_delivery_time_brt
369     13.009815 2024-04-01 13:49:23.308783593
2024-04-01 12:49:23.308783593
tem rota aberta
dist order to order é  2.9971546962047952 hub em questão 9
dist order to hub é  4.044813979678646 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 134

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

371
     order_id  order_latitude  order_longitude                ordered_at_brt  \
370       371      -23.664378       -46.735483 2024-04-01 12:50:16.060645426

     order_weight     sla_max_delivery_time_brt
370       7.44647 2024-04-01 15:50:16.060645426
2024-04-01 12:50:16.060645426
tem rota aberta
dist order to order é  8.416571851399128 hub em questão 15
dist order to hub é  3.5567126009782704 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 138
caiu aqui tb
372
     order_id  order_latitude  order_longitude                ordered_at_brt  \
371       372      -23.714862       -46.581717 2024-04-01 12:50:19.248853697

     order_weight     sla_max_delivery_time_brt
371      5.345975 2024-04-01 15:50:19.248853697
2024-04-01 12:50:19.248853697
tem rota aberta
dist order to order é  6.9719332750765615 hub em questão 12
dist order to hub é  1.3133942458692454 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 12
passou aqui1
passou aqui5
route_id 139
caiu aqui tb
373
     order_id  order_latitude  order_longitude                ordered_at_brt  \
372       373      -23.645388       -46.649832 2024-04-01 12:50:40.227727655

     order_weight     sla_max_delivery_time_brt
372     10.809604 2024-04-01 14:50:40.227727655
2024-04-01 12:50:40.227727655
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.3299580639950563 hub em questão 10
dist order to hub é  3.0537411914546024 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 136
374
     order_id  order_latitude  order_longitude                ordered_at_brt  \
373       374       -23.59675       -46.552974 2024-04-01 12:53:24.506966369

     order_weight     sla_max_delivery_time_brt
373     13.782243 2024-04-01 13:53:24.506966369
2024-04-01 12:53:24.506966369
tem rota aberta
dist order to order é  8.457237264922624 hub em questão 12
dist order to hub é  3.1020353205179827 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 12
passou aqui1
passou aqui5
route_id 140
caiu aqui tb
375
     order_id  order_latitude  order_longitude                ordered_at_brt  \
374       375      -23.616155       -46.719229 2024-04-01 12:53:28.211527633

     order_weight     sla_max_delivery_time_brt
374      6.451253 2024-04-01 14:53:28.211527633
2024-04-01 12:53:28.211527633
tem rota aberta
dist order to order é  3.7558197797778607 hub em questão 15
dist order to hub é  4.348423909966848 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 135
376
     order_id  order_latitude  order_longitude                ordered_at_brt  \
375       376      -23.613525       -46.583304 2024-04-01 12:54:22.999125062

     order_weight     sla_max_delivery_time_brt
375     10.580367 2024-04-01 15:54:22.999125062
2024-04-01 12:54:22.999125062
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.6096136478649474 hub em questão 3
dist order to hub é  0.8143995897729368 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 3
passou aqui1
rota em aberto, route_id:  140
rota_escolhida: 140
orders no hub: 1
passou aqui3
passou aqui4
377
     order_id  order_latitude  order_longitude                ordered_at_brt  \
376       377      -23.597573       -46.683095 2024-04-01 12:58:20.960784106

     order_weight     sla_max_delivery_time_brt
376      4.122005 2024-04-01 13:58:20.960784106
2024-04-01 12:58:20.960784106
tem rota aberta
dist order to order é  4.031532606862799 hub em questão 10
dist order to hub é  3.106829981694972 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 136
378
     order_id  order_latitude  order_longitude                ordered_at_brt  \
377       378      -23.618964       -46.668381 2024-04-01 13:00:42.543780336

     order_weight     sla_max_delivery_time_brt
377        7.7919 2024-04-01 14:00:42.543780336
2024-04-01 13:00:42.543780336
tem rota aberta
dist order to order é  2.044873132620405 hub em questão 10
dist order to hub é  0.9483949624606216 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 136
379
     order_id  order_latitude  order_longitude                ordered_at_brt  \
378       379      -23.612312       -46.697461 2024-04-01 13:03:03.450993588

     order_weight     sla_max_delivery_time_brt
378      8.917101 2024-04-01 15:03:03.450993588
2024-04-01 13:03:03.450993588
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  6.965537019242037 hub em questão 9
dist order to hub é  3.8528640339413522 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 9
passou aqui1
passou aqui5
route_id 141
caiu aqui tb
380
     order_id  order_latitude  order_longitude                ordered_at_brt  \
379       380      -23.630039       -46.695506 2024-04-01 13:03:28.535731683

     order_weight     sla_max_delivery_time_brt
379      5.645046 2024-04-01 15:03:28.535731683
2024-04-01 13:03:28.535731683
tem rota aberta
dist order to order é  1.9811668028549618 hub em questão 15
dist order to hub é  2.601135562650834 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 141
381
     order_id  order_latitude  order_longitude                ordered_at_brt  \
380       381      -23.698995         -46.7142 2024-04-01 13:04:38.522706655

     order_weight     sla_max_delivery_time_brt
380      5.410808 2024-04-01 14:04:38.522706655
2024-04-01 13:04:38.522706655
tem rota aberta
dist order to order é  4.417415763742414 hub em questão 9
dist order to hub é  5.3060415779696894 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 138
382
     order_id  order_latitude  order_longitude                ordered_at_brt  \
381       382      -23.623921       -46.637196 2024-04-01 13:06:23.074311048

     order_weight     sla_max_delivery_time_brt
381      8.898752 2024-04-01 16:06:23.074311048
2024-04-01 13:06:23.074311048
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.832659497186501 hub em questão 12
dist order to hub é  1.8782577053402485 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 12
passou aqui1
passou aqui5
route_id 142
caiu aqui tb
383
     order_id  order_latitude  order_longitude                ordered_at_brt  \
382       383      -23.602931       -46.713723 2024-04-01 13:15:32.751613681

     order_weight     sla_max_delivery_time_brt
382      9.624988 2024-04-01 15:15:32.751613681
2024-04-01 13:15:32.751613681
tem rota aberta
dist order to order é  1.9579351770836046 hub em questão 15
dist order to hub é  3.7707753032965363 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 141
384
     order_id  order_latitude  order_longitude                ordered_at_brt  \
383       384      -23.694821       -46.660103 2024-04-01 13:16:00.116208790

     order_weight     sla_max_delivery_time_brt
383      3.851893 2024-04-01 15:16:00.116208790
2024-04-01 13:16:00.116208790
tem rota aberta
dist order to order é  5.5276713407380305 hub em questão 9
dist order to hub é  2.542398930720805 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 9
passou aqui1
passou aqui5
route_id 143
caiu aqui tb
385
     order_id  order_latitude  order_longitude                ordered_at_brt  \
384       385      -23.638426       -46.648473 2024-04-01 13:16:34.275868902

     order_weight     sla_max_delivery_time_brt
384      5.177945 2024-04-01 16:16:34.275868902
2024-04-01 13:16:34.275868902
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.9801915718709855 hub em questão 10
dist order to hub é  2.3407244007144437 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 142
386
     order_id  order_latitude  order_longitude                ordered_at_brt  \
385       386      -23.596085       -46.614682 2024-04-01 13:17:10.761390431

     order_weight     sla_max_delivery_time_brt
385      8.254413 2024-04-01 16:17:10.761390431
2024-04-01 13:17:10.761390431
tem rota aberta
dist order to order é  3.7393585541508223 hub em questão 3
dist order to hub é  2.299001851113833 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 140
387
     order_id  order_latitude  order_longitude                ordered_at_brt  \
386       387      -23.668899       -46.642993 2024-04-01 13:19:57.199500698

     order_weight     sla_max_delivery_time_brt
386      2.374661 2024-04-01 14:19:57.199500698
2024-04-01 13:19:57.199500698
tem rota aberta
dist order to order é  3.3680289281627 hub em questão 5
dist order to hub é  1.3676176860492841 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 5
passou aqui1
rota em aberto, route_id:  143
rota_escolhida: 143
orders no hub: 1
passou aqui3
passou aqui4
388
     order_id  order_latitude  order_longitude                ordered_at_brt  \
387       388      -23.716281       -46.631946 2024-04-01 13:21:10.471563407

     order_weight     sla_max_delivery_time_brt
387      3.924417 2024-04-01 15:21:10.471563407
2024-04-01 13:21:10.471563407
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.7298731575876216 hub em questão 5
dist order to hub é  0.569615490977152 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 144
caiu aqui tb
389
     order_id  order_latitude  order_longitude                ordered_at_brt  \
388       389      -23.647149       -46.622292 2024-04-01 13:21:17.505264099

     order_weight     sla_max_delivery_time_brt
388      7.977925 2024-04-01 14:21:17.505264099
2024-04-01 13:21:17.505264099
tem rota aberta
dist order to order é  2.837715831721956 hub em questão 10
dist order to hub é  2.473136421331034 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 142
390
     order_id  order_latitude  order_longitude                ordered_at_brt  \
389       390      -23.570541       -46.648875 2024-04-01 13:22:42.744430045

     order_weight     sla_max_delivery_time_brt
389      9.415433 2024-04-01 15:22:42.744430045
2024-04-01 13:22:42.744430045
tem rota aberta
dist order to order é  4.495500058396585 hub em questão 3
dist order to hub é  3.5592839668386933 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 140
391
     order_id  order_latitude  order_longitude                ordered_at_brt  \
390       391      -23.695873       -46.629845 2024-04-01 13:23:11.329226595

     order_weight     sla_max_delivery_time_brt
390      7.821217 2024-04-01 14:23:11.329226595
2024-04-01 13:23:11.329226595
tem rota aberta
dist order to order é  2.279336078758607 hub em questão 1
dist order to hub é  1.8743686588798953 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 144
392

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
391       392      -23.655495       -46.696999 2024-04-01 13:26:23.627231617

     order_weight     sla_max_delivery_time_brt
391       6.77218 2024-04-01 14:26:23.627231617
2024-04-01 13:26:23.627231617
tem rota aberta
dist order to order é  2.8346309407597006 hub em questão 15
dist order to hub é  0.7135332905867913 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 145
caiu aqui tb
393
     order_id  order_latitude  order_longitude                ordered_at_brt  \
392       393      -23.687777       -46.686786 2024-04-01 13:27:05.971617247

     order_weight     sla_max_delivery_time_brt
392     12.047434 2024-04-01 15:27:05.971617247
2024-04-01 13:27:05.971617247
tem rota aberta
dist order to order é  2.827655995374763 hub em questão 5
dist order to hub é  3.5858467454446217 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 143
394
     order_id  order_latitude  order_longitude                ordered_at_brt  \
393       394      -23.668174       -46.553137 2024-04-01 13:27:09.330923545

     order_weight     sla_max_delivery_time_brt
393      7.606562 2024-04-01 16:27:09.330923545
2024-04-01 13:27:09.330923545
tem rota aberta
dist order to order é  7.421308204858485 hub em questão 10
dist order to hub é  2.4716607903332255 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 10
passou aqui1
passou aqui5
route_id 146
caiu aqui tb
395
     order_id  order_latitude  order_longitude                ordered_at_brt  \
394       395      -23.638487       -46.648599 2024-04-01 13:28:57.331546083

     order_weight     sla_max_delivery_time_brt
394      5.416114 2024-04-01 16:28:57.331546083
2024-04-01 13:28:57.331546083
tem rota aberta
dist order to order é  0.014570786285774491 hub em questão 10
dist order to hub é  2.3439161440805254 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 142
396
     order_id  order_latitude  order_longitude                ordered_at_brt  \
395       396      -23.576385       -46.683538 2024-04-01 13:32:40.156774450

     order_weight     sla_max_delivery_time_brt
395      0.786207 2024-04-01 16:32:40.156774450
2024-04-01 13:32:40.156774450
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.239433277432135 hub em questão 15
dist order to hub é  1.769973428673236 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 15
passou aqui1
passou aqui5
route_id 147
caiu aqui tb
397
     order_id  order_latitude  order_longitude                ordered_at_brt  \
396       397      -23.686058       -46.579019 2024-04-01 13:33:37.717901074

     order_weight     sla_max_delivery_time_brt
396      8.578496 2024-04-01 14:33:37.717901074
2024-04-01 13:33:37.717901074
tem rota aberta
dist order to order é  3.30168852275191 hub em questão 12
dist order to hub é  1.9287767388824897 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 146
398
     order_id  order_latitude  order_longitude                ordered_at_brt  \
397       398      -23.685658       -46.655855 2024-04-01 13:36:24.005232822

     order_weight     sla_max_delivery_time_brt
397      5.649151 2024-04-01 15:36:24.005232822
2024-04-01 13:36:24.005232822
tem rota aberta
dist order to order é  1.1068670728371202 hub em questão 5
dist order to hub é  1.4873500083568914 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 143
399
     order_id  order_latitude  order_longitude                ordered_at_brt  \
398       399       -23.69385       -46.680337 2024-04-01 13:37:49.887091186

     order_weight     sla_max_delivery_time_brt
398      5.953739 2024-04-01 14:37:49.887091186
2024-04-01 13:37:49.887091186
tem rota aberta
dist order to order é  4.590078023932532 hub em questão 9
dist order to hub é  3.455732031662207 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 145
400
     order_id  order_latitude  order_longitude                ordered_at_brt  \
399       400      -23.704915       -46.720462 2024-04-01 13:39:23.319100108

     order_weight     sla_max_delivery_time_brt
399      6.683144 2024-04-01 14:39:23.319100108
2024-04-01 13:39:23.319100108
tem rota aberta
dist order to order é  4.266666535319077 hub em questão 9
dist order to hub é  6.104053628351975 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 145
401
     order_id  order_latitude  order_longitude                ordered_at_brt  \
400       401       -23.72696       -46.609038 2024-04-01 13:45:47.899050055

     order_weight     sla_max_delivery_time_brt
400      4.414796 2024-04-01 14:45:47.899050055
2024-04-01 13:45:47.899050055
tem rota aberta
dist order to order é  2.617017564197896 hub em questão 1
dist order to hub é  2.502425830620626 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 144
402
     order_id  order_latitude  order_longitude                ordered_at_brt  \
401       402      -23.692788       -46.702328 2024-04-01 13:49:03.431982833

     order_weight     sla_max_delivery_time_brt
401      8.419407 2024-04-01 14:49:03.431982833

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 13:49:03.431982833
tem rota aberta
dist order to order é  2.2422364314785965 hub em questão 9
dist order to hub é  4.495211846582813 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 145
403
     order_id  order_latitude  order_longitude                ordered_at_brt  \
402       403      -23.655516       -46.674964 2024-04-01 13:49:07.374822103

     order_weight     sla_max_delivery_time_brt
402      6.583356 2024-04-01 15:49:07.374822103
2024-04-01 13:49:07.374822103
tem rota aberta
dist order to order é  6.422535260166007 hub em questão 1
dist order to hub é  2.6914398719079986 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 1
passou aqui1
passou aqui5
route_id 148
caiu aqui tb
404
     order_id  order_latitude  order_longitude                ordered_at_brt  \
403       404      -23.648182       -46.615808 2024-04-01 13:51:35.666461099

     order_weight     sla_max_delivery_time_brt
403     14.956419 2024-04-01 15:51:35.666461099
2024-04-01 13:51:35.666461099
tem rota aberta
dist order to order é  5.636932473425404 hub em questão 12
dist order to hub é  2.518153838483886 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 12
passou aqui1
passou aqui5
route_id 149
caiu aqui tb
405

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
404       405      -23.591603       -46.638831 2024-04-01 13:52:50.725417263

     order_weight     sla_max_delivery_time_brt
404      5.031259 2024-04-01 15:52:50.725417263
2024-04-01 13:52:50.725417263
tem rota aberta
dist order to order é  4.860058498316806 hub em questão 4
dist order to hub é  1.0176914133267716 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 4
passou aqui1
passou aqui5
route_id 150
caiu aqui tb
406
     order_id  order_latitude  order_longitude                ordered_at_brt  \
405       406      -23.691305       -46.652334 2024-04-01 13:58:44.470388609

     order_weight     sla_max_delivery_time_brt
405      7.838686 2024-04-01 15:58:44.470388609
2024-04-01 13:58:44.470388609
tem rota aberta
dist order to order é  4.598749821200208 hub em questão 5
dist order to hub é  2.146305306764461 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 5
passou aqui1
rota em aberto, route_id:  148
rota_escolhida: 148
orders no hub: 1
passou aqui3
passou aqui4
407
     order_id  order_latitude  order_longitude                ordered_at_brt  \
406       407      -23.689222       -46.658712 2024-04-01 13:59:14.506375076

     order_weight     sla_max_delivery_time_brt
406      5.176855 2024-04-01 16:59:14.506375076
2024-04-01 13:59:14.506375076
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  0.6895141850732254 hub em questão 5
dist order to hub é  1.9052363899523486 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 148
408
     order_id  order_latitude  order_longitude                ordered_at_brt  \
407       408      -23.688067       -46.590716 2024-04-01 13:59:51.791315305

     order_weight     sla_max_delivery_time_brt
407      9.189441 2024-04-01 14:59:51.791315305
2024-04-01 13:59:51.791315305
tem rota aberta
dist order to order é  5.118528798984077 hub em questão 14
dist order to hub é  2.5379529408478514 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 14
passou aqui1
passou aqui5
route_id 151
caiu aqui tb
409
     order_id  order_latitude  order_longitude                ordered_at_brt  \
408       409      -23.640438       -46.536499 2024-04-01 14:00:01.989518841

     order_weight     sla_max_delivery_time_brt
408      4.338437 2024-04-01 15:00:01.989518841
2024-04-01 14:00:01.989518841
tem rota aberta
dist order to order é  7.651070644050528 hub em questão 12
dist order to hub é  2.990377493451823 hub em questão 2
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 2
hub_order 12
passou aqui1
passou aqui5
route_id 152
caiu aqui tb
410
     order_id  order_latitude  order_longitude                ordered_at_brt  \
409       410      -23.658149       -46.675451 2024-04-01 14:01:09.153367825

     order_weight     sla_max_delivery_time_brt
409      7.231982 2024-04-01 16:01:09.153367825
2024-04-01 14:01:09.153367825
tem rota aberta
dist order to order é  0.2969339139028466 hub em questão 5
dist order to hub é  2.536263190781787 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 148
411
     order_id  order_latitude  order_longitude                ordered_at_brt  \
410       411      -23.611365       -46.619568 2024-04-01 14:01:23.005197173

     order_weight     sla_max_delivery_time_brt
410      7.220249 2024-04-01 16:01:23.005197173
2024-04-01 14:01:23.005197173
tem rota aberta
dist order to order é  2.946432077652274 hub em questão 8
dist order to hub é  1.0752571442587422 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 150
412
     order_id  order_latitude  order_longitude                ordered_at_brt  \
411       412      -23.689682       -46.551573 2024-04-01 14:03:23.549936448

     order_weight     sla_max_delivery_time_brt
411      8.248078 2024-04-01 16:03:23.549936448
2024-04-01 14:03:23.549936448
tem rota aberta
dist order to order é  3.9898795437594594 hub em questão 12
dist order to hub é  3.510091243263831 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 151
413
     order_id  order_latitude  order_longitude                ordered_at_brt  \
412       413      -23.604562        -46.59406 2024-04-01 14:06:38.473731088

     order_weight     sla_max_delivery_time_brt
412        1.3624 2024-04-01 17:06:38.473731088
2024-04-01 14:06:38.473731088
tem rota aberta
dist order to order é  2.706780671271325 hub em questão 8
dist order to hub é  2.236846554554968 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 150
414
     order_id  order_latitude  order_longitude                ordered_at_brt  \
413       414        -23.6031       -46.682354 2024-04-01 14:09:01.677442467

     order_weight     sla_max_delivery_time_brt
413      8.726377 2024-04-01 16:09:01.677442467
2024-04-01 14:09:01.677442467
tem rota aberta
dist order to order é  4.615468996613721 hub em questão 8
dist order to hub é  2.6853361565664935 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 150
415
     order_id  order_latitude  order_longitude                ordered_at_brt  \
414       415      -23.663349       -46.669547 2024-04-01 14:11:56.077991644

     order_weight     sla_max_delivery_time_brt
414      7.306187 2024-04-01 17:11:56.077991644
2024-04-01 14:11:56.077991644
tem rota aberta
dist order to order é  5.727333064873812 hub em questão 14
dist order to hub é  1.7079627753960676 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 14
passou aqui1
passou aqui5
route_id 153
caiu aqui tb
416
     order_id  order_latitude  order_longitude                ordered_at_brt  \
415       416      -23.681352       -46.677911 2024-04-01 14:12:46.386880163

     order_weight     sla_max_delivery_time_brt
415     10.552911 2024-04-01 17:12:46.386880163
2024-04-01 14:12:46.386880163
tem rota aberta
dist order to order é  2.175591178052141 hub em questão 5
dist order to hub é  2.457562268907931 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 153
417
     order_id  order_latitude  order_longitude                ordered_at_brt  \
416       417      -23.641167       -46.693685 2024-04-01 14:16:30.767529608

     order_weight     sla_max_delivery_time_brt
416      4.615471 2024-04-01 16:16:30.767529608
2024-04-01 14:16:30.767529608
tem rota aberta
dist order to order é  3.4825666940776974 hub em questão 5
dist order to hub é  1.5730203050288014 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 153
418
     order_id  order_latitude  order_longitude                ordered_at_brt  \
417       418      -23.689802       -46.679208 2024-04-01 14:17:37.962874068

     order_weight     sla_max_delivery_time_brt
417      6.622291 2024-04-01 16:17:37.962874068
2024-04-01 14:17:37.962874068
tem rota aberta
dist order to order é  0.9488124084195207 hub em questão 5
dist order to hub é  3.0702840701435066 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 153
419

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
418       419      -23.550615       -46.634919 2024-04-01 14:21:06.442158156

     order_weight     sla_max_delivery_time_brt
418      4.118961 2024-04-01 15:21:06.442158156
2024-04-01 14:21:06.442158156
tem rota aberta
dist order to order é  11.022351924990387 hub em questão 14
dist order to hub é  5.5551819813283 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 14
passou aqui1
passou aqui5
route_id 154
caiu aqui tb
420
     order_id  order_latitude  order_longitude                ordered_at_brt  \
419       420      -23.643181       -46.677364 2024-04-01 14:23:04.621396914

     order_weight     sla_max_delivery_time_brt
419       4.46826 2024-04-01 16:23:04.621396914
2024-04-01 14:23:04.621396914
tem rota aberta
dist order to order é  10.138252832615212 hub em questão 12
dist order to hub é  2.8150108418313935 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 12
passou aqui1
passou aqui5
route_id 155
caiu aqui tb
421
     order_id  order_latitude  order_longitude                ordered_at_brt  \
420       421      -23.610603       -46.604203 2024-04-01 14:23:23.198731472

     order_weight     sla_max_delivery_time_brt
420      8.885025 2024-04-01 17:23:23.198731472
2024-04-01 14:23:23.198731472
tem rota aberta
dist order to order é  7.368369337507492 hub em questão 8
dist order to hub é  1.298351297770765 hub em questão 13
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 13
hub_order 8
passou aqui1
passou aqui5
route_id 156
caiu aqui tb
422
     order_id  order_latitude  order_longitude                ordered_at_brt  \
421       422      -23.713581        -46.64185 2024-04-01 14:23:32.994304420

     order_weight     sla_max_delivery_time_brt
421      8.611643 2024-04-01 15:23:32.994304420

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 14:23:32.994304420
tem rota aberta
dist order to order é  5.929032135381353 hub em questão 12
dist order to hub é  1.4133449613888254 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 12
passou aqui1
passou aqui5
route_id 157
caiu aqui tb
423
     order_id  order_latitude  order_longitude                ordered_at_brt  \
422       423      -23.737763       -46.667869 2024-04-01 14:23:35.214636610

     order_weight     sla_max_delivery_time_brt
422      6.578887 2024-04-01 16:23:35.214636610
2024-04-01 14:23:35.214636610
tem rota aberta
dist order to order é  3.7743906142442927 hub em questão 1
dist order to hub é  4.92634887438308 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 157
424
     order_id  order_latitude  order_longitude                ordered_at_brt  \
423       424      -23.615862       -46.603708 2024-04-01 14:23:43.501281119

     order_weight     sla_max_delivery_time_brt
423      7.424925 2024-04-01 16:23:43.501281119
2024-04-01 14:23:43.501281119
tem rota aberta
dist order to order é  0.586911186631172 hub em questão 13
dist order to hub é  0.9232353614387875 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 156
425
     order_id  order_latitude  order_longitude                ordered_at_brt  \
424       425      -23.624431       -46.632064 2024-04-01 14:24:57.129321736

     order_weight     sla_max_delivery_time_brt
424      7.935906 2024-04-01 15:24:57.129321736
2024-04-01 14:24:57.129321736
tem rota aberta
dist order to order é  3.0419595502374426 hub em questão 13
dist order to hub é  1.5885022124606398 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 156
426
     order_id  order_latitude  order_longitude                ordered_at_brt  \
425       426      -23.688256       -46.634769 2024-04-01 14:25:11.564824126

     order_weight     sla_max_delivery_time_brt
425      9.307256 2024-04-01 17:25:11.564824126
2024-04-01 14:25:11.564824126
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.906845641032506 hub em questão 1
dist order to hub é  2.790488767537205 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 157
427
     order_id  order_latitude  order_longitude                ordered_at_brt  \
426       427      -23.678564       -46.596011 2024-04-01 14:25:14.946016993

     order_weight     sla_max_delivery_time_brt
426      8.752857 2024-04-01 15:25:14.946016993
2024-04-01 14:25:14.946016993
tem rota aberta
dist order to order é  1.1862847870283406 hub em questão 12
dist order to hub é  2.185786614872154 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 151
428
     order_id  order_latitude  order_longitude                ordered_at_brt  \
427       428      -23.684223        -46.61935 2024-04-01 14:28:03.657838528

     order_weight     sla_max_delivery_time_brt
427     12.365778 2024-04-01 16:28:03.657838528
2024-04-01 14:28:03.657838528
tem rota aberta
dist order to order é  1.63296118745138 hub em questão 1
dist order to hub é  3.280989244943513 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 157
429
     order_id  order_latitude  order_longitude                ordered_at_brt  \
428       429      -23.638834       -46.653458 2024-04-01 14:29:03.931403938

     order_weight     sla_max_delivery_time_brt
428      6.926107 2024-04-01 17:29:03.931403938
2024-04-01 14:29:03.931403938
tem rota aberta
dist order to order é  2.4827019400369688 hub em questão 9
dist order to hub é  2.3063800875421916 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 155
430

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
429       430      -23.604033       -46.601135 2024-04-01 14:31:48.826130269

     order_weight     sla_max_delivery_time_brt
429     11.470869 2024-04-01 16:31:48.826130269
2024-04-01 14:31:48.826130269
tem rota aberta
dist order to order é  0.7946688720109822 hub em questão 13
dist order to hub é  2.0601885292829043 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 156
431
     order_id  order_latitude  order_longitude                ordered_at_brt  \
430       431      -23.727468       -46.632547 2024-04-01 14:33:01.092410265

     order_weight     sla_max_delivery_time_brt
430      6.036769 2024-04-01 16:33:01.092410265
2024-04-01 14:33:01.092410265
tem rota aberta
dist order to order é  10.08310757360526 hub em questão 9
dist order to hub é  1.7119303726405788 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 9
passou aqui1
passou aqui5
route_id 158
caiu aqui tb
432
     order_id  order_latitude  order_longitude                ordered_at_brt  \
431       432      -23.626288       -46.502147 2024-04-01 14:34:12.851778466

     order_weight     sla_max_delivery_time_brt
431      8.682418 2024-04-01 15:34:12.851778466
2024-04-01 14:34:12.851778466
tem rota aberta
dist order to order é  15.476942848725518 hub em questão 9
dist order to hub é  3.399213951192292 hub em questão 2
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 2
hub_order 9
passou aqui1
passou aqui5
route_id 159
caiu aqui tb
433
     order_id  order_latitude  order_longitude                ordered_at_brt  \
432       433      -23.693934       -46.593078 2024-04-01 14:35:30.878970766

     order_weight     sla_max_delivery_time_brt
432      7.812357 2024-04-01 16:35:30.878970766
2024-04-01 14:35:30.878970766
tem rota aberta
dist order to order é  5.481868206637128 hub em questão 1
dist order to hub é  3.2211207300582974 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 1
passou aqui1
passou aqui5
route_id 160
caiu aqui tb
434
     order_id  order_latitude  order_longitude                ordered_at_brt  \
433       434      -23.676772       -46.590352 2024-04-01 14:36:47.974354512

     order_weight     sla_max_delivery_time_brt
433      9.300006 2024-04-01 16:36:47.974354512
2024-04-01 14:36:47.974354512
tem rota aberta
dist order to order é  1.928392637178505 hub em questão 12
dist order to hub é  1.5909212668955017 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 160
435
     order_id  order_latitude  order_longitude                ordered_at_brt  \
434       435      -23.658247       -46.583463 2024-04-01 14:40:03.020079547

     order_weight     sla_max_delivery_time_brt
434      7.100045 2024-04-01 16:40:03.020079547
2024-04-01 14:40:03.020079547
tem rota aberta
dist order to order é  2.17607580935081 hub em questão 12
dist order to hub é  1.3236544866352613 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 160

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

436
     order_id  order_latitude  order_longitude                ordered_at_brt  \
435       436      -23.718298       -46.644021 2024-04-01 14:41:04.798614939

     order_weight     sla_max_delivery_time_brt
435     12.281717 2024-04-01 16:41:04.798614939
2024-04-01 14:41:04.798614939
tem rota aberta
dist order to order é  1.5505104487808938 hub em questão 1
dist order to hub é  1.7474626491845053 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 158
437
     order_id  order_latitude  order_longitude                ordered_at_brt  \
436       437      -23.508028       -46.582368 2024-04-01 14:45:46.868245763

     order_weight     sla_max_delivery_time_brt
436      0.899243 2024-04-01 16:45:46.868245763
2024-04-01 14:45:46.868245763
tem rota aberta
dist order to order é  7.1503723293338375 hub em questão 8
dist order to hub é  11.684156387819685 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 154
438
     order_id  order_latitude  order_longitude                ordered_at_brt  \
437       438      -23.528976       -46.646845 2024-04-01 14:45:51.400077287

     order_weight     sla_max_delivery_time_brt
437      9.580708 2024-04-01 15:45:51.400077287
2024-04-01 14:45:51.400077287
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.6958137433313585 hub em questão 8
dist order to hub é  7.18882452779546 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 154
439
     order_id  order_latitude  order_longitude                ordered_at_brt  \
438       439      -23.612612       -46.689571 2024-04-01 14:48:49.799808714

     order_weight     sla_max_delivery_time_brt
438      9.094505 2024-04-01 17:48:49.799808714
2024-04-01 14:48:49.799808714
tem rota aberta
dist order to order é  3.619481516811298 hub em questão 9
dist order to hub é  3.0498445191787065 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 155
440
     order_id  order_latitude  order_longitude                ordered_at_brt  \
439       440      -23.617425       -46.676212 2024-04-01 14:49:05.911568924

     order_weight     sla_max_delivery_time_brt
439       9.30464 2024-04-01 16:49:05.911568924
2024-04-01 14:49:05.911568924
tem rota aberta
dist order to order é  1.462521088837479 hub em questão 9
dist order to hub é  1.6823035289594368 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 155
441
     order_id  order_latitude  order_longitude                ordered_at_brt  \
440       441      -23.702406       -46.621615 2024-04-01 14:51:01.553167833

     order_weight     sla_max_delivery_time_brt
440     12.255388 2024-04-01 16:51:01.553167833
2024-04-01 14:51:01.553167833
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.885502753552621 hub em questão 1
dist order to hub é  1.3112763150055542 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 158
442
     order_id  order_latitude  order_longitude                ordered_at_brt  \
441       442      -23.531358       -46.726069 2024-04-01 14:51:02.803369149

     order_weight     sla_max_delivery_time_brt
441      10.97821 2024-04-01 17:51:02.803369149
2024-04-01 14:51:02.803369149
tem rota aberta
dist order to order é  8.081148045656809 hub em questão 8
dist order to hub é  4.7260113973168245 hub em questão 11
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 11
hub_order 8
passou aqui1
passou aqui5
route_id 161
caiu aqui tb
443
     order_id  order_latitude  order_longitude                ordered_at_brt  \
442       443      -23.649309       -46.637595 2024-04-01 14:52:35.629256946

     order_weight     sla_max_delivery_time_brt
442        2.7853 2024-04-01 16:52:35.629256946
2024-04-01 14:52:35.629256946
tem rota aberta
dist order to order é  5.602372357761519 hub em questão 12
dist order to hub é  3.16266783492778 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
passou aqui5
route_id 162
caiu aqui tb
444
     order_id  order_latitude  order_longitude                ordered_at_brt  \
443       444      -23.656395        -46.68443 2024-04-01 14:52:35.991959326

     order_weight     sla_max_delivery_time_brt
443     10.375409 2024-04-01 16:52:35.991959326
2024-04-01 14:52:35.991959326
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.834971135977616 hub em questão 5
dist order to hub é  1.9552137359772637 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 163
caiu aqui tb
445
     order_id  order_latitude  order_longitude                ordered_at_brt  \
444       445      -23.590026       -46.612102 2024-04-01 14:58:38.379674652

     order_weight     sla_max_delivery_time_brt
444      5.676792 2024-04-01 16:58:38.379674652
2024-04-01 14:58:38.379674652
tem rota aberta
dist order to order é  7.085267284174749 hub em questão 5
dist order to hub é  2.7672647097290626 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 5
passou aqui1
passou aqui5
route_id 164
caiu aqui tb
446
     order_id  order_latitude  order_longitude                ordered_at_brt  \
445       446      -23.637185       -46.685321 2024-04-01 15:03:21.353990780

     order_weight     sla_max_delivery_time_brt
445      7.660673 2024-04-01 16:03:21.353990780
2024-04-01 15:03:21.353990780
tem rota aberta
dist order to order é  2.137960834523486 hub em questão 9
dist order to hub é  2.477085767522834 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 163
447
     order_id  order_latitude  order_longitude                ordered_at_brt  \
446       447      -23.689056       -46.554398 2024-04-01 15:06:32.090780655

     order_weight     sla_max_delivery_time_brt
446      8.344333 2024-04-01 17:06:32.090780655
2024-04-01 15:06:32.090780655
tem rota aberta
dist order to order é  9.556315811844517 hub em questão 5
dist order to hub é  3.2513456870444593 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 5
passou aqui1
passou aqui5
route_id 165
caiu aqui tb
448
     order_id  order_latitude  order_longitude                ordered_at_brt  \
447       448      -23.661171       -46.609622 2024-04-01 15:11:28.291164800

     order_weight     sla_max_delivery_time_brt
447      4.464728 2024-04-01 17:11:28.291164800
2024-04-01 15:11:28.291164800
tem rota aberta
dist order to order é  3.1396332594888743 hub em questão 5
dist order to hub é  3.3889937933823395 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 162
449
     order_id  order_latitude  order_longitude                ordered_at_brt  \
448       449       -23.66903       -46.711456 2024-04-01 15:11:47.167995826

     order_weight     sla_max_delivery_time_brt
448       2.88871 2024-04-01 17:11:47.167995826
2024-04-01 15:11:47.167995826
tem rota aberta
dist order to order é  3.090251943804036 hub em questão 9
dist order to hub é  2.0380318817785223 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 163
450
     order_id  order_latitude  order_longitude                ordered_at_brt  \
449       450      -23.646993       -46.560075 2024-04-01 15:12:07.766563907

     order_weight     sla_max_delivery_time_brt
449      7.466501 2024-04-01 17:12:07.766563907
2024-04-01 15:12:07.766563907
tem rota aberta
dist order to order é  4.712795389259691 hub em questão 12
dist order to hub é  2.9966158679642683 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 165
451

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
450       451      -23.622502       -46.659375 2024-04-01 15:12:32.702736331

     order_weight     sla_max_delivery_time_brt
450       7.43353 2024-04-01 17:12:32.702736331
2024-04-01 15:12:32.702736331
tem rota aberta
dist order to order é  3.1067588152534564 hub em questão 9
dist order to hub é  0.6955919447512855 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 9
passou aqui1
passou aqui5
route_id 166
caiu aqui tb
452
     order_id  order_latitude  order_longitude                ordered_at_brt  \
451       452      -23.623587       -46.684387 2024-04-01 15:14:29.603598993

     order_weight     sla_max_delivery_time_brt
451      5.272117 2024-04-01 18:14:29.603598993
2024-04-01 15:14:29.603598993
tem rota aberta
dist order to order é  1.5150206262301376 hub em questão 9
dist order to hub é  2.6552109140767186 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 163
453
     order_id  order_latitude  order_longitude                ordered_at_brt  \
452       453      -23.585165       -46.699203 2024-04-01 15:19:13.095908116

     order_weight     sla_max_delivery_time_brt
452      4.261599 2024-04-01 18:19:13.095908116
2024-04-01 15:19:13.095908116
tem rota aberta
dist order to order é  5.805585614067054 hub em questão 10
dist order to hub é  1.5304078016395202 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 10
passou aqui1
passou aqui5
route_id 167
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

454
     order_id  order_latitude  order_longitude                ordered_at_brt  \
453       454       -23.65043       -46.619625 2024-04-01 15:28:25.179672541

     order_weight     sla_max_delivery_time_brt
453      7.017961 2024-04-01 16:28:25.179672541
2024-04-01 15:28:25.179672541
tem rota aberta
dist order to order é  5.103000365059482 hub em questão 10
dist order to hub é  2.785147542960892 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 10
passou aqui1
passou aqui5
route_id 168
caiu aqui tb
455
     order_id  order_latitude  order_longitude                ordered_at_brt  \
454       455      -23.602322       -46.572787 2024-04-01 15:30:54.189962151

     order_weight     sla_max_delivery_time_brt
454      6.098981 2024-04-01 17:30:54.189962151
2024-04-01 15:30:54.189962151
tem rota aberta
dist order to order é  5.133200245567332 hub em questão 12
dist order to hub é  1.4852509907538585 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 12
passou aqui1
passou aqui5
route_id 169
caiu aqui tb
456
     order_id  order_latitude  order_longitude                ordered_at_brt  \
455       456      -23.564892       -46.676934 2024-04-01 15:33:32.112822188

     order_weight     sla_max_delivery_time_brt
455      6.828964 2024-04-01 16:33:32.112822188
2024-04-01 15:33:32.112822188
tem rota aberta
dist order to order é  3.198792974570374 hub em questão 4
dist order to hub é  2.4643609228418675 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 167

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

457
     order_id  order_latitude  order_longitude                ordered_at_brt  \
456       457      -23.711526       -46.697894 2024-04-01 15:38:20.127582467

     order_weight     sla_max_delivery_time_brt
456     12.544097 2024-04-01 16:38:20.127582467
2024-04-01 15:38:20.127582467
tem rota aberta
dist order to order é  10.472754043746004 hub em questão 14
dist order to hub é  6.109225724517434 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 14
passou aqui1
passou aqui5
route_id 170
caiu aqui tb
458
     order_id  order_latitude  order_longitude                ordered_at_brt  \
457       458      -23.614597       -46.704998 2024-04-01 15:39:21.601531151

     order_weight     sla_max_delivery_time_brt
457       8.75013 2024-04-01 17:39:21.601531151
2024-04-01 15:39:21.601531151
tem rota aberta
dist order to order é  3.3254896967008456 hub em questão 4
dist order to hub é  4.204400776687644 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 167
459
     order_id  order_latitude  order_longitude                ordered_at_brt  \
458       459      -23.703842       -46.573193 2024-04-01 15:39:56.099491059

     order_weight     sla_max_delivery_time_brt
458     11.014556 2024-04-01 16:39:56.099491059
2024-04-01 15:39:56.099491059
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  7.591483180958613 hub em questão 14
dist order to hub é  2.425845426696575 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 14
passou aqui1
passou aqui5
route_id 171
caiu aqui tb
460
     order_id  order_latitude  order_longitude                ordered_at_brt  \
459       460      -23.725579       -46.564476 2024-04-01 15:40:18.955996351

     order_weight     sla_max_delivery_time_brt
459      5.135088 2024-04-01 16:40:18.955996351
2024-04-01 15:40:18.955996351
tem rota aberta
dist order to order é  2.57480422678818 hub em questão 6
dist order to hub é  1.1831637184110164 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 171
461
     order_id  order_latitude  order_longitude                ordered_at_brt  \
460       461      -23.570992       -46.665436 2024-04-01 15:40:34.221985172

     order_weight     sla_max_delivery_time_brt
460     11.813976 2024-04-01 18:40:34.221985172
2024-04-01 15:40:34.221985172
tem rota aberta
dist order to order é  1.3540005870683067 hub em questão 4
dist order to hub é  3.5270197752159085 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 167
462
     order_id  order_latitude  order_longitude                ordered_at_brt  \
461       462      -23.593451       -46.621128 2024-04-01 15:43:55.169954421

     order_weight     sla_max_delivery_time_brt
461      6.935587 2024-04-01 17:43:55.169954421
2024-04-01 15:43:55.169954421
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  5.0235617214992745 hub em questão 3
dist order to hub é  1.7732913379761588 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 3
passou aqui1
passou aqui5
route_id 172
caiu aqui tb
463
     order_id  order_latitude  order_longitude                ordered_at_brt  \
462       463      -23.624057       -46.648158 2024-04-01 15:44:14.220236856

     order_weight     sla_max_delivery_time_brt
462       7.39864 2024-04-01 17:44:14.220236856
2024-04-01 15:44:14.220236856
tem rota aberta
dist order to order é  4.129002483134026 hub em questão 14
dist order to hub é  0.9247780496647648 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 14
passou aqui1
passou aqui5
route_id 173
caiu aqui tb
464
     order_id  order_latitude  order_longitude                ordered_at_brt  \
463       464      -23.674072       -46.651044 2024-04-01 15:44:51.051768509

     order_weight     sla_max_delivery_time_brt
463      7.184581 2024-04-01 17:44:51.051768509
2024-04-01 15:44:51.051768509
tem rota aberta
dist order to order é  4.141328916078822 hub em questão 14
dist order to hub é  0.5334463450100934 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 14
passou aqui1
rota em aberto, route_id:  170
rota_escolhida: 170
orders no hub: 1
passou aqui3
passou aqui4
465
     order_id  order_latitude  order_longitude                ordered_at_brt  \
464       465      -23.575047       -46.599812 2024-04-01 15:48:16.221896760

     order_weight     sla_max_delivery_time_brt
464       8.10195 2024-04-01 18:48:16.221896760
2024-04-01 15:48:16.221896760
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.984370763487253 hub em questão 8
dist order to hub é  4.709581478841684 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 172
466
     order_id  order_latitude  order_longitude                ordered_at_brt  \
465       466      -23.718584       -46.625965 2024-04-01 15:49:00.851712759

     order_weight     sla_max_delivery_time_brt
465        2.3571 2024-04-01 16:49:00.851712759
2024-04-01 15:49:00.851712759
tem rota aberta
dist order to order é  5.569403466293607 hub em questão 5
dist order to hub é  0.6922743727733272 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 174
caiu aqui tb
467
     order_id  order_latitude  order_longitude                ordered_at_brt  \
466       467      -23.646856       -46.631538 2024-04-01 15:57:05.753509459

     order_weight     sla_max_delivery_time_brt
466      7.004159 2024-04-01 17:57:05.753509459
2024-04-01 15:57:05.753509459
tem rota aberta
dist order to order é  1.276945030068855 hub em questão 14
dist order to hub é  2.820617677351364 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 168
468
     order_id  order_latitude  order_longitude                ordered_at_brt  \
467       468      -23.625966       -46.662642 2024-04-01 15:57:42.967524931

     order_weight     sla_max_delivery_time_brt
467      9.043129 2024-04-01 17:57:42.967524931
2024-04-01 15:57:42.967524931
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.4907355445598696 hub em questão 10
dist order to hub é  1.1858320095559651 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 173
469
     order_id  order_latitude  order_longitude                ordered_at_brt  \
468       469      -23.585869       -46.607233 2024-04-01 15:59:14.506648110

     order_weight     sla_max_delivery_time_brt
468     11.285205 2024-04-01 18:59:14.506648110
2024-04-01 15:59:14.506648110
tem rota aberta
dist order to order é  1.4212504254072282 hub em questão 8
dist order to hub é  3.4187547206978612 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 172
470
     order_id  order_latitude  order_longitude                ordered_at_brt  \
469       470      -23.726547       -46.662113 2024-04-01 15:59:59.813686999

     order_weight     sla_max_delivery_time_brt
469      8.357022 2024-04-01 16:59:59.813686999
2024-04-01 15:59:59.813686999
tem rota aberta
dist order to order é  3.7848893451981884 hub em questão 1
dist order to hub é  3.800809927867967 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 174
471
     order_id  order_latitude  order_longitude                ordered_at_brt  \
470       471      -23.803432       -46.645517 2024-04-01 16:04:49.802051301

     order_weight     sla_max_delivery_time_brt
470      5.003677 2024-04-01 18:04:49.802051301
2024-04-01 16:04:49.802051301
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  8.714543856954593 hub em questão 1
dist order to hub é  10.251245198012034 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 174
472
     order_id  order_latitude  order_longitude                ordered_at_brt  \
471       472      -23.644457       -46.637039 2024-04-01 16:05:44.592214982

     order_weight     sla_max_delivery_time_brt
471      2.864657 2024-04-01 17:05:44.592214982
2024-04-01 16:05:44.592214982
tem rota aberta
dist order to order é  2.535468075039136 hub em questão 10
dist order to hub é  2.965045006134024 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 173
473
     order_id  order_latitude  order_longitude                ordered_at_brt  \
472       473      -23.634354       -46.708071 2024-04-01 16:06:52.805157807

     order_weight     sla_max_delivery_time_brt
472      7.995381 2024-04-01 17:06:52.805157807
2024-04-01 16:06:52.805157807
tem rota aberta
dist order to order é  4.720949416789077 hub em questão 10
dist order to hub é  2.0657122019454026 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 10
passou aqui1
passou aqui5
route_id 175
caiu aqui tb
474
     order_id  order_latitude  order_longitude                ordered_at_brt  \
473       474      -23.641541       -46.662968 2024-04-01 16:08:18.969937686

     order_weight     sla_max_delivery_time_brt
473      1.577411 2024-04-01 18:08:18.969937686
2024-04-01 16:08:18.969937686
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.7321662442324293 hub em questão 10
dist order to hub é  2.7437510147155977 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 173
475
     order_id  order_latitude  order_longitude                ordered_at_brt  \
474       475      -23.694088       -46.663643 2024-04-01 16:13:54.372591803

     order_weight     sla_max_delivery_time_brt
474      6.590576 2024-04-01 17:13:54.372591803
2024-04-01 16:13:54.372591803
tem rota aberta
dist order to order é  3.6126448533499493 hub em questão 1
dist order to hub é  2.5495131460253666 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 174
476
     order_id  order_latitude  order_longitude                ordered_at_brt  \
475       476      -23.652433       -46.642953 2024-04-01 16:13:58.145157007

     order_weight     sla_max_delivery_time_brt
475      8.603969 2024-04-01 17:13:58.145157007
2024-04-01 16:13:58.145157007
tem rota aberta
dist order to order é  6.930953017427284 hub em questão 9
dist order to hub é  2.571223514615967 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 9
passou aqui1
passou aqui5
route_id 176
caiu aqui tb
477
     order_id  order_latitude  order_longitude                ordered_at_brt  \
476       477      -23.727229       -46.703604 2024-04-01 16:16:29.570723743

     order_weight     sla_max_delivery_time_brt
476      7.313741 2024-04-01 17:16:29.570723743
2024-04-01 16:16:29.570723743
tem rota aberta
dist order to order é  10.337290404671688 hub em questão 9
dist order to hub é  7.804943938440337 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 9
passou aqui1
rota em aberto, route_id:  176
rota_escolhida: 176
orders no hub: 1
passou aqui3
passou aqui4
478
     order_id  order_latitude  order_longitude                ordered_at_brt  \
477       478      -23.629196        -46.70734 2024-04-01 16:20:55.560480278

     order_weight     sla_max_delivery_time_brt
477      6.217893 2024-04-01 18:20:55.560480278
2024-04-01 16:20:55.560480278
tem rota aberta
dist order to order é  0.5783821830108701 hub em questão 9
dist order to hub é  2.6123824767361805 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 175
479
     order_id  order_latitude  order_longitude                ordered_at_brt  \
478       479      -23.605596        -46.56684 2024-04-01 16:20:58.880452372

     order_weight     sla_max_delivery_time_brt
478      1.313699 2024-04-01 19:20:58.880452372
2024-04-01 16:20:58.880452372
tem rota aberta
dist order to order é  9.340550573419975 hub em questão 5
dist order to hub é  1.4106489958614437 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 5
passou aqui1
passou aqui5
route_id 177
caiu aqui tb
480
     order_id  order_latitude  order_longitude                ordered_at_brt  \
479       480      -23.686827       -46.590191 2024-04-01 16:22:27.470664059

     order_weight     sla_max_delivery_time_brt
479      6.861136 2024-04-01 19:22:27.470664059
2024-04-01 16:22:27.470664059
tem rota aberta
dist order to order é  6.595351368820522 hub em questão 5
dist order to hub é  2.3929430764896713 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 5
passou aqui1
passou aqui5
route_id 178
caiu aqui tb
481
     order_id  order_latitude  order_longitude                ordered_at_brt  \
480       481      -23.750422       -46.603561 2024-04-01 16:23:14.811870312

     order_weight     sla_max_delivery_time_brt
480     10.176317 2024-04-01 17:23:14.811870312

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 16:23:14.811870312
tem rota aberta
dist order to order é  7.201309156164469 hub em questão 12
dist order to hub é  3.936559134609829 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 12
passou aqui1
passou aqui5
route_id 179
caiu aqui tb
482
     order_id  order_latitude  order_longitude                ordered_at_brt  \
481       482      -23.656714       -46.556772 2024-04-01 16:27:10.308484514

     order_weight     sla_max_delivery_time_brt
481      6.263016 2024-04-01 19:27:10.308484514
2024-04-01 16:27:10.308484514
tem rota aberta
dist order to order é  4.774332463170623 hub em questão 12
dist order to hub é  2.4922850875513487 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 12
passou aqui1
rota em aberto, route_id:  178
rota_escolhida: 178
orders no hub: 1
passou aqui3
passou aqui4
483
     order_id  order_latitude  order_longitude                ordered_at_brt  \
482       483       -23.66015       -46.627033 2024-04-01 16:28:48.422254222

     order_weight     sla_max_delivery_time_brt
482      5.756059 2024-04-01 19:28:48.422254222
2024-04-01 16:28:48.422254222
tem rota aberta
dist order to order é  1.8344915042474885 hub em questão 5
dist order to hub é  3.2350344744102966 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 176
484

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
483       484      -23.654256       -46.652567 2024-04-01 16:31:09.052451467

     order_weight     sla_max_delivery_time_brt
483      8.213193 2024-04-01 19:31:09.052451467
2024-04-01 16:31:09.052451467
tem rota aberta
dist order to order é  0.9999747247848604 hub em questão 5
dist order to hub é  2.033068423160354 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 176
485
     order_id  order_latitude  order_longitude                ordered_at_brt  \
484       485      -23.585047       -46.623904 2024-04-01 16:32:21.417094006

     order_weight     sla_max_delivery_time_brt
484      9.110283 2024-04-01 18:32:21.417094006
2024-04-01 16:32:21.417094006
tem rota aberta
dist order to order é  6.247623803010418 hub em questão 3
dist order to hub é  2.162001990256494 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 3
passou aqui1
passou aqui5
route_id 180
caiu aqui tb
486
     order_id  order_latitude  order_longitude                ordered_at_brt  \
485       486      -23.643296       -46.741977 2024-04-01 16:34:20.180195925

     order_weight     sla_max_delivery_time_brt
485      9.666467 2024-04-01 17:34:20.180195925
2024-04-01 16:34:20.180195925
tem rota aberta
dist order to order é  3.594146373051088 hub em questão 9
dist order to hub é  4.084789309379823 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 175
487

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
486       487      -23.546019       -46.702917 2024-04-01 16:35:01.295403414

     order_weight     sla_max_delivery_time_brt
486      4.387391 2024-04-01 19:35:01.295403414
2024-04-01 16:35:01.295403414
tem rota aberta
dist order to order é  9.147985784808734 hub em questão 8
dist order to hub é  2.840000972283895 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 8
passou aqui1
passou aqui5
route_id 181
caiu aqui tb
488
     order_id  order_latitude  order_longitude                ordered_at_brt  \
487       488      -23.631188       -46.610081 2024-04-01 16:35:02.422509436

     order_weight     sla_max_delivery_time_brt
487      5.542435 2024-04-01 18:35:02.422509436
2024-04-01 16:35:02.422509436
tem rota aberta
dist order to order é  5.2446337432535115 hub em questão 3
dist order to hub é  0.9076878522810822 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 182
caiu aqui tb
489
     order_id  order_latitude  order_longitude                ordered_at_brt  \
488       489      -23.704587       -46.646382 2024-04-01 16:36:45.599263093

     order_weight     sla_max_delivery_time_brt
488      7.908227 2024-04-01 18:36:45.599263093
2024-04-01 16:36:45.599263093
tem rota aberta
dist order to order é  6.052671173585014 hub em questão 12
dist order to hub é  2.0744343647589383 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 12
passou aqui1
passou aqui5
route_id 183
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

490
     order_id  order_latitude  order_longitude                ordered_at_brt  \
489       490      -23.593545       -46.711895 2024-04-01 16:37:30.378335757

     order_weight     sla_max_delivery_time_brt
489      9.998628 2024-04-01 17:37:30.378335757
2024-04-01 16:37:30.378335757
tem rota aberta
dist order to order é  5.363225324703419 hub em questão 4
dist order to hub é  2.740444132772215 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 4
passou aqui1
rota em aberto, route_id:  181
rota_escolhida: 181
orders no hub: 1
passou aqui3
passou aqui4
491
     order_id  order_latitude  order_longitude                ordered_at_brt  \
490       491      -23.654743       -46.615086 2024-04-01 16:38:57.773473320

     order_weight     sla_max_delivery_time_brt
490     11.220146 2024-04-01 17:38:57.773473320
2024-04-01 16:38:57.773473320
tem rota aberta
dist order to order é  2.6682895828533995 hub em questão 14
dist order to hub é  3.2498856949617467 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 182
492
     order_id  order_latitude  order_longitude                ordered_at_brt  \
491       492      -23.674664       -46.598068 2024-04-01 16:43:55.587286193

     order_weight     sla_max_delivery_time_brt
491      5.185245 2024-04-01 18:43:55.587286193
2024-04-01 16:43:55.587286193
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.572453836236634 hub em questão 12
dist order to hub é  2.204476924147071 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 178
493
     order_id  order_latitude  order_longitude                ordered_at_brt  \
492       493      -23.636255       -46.614619 2024-04-01 16:45:02.301692106

     order_weight     sla_max_delivery_time_brt
492       9.68252 2024-04-01 18:45:02.301692106
2024-04-01 16:45:02.301692106
tem rota aberta
dist order to order é  0.7288024907948107 hub em questão 14
dist order to hub é  1.2065413451692202 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 182
494
     order_id  order_latitude  order_longitude                ordered_at_brt  \
493       494      -23.644486       -46.649528 2024-04-01 16:45:36.407628253

     order_weight     sla_max_delivery_time_brt
493     10.980597 2024-04-01 18:45:36.407628253
2024-04-01 16:45:36.407628253
tem rota aberta
dist order to order é  3.6718324612555895 hub em questão 14
dist order to hub é  2.975969380622434 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 182
495
     order_id  order_latitude  order_longitude                ordered_at_brt  \
494       495      -23.728155       -46.689815 2024-04-01 16:46:32.098567505

     order_weight     sla_max_delivery_time_brt
494      7.859779 2024-04-01 19:46:32.098567505
2024-04-01 16:46:32.098567505
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  5.139960316795677 hub em questão 1
dist order to hub é  6.524428585363969 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 183
496
     order_id  order_latitude  order_longitude                ordered_at_brt  \
495       496      -23.692701       -46.642633 2024-04-01 16:51:54.443438017

     order_weight     sla_max_delivery_time_brt
495      6.347158 2024-04-01 18:51:54.443438017
2024-04-01 16:51:54.443438017
tem rota aberta
dist order to order é  1.3756554864553785 hub em questão 1
dist order to hub é  2.642263552101641 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 183
497
     order_id  order_latitude  order_longitude                ordered_at_brt  \
496       497      -23.592625       -46.626667 2024-04-01 16:57:25.947463577

     order_weight     sla_max_delivery_time_brt
496      4.080599 2024-04-01 18:57:25.947463577
2024-04-01 16:57:25.947463577
tem rota aberta
dist order to order é  0.8884652811087754 hub em questão 8
dist order to hub é  1.350502684698924 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 180
498
     order_id  order_latitude  order_longitude                ordered_at_brt  \
497       498      -23.641429       -46.665942 2024-04-01 17:01:09.149451560

     order_weight     sla_max_delivery_time_brt
497     10.239438 2024-04-01 20:01:09.149451560
2024-04-01 17:01:09.149451560
tem rota aberta
dist order to order é  6.175703587272435 hub em questão 1
dist order to hub é  2.8420584549310854 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 1
passou aqui1
passou aqui5
route_id 184
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

499
     order_id  order_latitude  order_longitude                ordered_at_brt  \
498       499      -23.618276       -46.617861 2024-04-01 17:06:12.547060851

     order_weight     sla_max_delivery_time_brt
498      6.978916 2024-04-01 19:06:12.547060851
2024-04-01 17:06:12.547060851
tem rota aberta
dist order to order é  5.533498032962631 hub em questão 10
dist order to hub é  0.49418999718046036 hub em questão 13
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 13
hub_order 10
passou aqui1
passou aqui5
route_id 185
caiu aqui tb
500
     order_id  order_latitude  order_longitude                ordered_at_brt  \
499       500      -23.599218       -46.632291 2024-04-01 17:06:43.584050355

     order_weight     sla_max_delivery_time_brt
499     11.374302 2024-04-01 20:06:43.584050355
2024-04-01 17:06:43.584050355
tem rota aberta
dist order to order é  2.579276134358835 hub em questão 13
dist order to hub é  0.47415322236017243 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 13
passou aqui1
passou aqui5
route_id 186
caiu aqui tb
501
     order_id  order_latitude  order_longitude                ordered_at_brt  \
500       501      -23.560595       -46.631357 2024-04-01 17:06:54.569774035

     order_weight     sla_max_delivery_time_brt
500      12.36723 2024-04-01 20:06:54.569774035
2024-04-01 17:06:54.569774035
tem rota aberta
dist order to order é  4.295744926414505 hub em questão 8
dist order to hub é  4.4758946216126425 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 186

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

502
     order_id  order_latitude  order_longitude                ordered_at_brt  \
501       502       -23.68218        -46.74964 2024-04-01 17:07:25.515014570

     order_weight     sla_max_delivery_time_brt
501      3.002307 2024-04-01 19:07:25.515014570
2024-04-01 17:07:25.515014570
tem rota aberta
dist order to order é  9.653878143385706 hub em questão 10
dist order to hub é  5.782525030706007 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 10
passou aqui1
passou aqui5
route_id 187
caiu aqui tb
503
     order_id  order_latitude  order_longitude                ordered_at_brt  \
502       503      -23.685395       -46.593958 2024-04-01 17:08:10.806231181

     order_weight     sla_max_delivery_time_brt
502       5.59637 2024-04-01 19:08:10.806231181
2024-04-01 17:08:10.806231181
tem rota aberta
dist order to order é  7.850371631723863 hub em questão 13
dist order to hub é  2.501842044414323 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 13
passou aqui1
passou aqui5
route_id 188
caiu aqui tb
504
     order_id  order_latitude  order_longitude                ordered_at_brt  \
503       504      -23.696451       -46.561793 2024-04-01 17:08:33.856808781

     order_weight     sla_max_delivery_time_brt
503      6.691059 2024-04-01 18:08:33.856808781
2024-04-01 17:08:33.856808781
tem rota aberta
dist order to order é  3.4982889660089755 hub em questão 12
dist order to hub é  3.463430714119347 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 188

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

505
     order_id  order_latitude  order_longitude                ordered_at_brt  \
504       505      -23.680248       -46.668136 2024-04-01 17:10:25.959044026

     order_weight     sla_max_delivery_time_brt
504      3.860775 2024-04-01 19:10:25.959044026
2024-04-01 17:10:25.959044026
tem rota aberta
dist order to order é  4.322252779348765 hub em questão 10
dist order to hub é  1.52845600184724 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 10
passou aqui1
passou aqui5
route_id 189
caiu aqui tb
506
     order_id  order_latitude  order_longitude                ordered_at_brt  \
505       506      -23.695855       -46.721858 2024-04-01 17:11:30.006639453

     order_weight     sla_max_delivery_time_brt
505      4.549809 2024-04-01 19:11:30.006639453
2024-04-01 17:11:30.006639453
tem rota aberta
dist order to order é  3.2116763008030893 hub em questão 9
dist order to hub é  5.198465111751536 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 187
507
     order_id  order_latitude  order_longitude                ordered_at_brt  \
506       507      -23.650975       -46.616066 2024-04-01 17:14:53.374448116

     order_weight     sla_max_delivery_time_brt
506      11.55396 2024-04-01 19:14:53.374448116
2024-04-01 17:14:53.374448116
tem rota aberta
dist order to order é  3.6405983212781377 hub em questão 13
dist order to hub é  2.8280891099714998 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 185

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

508
     order_id  order_latitude  order_longitude                ordered_at_brt  \
507       508      -23.655637       -46.671296 2024-04-01 17:15:17.941709286

     order_weight     sla_max_delivery_time_brt
507      5.146613 2024-04-01 18:15:17.941709286
2024-04-01 17:15:17.941709286
tem rota aberta
dist order to order é  1.6713221988903435 hub em questão 10
dist order to hub é  2.4254665376731626 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 184
509
     order_id  order_latitude  order_longitude                ordered_at_brt  \
508       509      -23.621163       -46.696363 2024-04-01 17:17:43.171415119

     order_weight     sla_max_delivery_time_brt
508      7.788574 2024-04-01 20:17:43.171415119
2024-04-01 17:17:43.171415119
tem rota aberta
dist order to order é  3.8316960620726217 hub em questão 10
dist order to hub é  3.537393411763912 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 184
510
     order_id  order_latitude  order_longitude                ordered_at_brt  \
509       510      -23.709758       -46.587127 2024-04-01 17:18:16.160001036

     order_weight     sla_max_delivery_time_brt
509      1.298718 2024-04-01 19:18:16.160001036
2024-04-01 17:18:16.160001036
tem rota aberta
dist order to order é  2.796889909709468 hub em questão 12
dist order to hub é  2.079103993755949 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 188

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

511
     order_id  order_latitude  order_longitude                ordered_at_brt  \
510       511      -23.682917       -46.717182 2024-04-01 17:19:58.619644003

     order_weight     sla_max_delivery_time_brt
510      5.001904 2024-04-01 19:19:58.619644003
2024-04-01 17:19:58.619644003
tem rota aberta
dist order to order é  1.5153976600586558 hub em questão 9
dist order to hub é  3.6864627343246807 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 187
512
     order_id  order_latitude  order_longitude                ordered_at_brt  \
511       512      -23.632252       -46.612141 2024-04-01 17:20:50.126834211

     order_weight     sla_max_delivery_time_brt
511      4.618798 2024-04-01 19:20:50.126834211
2024-04-01 17:20:50.126834211
tem rota aberta
dist order to order é  1.6597356066781028 hub em questão 13
dist order to hub é  0.8689689427342249 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 185
513
     order_id  order_latitude  order_longitude                ordered_at_brt  \
512       513      -23.615293       -46.710399 2024-04-01 17:20:57.164983569

     order_weight     sla_max_delivery_time_brt
512      4.572188 2024-04-01 18:20:57.164983569
2024-04-01 17:20:57.164983569
tem rota aberta
dist order to order é  1.5719517263278406 hub em questão 10
dist order to hub é  4.188847448003176 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 184
514
     order_id  order_latitude  order_longitude                ordered_at_brt  \
513       514      -23.766056       -46.574899 2024-04-01 17:21:28.344015094

     order_weight     sla_max_delivery_time_brt
513      6.616404 2024-04-01 19:21:28.344015094

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 17:21:28.344015094
tem rota aberta
dist order to order é  6.382621091450625 hub em questão 12
dist order to hub é  4.511836035301102 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 188
515
     order_id  order_latitude  order_longitude                ordered_at_brt  \
514       515      -23.680329       -46.622185 2024-04-01 17:23:39.257941879

     order_weight     sla_max_delivery_time_brt
514      6.593637 2024-04-01 20:23:39.257941879
2024-04-01 17:23:39.257941879
tem rota aberta
dist order to order é  3.322920308112322 hub em questão 13
dist order to hub é  3.5484701759566066 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 185
516
     order_id  order_latitude  order_longitude                ordered_at_brt  \
515       516      -23.662906       -46.660883 2024-04-01 17:25:01.777434202

     order_weight     sla_max_delivery_time_brt
515      2.563498 2024-04-01 19:25:01.777434202
2024-04-01 17:25:01.777434202
tem rota aberta
dist order to order é  2.0649427734782093 hub em questão 5
dist order to hub é  1.159281188161462 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 189
517
     order_id  order_latitude  order_longitude                ordered_at_brt  \
516       517      -23.752283       -46.640544 2024-04-01 17:26:29.607983044

     order_weight     sla_max_delivery_time_brt
516      5.521286 2024-04-01 19:26:29.607983044
2024-04-01 17:26:29.607983044
tem rota aberta
dist order to order é  8.488213860535584 hub em questão 5
dist order to hub é  4.5886762492024245 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 190
caiu aqui tb
518
     order_id  order_latitude  order_longitude                ordered_at_brt  \
517       518       -23.62779       -46.618908 2024-04-01 17:26:52.651911625

     order_weight     sla_max_delivery_time_brt
517      9.384842 2024-04-01 19:26:52.651911625
2024-04-01 17:26:52.651911625
tem rota aberta
dist order to order é  3.4573554734118526 hub em questão 8
dist order to hub é  0.3486716017099737 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 8
passou aqui1
passou aqui5
route_id 191
caiu aqui tb
519
     order_id  order_latitude  order_longitude                ordered_at_brt  \
518       519      -23.590019       -46.606518 2024-04-01 17:28:34.128259057

     order_weight     sla_max_delivery_time_brt
518      3.723359 2024-04-01 20:28:34.128259057
2024-04-01 17:28:34.128259057
tem rota aberta
dist order to order é  2.8184176363585984 hub em questão 8
dist order to hub é  3.2896073462668083 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 186

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

520
     order_id  order_latitude  order_longitude                ordered_at_brt  \
519       520       -23.74738       -46.606623 2024-04-01 17:40:01.746828890

     order_weight     sla_max_delivery_time_brt
519     13.259544 2024-04-01 20:40:01.746828890
2024-04-01 17:40:01.746828890
tem rota aberta
dist order to order é  3.495205131827605 hub em questão 1
dist order to hub é  3.946614529845156 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 190
521
     order_id  order_latitude  order_longitude                ordered_at_brt  \
520       521      -23.728472       -46.620676 2024-04-01 17:43:25.431047328

     order_weight     sla_max_delivery_time_brt
520     10.949959 2024-04-01 19:43:25.431047328
2024-04-01 17:43:25.431047328
tem rota aberta
dist order to order é  2.5429858188191448 hub em questão 1
dist order to hub é  1.9115023846033188 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 190
522
     order_id  order_latitude  order_longitude                ordered_at_brt  \
521       522      -23.602616       -46.671882 2024-04-01 17:45:13.709487347

     order_weight     sla_max_delivery_time_brt
521      5.600758 2024-04-01 19:45:13.709487347
2024-04-01 17:45:13.709487347
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  6.07984058757184 hub em questão 14
dist order to hub é  1.8978761921198057 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 14
passou aqui1
passou aqui5
route_id 192
caiu aqui tb
523
     order_id  order_latitude  order_longitude                ordered_at_brt  \
522       523      -23.593458       -46.614809 2024-04-01 17:52:41.219015281

     order_weight     sla_max_delivery_time_brt
522      0.588063 2024-04-01 19:52:41.219015281
2024-04-01 17:52:41.219015281
tem rota aberta
dist order to order é  3.840326291264745 hub em questão 14
dist order to hub é  2.367036695604751 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 191
524
     order_id  order_latitude  order_longitude                ordered_at_brt  \
523       524      -23.713864       -46.713579 2024-04-01 17:57:19.419132492

     order_weight     sla_max_delivery_time_brt
523      0.535251 2024-04-01 19:57:19.419132492
2024-04-01 17:57:19.419132492
tem rota aberta
dist order to order é  13.078912261257233 hub em questão 15
dist order to hub é  6.920502350547438 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 193
caiu aqui tb
525
     order_id  order_latitude  order_longitude                ordered_at_brt  \
524       525      -23.699606       -46.597808 2024-04-01 17:59:08.063581720

     order_weight     sla_max_delivery_time_brt
524      4.748887 2024-04-01 19:59:08.063581720
2024-04-01 17:59:08.063581720
tem rota aberta
dist order to order é  11.892998347148026 hub em questão 9
dist order to hub é  3.3991215342396957 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 9
passou aqui1
passou aqui5
route_id 194
caiu aqui tb
526

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
525       526      -23.617254       -46.604362 2024-04-01 17:59:12.019226611

     order_weight     sla_max_delivery_time_brt
525      4.815891 2024-04-01 19:59:12.019226611
2024-04-01 17:59:12.019226611
tem rota aberta
dist order to order é  7.06930503841374 hub em questão 15
dist order to hub é  0.7908447267579247 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 15
passou aqui1
passou aqui5
route_id 195
caiu aqui tb
527
     order_id  order_latitude  order_longitude                ordered_at_brt  \
526       527      -23.662377       -46.578309 2024-04-01 17:59:23.809142633

     order_weight     sla_max_delivery_time_brt
526      4.153184 2024-04-01 20:59:23.809142633
2024-04-01 17:59:23.809142633
tem rota aberta
dist order to order é  4.591361592688037 hub em questão 1
dist order to hub é  0.7175313457210284 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 1
passou aqui1
passou aqui5
route_id 196
caiu aqui tb
528
     order_id  order_latitude  order_longitude                ordered_at_brt  \
527       528      -23.676291       -46.677452 2024-04-01 17:59:31.921908825

     order_weight     sla_max_delivery_time_brt
527     12.261403 2024-04-01 18:59:31.921908825
2024-04-01 17:59:31.921908825
tem rota aberta
dist order to order é  5.5665551063508 hub em questão 9
dist order to hub é  2.23915835433187 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 9
passou aqui1
passou aqui5
route_id 197
caiu aqui tb
529
     order_id  order_latitude  order_longitude                ordered_at_brt  \
528       529      -23.570518       -46.638702 2024-04-01 18:00:44.041087498

     order_weight     sla_max_delivery_time_brt
528      9.925609 2024-04-01 21:00:44.041087498
2024-04-01 18:00:44.041087498
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.916402215131834 hub em questão 15
dist order to hub é  3.345166638531859 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 192
530
     order_id  order_latitude  order_longitude                ordered_at_brt  \
529       530      -23.635335       -46.605098 2024-04-01 18:01:40.525040031

     order_weight     sla_max_delivery_time_brt
529      9.741399 2024-04-01 20:01:40.525040031
2024-04-01 18:01:40.525040031
tem rota aberta
dist order to order é  2.0119145771094518 hub em questão 7
dist order to hub é  1.5933245937165679 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 195
531
     order_id  order_latitude  order_longitude                ordered_at_brt  \
530       531      -23.741198        -46.63212 2024-04-01 18:09:04.882612283

     order_weight     sla_max_delivery_time_brt
530      4.881086 2024-04-01 21:09:04.882612283
2024-04-01 18:09:04.882612283
tem rota aberta
dist order to order é  5.7956288427397 hub em questão 1
dist order to hub é  3.2024671435064023 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 1
passou aqui1
rota em aberto, route_id:  194
rota_escolhida: 194
orders no hub: 1
passou aqui3
passou aqui4
532
     order_id  order_latitude  order_longitude                ordered_at_brt  \
531       532       -23.63756       -46.669346 2024-04-01 18:09:26.950943251

     order_weight     sla_max_delivery_time_brt
531      9.536182 2024-04-01 21:09:26.950943251
2024-04-01 18:09:26.950943251
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.8941139683129333 hub em questão 15
dist order to hub é  2.6255392735945446 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 192
533
     order_id  order_latitude  order_longitude                ordered_at_brt  \
532       533      -23.720488       -46.632646 2024-04-01 18:16:39.440810941

     order_weight     sla_max_delivery_time_brt
532      6.995704 2024-04-01 20:16:39.440810941
2024-04-01 18:16:39.440810941
tem rota aberta
dist order to order é  2.30342428365394 hub em questão 1
dist order to hub é  0.9919160653311961 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 194
534
     order_id  order_latitude  order_longitude                ordered_at_brt  \
533       534      -23.613123       -46.644611 2024-04-01 18:19:34.491647207

     order_weight     sla_max_delivery_time_brt
533      7.339866 2024-04-01 21:19:34.491647207
2024-04-01 18:19:34.491647207
tem rota aberta
dist order to order é  4.126324516290542 hub em questão 7
dist order to hub é  1.1511115746634224 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 7
passou aqui1
passou aqui5
route_id 198
caiu aqui tb
535
     order_id  order_latitude  order_longitude                ordered_at_brt  \
534       535      -23.601126       -46.598228 2024-04-01 18:23:03.126474330

     order_weight     sla_max_delivery_time_brt
534      8.404302 2024-04-01 20:23:03.126474330
2024-04-01 18:23:03.126474330
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.8992449248400554 hub em questão 7
dist order to hub é  2.4964580873476145 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 195
536
     order_id  order_latitude  order_longitude                ordered_at_brt  \
535       536      -23.628297       -46.679436 2024-04-01 18:25:03.288133253

     order_weight     sla_max_delivery_time_brt
535     15.543346 2024-04-01 19:25:03.288133253
2024-04-01 18:25:03.288133253
tem rota aberta
dist order to order é  3.9287155084395557 hub em questão 10
dist order to hub é  2.4457232621262026 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 198
537
     order_id  order_latitude  order_longitude                ordered_at_brt  \
536       537      -23.603834       -46.631038 2024-04-01 18:27:15.867719880

     order_weight     sla_max_delivery_time_brt
536      2.679374 2024-04-01 19:27:15.867719880
2024-04-01 18:27:15.867719880
tem rota aberta
dist order to order é  1.726010610644122 hub em questão 10
dist order to hub é  0.6840358536840875 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 198
538
     order_id  order_latitude  order_longitude                ordered_at_brt  \
537       538      -23.552011       -46.633366 2024-04-01 18:28:33.621582661

     order_weight     sla_max_delivery_time_brt
537      6.490745 2024-04-01 19:28:33.621582661
2024-04-01 18:28:33.621582661
tem rota aberta
dist order to order é  5.7673417287918305 hub em questão 10
dist order to hub é  5.407681083239028 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 198
539
     order_id  order_latitude  order_longitude                ordered_at_brt  \
538       539      -23.613891       -46.610146 2024-04-01 18:28:35.208390901

     order_weight     sla_max_delivery_time_brt
538      1.584043 2024-04-01 20:28:35.208390901
2024-04-01 18:28:35.208390901
tem rota aberta
dist order to order é  0.6979202460097439 hub em questão 7
dist order to hub é  0.6402611961117989 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 195
540
     order_id  order_latitude  order_longitude                ordered_at_brt  \
539       540      -23.668823       -46.651657 2024-04-01 18:29:27.458597738

     order_weight     sla_max_delivery_time_brt
539      8.824066 2024-04-01 19:29:27.458597738
2024-04-01 18:29:27.458597738
tem rota aberta
dist order to order é  2.7549848624048225 hub em questão 5
dist order to hub é  0.5787721734737229 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 5
passou aqui1
rota em aberto, route_id:  197
rota_escolhida: 197
orders no hub: 1
passou aqui3
passou aqui4
541
     order_id  order_latitude  order_longitude                ordered_at_brt  \
540       541      -23.704891       -46.641647 2024-04-01 18:30:48.748419687

     order_weight     sla_max_delivery_time_brt
540      7.654611 2024-04-01 21:30:48.748419687
2024-04-01 18:30:48.748419687
não tem rota aberta
route_id 199

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist pro hub mais próximo é 1.63
hub alocado 1
542
     order_id  order_latitude  order_longitude                ordered_at_brt  \
541       542      -23.639003        -46.65156 2024-04-01 18:33:25.908963196

     order_weight     sla_max_delivery_time_brt
541     13.526411 2024-04-01 19:33:25.908963196
2024-04-01 18:33:25.908963196
tem rota aberta
dist order to order é  7.395621052092384 hub em questão 1
dist order to hub é  2.342008435623808 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 1
passou aqui1
passou aqui5
route_id 200
caiu aqui tb
543
     order_id  order_latitude  order_longitude                ordered_at_brt  \
542       543      -23.701977       -46.646309 2024-04-01 18:34:41.784193164

     order_weight     sla_max_delivery_time_brt
542      8.731148 2024-04-01 20:34:41.784193164
2024-04-01 18:34:41.784193164
tem rota aberta
dist order to order é  0.5747024617141556 hub em questão 1
dist order to hub é  2.209073065825453 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 199
544
     order_id  order_latitude  order_longitude                ordered_at_brt  \
543       544      -23.722163       -46.647595 2024-04-01 18:35:55.151225849

     order_weight     sla_max_delivery_time_brt
543      2.580458 2024-04-01 21:35:55.151225849
2024-04-01 18:35:55.151225849
tem rota aberta
dist order to order é  2.013763418848244 hub em questão 1
dist order to hub é  2.257726436669728 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 199
545
     order_id  order_latitude  order_longitude                ordered_at_brt  \
544       545      -23.673318        -46.66435 2024-04-01 18:36:12.924285813

     order_weight     sla_max_delivery_time_brt
544      3.259728 2024-04-01 20:36:12.924285813

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 18:36:12.924285813
tem rota aberta
dist order to order é  3.678344507904543 hub em questão 1
dist order to hub é  0.8677742987313717 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 1
passou aqui1
passou aqui5
route_id 201
caiu aqui tb
546
     order_id  order_latitude  order_longitude                ordered_at_brt  \
545       546      -23.739141       -46.506648 2024-04-01 18:36:14.238099806

     order_weight     sla_max_delivery_time_brt
545     12.358189 2024-04-01 20:36:14.238099806
2024-04-01 18:36:14.238099806
tem rota aberta
dist order to order é  14.260879366356592 hub em questão 1
dist order to hub é  7.230551359836501 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 1
passou aqui1
passou aqui5
route_id 202
caiu aqui tb
547
     order_id  order_latitude  order_longitude                ordered_at_brt  \
546       547      -23.715249       -46.690208 2024-04-01 18:39:04.634265935

     order_weight     sla_max_delivery_time_brt
546      0.080252 2024-04-01 20:39:04.634265935
2024-04-01 18:39:04.634265935
tem rota aberta
dist order to order é  4.405755542956666 hub em questão 1
dist order to hub é  5.918354300422271 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 199

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

548
     order_id  order_latitude  order_longitude                ordered_at_brt  \
547       548      -23.625168       -46.706683 2024-04-01 18:39:50.905441228

     order_weight     sla_max_delivery_time_brt
547      9.976403 2024-04-01 20:39:50.905441228
2024-04-01 18:39:50.905441228
tem rota aberta
dist order to order é  5.822308652112926 hub em questão 10
dist order to hub é  3.0463627951039283 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 10
passou aqui1
passou aqui5
route_id 203
caiu aqui tb
549
     order_id  order_latitude  order_longitude                ordered_at_brt  \
548       549      -23.673988       -46.687794 2024-04-01 18:48:10.036326272

     order_weight     sla_max_delivery_time_brt
548      4.253101 2024-04-01 20:48:10.036326272
2024-04-01 18:48:10.036326272
tem rota aberta
dist order to order é  2.3886570357185213 hub em questão 5
dist order to hub é  2.866084505827663 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 201
550
     order_id  order_latitude  order_longitude                ordered_at_brt  \
549       550      -23.665557       -46.683515 2024-04-01 18:48:39.887729593

     order_weight     sla_max_delivery_time_brt
549      6.268308 2024-04-01 20:48:39.887729593
2024-04-01 18:48:39.887729593
tem rota aberta
dist order to order é  1.0338102451786135 hub em questão 5
dist order to hub é  2.4771181770766115 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 201

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

551
     order_id  order_latitude  order_longitude                ordered_at_brt  \
550       551      -23.651521       -46.647441 2024-04-01 18:49:29.514908028

     order_weight     sla_max_delivery_time_brt
550      7.104436 2024-04-01 19:49:29.514908028
2024-04-01 18:49:29.514908028
tem rota aberta
dist order to order é  1.453843384929755 hub em questão 10
dist order to hub é  2.4641918225711184 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 200
552
     order_id  order_latitude  order_longitude                ordered_at_brt  \
551       552      -23.747935       -46.576466 2024-04-01 18:50:58.569217568

     order_weight     sla_max_delivery_time_brt
551      3.379873 2024-04-01 19:50:58.569217568
2024-04-01 18:50:58.569217568
tem rota aberta
dist order to order é  7.173290845435849 hub em questão 6
dist order to hub é  2.495468115498917 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 6
passou aqui1
rota em aberto, route_id:  202
rota_escolhida: 202
orders no hub: 1
passou aqui3
passou aqui4
553
     order_id  order_latitude  order_longitude                ordered_at_brt  \
552       553      -23.640914       -46.563594 2024-04-01 18:53:47.295713664

     order_weight     sla_max_delivery_time_brt
552      4.653164 2024-04-01 20:53:47.295713664
2024-04-01 18:53:47.295713664
tem rota aberta
dist order to order é  8.621670384271733 hub em questão 10
dist order to hub é  3.0857804115525957 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 10
passou aqui1
passou aqui5
route_id 204
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

554
     order_id  order_latitude  order_longitude                ordered_at_brt  \
553       554      -23.650417       -46.636147 2024-04-01 18:55:02.098412611

     order_weight     sla_max_delivery_time_brt
553      6.752324 2024-04-01 19:55:02.098412611
2024-04-01 18:55:02.098412611
tem rota aberta
dist order to order é  1.1569293726047942 hub em questão 10
dist order to hub é  3.156028245846172 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 200
555
     order_id  order_latitude  order_longitude                ordered_at_brt  \
554       555      -23.652486       -46.772923 2024-04-01 18:55:18.097845248

     order_weight     sla_max_delivery_time_brt
554     12.188014 2024-04-01 20:55:18.097845248
2024-04-01 18:55:18.097845248
tem rota aberta
dist order to order é  7.399769209603093 hub em questão 9
dist order to hub é  7.110125990478593 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 203
556
     order_id  order_latitude  order_longitude                ordered_at_brt  \
555       556      -23.633083       -46.628795 2024-04-01 18:56:03.061299790

     order_weight     sla_max_delivery_time_brt
555      8.974828 2024-04-01 19:56:03.061299790
2024-04-01 18:56:03.061299790
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.0678026545019463 hub em questão 10
dist order to hub é  1.5054610992680584 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 200
557
     order_id  order_latitude  order_longitude                ordered_at_brt  \
556       557      -23.758472       -46.713546 2024-04-01 18:57:27.328493416

     order_weight     sla_max_delivery_time_brt
556       4.62069 2024-04-01 19:57:27.328493416
2024-04-01 18:57:27.328493416
tem rota aberta
dist order to order é  9.753107949084619 hub em questão 5
dist order to hub é  10.088618515370058 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 201
558
     order_id  order_latitude  order_longitude                ordered_at_brt  \
557       558      -23.554634       -46.673048 2024-04-01 18:59:41.775874126

     order_weight     sla_max_delivery_time_brt
557      6.947349 2024-04-01 21:59:41.775874126
2024-04-01 18:59:41.775874126
tem rota aberta
dist order to order é  8.559243267206043 hub em questão 9
dist order to hub é  3.324757311412958 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 9
passou aqui1
passou aqui5
route_id 205
caiu aqui tb
559
     order_id  order_latitude  order_longitude                ordered_at_brt  \
558       559      -23.665393       -46.705499 2024-04-01 19:02:38.215254125

     order_weight     sla_max_delivery_time_brt
558      4.598318 2024-04-01 21:02:38.215254125
2024-04-01 19:02:38.215254125
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.47449041315645 hub em questão 9
dist order to hub é  1.468426954138 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 9
passou aqui1
rota em aberto, route_id:  203
rota_escolhida: 203
orders no hub: 2
passou aqui3
passou aqui4
560
     order_id  order_latitude  order_longitude                ordered_at_brt  \
559       560      -23.721936       -46.626732 2024-04-01 19:02:54.973025759

     order_weight     sla_max_delivery_time_brt
559      7.483116 2024-04-01 21:02:54.973025759
2024-04-01 19:02:54.973025759
tem rota aberta
dist order to order é  5.876766596285259 hub em questão 6
dist order to hub é  1.0412452970996646 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 6
passou aqui1
passou aqui5
route_id 206
caiu aqui tb
561
     order_id  order_latitude  order_longitude                ordered_at_brt  \
560       561      -23.644649       -46.679343 2024-04-01 19:02:57.754837451

     order_weight     sla_max_delivery_time_brt
560      3.891912 2024-04-01 21:02:57.754837451
2024-04-01 19:02:57.754837451
tem rota aberta
dist order to order é  3.523860176622623 hub em questão 9
dist order to hub é  2.5691496736767 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 203
562
     order_id  order_latitude  order_longitude                ordered_at_brt  \
561       562      -23.713784       -46.609407 2024-04-01 19:04:25.601938039

     order_weight     sla_max_delivery_time_brt
561      5.978676 2024-04-01 21:04:25.601938039
2024-04-01 19:04:25.601938039
tem rota aberta
dist order to order é  1.9830443484028584 hub em questão 1
dist order to hub é  1.8976654957496102 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 206
563
     order_id  order_latitude  order_longitude                ordered_at_brt  \
562       563      -23.646906       -46.624148 2024-04-01 19:07:44.882552961

     order_weight     sla_max_delivery_time_brt
562     12.326698 2024-04-01 21:07:44.882552961
2024-04-01 19:07:44.882552961
tem rota aberta
dist order to order é  6.203967110141091 hub em questão 3
dist order to hub é  2.499076619020919 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 207
caiu aqui tb
564
     order_id  order_latitude  order_longitude                ordered_at_brt  \
563       564      -23.623195       -46.660016 2024-04-01 19:07:46.404617152

     order_weight     sla_max_delivery_time_brt
563       3.23639 2024-04-01 21:07:46.404617152
2024-04-01 19:07:46.404617152
tem rota aberta
dist order to order é  4.505743183819693 hub em questão 14
dist order to hub é  0.7962099689170569 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 14
passou aqui1
passou aqui5
route_id 208
caiu aqui tb
565
     order_id  order_latitude  order_longitude                ordered_at_brt  \
564       565       -23.71617       -46.643985 2024-04-01 19:10:00.345635242

     order_weight     sla_max_delivery_time_brt
564      9.358648 2024-04-01 22:10:00.345635242
2024-04-01 19:10:00.345635242
tem rota aberta
dist order to order é  1.8697635745879495 hub em questão 1
dist order to hub é  1.6733888514005646 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 206
566
     order_id  order_latitude  order_longitude                ordered_at_brt  \
565       566      -23.607954       -46.602142 2024-04-01 19:12:19.658385043

     order_weight     sla_max_delivery_time_brt
565       6.16336 2024-04-01 20:12:19.658385043
2024-04-01 19:12:19.658385043
tem rota aberta
dist order to order é  4.877023477245553 hub em questão 14
dist order to hub é  1.6569181354492473 hub em questão 13
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 13
hub_order 14
passou aqui1
passou aqui5
route_id 209
caiu aqui tb
567
     order_id  order_latitude  order_longitude                ordered_at_brt  \
566       567      -23.643671       -46.666619 2024-04-01 19:13:31.234592897

     order_weight     sla_max_delivery_time_brt
566      9.080368 2024-04-01 21:13:31.234592897
2024-04-01 19:13:31.234592897
tem rota aberta
dist order to order é  2.3740612713156235 hub em questão 10
dist order to hub é  3.097954264640276 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 208
568
     order_id  order_latitude  order_longitude                ordered_at_brt  \
567       568      -23.632771       -46.602232 2024-04-01 19:18:26.749121206

     order_weight     sla_max_delivery_time_brt
567       6.60413 2024-04-01 21:18:26.749121206
2024-04-01 19:18:26.749121206
tem rota aberta
dist order to order é  2.7301979985348424 hub em questão 14
dist order to hub é  1.6625343216858373 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 207
569
     order_id  order_latitude  order_longitude                ordered_at_brt  \
568       569      -23.630022       -46.648979 2024-04-01 19:20:30.809842712

     order_weight     sla_max_delivery_time_brt
568      6.879134 2024-04-01 21:20:30.809842712
2024-04-01 19:20:30.809842712
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.356697716474641 hub em questão 10
dist order to hub é  1.43892861502299 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 208
570
     order_id  order_latitude  order_longitude                ordered_at_brt  \
569       570      -23.624604       -46.634543 2024-04-01 19:20:31.440276361

     order_weight     sla_max_delivery_time_brt
569      7.101034 2024-04-01 21:20:31.440276361
2024-04-01 19:20:31.440276361
tem rota aberta
dist order to order é  1.5892470396400495 hub em questão 10
dist order to hub é  1.8391656656128208 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 208
571
     order_id  order_latitude  order_longitude                ordered_at_brt  \
570       571      -23.594207       -46.608051 2024-04-01 19:21:50.937777861

     order_weight     sla_max_delivery_time_brt
570     11.220604 2024-04-01 21:21:50.937777861
2024-04-01 19:21:50.937777861
tem rota aberta
dist order to order é  1.6428768697767826 hub em questão 13
dist order to hub é  2.802490366632831 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 209
572
     order_id  order_latitude  order_longitude                ordered_at_brt  \
571       572      -23.607203       -46.581436 2024-04-01 19:25:46.288003042

     order_weight     sla_max_delivery_time_brt
571     10.166008 2024-04-01 20:25:46.288003042
2024-04-01 19:25:46.288003042
tem rota aberta
dist order to order é  2.1113334534151127 hub em questão 13
dist order to hub é  1.0919599024740363 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 13 2
route_id 209
573
     order_id  order_latitude  order_longitude                ordered_at_brt  \
572       573       -23.62588       -46.621972 2024-04-01 19:29:19.205205498

     order_weight     sla_max_delivery_time_brt
572      7.633287 2024-04-01 21:29:19.205205498
2024-04-01 19:29:19.205205498
tem rota aberta
dist order to order é  2.152040177730434 hub em questão 14
dist order to hub é  0.5567748785989748 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 207
574
     order_id  order_latitude  order_longitude                ordered_at_brt  \
573       574      -23.688442       -46.645094 2024-04-01 19:31:24.894220704

     order_weight     sla_max_delivery_time_brt
573     11.339181 2024-04-01 21:31:24.894220704
2024-04-01 19:31:24.894220704
tem rota aberta
dist order to order é  3.08527007148601 hub em questão 1
dist order to hub é  2.107315011719945 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 206
575
     order_id  order_latitude  order_longitude                ordered_at_brt  \
574       575      -23.635909       -46.611978 2024-04-01 19:33:39.286210124

     order_weight     sla_max_delivery_time_brt
574     10.576882 2024-04-01 20:33:39.286210124
2024-04-01 19:33:39.286210124
tem rota aberta
dist order to order é  1.0523894821482782 hub em questão 14
dist order to hub é  1.2417510656707353 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 207
576
     order_id  order_latitude  order_longitude                ordered_at_brt  \
575       576      -23.678117       -46.725285 2024-04-01 19:35:22.958350675

     order_weight     sla_max_delivery_time_brt
575     10.358655 2024-04-01 21:35:22.958350675
2024-04-01 19:35:22.958350675
tem rota aberta
dist order to order é  14.771901302424304 hub em questão 13
dist order to hub é  3.6461945269051372 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 13
passou aqui1
passou aqui5
route_id 210
caiu aqui tb
577
     order_id  order_latitude  order_longitude                ordered_at_brt  \
576       577      -23.722663       -46.566065 2024-04-01 19:36:01.402781555

     order_weight     sla_max_delivery_time_brt
576     10.693369 2024-04-01 20:36:01.402781555
2024-04-01 19:36:01.402781555
tem rota aberta
dist order to order é  12.933714899563979 hub em questão 13
dist order to hub é  1.0688933355210923 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 13
passou aqui1
passou aqui5
route_id 211
caiu aqui tb
578
     order_id  order_latitude  order_longitude                ordered_at_brt  \
577       578      -23.652294       -46.714287 2024-04-01 19:37:40.065077799

     order_weight     sla_max_delivery_time_brt
577      3.030485 2024-04-01 22:37:40.065077799
2024-04-01 19:37:40.065077799
tem rota aberta
dist order to order é  3.0820993359117552 hub em questão 9
dist order to hub é  1.1378118060992797 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 210
579
     order_id  order_latitude  order_longitude                ordered_at_brt  \
578       579      -23.695866       -46.602827 2024-04-01 19:39:53.735259756

     order_weight     sla_max_delivery_time_brt
578     12.145562 2024-04-01 21:39:53.735259756
2024-04-01 19:39:53.735259756
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.784056590601503 hub em questão 6
dist order to hub é  3.1705239814042403 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 211
580
     order_id  order_latitude  order_longitude                ordered_at_brt  \
579       580      -23.593468       -46.676221 2024-04-01 19:40:45.878597209

     order_weight     sla_max_delivery_time_brt
579      3.479281 2024-04-01 21:40:45.878597209
2024-04-01 19:40:45.878597209
tem rota aberta
dist order to order é  6.947020737358643 hub em questão 13
dist order to hub é  2.9767420048826074 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 13
passou aqui1
passou aqui5
route_id 212
caiu aqui tb
581
     order_id  order_latitude  order_longitude                ordered_at_brt  \
580       581      -23.652111        -46.62265 2024-04-01 19:44:38.288692618

     order_weight     sla_max_delivery_time_brt
580      6.659432 2024-04-01 21:44:38.288692618
2024-04-01 19:44:38.288692618
tem rota aberta
dist order to order é  5.267522272853713 hub em questão 6
dist order to hub é  3.0192664834229292 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 6
passou aqui1
passou aqui5
route_id 213
caiu aqui tb
582
     order_id  order_latitude  order_longitude                ordered_at_brt  \
581       582      -23.647962       -46.653841 2024-04-01 19:45:04.323840912

     order_weight     sla_max_delivery_time_brt
581      9.113655 2024-04-01 22:45:04.323840912
2024-04-01 19:45:04.323840912
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.2103050807808016 hub em questão 14
dist order to hub é  2.712406062458786 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 213
583
     order_id  order_latitude  order_longitude                ordered_at_brt  \
582       583      -23.611465       -46.632833 2024-04-01 19:47:49.399995300

     order_weight     sla_max_delivery_time_brt
582      0.739014 2024-04-01 21:47:49.399995300
2024-04-01 19:47:49.399995300
tem rota aberta
dist order to order é  4.58802000280131 hub em questão 14
dist order to hub é  1.2767658762438978 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 14
passou aqui1
passou aqui5
route_id 214
caiu aqui tb
584
     order_id  order_latitude  order_longitude                ordered_at_brt  \
583       584      -23.671132       -46.688052 2024-04-01 19:48:30.431709660

     order_weight     sla_max_delivery_time_brt
583      7.229939 2024-04-01 21:48:30.431709660
2024-04-01 19:48:30.431709660
tem rota aberta
dist order to order é  3.395129370309229 hub em questão 9
dist order to hub é  2.5897626778103073 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 210
585
     order_id  order_latitude  order_longitude                ordered_at_brt  \
584       585      -23.663055       -46.756044 2024-04-01 19:51:28.791617376

     order_weight     sla_max_delivery_time_brt
584     10.191021 2024-04-01 20:51:28.791617376
2024-04-01 19:51:28.791617376
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.552122336099399 hub em questão 9
dist order to hub é  5.520090878988383 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 210
586
     order_id  order_latitude  order_longitude                ordered_at_brt  \
585       586      -23.591992        -46.62768 2024-04-01 19:52:35.770478803

     order_weight     sla_max_delivery_time_brt
585      7.691208 2024-04-01 21:52:35.770478803
2024-04-01 19:52:35.770478803
tem rota aberta
dist order to order é  2.2280868224326658 hub em questão 8
dist order to hub é  1.3236727131047716 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 214
587
     order_id  order_latitude  order_longitude                ordered_at_brt  \
586       587      -23.719409       -46.678038 2024-04-01 19:55:53.613321219

     order_weight     sla_max_delivery_time_brt
586      9.402553 2024-04-01 21:55:53.613321219
2024-04-01 19:55:53.613321219
tem rota aberta
dist order to order é  8.0924398453153 hub em questão 6
dist order to hub é  5.1488213976458335 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 6
passou aqui1
passou aqui5
route_id 215
caiu aqui tb
588
     order_id  order_latitude  order_longitude                ordered_at_brt  \
587       588      -23.693573       -46.680445 2024-04-01 19:56:45.961642114

     order_weight     sla_max_delivery_time_brt
587      5.445548 2024-04-01 21:56:45.961642114
2024-04-01 19:56:45.961642114
tem rota aberta
dist order to order é  2.883284440945638 hub em questão 1
dist order to hub é  3.442320958267968 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 215
589
     order_id  order_latitude  order_longitude                ordered_at_brt  \
588       589       -23.65691       -46.684279 2024-04-01 19:57:14.810635687

     order_weight     sla_max_delivery_time_brt
588      2.367074 2024-04-01 22:57:14.810635687
2024-04-01 19:57:14.810635687
tem rota aberta
dist order to order é  3.2559610459949937 hub em questão 14
dist order to hub é  1.984013982874793 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 213
590
     order_id  order_latitude  order_longitude                ordered_at_brt  \
589       590      -23.610986       -46.548792 2024-04-01 20:00:09.763272212

     order_weight     sla_max_delivery_time_brt
589      7.329422 2024-04-01 21:00:09.763272212
2024-04-01 20:00:09.763272212
tem rota aberta
dist order to order é  8.311023491351513 hub em questão 8
dist order to hub é  2.7742160354125818 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 8
passou aqui1
passou aqui5
route_id 216
caiu aqui tb
591
     order_id  order_latitude  order_longitude                ordered_at_brt  \
590       591      -23.637736       -46.677122 2024-04-01 20:00:54.054963080

     order_weight     sla_max_delivery_time_brt
590      3.414428 2024-04-01 22:00:54.054963080
2024-04-01 20:00:54.054963080
tem rota aberta
dist order to order é  2.2532593352710353 hub em questão 14
dist order to hub é  3.0257123480999075 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 213

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

592
     order_id  order_latitude  order_longitude                ordered_at_brt  \
591       592      -23.708101       -46.631672 2024-04-01 20:03:32.625950926

     order_weight     sla_max_delivery_time_brt
591      6.132663 2024-04-01 22:03:32.625950926
2024-04-01 20:03:32.625950926
tem rota aberta
dist order to order é  3.2366796792800723 hub em questão 6
dist order to hub é  0.628197030944302 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 6
passou aqui1
rota em aberto, route_id:  215
rota_escolhida: 215
orders no hub: 2
passou aqui3
passou aqui4
593
     order_id  order_latitude  order_longitude                ordered_at_brt  \
592       593      -23.696214       -46.706035 2024-04-01 20:06:16.357286787

     order_weight     sla_max_delivery_time_brt
592      4.406474 2024-04-01 22:06:16.357286787
2024-04-01 20:06:16.357286787
tem rota aberta
dist order to order é  2.62213693150187 hub em questão 1
dist order to hub é  4.884451991290167 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 215
594
     order_id  order_latitude  order_longitude                ordered_at_brt  \
593       594      -23.565502       -46.571858 2024-04-01 20:06:46.387719579

     order_weight     sla_max_delivery_time_brt
593      7.681067 2024-04-01 23:06:46.387719579
2024-04-01 20:06:46.387719579
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  5.577059359685811 hub em questão 3
dist order to hub é  5.564751684642279 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 216
595
     order_id  order_latitude  order_longitude                ordered_at_brt  \
594       595      -23.634412       -46.675826 2024-04-01 20:07:15.300659312

     order_weight     sla_max_delivery_time_brt
594      4.527996 2024-04-01 22:07:15.300659312
2024-04-01 20:07:15.300659312
tem rota aberta
dist order to order é  4.552905153613018 hub em questão 15
dist order to hub é  2.650607895585498 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 212
596
     order_id  order_latitude  order_longitude                ordered_at_brt  \
595       596      -23.681147       -46.778045 2024-04-01 20:07:41.920177661

     order_weight     sla_max_delivery_time_brt
595      5.708662 2024-04-01 22:07:41.920177661
2024-04-01 20:07:41.920177661
tem rota aberta
dist order to order é  11.635929543110821 hub em questão 15
dist order to hub é  8.274742280048999 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 217
caiu aqui tb
597
     order_id  order_latitude  order_longitude                ordered_at_brt  \
596       597      -23.674439       -46.512415 2024-04-01 20:08:00.370835899

     order_weight     sla_max_delivery_time_brt
596     13.844239 2024-04-01 22:08:00.370835899
2024-04-01 20:08:00.370835899
tem rota aberta
dist order to order é  7.969505693538516 hub em questão 3
dist order to hub é  2.11122748903473 hub em questão 2
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 2
hub_order 3
passou aqui1
passou aqui5
route_id 218
caiu aqui tb
598
     order_id  order_latitude  order_longitude                ordered_at_brt  \
597       598      -23.463213        -46.70292 2024-04-01 20:08:57.171798136

     order_weight     sla_max_delivery_time_brt
597      6.975383 2024-04-01 21:08:57.171798136
2024-04-01 20:08:57.171798136
tem rota aberta
dist order to order é  14.73731709409209 hub em questão 15
dist order to hub é  12.036056473476433 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 15
passou aqui1
passou aqui5
route_id 219
caiu aqui tb
599
     order_id  order_latitude  order_longitude                ordered_at_brt  \
598       599      -23.583212       -46.582566 2024-04-01 20:09:00.410457578

     order_weight     sla_max_delivery_time_brt
598      6.425891 2024-04-01 22:09:00.410457578
2024-04-01 20:09:00.410457578
tem rota aberta
dist order to order é  2.2513861217701576 hub em questão 3
dist order to hub é  3.6525004215818875 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 216
600
     order_id  order_latitude  order_longitude                ordered_at_brt  \
599       600      -23.732049       -46.611359 2024-04-01 20:09:14.518674438

     order_weight     sla_max_delivery_time_brt
599     10.781547 2024-04-01 22:09:14.518674438
2024-04-01 20:09:14.518674438
tem rota aberta
dist order to order é  11.93817684926712 hub em questão 2
dist order to hub é  2.7435394199197254 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 2
passou aqui1
passou aqui5
route_id 220
caiu aqui tb
601
     order_id  order_latitude  order_longitude                ordered_at_brt  \
600       601      -23.673164       -46.615404 2024-04-01 20:11:29.229418070

     order_weight     sla_max_delivery_time_brt
600      8.496684 2024-04-01 22:11:29.229418070
2024-04-01 20:11:29.229418070
tem rota aberta
dist order to order é  6.560654039873712 hub em questão 1
dist order to hub é  3.9011503592792343 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 1
passou aqui1
passou aqui5
route_id 221
caiu aqui tb
602
     order_id  order_latitude  order_longitude                ordered_at_brt  \
601       602      -23.614084       -46.659587 2024-04-01 20:14:42.227964548

     order_weight     sla_max_delivery_time_brt
601     11.230012 2024-04-01 23:14:42.227964548
2024-04-01 20:14:42.227964548
tem rota aberta
dist order to order é  2.741320954787563 hub em questão 8
dist order to hub é  0.17245749019465298 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 8
passou aqui1
passou aqui5
route_id 222
caiu aqui tb
603
     order_id  order_latitude  order_longitude                ordered_at_brt  \
602       603      -23.663999       -46.638553 2024-04-01 20:14:52.302846261

     order_weight     sla_max_delivery_time_brt
602      8.245903 2024-04-01 22:14:52.302846261
2024-04-01 20:14:52.302846261
tem rota aberta
dist order to order é  2.5683620398193825 hub em questão 12
dist order to hub é  1.9927123360285857 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 221
604
     order_id  order_latitude  order_longitude                ordered_at_brt  \
603       604      -23.593273       -46.586816 2024-04-01 20:15:23.932206787

     order_weight     sla_max_delivery_time_brt
603      8.175873 2024-04-01 22:15:23.932206787

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 20:15:23.932206787
tem rota aberta
dist order to order é  1.1996253242530759 hub em questão 3
dist order to hub é  2.7166010774519114 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 216
605
     order_id  order_latitude  order_longitude                ordered_at_brt  \
604       605      -23.562013       -46.663059 2024-04-01 20:15:51.858768738

     order_weight     sla_max_delivery_time_brt
604       6.33281 2024-04-01 22:15:51.858768738
2024-04-01 20:15:51.858768738
tem rota aberta
dist order to order é  4.910467488702537 hub em questão 8
dist order to hub é  3.911641870554203 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 214
606
     order_id  order_latitude  order_longitude                ordered_at_brt  \
605       606      -23.649847       -46.635447 2024-04-01 20:20:51.011760822

     order_weight     sla_max_delivery_time_brt
605     11.306211 2024-04-01 21:20:51.011760822
2024-04-01 20:20:51.011760822
tem rota aberta
dist order to order é  1.6051146125025009 hub em questão 12
dist order to hub é  3.250257455776296 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 221
607
     order_id  order_latitude  order_longitude                ordered_at_brt  \
606       607      -23.635488       -46.601598 2024-04-01 20:23:20.101858607

     order_weight     sla_max_delivery_time_brt
606      8.004166 2024-04-01 23:23:20.101858607
2024-04-01 20:23:20.101858607
tem rota aberta
dist order to order é  3.7996658154005822 hub em questão 12
dist order to hub é  1.8795860746305448 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 221
608
     order_id  order_latitude  order_longitude                ordered_at_brt  \
607       608      -23.658658       -46.643843 2024-04-01 20:24:56.963175504

     order_weight     sla_max_delivery_time_brt
607      7.056291 2024-04-01 21:24:56.963175504
2024-04-01 20:24:56.963175504
tem rota aberta
dist order to order é  5.209444120836555 hub em questão 15
dist order to hub é  1.9503043470548729 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 15
passou aqui1
passou aqui5
route_id 223
caiu aqui tb
609
     order_id  order_latitude  order_longitude                ordered_at_brt  \
608       609      -23.606085       -46.669262 2024-04-01 20:25:40.541191253

     order_weight     sla_max_delivery_time_brt
608     13.302199 2024-04-01 22:25:40.541191253
2024-04-01 20:25:40.541191253
tem rota aberta
dist order to order é  1.3277002912497295 hub em questão 15
dist order to hub é  1.4318202045176753 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 222
610
     order_id  order_latitude  order_longitude                ordered_at_brt  \
609       610      -23.575229       -46.575429 2024-04-01 20:29:16.652267605

     order_weight     sla_max_delivery_time_brt
609      0.775631 2024-04-01 22:29:16.652267605
2024-04-01 20:29:16.652267605
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  9.602524489955748 hub em questão 15
dist order to hub é  4.470234329079539 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 15
passou aqui1
passou aqui5
route_id 224
caiu aqui tb
611
     order_id  order_latitude  order_longitude                ordered_at_brt  \
610       611      -23.603506       -46.630928 2024-04-01 20:30:25.228813097

     order_weight     sla_max_delivery_time_brt
610       5.12062 2024-04-01 22:30:25.228813097
2024-04-01 20:30:25.228813097
tem rota aberta
dist order to order é  3.1480069378124953 hub em questão 15
dist order to hub é  0.6749859661457214 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 15
passou aqui1
passou aqui5
route_id 225
caiu aqui tb
612
     order_id  order_latitude  order_longitude                ordered_at_brt  \
611       612      -23.704374       -46.654271 2024-04-01 20:35:33.615895156

     order_weight     sla_max_delivery_time_brt
611      9.565247 2024-04-01 22:35:33.615895156
2024-04-01 20:35:33.615895156
tem rota aberta
dist order to order é  5.193099290333679 hub em questão 5
dist order to hub é  2.827900984870373 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
rota em aberto, route_id:  220
rota_escolhida: 220
orders no hub: 1
passou aqui3
passou aqui4
613
     order_id  order_latitude  order_longitude                ordered_at_brt  \
612       613      -23.612507       -46.686808 2024-04-01 20:38:00.538103043

     order_weight     sla_max_delivery_time_brt
612      4.556982 2024-04-01 22:38:00.538103043
2024-04-01 20:38:00.538103043
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.925020010188689 hub em questão 15
dist order to hub é  2.771546759265407 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 222
614
     order_id  order_latitude  order_longitude                ordered_at_brt  \
613       614      -23.679163       -46.698293 2024-04-01 20:39:18.555823424

     order_weight     sla_max_delivery_time_brt
613      4.921309 2024-04-01 23:39:18.555823424
2024-04-01 20:39:18.555823424
tem rota aberta
dist order to order é  5.995632926654191 hub em questão 5
dist order to hub é  3.019650151218049 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 226
caiu aqui tb
615
     order_id  order_latitude  order_longitude                ordered_at_brt  \
614       615      -23.562807       -46.603324 2024-04-01 20:39:34.745662487

     order_weight     sla_max_delivery_time_brt
614      8.845941 2024-04-01 23:39:34.745662487
2024-04-01 20:39:34.745662487
tem rota aberta
dist order to order é  3.160779938734783 hub em questão 3
dist order to hub é  5.4026311030880905 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 224
616
     order_id  order_latitude  order_longitude                ordered_at_brt  \
615       616      -23.626411       -46.600549 2024-04-01 20:47:02.527786468

     order_weight     sla_max_delivery_time_brt
615      7.209403 2024-04-01 23:47:02.527786468
2024-04-01 20:47:02.527786468
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.008350218675018 hub em questão 8
dist order to hub é  1.3016739792935528 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 8
passou aqui1
passou aqui5
route_id 227
caiu aqui tb
617
     order_id  order_latitude  order_longitude                ordered_at_brt  \
616       617      -23.597319       -46.756548 2024-04-01 20:47:23.426431041

     order_weight     sla_max_delivery_time_brt
616      9.142586 2024-04-01 22:47:23.426431041
2024-04-01 20:47:23.426431041
tem rota aberta
dist order to order é  10.864493342623117 hub em questão 9
dist order to hub é  4.425115533441723 hub em questão 11
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 11
hub_order 9
passou aqui1
passou aqui5
route_id 228
caiu aqui tb
618
     order_id  order_latitude  order_longitude                ordered_at_brt  \
617       618      -23.651278       -46.678787 2024-04-01 20:47:50.594612147

     order_weight     sla_max_delivery_time_brt
617       5.13686 2024-04-01 22:47:50.594612147
2024-04-01 20:47:50.594612147
tem rota aberta
dist order to order é  3.6525110128664044 hub em questão 5
dist order to hub é  2.4810180731425415 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 223
619
     order_id  order_latitude  order_longitude                ordered_at_brt  \
618       619      -23.651842       -46.599768 2024-04-01 20:48:58.297931145

     order_weight     sla_max_delivery_time_brt
618      7.019892 2024-04-01 22:48:58.297931145
2024-04-01 20:48:58.297931145
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.82893057641556 hub em questão 7
dist order to hub é  2.9557127256868885 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 227
620
     order_id  order_latitude  order_longitude                ordered_at_brt  \
619       620      -23.628686       -46.526797 2024-04-01 20:50:00.440343631

     order_weight     sla_max_delivery_time_brt
619      5.498208 2024-04-01 22:50:00.440343631
2024-04-01 20:50:00.440343631
tem rota aberta
dist order to order é  7.517633571981501 hub em questão 7
dist order to hub é  3.329757853674218 hub em questão 2
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 2
hub_order 7
passou aqui1
passou aqui5
route_id 229
caiu aqui tb
621
     order_id  order_latitude  order_longitude                ordered_at_brt  \
620       621      -23.651765       -46.540495 2024-04-01 20:50:19.484874827

     order_weight     sla_max_delivery_time_brt
620      4.021668 2024-04-01 22:50:19.484874827
2024-04-01 20:50:19.484874827
tem rota aberta
dist order to order é  2.9210547048144027 hub em questão 2
dist order to hub é  2.9166919154471422 hub em questão 2
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 2 2
route_id 229
622
     order_id  order_latitude  order_longitude                ordered_at_brt  \
621       622       -23.57128       -46.600919 2024-04-01 20:52:56.302551864

     order_weight     sla_max_delivery_time_brt
621      4.039538 2024-04-01 21:52:56.302551864
2024-04-01 20:52:56.302551864
tem rota aberta
dist order to order é  0.9734327282087235 hub em questão 3
dist order to hub é  4.888305488057895 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 224
623

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
622       623      -23.707335       -46.579346 2024-04-01 20:53:21.403303474

     order_weight     sla_max_delivery_time_brt
622      9.277193 2024-04-01 21:53:21.403303474
2024-04-01 20:53:21.403303474
tem rota aberta
dist order to order é  6.511569210021375 hub em questão 7
dist order to hub é  2.0461921368411624 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 7
passou aqui1
passou aqui5
route_id 230
caiu aqui tb
624
     order_id  order_latitude  order_longitude                ordered_at_brt  \
623       624      -23.615955       -46.674384 2024-04-01 20:55:25.307078329

     order_weight     sla_max_delivery_time_brt
623      0.062194 2024-04-01 22:55:25.307078329
2024-04-01 20:55:25.307078329
tem rota aberta
dist order to order é  4.638908826980465 hub em questão 8
dist order to hub é  1.4844989262897088 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 8
passou aqui1
passou aqui5
route_id 231
caiu aqui tb
625
     order_id  order_latitude  order_longitude                ordered_at_brt  \
624       625      -23.679558       -46.609286 2024-04-01 20:58:13.747264563

     order_weight     sla_max_delivery_time_brt
624      6.030479 2024-04-01 21:58:13.747264563
2024-04-01 20:58:13.747264563
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.2307342028017336 hub em questão 7
dist order to hub é  3.461681273666154 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 227
626
     order_id  order_latitude  order_longitude                ordered_at_brt  \
625       626      -23.607173       -46.709871 2024-04-01 20:58:42.145245616

     order_weight     sla_max_delivery_time_brt
625      3.778265 2024-04-01 22:58:42.145245616
2024-04-01 20:58:42.145245616
tem rota aberta
dist order to order é  3.7451894348604 hub em questão 15
dist order to hub é  4.0994843995272445 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 231
627
     order_id  order_latitude  order_longitude                ordered_at_brt  \
626       627      -23.740081       -46.676107 2024-04-01 21:00:32.386749888

     order_weight     sla_max_delivery_time_brt
626      7.929599 2024-04-02 00:00:32.386749888
2024-04-01 21:00:32.386749888
tem rota aberta
dist order to order é  7.140465781827508 hub em questão 9
dist order to hub é  5.769204101854362 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 226
628
     order_id  order_latitude  order_longitude                ordered_at_brt  \
627       628      -23.585919       -46.631964 2024-04-01 21:03:18.228792644

     order_weight     sla_max_delivery_time_brt
627      6.068696 2024-04-02 00:03:18.228792644
2024-04-01 21:03:18.228792644
tem rota aberta
dist order to order é  5.462288991756758 hub em questão 15
dist order to hub é  1.6969961331634142 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 15
passou aqui1
passou aqui5
route_id 232
caiu aqui tb
629
     order_id  order_latitude  order_longitude                ordered_at_brt  \
628       629      -23.665694       -46.539616 2024-04-01 21:05:20.234643371

     order_weight     sla_max_delivery_time_brt
628      8.907649 2024-04-01 22:05:20.234643371
2024-04-01 21:05:20.234643371
tem rota aberta
dist order to order é  1.551352876909773 hub em questão 2
dist order to hub é  3.020807027021916 hub em questão 2
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 2 2
route_id 229
630
     order_id  order_latitude  order_longitude                ordered_at_brt  \
629       630      -23.711909       -46.610615 2024-04-01 21:07:09.330801988

     order_weight     sla_max_delivery_time_brt
629      8.282169 2024-04-01 23:07:09.330801988
2024-04-01 21:07:09.330801988
tem rota aberta
dist order to order é  3.22380155489972 hub em questão 6
dist order to hub é  1.7723725143525608 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 230
631
     order_id  order_latitude  order_longitude                ordered_at_brt  \
630       631      -23.614391       -46.634321 2024-04-01 21:07:51.359818395

     order_weight     sla_max_delivery_time_brt
630      1.561238 2024-04-01 22:07:51.359818395
2024-04-01 21:07:51.359818395
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.1750549568972937 hub em questão 8
dist order to hub é  1.558567652250064 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 232
632
     order_id  order_latitude  order_longitude                ordered_at_brt  \
631       632      -23.659814       -46.656517 2024-04-01 21:10:29.195936548

     order_weight     sla_max_delivery_time_brt
631      8.561162 2024-04-01 22:10:29.195936548
2024-04-01 21:10:29.195936548
tem rota aberta
dist order to order é  5.205512846538919 hub em questão 15
dist order to hub é  1.387777301724792 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 15
passou aqui1
passou aqui5
route_id 233
caiu aqui tb
633
     order_id  order_latitude  order_longitude                ordered_at_brt  \
632       633      -23.636368       -46.714135 2024-04-01 21:16:17.921441862

     order_weight     sla_max_delivery_time_brt
632      5.825662 2024-04-01 23:16:17.921441862
2024-04-01 21:16:17.921441862
tem rota aberta
dist order to order é  3.275316191426474 hub em questão 15
dist order to hub é  2.103556103417382 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 231
634
     order_id  order_latitude  order_longitude                ordered_at_brt  \
633       634       -23.58883        -46.61787 2024-04-01 21:17:24.444887381

     order_weight     sla_max_delivery_time_brt
633      7.037067 2024-04-01 23:17:24.444887381
2024-04-01 21:17:24.444887381
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.472326324973502 hub em questão 8
dist order to hub é  2.3203944455855594 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 232
635
     order_id  order_latitude  order_longitude                ordered_at_brt  \
634       635      -23.704785       -46.665467 2024-04-01 21:20:27.336237742

     order_weight     sla_max_delivery_time_brt
634      6.141017 2024-04-01 23:20:27.336237742
2024-04-01 21:20:27.336237742
tem rota aberta
dist order to order é  5.082903795482616 hub em questão 5
dist order to hub é  3.7430328769487233 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 233
636
     order_id  order_latitude  order_longitude                ordered_at_brt  \
635       636      -23.687044       -46.636061 2024-04-01 21:20:34.269661392

     order_weight     sla_max_delivery_time_brt
635      8.468002 2024-04-01 22:20:34.269661392
2024-04-01 21:20:34.269661392
tem rota aberta
dist order to order é  3.585640917379382 hub em questão 5
dist order to hub é  2.603429887252342 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 233
637
     order_id  order_latitude  order_longitude                ordered_at_brt  \
636       637      -23.646205       -46.692479 2024-04-01 21:24:10.684529837

     order_weight     sla_max_delivery_time_brt
636     13.826973 2024-04-02 00:24:10.684529837
2024-04-01 21:24:10.684529837
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.462186506115402 hub em questão 15
dist order to hub é  1.2820508665438954 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 231
638
     order_id  order_latitude  order_longitude                ordered_at_brt  \
637       638       -23.62185        -46.64195 2024-04-01 21:24:36.304853249

     order_weight     sla_max_delivery_time_brt
637      6.668374 2024-04-01 23:24:36.304853249
2024-04-01 21:24:36.304853249
tem rota aberta
dist order to order é  1.136601849717293 hub em questão 8
dist order to hub é  1.3452222815586163 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 232
639
     order_id  order_latitude  order_longitude                ordered_at_brt  \
638       639      -23.685406       -46.724864 2024-04-01 21:25:36.627286965

     order_weight     sla_max_delivery_time_brt
638     13.764331 2024-04-02 00:25:36.627286965
2024-04-01 21:25:36.627286965
tem rota aberta
dist order to order é  6.420249727671963 hub em questão 5
dist order to hub é  4.289612114677463 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 234
caiu aqui tb
640
     order_id  order_latitude  order_longitude                ordered_at_brt  \
639       640      -23.689883       -46.622817 2024-04-01 21:26:19.442174629

     order_weight     sla_max_delivery_time_brt
639      5.164107 2024-04-01 22:26:19.442174629
2024-04-01 21:26:19.442174629
tem rota aberta
dist order to order é  1.3849346776576525 hub em questão 5
dist order to hub é  2.585563643212158 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 233

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

641
     order_id  order_latitude  order_longitude                ordered_at_brt  \
640       641      -23.611659       -46.582026 2024-04-01 21:26:29.461487220

     order_weight     sla_max_delivery_time_brt
640      6.007026 2024-04-01 22:26:29.461487220
2024-04-01 21:26:29.461487220
tem rota aberta
dist order to order é  16.70093151928382 hub em questão 9
dist order to hub é  0.7788130309113768 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 9
passou aqui1
passou aqui5
route_id 235
caiu aqui tb
642
     order_id  order_latitude  order_longitude                ordered_at_brt  \
641       642      -23.601043       -46.602315 2024-04-01 21:31:11.461695025

     order_weight     sla_max_delivery_time_brt
641     10.725891 2024-04-01 23:31:11.461695025
2024-04-01 21:31:11.461695025
tem rota aberta
dist order to order é  2.380472187669421 hub em questão 3
dist order to hub é  2.2764646610790664 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 235
643
     order_id  order_latitude  order_longitude                ordered_at_brt  \
642       643      -23.580362       -46.542322 2024-04-01 21:32:06.935320923

     order_weight     sla_max_delivery_time_brt
642       7.48633 2024-04-01 23:32:06.935320923
2024-04-01 21:32:06.935320923
tem rota aberta
dist order to order é  5.336643191941277 hub em questão 3
dist order to hub é  5.166686544963126 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 235
644
     order_id  order_latitude  order_longitude                ordered_at_brt  \
643       644      -23.664982       -46.631785 2024-04-01 21:33:37.716232685

     order_weight     sla_max_delivery_time_brt
643      9.131699 2024-04-01 22:33:37.716232685

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 21:33:37.716232685
tem rota aberta
dist order to order é  7.717502809401146 hub em questão 3
dist order to hub é  2.586984700618665 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 3
passou aqui1
passou aqui5
route_id 236
caiu aqui tb
645
     order_id  order_latitude  order_longitude                ordered_at_brt  \
644       645      -23.779337       -46.622745 2024-04-01 21:34:59.490041956

     order_weight     sla_max_delivery_time_brt
644      8.101013 2024-04-01 22:34:59.490041956
2024-04-01 21:34:59.490041956
tem rota aberta
dist order to order é  12.748971868562219 hub em questão 5
dist order to hub é  7.435161305021086 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 237
caiu aqui tb
646
     order_id  order_latitude  order_longitude                ordered_at_brt  \
645       646      -23.624056        -46.62227 2024-04-01 21:35:16.499949430

     order_weight     sla_max_delivery_time_brt
645      12.00019 2024-04-01 22:35:16.499949430
2024-04-01 21:35:16.499949430
tem rota aberta
dist order to order é  3.268194096527484 hub em questão 3
dist order to hub é  0.608786713402496 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 238
caiu aqui tb
647
     order_id  order_latitude  order_longitude                ordered_at_brt  \
646       647      -23.612229       -46.691999 2024-04-01 21:35:44.249210697

     order_weight     sla_max_delivery_time_brt
646      2.910205 2024-04-01 22:35:44.249210697

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 21:35:44.249210697
tem rota aberta
dist order to order é  7.224830992287069 hub em questão 14
dist order to hub é  3.300420843753875 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 14
passou aqui1
passou aqui5
route_id 239
caiu aqui tb
648
     order_id  order_latitude  order_longitude                ordered_at_brt  \
647       648      -23.723566       -46.540351 2024-04-01 21:35:53.758918737

     order_weight     sla_max_delivery_time_brt
647      4.053602 2024-04-01 22:35:53.758918737
2024-04-01 21:35:53.758918737
tem rota aberta
dist order to order é  10.429695839351208 hub em questão 1
dist order to hub é  3.6453491978537658 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 1
passou aqui1
passou aqui5
route_id 240
caiu aqui tb
649
     order_id  order_latitude  order_longitude                ordered_at_brt  \
648       649      -23.645706       -46.598584 2024-04-01 21:37:18.853010180

     order_weight     sla_max_delivery_time_brt
648      8.225859 2024-04-01 23:37:18.853010180
2024-04-01 21:37:18.853010180
tem rota aberta
dist order to order é  3.408425183288615 hub em questão 14
dist order to hub é  2.8920137705198345 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 238
650
     order_id  order_latitude  order_longitude                ordered_at_brt  \
649       650       -23.63646       -46.660154 2024-04-01 21:37:55.237163444

     order_weight     sla_max_delivery_time_brt
649     15.331159 2024-04-01 23:37:55.237163444
2024-04-01 21:37:55.237163444
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.098419042910455 hub em questão 14
dist order to hub é  2.1194193672642747 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 238
651
     order_id  order_latitude  order_longitude                ordered_at_brt  \
650       651      -23.633208       -46.693154 2024-04-01 21:38:48.241928333

     order_weight     sla_max_delivery_time_brt
650      5.156297 2024-04-02 00:38:48.241928333
2024-04-01 21:38:48.241928333
tem rota aberta
dist order to order é  2.335712015293828 hub em questão 15
dist order to hub é  2.3599253675437337 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 239
652
     order_id  order_latitude  order_longitude                ordered_at_brt  \
651       652       -23.67346       -46.618937 2024-04-01 21:39:01.965414837

     order_weight     sla_max_delivery_time_brt
651      8.662151 2024-04-01 22:39:01.965414837
2024-04-01 21:39:01.965414837
tem rota aberta
dist order to order é  1.6126672750169342 hub em questão 5
dist order to hub é  3.766932288795437 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 236
653
     order_id  order_latitude  order_longitude                ordered_at_brt  \
652       653      -23.646054       -46.605135 2024-04-01 21:42:07.852287439

     order_weight     sla_max_delivery_time_brt
652     12.607065 2024-04-02 00:42:07.852287439
2024-04-01 21:42:07.852287439
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  0.6684510182665949 hub em questão 14
dist order to hub é  2.55835142425867 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 238
654
     order_id  order_latitude  order_longitude                ordered_at_brt  \
653       654      -23.620206       -46.641119 2024-04-01 21:42:21.376626223

     order_weight     sla_max_delivery_time_brt
653      9.970792 2024-04-01 23:42:21.376626223
2024-04-01 21:42:21.376626223
tem rota aberta
dist order to order é  4.491165294162541 hub em questão 3
dist order to hub é  1.3839012088375333 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 3
passou aqui1
passou aqui5
route_id 241
caiu aqui tb
655
     order_id  order_latitude  order_longitude                ordered_at_brt  \
654       655      -23.739034       -46.638709 2024-04-01 21:50:51.150183228

     order_weight     sla_max_delivery_time_brt
654     13.904683 2024-04-02 00:50:51.150183228
2024-04-01 21:50:51.150183228
tem rota aberta
dist order to order é  4.766924864142422 hub em questão 1
dist order to hub é  3.130133477771649 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 237
656
     order_id  order_latitude  order_longitude                ordered_at_brt  \
655       656      -23.604671       -46.657419 2024-04-01 21:51:14.549573993

     order_weight     sla_max_delivery_time_brt
655      2.220557 2024-04-01 22:51:14.549573993
2024-04-01 21:51:14.549573993
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.39620331900681 hub em questão 10
dist order to hub é  1.2418206231971125 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 241
657
     order_id  order_latitude  order_longitude                ordered_at_brt  \
656       657      -23.668517        -46.64815 2024-04-01 21:52:56.499060715

     order_weight     sla_max_delivery_time_brt
656      3.681148 2024-04-01 22:52:56.499060715
2024-04-01 21:52:56.499060715
tem rota aberta
dist order to order é  1.7123936544674987 hub em questão 5
dist order to hub é  0.8937910934958408 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 236
658
     order_id  order_latitude  order_longitude                ordered_at_brt  \
657       658         -23.612       -46.581256 2024-04-01 21:53:02.004900511

     order_weight     sla_max_delivery_time_brt
657      1.013846 2024-04-02 00:53:02.004900511
2024-04-01 21:53:02.004900511
tem rota aberta
dist order to order é  0.0872373597066145 hub em questão 3
dist order to hub é  0.6922602204830526 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 235
659
     order_id  order_latitude  order_longitude                ordered_at_brt  \
658       659      -23.685356       -46.577982 2024-04-01 21:56:07.646007293

     order_weight     sla_max_delivery_time_brt
658      5.438614 2024-04-01 23:56:07.646007293
2024-04-01 21:56:07.646007293
tem rota aberta
dist order to order é  4.375377282802936 hub em questão 5
dist order to hub é  1.8446914968546286 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 5
passou aqui1
passou aqui5
route_id 242
caiu aqui tb
660
     order_id  order_latitude  order_longitude                ordered_at_brt  \
659       660      -23.735814       -46.723022 2024-04-01 21:56:32.874167145

     order_weight     sla_max_delivery_time_brt
659      7.817923 2024-04-01 23:56:32.874167145
2024-04-01 21:56:32.874167145
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  8.589472207526878 hub em questão 1
dist order to hub é  9.49745213091918 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 237
661
     order_id  order_latitude  order_longitude                ordered_at_brt  \
660       661      -23.591168       -46.641069 2024-04-01 21:58:02.942912566

     order_weight     sla_max_delivery_time_brt
660      4.475665 2024-04-01 22:58:02.942912566
2024-04-01 21:58:02.942912566
tem rota aberta
dist order to order é  2.2427346298979365 hub em questão 10
dist order to hub é  1.1333853222109724 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 241
662
     order_id  order_latitude  order_longitude                ordered_at_brt  \
661       662      -23.568169       -46.708218 2024-04-01 22:00:44.627544810

     order_weight     sla_max_delivery_time_brt
661      7.902066 2024-04-02 00:00:44.627544810
2024-04-01 22:00:44.627544810
tem rota aberta
dist order to order é  5.170531291642048 hub em questão 15
dist order to hub é  0.9086810834432556 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 15
passou aqui1
passou aqui5
route_id 243
caiu aqui tb
663
     order_id  order_latitude  order_longitude                ordered_at_brt  \
662       663      -23.743252       -46.714798 2024-04-01 22:01:04.120144021

     order_weight     sla_max_delivery_time_brt
662      7.888414 2024-04-02 01:01:04.120144021
2024-04-01 22:01:04.120144021
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.1767880362264942 hub em questão 1
dist order to hub é  9.467909657811152 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 237
664
     order_id  order_latitude  order_longitude                ordered_at_brt  \
663       664      -23.714839       -46.618715 2024-04-01 22:02:40.231331455

     order_weight     sla_max_delivery_time_brt
663      4.877683 2024-04-02 01:02:40.231331455
2024-04-01 22:02:40.231331455
tem rota aberta
dist order to order é  4.601208805134166 hub em questão 5
dist order to hub é  0.9767470484883684 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 244
caiu aqui tb
665
     order_id  order_latitude  order_longitude                ordered_at_brt  \
664       665      -23.645517       -46.690091 2024-04-01 22:03:09.527390359

     order_weight     sla_max_delivery_time_brt
664      8.501957 2024-04-02 00:03:09.527390359
2024-04-01 22:03:09.527390359
tem rota aberta
dist order to order é  1.403825539915453 hub em questão 15
dist order to hub é  1.5299327387789263 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 239
666
     order_id  order_latitude  order_longitude                ordered_at_brt  \
665       666      -23.702693       -46.805681 2024-04-01 22:06:00.380049462

     order_weight     sla_max_delivery_time_brt
665      5.111195 2024-04-02 00:06:00.380049462
2024-04-01 22:06:00.380049462
tem rota aberta
dist order to order é  17.953483148844196 hub em questão 4
dist order to hub é  11.849170592156606 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 4
passou aqui1
passou aqui5
route_id 245
caiu aqui tb
667
     order_id  order_latitude  order_longitude                ordered_at_brt  \
666       667      -23.612213       -46.615755 2024-04-01 22:08:34.391848566

     order_weight     sla_max_delivery_time_brt
666      4.538033 2024-04-02 00:08:34.391848566
2024-04-01 22:08:34.391848566
tem rota aberta
dist order to order é  2.73265353697298 hub em questão 10
dist order to hub é  0.8013011122834888 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 241
668
     order_id  order_latitude  order_longitude                ordered_at_brt  \
667       668      -23.690079       -46.583906 2024-04-01 22:08:57.702001552

     order_weight     sla_max_delivery_time_brt
667     10.281978 2024-04-01 23:08:57.702001552
2024-04-01 22:08:57.702001552
tem rota aberta
dist order to order é  0.7997278658996215 hub em questão 12
dist order to hub é  2.4597690281190663 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 242
669
     order_id  order_latitude  order_longitude                ordered_at_brt  \
668       669      -23.676104       -46.546074 2024-04-01 22:12:55.333116044

     order_weight     sla_max_delivery_time_brt
668     12.731424 2024-04-01 23:12:55.333116044
2024-04-01 22:12:55.333116044
tem rota aberta
dist order to order é  3.408233712796776 hub em questão 12
dist order to hub é  3.2924535331206766 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 242

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

670
     order_id  order_latitude  order_longitude                ordered_at_brt  \
669       670      -23.639654       -46.667827 2024-04-01 22:12:57.729905246

     order_weight     sla_max_delivery_time_brt
669      9.798355 2024-04-02 00:12:57.729905246
2024-04-01 22:12:57.729905246
tem rota aberta
dist order to order é  8.950989370150156 hub em questão 4
dist order to hub é  2.752634595225297 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 4
passou aqui1
passou aqui5
route_id 246
caiu aqui tb
671
     order_id  order_latitude  order_longitude                ordered_at_brt  \
670       671      -23.759137       -46.575741 2024-04-01 22:16:53.866760795

     order_weight     sla_max_delivery_time_brt
670      5.405477 2024-04-02 00:16:53.866760795
2024-04-01 22:16:53.866760795
tem rota aberta
dist order to order é  6.5876176241114885 hub em questão 1
dist order to hub é  3.740935426102036 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 1
passou aqui1
passou aqui5
route_id 247
caiu aqui tb
672
     order_id  order_latitude  order_longitude                ordered_at_brt  \
671       672      -23.666221       -46.779063 2024-04-01 22:18:32.085838239

     order_weight     sla_max_delivery_time_brt
671      8.663589 2024-04-02 00:18:32.085838239
2024-04-01 22:18:32.085838239
tem rota aberta
dist order to order é  4.877848975738283 hub em questão 9
dist order to hub é  7.8869726421717115 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 245

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

673
     order_id  order_latitude  order_longitude                ordered_at_brt  \
672       673      -23.549493       -46.700183 2024-04-01 22:19:34.030742295

     order_weight     sla_max_delivery_time_brt
672      9.917638 2024-04-02 01:19:34.030742295
2024-04-01 22:19:34.030742295
tem rota aberta
dist order to order é  2.232302940531108 hub em questão 4
dist order to hub é  2.4386047740886494 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 243
674
     order_id  order_latitude  order_longitude                ordered_at_brt  \
673       674      -23.620881       -46.622064 2024-04-01 22:22:24.659800418

     order_weight     sla_max_delivery_time_brt
673      8.592528 2024-04-01 23:22:24.659800418
2024-04-01 22:22:24.659800418
tem rota aberta
dist order to order é  5.107948088917752 hub em questão 10
dist order to hub é  0.7668848503155744 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 10
passou aqui1
passou aqui5
route_id 248
caiu aqui tb
675
     order_id  order_latitude  order_longitude                ordered_at_brt  \
674       675      -23.700181       -46.624436 2024-04-01 22:24:56.106704664

     order_weight     sla_max_delivery_time_brt
674      6.415208 2024-04-02 00:24:56.106704664
2024-04-01 22:24:56.106704664
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.7308808367811543 hub em questão 1
dist order to hub é  1.432772781254607 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 244
676
     order_id  order_latitude  order_longitude                ordered_at_brt  \
675       676      -23.597925       -46.581992 2024-04-01 22:33:40.292675166

     order_weight     sla_max_delivery_time_brt
675          0.01 2024-04-02 01:33:40.292675166
2024-04-01 22:33:40.292675166
tem rota aberta
dist order to order é  4.815185131396551 hub em questão 14
dist order to hub é  2.0531017756142775 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 14
passou aqui1
passou aqui5
route_id 249
caiu aqui tb
677
     order_id  order_latitude  order_longitude                ordered_at_brt  \
676       677      -23.547066       -46.600178 2024-04-01 22:34:19.394428312

     order_weight     sla_max_delivery_time_brt
676      9.152481 2024-04-02 00:34:19.394428312
2024-04-01 22:34:19.394428312
tem rota aberta
dist order to order é  5.951211419661907 hub em questão 3
dist order to hub é  7.016291064564638 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 249
678
     order_id  order_latitude  order_longitude                ordered_at_brt  \
677       678      -23.586492       -46.652091 2024-04-01 22:34:19.850534708

     order_weight     sla_max_delivery_time_brt
677      7.069815 2024-04-02 00:34:19.850534708
2024-04-01 22:34:19.850534708
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.897233267503869 hub em questão 14
dist order to hub é  2.2131965430106306 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 14
passou aqui1
passou aqui5
route_id 250
caiu aqui tb
679
     order_id  order_latitude  order_longitude                ordered_at_brt  \
678       679      -23.679456        -46.57155 2024-04-01 22:39:45.845653872

     order_weight     sla_max_delivery_time_brt
678       7.29368 2024-04-01 23:39:45.845653872
2024-04-01 22:39:45.845653872
tem rota aberta
dist order to order é  8.300280758266338 hub em questão 14
dist order to hub é  1.328565728253729 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 14
passou aqui1
passou aqui5
route_id 251
caiu aqui tb
680
     order_id  order_latitude  order_longitude                ordered_at_brt  \
679       680      -23.683105       -46.613689 2024-04-01 22:43:39.990118014

     order_weight     sla_max_delivery_time_brt
679      5.159803 2024-04-01 23:43:39.990118014
2024-04-01 22:43:39.990118014
tem rota aberta
dist order to order é  4.310157444829115 hub em questão 12
dist order to hub é  3.5935818818444023 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 251
681
     order_id  order_latitude  order_longitude                ordered_at_brt  \
680       681      -23.668749       -46.562158 2024-04-01 22:46:16.600479052

     order_weight     sla_max_delivery_time_brt
680      0.547465 2024-04-02 00:46:16.600479052
2024-04-01 22:46:16.600479052
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.5271492021810533 hub em questão 12
dist order to hub é  1.5520297166504746 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 251
682
     order_id  order_latitude  order_longitude                ordered_at_brt  \
681       682      -23.702678       -46.688227 2024-04-01 22:47:43.851817978

     order_weight     sla_max_delivery_time_brt
681      6.576919 2024-04-02 00:47:43.851817978
2024-04-01 22:47:43.851817978
tem rota aberta
dist order to order é  7.895548087022986 hub em questão 12
dist order to hub é  4.717636909077849 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
passou aqui5
route_id 252
caiu aqui tb
683
     order_id  order_latitude  order_longitude                ordered_at_brt  \
682       683      -23.648765          -46.633 2024-04-01 22:50:11.143819677

     order_weight     sla_max_delivery_time_brt
682     10.407703 2024-04-01 23:50:11.143819677
2024-04-01 22:50:11.143819677
tem rota aberta
dist order to order é  3.2945596442004486 hub em questão 14
dist order to hub é  3.079716529807678 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 248
684
     order_id  order_latitude  order_longitude                ordered_at_brt  \
683       684       -23.70051       -46.669493 2024-04-01 22:53:13.128344998

     order_weight     sla_max_delivery_time_brt
683      9.148997 2024-04-02 00:53:13.128344998
2024-04-01 22:53:13.128344998
tem rota aberta
dist order to order é  1.922602781277479 hub em questão 5
dist order to hub é  3.4302276818642072 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 252

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

685
     order_id  order_latitude  order_longitude                ordered_at_brt  \
684       685      -23.693987       -46.607717 2024-04-01 22:54:09.504964030

     order_weight     sla_max_delivery_time_brt
684      5.276485 2024-04-02 00:54:09.504964030
2024-04-01 22:54:09.504964030
tem rota aberta
dist order to order é  1.3542298159479018 hub em questão 12
dist order to hub é  2.927590975881499 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 251
686
     order_id  order_latitude  order_longitude                ordered_at_brt  \
685       686      -23.634184        -46.65899 2024-04-01 22:57:06.034472616

     order_weight     sla_max_delivery_time_brt
685      7.150631 2024-04-02 01:57:06.034472616
2024-04-01 22:57:06.034472616
tem rota aberta
dist order to order é  5.349553131459223 hub em questão 8
dist order to hub é  1.8442781579414629 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 8
passou aqui1
passou aqui5
route_id 253
caiu aqui tb
687
     order_id  order_latitude  order_longitude                ordered_at_brt  \
686       687      -23.678406       -46.660605 2024-04-01 22:59:52.689843962

     order_weight     sla_max_delivery_time_brt
686      5.879334 2024-04-02 01:59:52.689843962
2024-04-01 22:59:52.689843962
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.6190885173349767 hub em questão 5
dist order to hub é  0.8324351005764585 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 252
688
     order_id  order_latitude  order_longitude                ordered_at_brt  \
687       688      -23.660445       -46.714337 2024-04-01 23:01:46.675024106

     order_weight     sla_max_delivery_time_brt
687      0.958065 2024-04-02 02:01:46.675024106
2024-04-01 23:01:46.675024106
tem rota aberta
dist order to order é  5.396618825135477 hub em questão 5
dist order to hub é  1.453441592666878 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 254
caiu aqui tb
689
     order_id  order_latitude  order_longitude                ordered_at_brt  \
688       689      -23.542816       -46.632603 2024-04-01 23:02:48.347865236

     order_weight     sla_max_delivery_time_brt
688      7.504718 2024-04-02 02:02:48.347865236
2024-04-01 23:02:48.347865236
tem rota aberta
dist order to order é  3.3388648145168682 hub em questão 3
dist order to hub é  6.433000484400527 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 249
690
     order_id  order_latitude  order_longitude                ordered_at_brt  \
689       690      -23.631814       -46.592238 2024-04-01 23:05:11.752611926

     order_weight     sla_max_delivery_time_brt
689      11.45039 2024-04-02 02:05:11.752611926
2024-04-01 23:05:11.752611926
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  6.805096847733999 hub em questão 10
dist order to hub é  2.3387434887044725 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 10
passou aqui1
passou aqui5
route_id 255
caiu aqui tb
691
     order_id  order_latitude  order_longitude                ordered_at_brt  \
690       691      -23.590709       -46.597603 2024-04-01 23:05:12.126737467

     order_weight     sla_max_delivery_time_brt
690     12.718358 2024-04-02 00:05:12.126737467
2024-04-01 23:05:12.126737467
tem rota aberta
dist order to order é  4.603260536713003 hub em questão 7
dist order to hub é  3.517306082316725 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 255
692
     order_id  order_latitude  order_longitude                ordered_at_brt  \
691       692      -23.628329       -46.798814 2024-04-01 23:08:11.070213589

     order_weight     sla_max_delivery_time_brt
691      6.347898 2024-04-02 02:08:11.070213589
2024-04-01 23:08:11.070213589
tem rota aberta
dist order to order é  9.316456629938006 hub em questão 9
dist order to hub é  8.672944861363067 hub em questão 11
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 254
693
     order_id  order_latitude  order_longitude                ordered_at_brt  \
692       693      -23.620076       -46.728995 2024-04-01 23:12:43.155599673

     order_weight     sla_max_delivery_time_brt
692      8.753133 2024-04-02 00:12:43.155599673
2024-04-01 23:12:43.155599673
tem rota aberta
dist order to order é  4.730556813338154 hub em questão 9
dist order to hub é  4.454506861402995 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 254

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

694
     order_id  order_latitude  order_longitude                ordered_at_brt  \
693       694      -23.717684       -46.547756 2024-04-01 23:13:15.980023575

     order_weight     sla_max_delivery_time_brt
693       1.48646 2024-04-02 02:13:15.980023575
2024-04-01 23:13:15.980023575
tem rota aberta
dist order to order é  10.568370252355805 hub em questão 7
dist order to hub é  3.013215973404926 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 7
passou aqui1
passou aqui5
route_id 256
caiu aqui tb
695
     order_id  order_latitude  order_longitude                ordered_at_brt  \
694       695      -23.677574       -46.657394 2024-04-01 23:13:31.424689827

     order_weight     sla_max_delivery_time_brt
694      3.405086 2024-04-02 01:13:31.424689827
2024-04-01 23:13:31.424689827
tem rota aberta
dist order to order é  0.33986954590428425 hub em questão 5
dist order to hub é  0.6076678617037176 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 252
696
     order_id  order_latitude  order_longitude                ordered_at_brt  \
695       696      -23.663338        -46.65546 2024-04-01 23:14:01.283751328

     order_weight     sla_max_delivery_time_brt
695      8.207966 2024-04-02 01:14:01.283751328
2024-04-01 23:14:01.283751328
tem rota aberta
dist order to order é  3.2616256081220913 hub em questão 10
dist order to hub é  0.9955683865932897 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 10
passou aqui1

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

passou aqui5
route_id 257
caiu aqui tb
697
     order_id  order_latitude  order_longitude                ordered_at_brt  \
696       697      -23.672557       -46.589746 2024-04-01 23:14:44.444723648

     order_weight     sla_max_delivery_time_brt
696      8.452318 2024-04-02 01:14:44.444723648
2024-04-01 23:14:44.444723648
tem rota aberta
dist order to order é  4.5374506624725255 hub em questão 7
dist order to hub é  1.3259578430581336 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 7
passou aqui1
passou aqui5
route_id 258
caiu aqui tb
698
     order_id  order_latitude  order_longitude                ordered_at_brt  \
697       698      -23.660371       -46.638181 2024-04-01 23:19:01.943728065

     order_weight     sla_max_delivery_time_brt
697      2.398469 2024-04-02 00:19:01.943728065
2024-04-01 23:19:01.943728065
tem rota aberta
dist order to order é  1.79050885321598 hub em questão 5
dist order to hub é  2.2388531223898096 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 257
699
     order_id  order_latitude  order_longitude                ordered_at_brt  \
698       699       -23.64223       -46.679642 2024-04-01 23:20:35.956064189

     order_weight     sla_max_delivery_time_brt
698      4.377487 2024-04-02 02:20:35.956064189
2024-04-01 23:20:35.956064189
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.286049018495042 hub em questão 10
dist order to hub é  2.6434888812510704 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 253
700
     order_id  order_latitude  order_longitude                ordered_at_brt  \
699       700      -23.661356       -46.658505 2024-04-01 23:21:16.500406807

     order_weight     sla_max_delivery_time_brt
699      4.611029 2024-04-02 01:21:16.500406807
2024-04-01 23:21:16.500406807
tem rota aberta
dist order to order é  0.3804850597252841 hub em questão 5
dist order to hub é  1.2434745184250795 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 257
701
     order_id  order_latitude  order_longitude                ordered_at_brt  \
700       701      -23.615746       -46.553155 2024-04-01 23:21:34.369794735

     order_weight     sla_max_delivery_time_brt
700       9.22942 2024-04-02 02:21:34.369794735
2024-04-01 23:21:34.369794735
tem rota aberta
dist order to order é  4.364220688459095 hub em questão 7
dist order to hub é  2.2855900326981122 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 7
passou aqui1
passou aqui5
route_id 259
caiu aqui tb
702
     order_id  order_latitude  order_longitude                ordered_at_brt  \
701       702      -23.662615       -46.717082 2024-04-01 23:22:15.493050592

     order_weight     sla_max_delivery_time_brt
701      6.222874 2024-04-02 01:22:15.493050592
2024-04-01 23:22:15.493050592
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  0.36935139638965453 hub em questão 9
dist order to hub é  1.8224785533164771 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 254
703
     order_id  order_latitude  order_longitude                ordered_at_brt  \
702       703      -23.596028       -46.582952 2024-04-01 23:24:09.683130696

     order_weight     sla_max_delivery_time_brt
702      7.125365 2024-04-02 01:24:09.683130696
2024-04-01 23:24:09.683130696
tem rota aberta
dist order to order é  1.6058519219730591 hub em questão 7
dist order to hub é  2.2843101819828617 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 255
704
     order_id  order_latitude  order_longitude                ordered_at_brt  \
703       704       -23.65088       -46.663632 2024-04-01 23:24:56.695188674

     order_weight     sla_max_delivery_time_brt
703     10.297725 2024-04-02 01:24:56.695188674
2024-04-01 23:24:56.695188674
tem rota aberta
dist order to order é  1.2765648093325446 hub em questão 5
dist order to hub é  2.5065801385346833 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 257
705
     order_id  order_latitude  order_longitude                ordered_at_brt  \
704       705      -23.679959       -46.661574 2024-04-01 23:26:10.052328334

     order_weight     sla_max_delivery_time_brt
704      8.603869 2024-04-02 01:26:10.052328334
2024-04-01 23:26:10.052328334
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.581109638863523 hub em questão 10
dist order to hub é  1.0305859029462856 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 10
passou aqui1
passou aqui5
route_id 260
caiu aqui tb
706
     order_id  order_latitude  order_longitude                ordered_at_brt  \
705       706      -23.712795       -46.554867 2024-04-01 23:27:20.516044059

     order_weight     sla_max_delivery_time_brt
705      3.969734 2024-04-02 01:27:20.516044059
2024-04-01 23:27:20.516044059
tem rota aberta
dist order to order é  0.9053748346105266 hub em questão 6
dist order to hub é  2.581877677335577 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 256
707
     order_id  order_latitude  order_longitude                ordered_at_brt  \
706       707      -23.688695       -46.680156 2024-04-01 23:30:51.841815218

     order_weight     sla_max_delivery_time_brt
706       7.20169 2024-04-02 01:30:51.841815218
2024-04-01 23:30:51.841815218
tem rota aberta
dist order to order é  2.1269634671115476 hub em questão 5
dist order to hub é  3.07078952278575 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 260
708
     order_id  order_latitude  order_longitude                ordered_at_brt  \
707       708      -23.662941        -46.60626 2024-04-01 23:31:58.529728077

     order_weight     sla_max_delivery_time_brt
707      3.771469 2024-04-02 00:31:58.529728077
2024-04-01 23:31:58.529728077
tem rota aberta
dist order to order é  1.9929207834765466 hub em questão 12
dist order to hub é  3.0101469498513262 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 258
709
     order_id  order_latitude  order_longitude                ordered_at_brt  \
708       709      -23.590122       -46.666165 2024-04-01 23:32:49.432229931

     order_weight     sla_max_delivery_time_brt
708      7.378163 2024-04-02 02:32:49.432229931
2024-04-01 23:32:49.432229931
tem rota aberta
dist order to order é  6.986988101929636 hub em questão 7
dist order to hub é  2.908126200049085 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 7
passou aqui1
passou aqui5
route_id 261
caiu aqui tb
710
     order_id  order_latitude  order_longitude                ordered_at_brt  \
709       710      -23.713819       -46.719616 2024-04-01 23:35:04.293357609

     order_weight     sla_max_delivery_time_brt
709     10.525417 2024-04-02 02:35:04.293357609
2024-04-01 23:35:04.293357609
tem rota aberta
dist order to order é  4.8934909660583035 hub em questão 5
dist order to hub é  7.036521917402674 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 260
711
     order_id  order_latitude  order_longitude                ordered_at_brt  \
710       711      -23.598218       -46.656314 2024-04-01 23:35:34.336946190

     order_weight     sla_max_delivery_time_brt
710      9.602347 2024-04-02 02:35:34.336946190
2024-04-01 23:35:34.336946190
tem rota aberta
dist order to order é  1.348357602054986 hub em questão 15
dist order to hub é  1.967782772457313 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 261

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

712
     order_id  order_latitude  order_longitude                ordered_at_brt  \
711       712      -23.654814       -46.589566 2024-04-01 23:36:49.900366508

     order_weight     sla_max_delivery_time_brt
711      9.097181 2024-04-02 01:36:49.900366508
2024-04-01 23:36:49.900366508
tem rota aberta
dist order to order é  1.9254665157447284 hub em questão 12
dist order to hub é  1.9864810630771346 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 258
713
     order_id  order_latitude  order_longitude                ordered_at_brt  \
712       713      -23.691798       -46.657307 2024-04-01 23:37:35.259698937

     order_weight     sla_max_delivery_time_brt
712      8.423522 2024-04-02 02:37:35.259698937
2024-04-01 23:37:35.259698937
tem rota aberta
dist order to order é  1.38622600986025 hub em questão 5
dist order to hub é  2.174722862596186 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 260
714
     order_id  order_latitude  order_longitude                ordered_at_brt  \
713       714       -23.71618       -46.620542 2024-04-01 23:39:33.554475978

     order_weight     sla_max_delivery_time_brt
713      9.877225 2024-04-02 00:39:33.554475978
2024-04-01 23:39:33.554475978
tem rota aberta
dist order to order é  5.775947496811366 hub em questão 12
dist order to hub é  0.8554795678004604 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 12
passou aqui1
passou aqui5
route_id 262
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

715
     order_id  order_latitude  order_longitude                ordered_at_brt  \
714       715      -23.622776       -46.638585 2024-04-01 23:43:45.375185785

     order_weight     sla_max_delivery_time_brt
714      7.846701 2024-04-02 00:43:45.375185785
2024-04-01 23:43:45.375185785
tem rota aberta
dist order to order é  3.2740785596182707 hub em questão 15
dist order to hub é  1.7030940071781018 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 261
716
     order_id  order_latitude  order_longitude                ordered_at_brt  \
715       716      -23.745537       -46.645671 2024-04-01 23:44:56.612464084

     order_weight     sla_max_delivery_time_brt
715      9.278662 2024-04-02 01:44:56.612464084
2024-04-01 23:44:56.612464084
tem rota aberta
dist order to order é  4.1472267496566575 hub em questão 1
dist order to hub é  4.0756465448955055 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 262
717
     order_id  order_latitude  order_longitude                ordered_at_brt  \
716       717      -23.673301       -46.668888 2024-04-01 23:48:00.764079645

     order_weight     sla_max_delivery_time_brt
716      7.464175 2024-04-02 01:48:00.764079645
2024-04-01 23:48:00.764079645
tem rota aberta
dist order to order é  6.41020144517483 hub em questão 15
dist order to hub é  1.327051809754185 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 15
passou aqui1
passou aqui5
route_id 263
caiu aqui tb
718
     order_id  order_latitude  order_longitude                ordered_at_brt  \
717       718      -23.672243       -46.641424 2024-04-01 23:49:14.034014983

     order_weight     sla_max_delivery_time_brt
717      8.596226 2024-04-02 02:49:14.034014983

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 23:49:14.034014983
tem rota aberta
dist order to order é  2.7993615647393377 hub em questão 5
dist order to hub é  1.4746953957216555 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 263
719
     order_id  order_latitude  order_longitude                ordered_at_brt  \
718       719      -23.658382       -46.749657 2024-04-01 23:51:22.167675690

     order_weight     sla_max_delivery_time_brt
718       7.76491 2024-04-02 01:51:22.167675690
2024-04-01 23:51:22.167675690
tem rota aberta
dist order to order é  8.391520589608778 hub em questão 5
dist order to hub é  4.787192642850688 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 264
caiu aqui tb
720
     order_id  order_latitude  order_longitude                ordered_at_brt  \
719       720      -23.621166       -46.670429 2024-04-01 23:51:39.133320403

     order_weight     sla_max_delivery_time_brt
719      9.978132 2024-04-02 01:51:39.133320403
2024-04-01 23:51:39.133320403
tem rota aberta
dist order to order é  2.9291119113074107 hub em questão 15
dist order to hub é  1.2445691357803292 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 261
721
     order_id  order_latitude  order_longitude                ordered_at_brt  \
720       721      -23.680957        -46.73821 2024-04-01 23:52:47.216923628

     order_weight     sla_max_delivery_time_brt
720      10.20975 2024-04-02 02:52:47.216923628

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-01 23:52:47.216923628
tem rota aberta
dist order to order é  2.767821230857191 hub em questão 9
dist order to hub é  4.783221563794533 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 264
722
     order_id  order_latitude  order_longitude                ordered_at_brt  \
721       722      -23.644208       -46.634528 2024-04-01 23:57:35.256536805

     order_weight     sla_max_delivery_time_brt
721      5.406161 2024-04-02 01:57:35.256536805
2024-04-01 23:57:35.256536805
tem rota aberta
dist order to order é  3.1955166162882356 hub em questão 5
dist order to hub é  2.769845418415533 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 263
723
     order_id  order_latitude  order_longitude                ordered_at_brt  \
722       723      -23.711118        -46.63028 2024-04-01 23:59:26.866486099

     order_weight     sla_max_delivery_time_brt
722      3.900071 2024-04-02 01:59:26.866486099
2024-04-01 23:59:26.866486099
tem rota aberta
dist order to order é  1.1400552654747085 hub em questão 1
dist order to hub é  0.2871640616914358 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 262
724
     order_id  order_latitude  order_longitude                ordered_at_brt  \
723       724      -23.647341       -46.687816 2024-04-02 00:02:21.556468858

     order_weight     sla_max_delivery_time_brt
723      6.438716 2024-04-02 01:02:21.556468858
2024-04-02 00:02:21.556468858
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.471202557194417 hub em questão 5
dist order to hub é  1.6557077374446572 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 263
725
     order_id  order_latitude  order_longitude                ordered_at_brt  \
724       725      -23.619808       -46.607947 2024-04-02 00:03:45.867612912

     order_weight     sla_max_delivery_time_brt
724     12.688047 2024-04-02 01:03:45.867612912
2024-04-02 00:03:45.867612912
tem rota aberta
dist order to order é  10.404858119000124 hub em questão 1
dist order to hub é  0.35578159219590416 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 1
passou aqui1
passou aqui5
route_id 265
caiu aqui tb
726
     order_id  order_latitude  order_longitude                ordered_at_brt  \
725       726       -23.66781       -46.628221 2024-04-02 00:05:08.579529535

     order_weight     sla_max_delivery_time_brt
725      9.042329 2024-04-02 02:05:08.579529535
2024-04-02 00:05:08.579529535
tem rota aberta
dist order to order é  4.820163770128353 hub em questão 1
dist order to hub é  2.86277671893455 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 262
727
     order_id  order_latitude  order_longitude                ordered_at_brt  \
726       727      -23.631792       -46.633334 2024-04-02 00:08:50.684135513

     order_weight     sla_max_delivery_time_brt
726      0.052758 2024-04-02 02:08:50.684135513
2024-04-02 00:08:50.684135513
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.909414657527727 hub em questão 7
dist order to hub é  1.848473827399908 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 265
728
     order_id  order_latitude  order_longitude                ordered_at_brt  \
727       728      -23.644994       -46.666083 2024-04-02 00:08:59.109975563

     order_weight     sla_max_delivery_time_brt
727      9.201015 2024-04-02 02:08:59.109975563
2024-04-02 00:08:59.109975563
tem rota aberta
dist order to order é  3.644660524772503 hub em questão 7
dist order to hub é  3.20654445680521 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 265
729
     order_id  order_latitude  order_longitude                ordered_at_brt  \
728       729       -23.66744       -46.624373 2024-04-02 00:10:41.303068453

     order_weight     sla_max_delivery_time_brt
728      4.161158 2024-04-02 03:10:41.303068453
2024-04-02 00:10:41.303068453
tem rota aberta
dist order to order é  4.067582769457022 hub em questão 7
dist order to hub é  3.2559840183845385 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 265
730
     order_id  order_latitude  order_longitude                ordered_at_brt  \
729       730      -23.653266       -46.595302 2024-04-02 00:16:24.568746720

     order_weight     sla_max_delivery_time_brt
729      7.294516 2024-04-02 02:16:24.568746720
2024-04-02 00:16:24.568746720
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  14.876254551401004 hub em questão 9
dist order to hub é  2.509832206865519 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 9
passou aqui1
passou aqui5
route_id 266
caiu aqui tb
731
     order_id  order_latitude  order_longitude                ordered_at_brt  \
730       731      -23.659976       -46.681035 2024-04-02 00:17:52.111248790

     order_weight     sla_max_delivery_time_brt
730      2.424818 2024-04-02 01:17:52.111248790
2024-04-02 00:17:52.111248790
tem rota aberta
dist order to order é  6.272705306370683 hub em questão 9
dist order to hub é  2.402889604706714 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 9
passou aqui1
rota em aberto, route_id:  264
rota_escolhida: 264
orders no hub: 2
passou aqui3
passou aqui4
732
     order_id  order_latitude  order_longitude                ordered_at_brt  \
731       732      -23.748938       -46.688855 2024-04-02 00:18:18.061204509

     order_weight     sla_max_delivery_time_brt
731          0.01 2024-04-02 02:18:18.061204509
2024-04-02 00:18:18.061204509
tem rota aberta
dist order to order é  9.076692910983237 hub em questão 9
dist order to hub é  7.392764958545016 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 264
733
     order_id  order_latitude  order_longitude                ordered_at_brt  \
732       733      -23.725183       -46.588562 2024-04-02 00:22:04.078336951

     order_weight     sla_max_delivery_time_brt
732      12.10165 2024-04-02 03:22:04.078336951
2024-04-02 00:22:04.078336951
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  8.026244089088387 hub em questão 12
dist order to hub é  1.2692289946781072 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 12
passou aqui1
passou aqui5
route_id 267
caiu aqui tb
734
     order_id  order_latitude  order_longitude                ordered_at_brt  \
733       734      -23.628583       -46.763934 2024-04-02 00:22:38.862735431

     order_weight     sla_max_delivery_time_brt
733      10.01281 2024-04-02 02:22:38.862735431
2024-04-02 00:22:38.862735431
tem rota aberta
dist order to order é  17.395268966916323 hub em questão 12
dist order to hub é  6.7360569278628155 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 12
passou aqui1
passou aqui5
route_id 268
caiu aqui tb
735
     order_id  order_latitude  order_longitude                ordered_at_brt  \
734       735      -23.754643       -46.778877 2024-04-02 00:25:03.630238530

     order_weight     sla_max_delivery_time_brt
734      11.69673 2024-04-02 02:25:03.630238530
2024-04-02 00:25:03.630238530
tem rota aberta
dist order to order é  14.099587864992932 hub em questão 9
dist order to hub é  13.741524641148457 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 268
736
     order_id  order_latitude  order_longitude                ordered_at_brt  \
735       736      -23.592306       -46.738749 2024-04-02 00:26:36.881783992

     order_weight     sla_max_delivery_time_brt
735      8.845855 2024-04-02 03:26:36.881783992
2024-04-02 00:26:36.881783992
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.780771026184993 hub em questão 9
dist order to hub é  4.518920665465476 hub em questão 11
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 268
737
     order_id  order_latitude  order_longitude                ordered_at_brt  \
736       737      -23.720724       -46.638926 2024-04-02 00:32:33.608754435

     order_weight     sla_max_delivery_time_brt
736      2.606297 2024-04-02 02:32:33.608754435
2024-04-02 00:32:33.608754435
tem rota aberta
dist order to order é  5.150891028052855 hub em questão 6
dist order to hub é  1.4293615740452756 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 6
passou aqui1
passou aqui5
route_id 269
caiu aqui tb
738
     order_id  order_latitude  order_longitude                ordered_at_brt  \
737       738      -23.648699       -46.640394 2024-04-02 00:34:31.096197062

     order_weight     sla_max_delivery_time_brt
737     13.247478 2024-04-02 01:34:31.096197062
2024-04-02 00:34:31.096197062
tem rota aberta
dist order to order é  4.620817650892901 hub em questão 12
dist order to hub é  3.0613655361925516 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 266
739
     order_id  order_latitude  order_longitude                ordered_at_brt  \
738       739      -23.626619       -46.623188 2024-04-02 00:38:09.498947013

     order_weight     sla_max_delivery_time_brt
738          0.01 2024-04-02 03:38:09.498947013
2024-04-02 00:38:09.498947013
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.0166857424367954 hub em questão 12
dist order to hub é  0.6897475914451204 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 12
passou aqui1
passou aqui5
route_id 270
caiu aqui tb
740
     order_id  order_latitude  order_longitude                ordered_at_brt  \
739       740      -23.682062       -46.644214 2024-04-02 00:38:10.454688076

     order_weight     sla_max_delivery_time_brt
739      6.613908 2024-04-02 02:38:10.454688076
2024-04-02 00:38:10.454688076
tem rota aberta
dist order to order é  3.730145213879846 hub em questão 12
dist order to hub é  1.61241588686407 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
passou aqui5
route_id 271
caiu aqui tb
741
     order_id  order_latitude  order_longitude                ordered_at_brt  \
740       741      -23.592096       -46.571144 2024-04-02 00:47:15.406143576

     order_weight     sla_max_delivery_time_brt
740      5.038491 2024-04-02 02:47:15.406143576
2024-04-02 00:47:15.406143576
tem rota aberta
dist order to order é  6.546277643674897 hub em questão 14
dist order to hub é  2.6338731067886094 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 14
passou aqui1
passou aqui5
route_id 272
caiu aqui tb
742
     order_id  order_latitude  order_longitude                ordered_at_brt  \
741       742      -23.718768       -46.569224 2024-04-02 00:47:25.114206778

     order_weight     sla_max_delivery_time_brt
741      4.918393 2024-04-02 02:47:25.114206778
2024-04-02 00:47:25.114206778
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.0939363567580083 hub em questão 6
dist order to hub é  1.024395455427029 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 267
743
     order_id  order_latitude  order_longitude                ordered_at_brt  \
742       743      -23.604887       -46.590062 2024-04-02 00:48:11.770090656

     order_weight     sla_max_delivery_time_brt
742      0.137814 2024-04-02 02:48:11.770090656
2024-04-02 00:48:11.770090656
tem rota aberta
dist order to order é  2.3956338517906977 hub em questão 3
dist order to hub é  1.8841634850838649 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 272
744
     order_id  order_latitude  order_longitude                ordered_at_brt  \
743       744      -23.642798       -46.705803 2024-04-02 00:54:02.361773885

     order_weight     sla_max_delivery_time_brt
743      2.599417 2024-04-02 02:54:02.361773885
2024-04-02 00:54:02.361773885
tem rota aberta
dist order to order é  7.642501179911651 hub em questão 5
dist order to hub é  1.0988593971185678 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 273
caiu aqui tb
745
     order_id  order_latitude  order_longitude                ordered_at_brt  \
744       745      -23.657785       -46.629834 2024-04-02 00:54:03.439289387

     order_weight     sla_max_delivery_time_brt
744      5.793737 2024-04-02 02:54:03.439289387
2024-04-02 00:54:03.439289387
tem rota aberta
dist order to order é  3.0711822359381133 hub em questão 5
dist order to hub é  3.106186522103399 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 271
746
     order_id  order_latitude  order_longitude                ordered_at_brt  \
745       746      -23.599641       -46.691323 2024-04-02 00:57:31.049047252

     order_weight     sla_max_delivery_time_brt
745     11.256794 2024-04-02 01:57:31.049047252
2024-04-02 00:57:31.049047252
tem rota aberta
dist order to order é  5.02046547552182 hub em questão 9
dist order to hub é  3.2609329898537855 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 273
747
     order_id  order_latitude  order_longitude                ordered_at_brt  \
746       747      -23.623263       -46.673048 2024-04-02 01:01:28.025657371

     order_weight     sla_max_delivery_time_brt
746      4.160742 2024-04-02 03:01:28.025657371
2024-04-02 01:01:28.025657371
tem rota aberta
dist order to order é  3.219648401757809 hub em questão 9
dist order to hub é  1.5934263682274248 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 273
748
     order_id  order_latitude  order_longitude                ordered_at_brt  \
747       748      -23.710449       -46.699181 2024-04-02 01:02:37.567628178

     order_weight     sla_max_delivery_time_brt
747      8.473935 2024-04-02 03:02:37.567628178
2024-04-02 01:02:37.567628178
tem rota aberta
dist order to order é  6.425501575873194 hub em questão 5
dist order to hub é  6.117967902586078 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 271
749
     order_id  order_latitude  order_longitude                ordered_at_brt  \
748       749      -23.579635       -46.647477 2024-04-02 01:03:13.012246738

     order_weight     sla_max_delivery_time_brt
748      8.610355 2024-04-02 04:03:13.012246738
2024-04-02 01:03:13.012246738
tem rota aberta
dist order to order é  4.99116749250049 hub em questão 9
dist order to hub é  2.5710684231011305 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 9
passou aqui1
passou aqui5
route_id 274
caiu aqui tb
750
     order_id  order_latitude  order_longitude                ordered_at_brt  \
749       750      -23.600026       -46.620807 2024-04-02 01:06:27.769456549

     order_weight     sla_max_delivery_time_brt
749      9.814623 2024-04-02 02:06:27.769456549
2024-04-02 01:06:27.769456549
tem rota aberta
dist order to order é  2.9669470844171726 hub em questão 14
dist order to hub é  1.6217852033110458 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 270
751
     order_id  order_latitude  order_longitude                ordered_at_brt  \
750       751      -23.645035       -46.644078 2024-04-02 01:07:45.748260554

     order_weight     sla_max_delivery_time_brt
750       5.25614 2024-04-02 04:07:45.748260554
2024-04-02 01:07:45.748260554
tem rota aberta
dist order to order é  2.0285095063088363 hub em questão 5
dist order to hub é  3.1764150154732396 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 271
752
     order_id  order_latitude  order_longitude                ordered_at_brt  \
751       752      -23.642741       -46.707681 2024-04-02 01:08:03.059634547

     order_weight     sla_max_delivery_time_brt
751     10.587268 2024-04-02 04:08:03.059634547
2024-04-02 01:08:03.059634547
tem rota aberta
dist order to order é  0.19144257217905755 hub em questão 9
dist order to hub é  1.167142657249187 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 273
753
     order_id  order_latitude  order_longitude                ordered_at_brt  \
752       753      -23.583414       -46.724315 2024-04-02 01:13:18.538918675

     order_weight     sla_max_delivery_time_brt
752      3.601078 2024-04-02 04:13:18.538918675
2024-04-02 01:13:18.538918675
tem rota aberta
dist order to order é  7.841714364979993 hub em questão 8
dist order to hub é  2.8102893853795363 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 8
passou aqui1
passou aqui5
route_id 275
caiu aqui tb
754
     order_id  order_latitude  order_longitude                ordered_at_brt  \
753       754      -23.567317       -46.686117 2024-04-02 01:17:50.107995804

     order_weight     sla_max_delivery_time_brt
753      8.952891 2024-04-02 04:17:50.107995804
2024-04-02 01:17:50.107995804
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.169411721920963 hub em questão 8
dist order to hub é  1.4906573292290104 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 8
passou aqui1
rota em aberto, route_id:  275
rota_escolhida: 275
orders no hub: 1
passou aqui3
passou aqui4
755
     order_id  order_latitude  order_longitude                ordered_at_brt  \
754       755      -23.619592       -46.686895 2024-04-02 01:19:11.273458767

     order_weight     sla_max_delivery_time_brt
754      4.864839 2024-04-02 02:19:11.273458767
2024-04-02 01:19:11.273458767
tem rota aberta
dist order to order é  5.542716037733745 hub em questão 4
dist order to hub é  2.7937735730451414 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 4
passou aqui1
passou aqui5
route_id 276
caiu aqui tb
756
     order_id  order_latitude  order_longitude                ordered_at_brt  \
755       756      -23.708356       -46.608799 2024-04-02 01:23:04.413342677

     order_weight     sla_max_delivery_time_brt
755         4.687 2024-04-02 04:23:04.413342677
2024-04-02 01:23:04.413342677
tem rota aberta
dist order to order é  12.67596202200646 hub em questão 15
dist order to hub é  2.0126442200219072 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 15
passou aqui1
passou aqui5
route_id 277
caiu aqui tb
757
     order_id  order_latitude  order_longitude                ordered_at_brt  \
756       757      -23.644213       -46.663977 2024-04-02 01:24:09.486762219

     order_weight     sla_max_delivery_time_brt
756      5.202362 2024-04-02 02:24:09.486762219
2024-04-02 01:24:09.486762219
tem rota aberta
dist order to order é  3.5979742873340648 hub em questão 15
dist order to hub é  3.058070306229945 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 276
758
     order_id  order_latitude  order_longitude                ordered_at_brt  \
757       758      -23.609224       -46.657446 2024-04-02 01:26:27.525299450

     order_weight     sla_max_delivery_time_brt
757      2.379475 2024-04-02 03:26:27.525299450
2024-04-02 01:26:27.525299450
tem rota aberta
dist order to order é  3.214210041828528 hub em questão 15
dist order to hub é  0.7511647088945606 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 15
passou aqui1
rota em aberto, route_id:  276
rota_escolhida: 276
orders no hub: 2
passou aqui3
passou aqui4
759
     order_id  order_latitude  order_longitude                ordered_at_brt  \
758       759       -23.69195        -46.65586 2024-04-02 01:27:28.423173606

     order_weight     sla_max_delivery_time_brt
758      4.167218 2024-04-02 03:27:28.423173606
2024-04-02 01:27:28.423173606
tem rota aberta
dist order to order é  5.127083640093406 hub em questão 1
dist order to hub é  2.187004278727818 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 1
passou aqui1
passou aqui5
route_id 278
caiu aqui tb
760
     order_id  order_latitude  order_longitude                ordered_at_brt  \
759       760      -23.710519        -46.59317 2024-04-02 01:28:52.986893553

     order_weight     sla_max_delivery_time_brt
759      8.027278 2024-04-02 03:28:52.986893553
2024-04-02 01:28:52.986893553
tem rota aberta
dist order to order é  1.6092230331093313 hub em questão 1
dist order to hub é  2.4070187893582298 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 277
761
     order_id  order_latitude  order_longitude                ordered_at_brt  \
760       761      -23.649936       -46.566207 2024-04-02 01:29:18.207021287

     order_weight     sla_max_delivery_time_brt
760      9.044317 2024-04-02 03:29:18.207021287
2024-04-02 01:29:18.207021287
tem rota aberta
dist order to order é  7.274536812971991 hub em questão 1
dist order to hub é  2.384796261948674 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 1
passou aqui1
passou aqui5
route_id 279
caiu aqui tb
762
     order_id  order_latitude  order_longitude                ordered_at_brt  \
761       762      -23.644607        -46.62666 2024-04-02 01:36:00.457918916

     order_weight     sla_max_delivery_time_brt
761      6.625025 2024-04-02 03:36:00.457918916
2024-04-02 01:36:00.457918916
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.8013777500691184 hub em questão 15
dist order to hub é  2.3579250289520286 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 276
763
     order_id  order_latitude  order_longitude                ordered_at_brt  \
762       763      -23.631334       -46.660428 2024-04-02 01:36:42.271390387

     order_weight     sla_max_delivery_time_brt
762     10.047189 2024-04-02 02:36:42.271390387
2024-04-02 01:36:42.271390387
tem rota aberta
dist order to order é  6.756287089653989 hub em questão 5
dist order to hub é  1.5887906066572137 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 5
passou aqui1
passou aqui5
route_id 280
caiu aqui tb
764
     order_id  order_latitude  order_longitude                ordered_at_brt  \
763       764       -23.58871       -46.577888 2024-04-02 01:36:55.376815250

     order_weight     sla_max_delivery_time_brt
763      2.415568 2024-04-02 03:36:55.376815250
2024-04-02 01:36:55.376815250
tem rota aberta
dist order to order é  6.911259669810389 hub em questão 12
dist order to hub é  2.9803976158087715 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 12
passou aqui1
passou aqui5
route_id 281
caiu aqui tb
765
     order_id  order_latitude  order_longitude                ordered_at_brt  \
764       765      -23.759347       -46.626101 2024-04-02 01:37:14.079226723

     order_weight     sla_max_delivery_time_brt
764      6.801692 2024-04-02 03:37:14.079226723
2024-04-02 01:37:14.079226723
tem rota aberta
dist order to order é  5.937080342720742 hub em questão 1
dist order to hub é  5.196632793291953 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 277
766
     order_id  order_latitude  order_longitude                ordered_at_brt  \
765       766      -23.645232       -46.669068 2024-04-02 01:37:15.782330733

     order_weight     sla_max_delivery_time_brt
765      9.194695 2024-04-02 02:37:15.782330733
2024-04-02 01:37:15.782330733
tem rota aberta
dist order to order é  1.778452952438504 hub em questão 10
dist order to hub é  3.2930748519400246 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 280
767
     order_id  order_latitude  order_longitude                ordered_at_brt  \
766       767      -23.660509       -46.597484 2024-04-02 01:39:46.813113935

     order_weight     sla_max_delivery_time_brt
766      9.527616 2024-04-02 02:39:46.813113935
2024-04-02 01:39:46.813113935
tem rota aberta
dist order to order é  3.3956451263599137 hub em questão 12
dist order to hub é  2.2426719622409563 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 279
768
     order_id  order_latitude  order_longitude                ordered_at_brt  \
767       768      -23.649438       -46.637651 2024-04-02 01:41:26.563909008

     order_weight     sla_max_delivery_time_brt
767      7.002409 2024-04-02 03:41:26.563909008
2024-04-02 01:41:26.563909008
tem rota aberta
dist order to order é  3.07172132157438 hub em questão 10
dist order to hub é  3.1477660267245917 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 280
769
     order_id  order_latitude  order_longitude                ordered_at_brt  \
768       769      -23.641854       -46.719714 2024-04-02 01:44:36.486779654

     order_weight     sla_max_delivery_time_brt
768     13.728624 2024-04-02 02:44:36.486779654

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-02 01:44:36.486779654
tem rota aberta
dist order to order é  5.172591969040795 hub em questão 10
dist order to hub é  2.055528046586438 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 10
passou aqui1
passou aqui5
route_id 282
caiu aqui tb
770
     order_id  order_latitude  order_longitude                ordered_at_brt  \
769       770      -23.598938       -46.616667 2024-04-02 01:46:01.375767767

     order_weight     sla_max_delivery_time_brt
769      7.656182 2024-04-02 04:46:01.375767767
2024-04-02 01:46:01.375767767
tem rota aberta
dist order to order é  4.112040141003417 hub em questão 3
dist order to hub é  2.050332493064502 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 3
passou aqui1
passou aqui5
route_id 283
caiu aqui tb
771
     order_id  order_latitude  order_longitude                ordered_at_brt  \
770       771      -23.622279       -46.633022 2024-04-02 01:49:09.698629631

     order_weight     sla_max_delivery_time_brt
770       3.57303 2024-04-02 03:49:09.698629631
2024-04-02 01:49:09.698629631
tem rota aberta
dist order to order é  2.968029640073918 hub em questão 10
dist order to hub é  1.7199941192086654 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 280
772
     order_id  order_latitude  order_longitude                ordered_at_brt  \
771       772       -23.65251       -46.740845 2024-04-02 01:51:32.492901702

     order_weight     sla_max_delivery_time_brt
771      7.893168 2024-04-02 03:51:32.492901702
2024-04-02 01:51:32.492901702
tem rota aberta
dist order to order é  2.4569564820819596 hub em questão 9
dist order to hub é  3.8428079479374517 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 282
773
     order_id  order_latitude  order_longitude                ordered_at_brt  \
772       773      -23.645769       -46.755565 2024-04-02 01:54:33.020372893

     order_weight     sla_max_delivery_time_brt
772      2.497033 2024-04-02 03:54:33.020372893
2024-04-02 01:54:33.020372893
tem rota aberta
dist order to order é  1.6762612088950604 hub em questão 9
dist order to hub é  5.392375972241266 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 282
774
     order_id  order_latitude  order_longitude                ordered_at_brt  \
773       774      -23.644957       -46.641198 2024-04-02 01:55:35.623077006

     order_weight     sla_max_delivery_time_brt
773     10.073649 2024-04-02 03:55:35.623077006
2024-04-02 01:55:35.623077006
tem rota aberta
dist order to order é  4.776437136732011 hub em questão 12
dist order to hub é  3.278385432825004 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 279
775
     order_id  order_latitude  order_longitude                ordered_at_brt  \
774       775      -23.656874       -46.613845 2024-04-02 01:57:40.839801645

     order_weight     sla_max_delivery_time_brt
774       6.03392 2024-04-02 02:57:40.839801645
2024-04-02 01:57:40.839801645
tem rota aberta
dist order to order é  1.714681017615124 hub em questão 12
dist order to hub é  3.4942033726433546 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 279
776
     order_id  order_latitude  order_longitude                ordered_at_brt  \
775       776      -23.584125       -46.617584 2024-04-02 01:58:04.623815290

     order_weight     sla_max_delivery_time_brt
775      5.748271 2024-04-02 04:58:04.623815290

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-02 01:58:04.623815290
tem rota aberta
dist order to order é  1.6498007339959588 hub em questão 8
dist order to hub é  2.6709817837886995 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 283
777
     order_id  order_latitude  order_longitude                ordered_at_brt  \
776       777      -23.745837       -46.716062 2024-04-02 01:58:51.224913557

     order_weight     sla_max_delivery_time_brt
776       7.84985 2024-04-02 03:58:51.224913557
2024-04-02 01:58:51.224913557
tem rota aberta
dist order to order é  10.679874783353007 hub em questão 9
dist order to hub é  9.693798250217235 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 282
778
     order_id  order_latitude  order_longitude                ordered_at_brt  \
777       778        -23.7203       -46.665363 2024-04-02 01:59:13.961626621

     order_weight     sla_max_delivery_time_brt
777      6.649219 2024-04-02 03:59:13.961626621
2024-04-02 01:59:13.961626621
tem rota aberta
dist order to order é  14.37740171862242 hub em questão 8
dist order to hub é  3.897323110246078 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 8
passou aqui1
passou aqui5
route_id 284
caiu aqui tb
779
     order_id  order_latitude  order_longitude                ordered_at_brt  \
778       779      -23.570343       -46.614683 2024-04-02 02:00:17.000700712

     order_weight     sla_max_delivery_time_brt
778       0.93908 2024-04-02 03:00:17.000700712
2024-04-02 02:00:17.000700712
tem rota aberta
dist order to order é  1.560646806113878 hub em questão 8
dist order to hub é  4.039687498911817 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 283
780
     order_id  order_latitude  order_longitude                ordered_at_brt  \
779       780      -23.621543         -46.7248 2024-04-02 02:00:50.157344384

     order_weight     sla_max_delivery_time_brt
779      0.276932 2024-04-02 03:00:50.157344384
2024-04-02 02:00:50.157344384
tem rota aberta
dist order to order é  11.30043477931845 hub em questão 8
dist order to hub é  4.077745396017784 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 8
passou aqui1
passou aqui5
route_id 285
caiu aqui tb
781
     order_id  order_latitude  order_longitude                ordered_at_brt  \
780       781      -23.618693       -46.643749 2024-04-02 02:01:52.848865683

     order_weight     sla_max_delivery_time_brt
780      6.013892 2024-04-02 04:01:52.848865683
2024-04-02 02:01:52.848865683
tem rota aberta
dist order to order é  3.5268918706319132 hub em questão 8
dist order to hub é  1.0981681477078036 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 8
passou aqui1
passou aqui5
route_id 286
caiu aqui tb
782

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
781       782      -23.592316       -46.637346 2024-04-02 02:09:16.586418075

     order_weight     sla_max_delivery_time_brt
781       7.65004 2024-04-02 03:09:16.586418075
2024-04-02 02:09:16.586418075
tem rota aberta
dist order to order é  2.21028477126284 hub em questão 8
dist order to hub é  0.9175139475351022 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 283
783
     order_id  order_latitude  order_longitude                ordered_at_brt  \
782       783      -23.751143       -46.601825 2024-04-02 02:10:02.922280623

     order_weight     sla_max_delivery_time_brt
782      8.645164 2024-04-02 03:10:02.922280623
2024-04-02 02:10:02.922280623
tem rota aberta
dist order to order é  7.3205758511337455 hub em questão 1
dist order to hub é  3.8717630421220988 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 1
passou aqui1
passou aqui5
route_id 287
caiu aqui tb
784
     order_id  order_latitude  order_longitude                ordered_at_brt  \
783       784      -23.578269       -46.770707 2024-04-02 02:18:08.326732847

     order_weight     sla_max_delivery_time_brt
783      6.192346 2024-04-02 04:18:08.326732847
2024-04-02 02:18:08.326732847
tem rota aberta
dist order to order é  6.710805794069394 hub em questão 9
dist order to hub é  2.4242276539910983 hub em questão 11
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 11
hub_order 9
passou aqui1
passou aqui5
route_id 288
caiu aqui tb
785
     order_id  order_latitude  order_longitude                ordered_at_brt  \
784       785      -23.708549       -46.640763 2024-04-02 02:20:09.699865281

     order_weight     sla_max_delivery_time_brt
784      4.482927 2024-04-02 05:20:09.699865281
2024-04-02 02:20:09.699865281
tem rota aberta
dist order to order é  2.8248179208969884 hub em questão 1
dist order to hub é  1.3764551506352056 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 284
786
     order_id  order_latitude  order_longitude                ordered_at_brt  \
785       786      -23.699362       -46.547107 2024-04-02 02:21:06.117777594

     order_weight     sla_max_delivery_time_brt
785      7.319049 2024-04-02 04:21:06.117777594
2024-04-02 02:21:06.117777594
tem rota aberta
dist order to order é  8.011171334298608 hub em questão 6
dist order to hub é  4.141972651971437 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 6
passou aqui1
rota em aberto, route_id:  287
rota_escolhida: 287
orders no hub: 1
passou aqui3
passou aqui4
787
     order_id  order_latitude  order_longitude                ordered_at_brt  \
786       787      -23.598413       -46.679073 2024-04-02 02:24:59.914318413

     order_weight     sla_max_delivery_time_brt
786      4.447595 2024-04-02 04:24:59.914318413
2024-04-02 02:24:59.914318413
tem rota aberta
dist order to order é  4.247252307234197 hub em questão 10
dist order to hub é  2.7404816725243566 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 286
788
     order_id  order_latitude  order_longitude                ordered_at_brt  \
787       788      -23.708011       -46.663825 2024-04-02 02:26:55.893969118

     order_weight     sla_max_delivery_time_brt
787      7.062867 2024-04-02 04:26:55.893969118
2024-04-02 02:26:55.893969118
tem rota aberta
dist order to order é  1.3754252782992618 hub em questão 1
dist order to hub é  3.6829848102424334 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 284
789
     order_id  order_latitude  order_longitude                ordered_at_brt  \
788       789      -23.623679       -46.600313 2024-04-02 02:27:30.741552329

     order_weight     sla_max_delivery_time_brt
788      2.394029 2024-04-02 05:27:30.741552329

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-02 02:27:30.741552329
tem rota aberta
dist order to order é  4.4597384872271855 hub em questão 10
dist order to hub é  1.193167301881315 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 10
passou aqui1
passou aqui5
route_id 289
caiu aqui tb
790
     order_id  order_latitude  order_longitude                ordered_at_brt  \
789       790      -23.578859        -46.68617 2024-04-02 02:30:39.662294826

     order_weight     sla_max_delivery_time_brt
789      6.006907 2024-04-02 03:30:39.662294826
2024-04-02 02:30:39.662294826
tem rota aberta
dist order to order é  2.291457593103456 hub em questão 10
dist order to hub é  1.63758306446734 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 286
791
     order_id  order_latitude  order_longitude                ordered_at_brt  \
790       791      -23.682705       -46.590165 2024-04-02 02:31:47.736798537

     order_weight     sla_max_delivery_time_brt
790      1.298795 2024-04-02 04:31:47.736798537
2024-04-02 02:31:47.736798537
tem rota aberta
dist order to order é  4.75956526668589 hub em questão 6
dist order to hub é  2.022258491970791 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 6
passou aqui1
passou aqui5
route_id 290
caiu aqui tb
792
     order_id  order_latitude  order_longitude                ordered_at_brt  \
791       792      -23.679679       -46.620986 2024-04-02 02:32:40.825499747

     order_weight     sla_max_delivery_time_brt
791     12.578693 2024-04-02 04:32:40.825499747
2024-04-02 02:32:40.825499747
tem rota aberta
dist order to order é  3.156548811323489 hub em questão 12
dist order to hub é  3.6498151352223207 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 290
793
     order_id  order_latitude  order_longitude                ordered_at_brt  \
792       793      -23.616624       -46.726716 2024-04-02 02:33:28.932418564

     order_weight     sla_max_delivery_time_brt
792      5.597624 2024-04-02 05:33:28.932418564
2024-04-02 02:33:28.932418564
tem rota aberta
dist order to order é  6.187308419994222 hub em questão 11
dist order to hub é  4.645127466428949 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 11 2
route_id 288
794
     order_id  order_latitude  order_longitude                ordered_at_brt  \
793       794      -23.605409       -46.642983 2024-04-02 02:35:52.361293730

     order_weight     sla_max_delivery_time_brt
793      9.895953 2024-04-02 04:35:52.361293730
2024-04-02 02:35:52.361293730
tem rota aberta
dist order to order é  4.798623486756384 hub em questão 7
dist order to hub é  0.8369761357883204 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 7
passou aqui1
passou aqui5
route_id 291
caiu aqui tb
795
     order_id  order_latitude  order_longitude                ordered_at_brt  \
794       795      -23.633139       -46.720962 2024-04-02 02:36:29.904890578

     order_weight     sla_max_delivery_time_brt
794      5.590975 2024-04-02 05:36:29.904890578
2024-04-02 02:36:29.904890578
tem rota aberta
dist order to order é  1.927712370502269 hub em questão 11
dist order to hub é  2.8064555910530706 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 11 2
route_id 288
796
     order_id  order_latitude  order_longitude                ordered_at_brt  \
795       796      -23.729294       -46.600385 2024-04-02 02:39:48.109963900

     order_weight     sla_max_delivery_time_brt
795      6.899555 2024-04-02 05:39:48.109963900
2024-04-02 02:39:48.109963900
tem rota aberta
dist order to order é  2.433955221299041 hub em questão 6
dist order to hub é  2.508103606219801 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 287
797
     order_id  order_latitude  order_longitude                ordered_at_brt  \
796       797      -23.569715       -46.732047 2024-04-02 02:40:30.106027604

     order_weight     sla_max_delivery_time_brt
796      7.318647 2024-04-02 04:40:30.106027604
2024-04-02 02:40:30.106027604
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.053298220489315 hub em questão 11
dist order to hub é  3.2675814596880697 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 11 2
route_id 288
798
     order_id  order_latitude  order_longitude                ordered_at_brt  \
797       798      -23.619101         -46.7386 2024-04-02 02:42:04.369471241

     order_weight     sla_max_delivery_time_brt
797      4.588498 2024-04-02 03:42:04.369471241
2024-04-02 02:42:04.369471241
tem rota aberta
dist order to order é  9.860260029360193 hub em questão 8
dist order to hub é  5.172032923982313 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 8
passou aqui1
passou aqui5
route_id 292
caiu aqui tb
799
     order_id  order_latitude  order_longitude                ordered_at_brt  \
798       799      -23.768069       -46.704878 2024-04-02 02:43:24.682750766

     order_weight     sla_max_delivery_time_brt
798      5.583413 2024-04-02 03:43:24.682750766
2024-04-02 02:43:24.682750766
tem rota aberta
dist order to order é  13.020414213380125 hub em questão 12
dist order to hub é  9.96014733405422 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 12
passou aqui1
passou aqui5
route_id 293
caiu aqui tb
800
     order_id  order_latitude  order_longitude                ordered_at_brt  \
799       800      -23.695215       -46.688166 2024-04-02 02:47:16.700660407

     order_weight     sla_max_delivery_time_brt
799      5.835251 2024-04-02 03:47:16.700660407
2024-04-02 02:47:16.700660407
tem rota aberta
dist order to order é  7.055506553315467 hub em questão 12
dist order to hub é  4.1587625457326665 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
passou aqui5
route_id 294
caiu aqui tb
801
     order_id  order_latitude  order_longitude                ordered_at_brt  \
800       801      -23.703227       -46.582266 2024-04-02 02:51:39.826182106

     order_weight     sla_max_delivery_time_brt
800      8.867559 2024-04-02 05:51:39.826182106
2024-04-02 02:51:39.826182106
tem rota aberta
dist order to order é  2.4195527254514215 hub em questão 12
dist order to hub é  2.5544659404741448 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 290
802
     order_id  order_latitude  order_longitude                ordered_at_brt  \
801       802       -23.68911       -46.648926 2024-04-02 02:52:04.283641952

     order_weight     sla_max_delivery_time_brt
801      4.676758 2024-04-02 03:52:04.283641952
2024-04-02 02:52:04.283641952
tem rota aberta
dist order to order é  3.032176446139326 hub em questão 12
dist order to hub é  2.001603780710562 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 290
803
     order_id  order_latitude  order_longitude                ordered_at_brt  \
802       803      -23.637423       -46.633463 2024-04-02 02:53:49.921654538

     order_weight     sla_max_delivery_time_brt
802      8.091897 2024-04-02 05:53:49.921654538
2024-04-02 02:53:49.921654538
tem rota aberta
dist order to order é  3.6895158615922736 hub em questão 8
dist order to hub é  2.1733653495890928 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 291
804
     order_id  order_latitude  order_longitude                ordered_at_brt  \
803       804      -23.685987       -46.594268 2024-04-02 02:58:24.097023823

     order_weight     sla_max_delivery_time_brt
803      8.956781 2024-04-02 03:58:24.097023823
2024-04-02 02:58:24.097023823
tem rota aberta
dist order to order é  6.715365623336369 hub em questão 8
dist order to hub é  2.571794952990559 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 8
passou aqui1
passou aqui5
route_id 295
caiu aqui tb
805
     order_id  order_latitude  order_longitude                ordered_at_brt  \
804       805      -23.588978       -46.682903 2024-04-02 02:59:34.993287982

     order_weight     sla_max_delivery_time_brt
804      4.811229 2024-04-02 04:59:34.993287982
2024-04-02 02:59:34.993287982
tem rota aberta
dist order to order é  4.459240422031944 hub em questão 8
dist order to hub é  2.6191849076985876 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 291
806
     order_id  order_latitude  order_longitude                ordered_at_brt  \
805       806      -23.594788       -46.676929 2024-04-02 03:04:40.916426156

     order_weight     sla_max_delivery_time_brt
805       7.28735 2024-04-02 05:04:40.916426156
2024-04-02 03:04:40.916426156
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  0.8877219854093634 hub em questão 8
dist order to hub é  2.8992580570141704 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 291
807
     order_id  order_latitude  order_longitude                ordered_at_brt  \
806       807      -23.646513       -46.690385 2024-04-02 03:05:20.168847017

     order_weight     sla_max_delivery_time_brt
806      8.783536 2024-04-02 05:05:20.168847017
2024-04-02 03:05:20.168847017
tem rota aberta
dist order to order é  5.420125651726953 hub em questão 5
dist order to hub é  1.4510559038781208 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
rota em aberto, route_id:  292
rota_escolhida: 292
orders no hub: 1
passou aqui3
passou aqui4
808
     order_id  order_latitude  order_longitude                ordered_at_brt  \
807       808      -23.702887       -46.608768 2024-04-02 03:07:12.802770932

     order_weight     sla_max_delivery_time_brt
807      8.643385 2024-04-02 05:07:12.802770932
2024-04-02 03:07:12.802770932
tem rota aberta
dist order to order é  2.3897680777101074 hub em questão 12
dist order to hub é  2.239069378083323 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 295
809
     order_id  order_latitude  order_longitude                ordered_at_brt  \
808       809      -23.650256       -46.566349 2024-04-02 03:09:30.458571963

     order_weight     sla_max_delivery_time_brt
808      7.945148 2024-04-02 06:09:30.458571963
2024-04-02 03:09:30.458571963
tem rota aberta
dist order to order é  4.885691843459816 hub em questão 12
dist order to hub é  2.34667660629243 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 12
passou aqui1
rota em aberto, route_id:  295
rota_escolhida: 295
orders no hub: 2
passou aqui3
passou aqui4
810
     order_id  order_latitude  order_longitude                ordered_at_brt  \
809       810      -23.629887       -46.635076 2024-04-02 03:10:01.543042977

     order_weight     sla_max_delivery_time_brt
809     11.765687 2024-04-02 05:10:01.543042977
2024-04-02 03:10:01.543042977
tem rota aberta
dist order to order é  5.929685763252349 hub em questão 9
dist order to hub é  1.951104331424977 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 9
passou aqui1
passou aqui5
route_id 296
caiu aqui tb
811
     order_id  order_latitude  order_longitude                ordered_at_brt  \
810       811      -23.592102       -46.679177 2024-04-02 03:10:03.206622620

     order_weight     sla_max_delivery_time_brt
810      4.113542 2024-04-02 04:10:03.206622620
2024-04-02 03:10:03.206622620
tem rota aberta
dist order to order é  6.151614730914763 hub em questão 14
dist order to hub é  3.1317320203823162 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 14
passou aqui1
passou aqui5
route_id 297
caiu aqui tb
812
     order_id  order_latitude  order_longitude                ordered_at_brt  \
811       812       -23.67344       -46.674031 2024-04-02 03:11:07.897989831

     order_weight     sla_max_delivery_time_brt
811     12.997617 2024-04-02 04:11:07.897989831
2024-04-02 03:11:07.897989831
tem rota aberta
dist order to order é  2.816790357728237 hub em questão 5
dist order to hub é  1.8504619596787109 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 294
813
     order_id  order_latitude  order_longitude                ordered_at_brt  \
812       813      -23.646239       -46.703628 2024-04-02 03:16:42.508834569

     order_weight     sla_max_delivery_time_brt
812      4.003274 2024-04-02 06:16:42.508834569
2024-04-02 03:16:42.508834569
tem rota aberta
dist order to order é  4.270275039706622 hub em questão 5
dist order to hub é  0.683539943836205 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 298
caiu aqui tb
814
     order_id  order_latitude  order_longitude                ordered_at_brt  \
813       814      -23.700062       -46.611456 2024-04-02 03:17:32.922520154

     order_weight     sla_max_delivery_time_brt
813      5.029928 2024-04-02 05:17:32.922520154
2024-04-02 03:17:32.922520154
tem rota aberta
dist order to order é  0.41656938071442395 hub em questão 12
dist order to hub é  2.190102562269155 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 295
815
     order_id  order_latitude  order_longitude                ordered_at_brt  \
814       815      -23.673274       -46.701159 2024-04-02 03:20:34.478453871

     order_weight     sla_max_delivery_time_brt
814      8.909472 2024-04-02 05:20:34.478453871

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-02 03:20:34.478453871
tem rota aberta
dist order to order é  3.01668445892109 hub em questão 9
dist order to hub é  2.333166876792451 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 298
816
     order_id  order_latitude  order_longitude                ordered_at_brt  \
815       816      -23.591808       -46.660744 2024-04-02 03:20:57.524732619

     order_weight     sla_max_delivery_time_brt
815     13.775133 2024-04-02 05:20:57.524732619
2024-04-02 03:20:57.524732619
tem rota aberta
dist order to order é  1.8785641777706201 hub em questão 4
dist order to hub é  2.6345251576635587 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 297
817
     order_id  order_latitude  order_longitude                ordered_at_brt  \
816       817      -23.570415       -46.706461 2024-04-02 03:21:47.742173363

     order_weight     sla_max_delivery_time_brt
816      4.291928 2024-04-02 05:21:47.742173363
2024-04-02 03:21:47.742173363
tem rota aberta
dist order to order é  3.68057883994024 hub em questão 4
dist order to hub é  0.6639513801262813 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 4
passou aqui1
rota em aberto, route_id:  297
rota_escolhida: 297
orders no hub: 2
passou aqui3
passou aqui4
818
     order_id  order_latitude  order_longitude                ordered_at_brt  \
817       818      -23.667474       -46.742986 2024-04-02 03:22:06.484183613

     order_weight     sla_max_delivery_time_brt
817      2.453298 2024-04-02 05:22:06.484183613
2024-04-02 03:22:06.484183613
tem rota aberta
dist order to order é  4.308197364766155 hub em questão 9
dist order to hub é  4.394302684120449 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 298
819
     order_id  order_latitude  order_longitude                ordered_at_brt  \
818       819      -23.663432       -46.775011 2024-04-02 03:24:37.864047422

     order_weight     sla_max_delivery_time_brt
818      7.064121 2024-04-02 05:24:37.864047422
2024-04-02 03:24:37.864047422
tem rota aberta
dist order to order é  3.2923370480082497 hub em questão 9
dist order to hub é  7.425017545720841 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 298
820
     order_id  order_latitude  order_longitude                ordered_at_brt  \
819       820      -23.688258       -46.692511 2024-04-02 03:27:02.064152518

     order_weight     sla_max_delivery_time_brt
819      5.491617 2024-04-02 05:27:02.064152518
2024-04-02 03:27:02.064152518
tem rota aberta
dist order to order é  8.737668607257909 hub em questão 14
dist order to hub é  4.12940210919887 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 14
passou aqui1
passou aqui5
route_id 299
caiu aqui tb
821
     order_id  order_latitude  order_longitude                ordered_at_brt  \
820       821      -23.726705       -46.637109 2024-04-02 03:29:22.025832199

     order_weight     sla_max_delivery_time_brt
820     12.948291 2024-04-02 05:29:22.025832199
2024-04-02 03:29:22.025832199
tem rota aberta
dist order to order é  7.077587929683361 hub em questão 5
dist order to hub é  1.8175024401453426 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 5
passou aqui1
passou aqui5
route_id 300
caiu aqui tb
822
     order_id  order_latitude  order_longitude                ordered_at_brt  \
821       822      -23.631587       -46.663904 2024-04-02 03:29:57.092280329

     order_weight     sla_max_delivery_time_brt
821      8.182453 2024-04-02 04:29:57.092280329
2024-04-02 03:29:57.092280329
tem rota aberta
dist order to order é  2.9428083127092886 hub em questão 14
dist order to hub é  1.7777166853622444 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 296
823
     order_id  order_latitude  order_longitude                ordered_at_brt  \
822       823      -23.626591       -46.659192 2024-04-02 03:32:18.551329065

     order_weight     sla_max_delivery_time_brt
822      4.905617 2024-04-02 06:32:18.551329065
2024-04-02 03:32:18.551329065
tem rota aberta
dist order to order é  0.7342344597501896 hub em questão 14
dist order to hub é  1.0563580461037125 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 296
824
     order_id  order_latitude  order_longitude                ordered_at_brt  \
823       824      -23.620003       -46.701582 2024-04-02 03:32:49.494675655

     order_weight     sla_max_delivery_time_brt
823       9.50052 2024-04-02 06:32:49.494675655
2024-04-02 03:32:49.494675655
tem rota aberta
dist order to order é  3.851791749438646 hub em questão 4
dist order to hub é  3.602286382959943 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 297
825
     order_id  order_latitude  order_longitude                ordered_at_brt  \
824       825      -23.648919       -46.694597 2024-04-02 03:33:55.827698591

     order_weight     sla_max_delivery_time_brt
824      9.134835 2024-04-02 05:33:55.827698591
2024-04-02 03:33:55.827698591
tem rota aberta
dist order to order é  3.6727639835166768 hub em questão 14
dist order to hub é  0.9487943699627124 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 14
passou aqui1
passou aqui5
route_id 301
caiu aqui tb
826
     order_id  order_latitude  order_longitude                ordered_at_brt  \
825       826      -23.623765       -46.701398 2024-04-02 03:34:51.638631805

     order_weight     sla_max_delivery_time_brt
825      2.448546 2024-04-02 05:34:51.638631805
2024-04-02 03:34:51.638631805
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.8815213909962543 hub em questão 9
dist order to hub é  3.18541441743331 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 301
827
     order_id  order_latitude  order_longitude                ordered_at_brt  \
826       827      -23.641956       -46.637451 2024-04-02 03:35:44.316526828

     order_weight     sla_max_delivery_time_brt
826     15.457261 2024-04-02 06:35:44.316526828
2024-04-02 03:35:44.316526828
tem rota aberta
dist order to order é  1.363642763878933 hub em questão 14
dist order to hub é  2.8065589560014184 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 296
828
     order_id  order_latitude  order_longitude                ordered_at_brt  \
827       828      -23.588002        -46.54563 2024-04-02 03:35:51.442561811

     order_weight     sla_max_delivery_time_brt
827       8.68004 2024-04-02 05:35:51.442561811
2024-04-02 03:35:51.442561811
tem rota aberta
dist order to order é  16.361850618062235 hub em questão 9
dist order to hub é  4.314879412163311 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 9
passou aqui1
passou aqui5
route_id 302
caiu aqui tb
829
     order_id  order_latitude  order_longitude                ordered_at_brt  \
828       829      -23.631497       -46.654831 2024-04-02 03:37:51.288067628

     order_weight     sla_max_delivery_time_brt
828      6.944624 2024-04-02 06:37:51.288067628
2024-04-02 03:37:51.288067628
tem rota aberta
dist order to order é  4.490080775130469 hub em questão 9
dist order to hub é  1.4883646478942112 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 9
passou aqui1
passou aqui5
route_id 303
caiu aqui tb
830

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
829       830      -23.577659       -46.716477 2024-04-02 03:40:18.727724757

     order_weight     sla_max_delivery_time_brt
829      6.616443 2024-04-02 04:40:18.727724757
2024-04-02 03:40:18.727724757
tem rota aberta
dist order to order é  5.352063974476541 hub em questão 9
dist order to hub é  1.8129829676332487 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 9
passou aqui1
passou aqui5
route_id 304
caiu aqui tb
831
     order_id  order_latitude  order_longitude                ordered_at_brt  \
830       831      -23.596607       -46.584382 2024-04-02 03:42:12.830074981

     order_weight     sla_max_delivery_time_brt
830     12.753957 2024-04-02 05:42:12.830074981
2024-04-02 03:42:12.830074981
tem rota aberta
dist order to order é  4.0630918499763515 hub em questão 3
dist order to hub é  2.2768665522652842 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 302
832
     order_id  order_latitude  order_longitude                ordered_at_brt  \
831       832      -23.632275       -46.697941 2024-04-02 03:44:18.231636201

     order_weight     sla_max_delivery_time_brt
831      8.018079 2024-04-02 06:44:18.231636201
2024-04-02 03:44:18.231636201
tem rota aberta
dist order to order é  1.0096460884428815 hub em questão 9
dist order to hub é  2.2957111929078913 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 301

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

833
     order_id  order_latitude  order_longitude                ordered_at_brt  \
832       833       -23.71234       -46.620136 2024-04-02 03:44:40.582614451

     order_weight     sla_max_delivery_time_brt
832      7.696886 2024-04-02 04:44:40.582614451
2024-04-02 03:44:40.582614451
tem rota aberta
dist order to order é  2.3530531028284645 hub em questão 1
dist order to hub é  0.8018320970056814 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 300
834
     order_id  order_latitude  order_longitude                ordered_at_brt  \
833       834      -23.624362       -46.670146 2024-04-02 03:45:00.006812420

     order_weight     sla_max_delivery_time_brt
833      1.588507 2024-04-02 04:45:00.006812420
2024-04-02 03:45:00.006812420
tem rota aberta
dist order to order é  1.75023822897481 hub em questão 10
dist order to hub é  1.4324224994649157 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 303
835
     order_id  order_latitude  order_longitude                ordered_at_brt  \
834       835      -23.634187       -46.643959 2024-04-02 03:46:26.635639438

     order_weight     sla_max_delivery_time_brt
834      5.089292 2024-04-02 05:46:26.635639438
2024-04-02 03:46:26.635639438
tem rota aberta
dist order to order é  1.1473037452598824 hub em questão 10
dist order to hub é  2.085501309942878 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 303
836

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
835       836      -23.554294        -46.47638 2024-04-02 03:50:36.488467610

     order_weight     sla_max_delivery_time_brt
835      1.981767 2024-04-02 05:50:36.488467610
2024-04-02 03:50:36.488467610
tem rota aberta
dist order to order é  7.991348704463209 hub em questão 3
dist order to hub é  11.824000765084696 hub em questão 2
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 302
837
     order_id  order_latitude  order_longitude                ordered_at_brt  \
836       837      -23.613108       -46.685389 2024-04-02 03:51:00.882531856

     order_weight     sla_max_delivery_time_brt
836       7.62657 2024-04-02 05:51:00.882531856
2024-04-02 03:51:00.882531856
tem rota aberta
dist order to order é  1.9944159251920583 hub em questão 10
dist order to hub é  2.6202531352960006 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 303
838
     order_id  order_latitude  order_longitude                ordered_at_brt  \
837       838      -23.706789       -46.677347 2024-04-02 03:52:15.457448250

     order_weight     sla_max_delivery_time_brt
837      8.599876 2024-04-02 04:52:15.457448250
2024-04-02 03:52:15.457448250
tem rota aberta
dist order to order é  2.574790554854034 hub em questão 5
dist order to hub é  4.414707413659225 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 299
839
     order_id  order_latitude  order_longitude                ordered_at_brt  \
838       839      -23.689869       -46.629251 2024-04-02 03:53:22.687156892

     order_weight     sla_max_delivery_time_brt
838          0.01 2024-04-02 05:53:22.687156892
2024-04-02 03:53:22.687156892
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.6655303375211767 hub em questão 1
dist order to hub é  2.5357798979079194 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 300
840
     order_id  order_latitude  order_longitude                ordered_at_brt  \
839       840      -23.602028        -46.64911 2024-04-02 03:54:45.215980474

     order_weight     sla_max_delivery_time_brt
839      6.607608 2024-04-02 04:54:45.215980474
2024-04-02 03:54:45.215980474
tem rota aberta
dist order to order é  5.849981951625468 hub em questão 9
dist order to hub é  1.2739228484609744 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 9
passou aqui1
passou aqui5
route_id 305
caiu aqui tb
841
     order_id  order_latitude  order_longitude                ordered_at_brt  \
840       841      -23.659881       -46.668316 2024-04-02 03:55:06.354405603

     order_weight     sla_max_delivery_time_brt
840      1.719052 2024-04-02 04:55:06.354405603
2024-04-02 03:55:06.354405603
tem rota aberta
dist order to order é  2.9412210065865296 hub em questão 9
dist order to hub é  1.87067280604825 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 301
842
     order_id  order_latitude  order_longitude                ordered_at_brt  \
841       842       -23.71037       -46.682433 2024-04-02 03:55:56.660834326

     order_weight     sla_max_delivery_time_brt
841      8.493333 2024-04-02 05:55:56.660834326
2024-04-02 03:55:56.660834326
tem rota aberta
dist order to order é  0.6532322219373734 hub em questão 5
dist order to hub é  5.023297525696721 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 299
843
     order_id  order_latitude  order_longitude                ordered_at_brt  \
842       843      -23.625687       -46.618488 2024-04-02 03:56:33.098763940

     order_weight     sla_max_delivery_time_brt
842      8.231306 2024-04-02 04:56:33.098763940
2024-04-02 03:56:33.098763940
tem rota aberta
dist order to order é  4.081002939876023 hub em questão 8
dist order to hub é  0.20121036179500693 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 8
passou aqui1
passou aqui5
route_id 306
caiu aqui tb
844
     order_id  order_latitude  order_longitude                ordered_at_brt  \
843       844      -23.625543       -46.594144 2024-04-02 04:00:16.452703627

     order_weight     sla_max_delivery_time_brt
843      3.625089 2024-04-02 06:00:16.452703627
2024-04-02 04:00:16.452703627
tem rota aberta
dist order to order é  2.4801135291045333 hub em questão 14
dist order to hub é  1.8549303415564142 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 306
845
     order_id  order_latitude  order_longitude                ordered_at_brt  \
844       845      -23.656152       -46.695617 2024-04-02 04:03:29.784766349

     order_weight     sla_max_delivery_time_brt
844      7.030044 2024-04-02 06:03:29.784766349
2024-04-02 04:03:29.784766349
tem rota aberta
dist order to order é  7.659409000228884 hub em questão 8
dist order to hub é  0.8720764325976958 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 8
passou aqui1
passou aqui5
route_id 307
caiu aqui tb
846
     order_id  order_latitude  order_longitude                ordered_at_brt  \
845       846      -23.607146       -46.704834 2024-04-02 04:04:36.533568656

     order_weight     sla_max_delivery_time_brt
845      7.904767 2024-04-02 07:04:36.533568656
2024-04-02 04:04:36.533568656
tem rota aberta
dist order to order é  3.4868350020894288 hub em questão 4
dist order to hub é  4.002064367282911 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 304
847
     order_id  order_latitude  order_longitude                ordered_at_brt  \
846       847      -23.655437       -46.556517 2024-04-02 04:06:28.611769654

     order_weight     sla_max_delivery_time_brt
846       7.70314 2024-04-02 06:06:28.611769654
2024-04-02 04:06:28.611769654
tem rota aberta
dist order to order é  5.073424029835855 hub em questão 14
dist order to hub é  2.592720745243303 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 14
passou aqui1
passou aqui5
route_id 308
caiu aqui tb
848
     order_id  order_latitude  order_longitude                ordered_at_brt  \
847       848      -23.556985       -46.719271 2024-04-02 04:06:47.475593468

     order_weight     sla_max_delivery_time_brt
847     13.156015 2024-04-02 07:06:47.475593468
2024-04-02 04:06:47.475593468
tem rota aberta
dist order to order é  2.316415960957293 hub em questão 4
dist order to hub é  2.533678835217292 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 304
849
     order_id  order_latitude  order_longitude                ordered_at_brt  \
848       849      -23.705101       -46.612246 2024-04-02 04:08:12.982913906

     order_weight     sla_max_delivery_time_brt
848       8.05227 2024-04-02 06:08:12.982913906

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-02 04:08:12.982913906
tem rota aberta
dist order to order é  7.9184641308042325 hub em questão 12
dist order to hub é  1.810483459860467 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 12
passou aqui1
passou aqui5
route_id 309
caiu aqui tb
850
     order_id  order_latitude  order_longitude                ordered_at_brt  \
849       850      -23.604829       -46.626056 2024-04-02 04:08:55.261688408

     order_weight     sla_max_delivery_time_brt
849      2.989007 2024-04-02 06:08:55.261688408
2024-04-02 04:08:55.261688408
tem rota aberta
dist order to order é  2.3695512584037246 hub em questão 8
dist order to hub é  1.1856203584763558 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 305
851
     order_id  order_latitude  order_longitude                ordered_at_brt  \
850       851      -23.600676       -46.703161 2024-04-02 04:12:50.896420858

     order_weight     sla_max_delivery_time_brt
850      7.190033 2024-04-02 06:12:50.896420858
2024-04-02 04:12:50.896420858
tem rota aberta
dist order to order é  5.5095383327527925 hub em questão 8
dist order to hub é  3.2682682695655108 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 8
passou aqui1
passou aqui5
route_id 310
caiu aqui tb
852
     order_id  order_latitude  order_longitude                ordered_at_brt  \
851       852      -23.586882       -46.610038 2024-04-02 04:15:04.518577398

     order_weight     sla_max_delivery_time_brt
851      7.452189 2024-04-02 06:15:04.518577398
2024-04-02 04:15:04.518577398
tem rota aberta
dist order to order é  2.5781371586536235 hub em questão 8
dist order to hub é  3.114010252728919 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 305
853
     order_id  order_latitude  order_longitude                ordered_at_brt  \
852       853      -23.656488       -46.703174 2024-04-02 04:17:04.960879790

     order_weight     sla_max_delivery_time_brt
852      6.789162 2024-04-02 06:17:04.960879790
2024-04-02 04:17:04.960879790
tem rota aberta
dist order to order é  0.7705545944507595 hub em questão 9
dist order to hub é  0.45810498767152275 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 307
854
     order_id  order_latitude  order_longitude                ordered_at_brt  \
853       854      -23.670875        -46.70249 2024-04-02 04:17:20.950544332

     order_weight     sla_max_delivery_time_brt
853      6.271957 2024-04-02 05:17:20.950544332
2024-04-02 04:17:20.950544332
tem rota aberta
dist order to order é  1.601276921450615 hub em questão 9
dist order to hub é  2.0588209238509614 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 307
855
     order_id  order_latitude  order_longitude                ordered_at_brt  \
854       855      -23.563192        -46.71749 2024-04-02 04:18:37.269115691

     order_weight     sla_max_delivery_time_brt
854      9.950905 2024-04-02 05:18:37.269115691
2024-04-02 04:18:37.269115691
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.416479822239786 hub em questão 4
dist order to hub é  2.000279707222561 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 4
passou aqui1
rota em aberto, route_id:  310
rota_escolhida: 310
orders no hub: 1
passou aqui3
passou aqui4
856
     order_id  order_latitude  order_longitude                ordered_at_brt  \
855       856      -23.622897       -46.606299 2024-04-02 04:27:14.525666694

     order_weight     sla_max_delivery_time_brt
855     12.890332 2024-04-02 06:27:14.525666694
2024-04-02 04:27:14.525666694
tem rota aberta
dist order to order é  6.2294876871621305 hub em questão 12
dist order to hub é  0.5984197557962504 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 12
passou aqui1
passou aqui5
route_id 311
caiu aqui tb
857
     order_id  order_latitude  order_longitude                ordered_at_brt  \
856       857      -23.679482        -46.67048 2024-04-02 04:33:09.999449359

     order_weight     sla_max_delivery_time_brt
856     11.498341 2024-04-02 05:33:09.999449359
2024-04-02 04:33:09.999449359
tem rota aberta
dist order to order é  3.397403952948438 hub em questão 9
dist order to hub é  1.6864837970378252 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 307
858
     order_id  order_latitude  order_longitude                ordered_at_brt  \
857       858      -23.608608        -46.59375 2024-04-02 04:35:14.304900412

     order_weight     sla_max_delivery_time_brt
857      4.917028 2024-04-02 06:35:14.304900412
2024-04-02 04:35:14.304900412
tem rota aberta
dist order to order é  2.039367870338805 hub em questão 7
dist order to hub é  2.000177225810112 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 311

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

859
     order_id  order_latitude  order_longitude                ordered_at_brt  \
858       859      -23.570871        -46.68852 2024-04-02 04:35:34.050930564

     order_weight     sla_max_delivery_time_brt
858       5.04747 2024-04-02 06:35:34.050930564
2024-04-02 04:35:34.050930564
tem rota aberta
dist order to order é  3.0736950433776693 hub em questão 4
dist order to hub é  1.1756944548348616 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 310
860
     order_id  order_latitude  order_longitude                ordered_at_brt  \
859       860      -23.616906        -46.61728 2024-04-02 04:37:36.358382231

     order_weight     sla_max_delivery_time_brt
859      8.943549 2024-04-02 06:37:36.358382231
2024-04-02 04:37:36.358382231
tem rota aberta
dist order to order é  1.3020397326066675 hub em questão 7
dist order to hub é  0.48705969609686617 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 311
861
     order_id  order_latitude  order_longitude                ordered_at_brt  \
860       861      -23.686524       -46.577642 2024-04-02 04:39:16.430282862

     order_weight     sla_max_delivery_time_brt
860      7.900265 2024-04-02 05:39:16.430282862
2024-04-02 04:39:16.430282862
tem rota aberta
dist order to order é  7.653457731814491 hub em questão 7
dist order to hub é  1.9737642506101725 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 7
passou aqui1
passou aqui5
route_id 312
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

862
     order_id  order_latitude  order_longitude                ordered_at_brt  \
861       862      -23.601254       -46.652313 2024-04-02 04:40:32.313980629

     order_weight     sla_max_delivery_time_brt
861     13.265431 2024-04-02 06:40:32.313980629
2024-04-02 04:40:32.313980629
tem rota aberta
dist order to order é  3.9712281515264274 hub em questão 7
dist order to hub é  1.591575040969459 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 7
passou aqui1
passou aqui5
route_id 313
caiu aqui tb
863
     order_id  order_latitude  order_longitude                ordered_at_brt  \
862       863      -23.727102       -46.704285 2024-04-02 04:41:39.355796126

     order_weight     sla_max_delivery_time_brt
862      8.689965 2024-04-02 07:41:39.355796126
2024-04-02 04:41:39.355796126
tem rota aberta
dist order to order é  13.660453791171664 hub em questão 12
dist order to hub é  7.837318348783616 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
passou aqui5
route_id 314
caiu aqui tb
864
     order_id  order_latitude  order_longitude                ordered_at_brt  \
863       864      -23.611384       -46.665141 2024-04-02 04:43:29.091810376

     order_weight     sla_max_delivery_time_brt
863      4.511151 2024-04-02 05:43:29.091810376
2024-04-02 04:43:29.091810376
tem rota aberta
dist order to order é  1.7254559840422576 hub em questão 8
dist order to hub é  0.7183961005843464 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 313
865
     order_id  order_latitude  order_longitude                ordered_at_brt  \
864       865      -23.601309       -46.585176 2024-04-02 04:47:16.722121792

     order_weight     sla_max_delivery_time_brt
864      2.598542 2024-04-02 05:47:16.722121792
2024-04-02 04:47:16.722121792
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.1924490408984425 hub em questão 7
dist order to hub é  1.8494579730226401 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 311
866
     order_id  order_latitude  order_longitude                ordered_at_brt  \
865       866      -23.661324       -46.611058 2024-04-02 04:50:03.616754585

     order_weight     sla_max_delivery_time_brt
865      7.624666 2024-04-02 06:50:03.616754585
2024-04-02 04:50:03.616754585
tem rota aberta
dist order to order é  4.408232344531351 hub em questão 12
dist order to hub é  3.526806631796644 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 312
867
     order_id  order_latitude  order_longitude                ordered_at_brt  \
866       867      -23.636369       -46.667312 2024-04-02 04:51:47.534258880

     order_weight     sla_max_delivery_time_brt
866     12.252985 2024-04-02 06:51:47.534258880
2024-04-02 04:51:47.534258880
tem rota aberta
dist order to order é  2.786957875511481 hub em questão 8
dist order to hub é  2.4127339353618558 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 313
868
     order_id  order_latitude  order_longitude                ordered_at_brt  \
867       868      -23.642711       -46.735231 2024-04-02 04:56:57.893940168

     order_weight     sla_max_delivery_time_brt
867      4.618851 2024-04-02 06:56:57.893940168
2024-04-02 04:56:57.893940168
tem rota aberta
dist order to order é  6.954392582229 hub em questão 8
dist order to hub é  3.442892382297337 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 8
passou aqui1
passou aqui5
route_id 315
caiu aqui tb
869
     order_id  order_latitude  order_longitude                ordered_at_brt  \
868       869      -23.677015       -46.612236 2024-04-02 04:57:05.925623661

     order_weight     sla_max_delivery_time_brt
868      7.051625 2024-04-02 07:57:05.925623661
2024-04-02 04:57:05.925623661
tem rota aberta
dist order to order é  1.7489181204117925 hub em questão 12
dist order to hub é  3.6642384117135465 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 312
870
     order_id  order_latitude  order_longitude                ordered_at_brt  \
869       870      -23.693105       -46.566467 2024-04-02 05:06:35.900714618

     order_weight     sla_max_delivery_time_brt
869      7.526246 2024-04-02 08:06:35.900714618

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-02 05:06:35.900714618
tem rota aberta
dist order to order é  1.3528683925590899 hub em questão 12
dist order to hub é  2.925412524132451 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 312
871
     order_id  order_latitude  order_longitude                ordered_at_brt  \
870       871      -23.664159       -46.565583 2024-04-02 05:06:42.434765384

     order_weight     sla_max_delivery_time_brt
870        5.1339 2024-04-02 07:06:42.434765384
2024-04-02 05:06:42.434765384
tem rota aberta
dist order to order é  10.81268488314588 hub em questão 8
dist order to hub é  1.308164112774939 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 8
passou aqui1
passou aqui5
route_id 316
caiu aqui tb
872
     order_id  order_latitude  order_longitude                ordered_at_brt  \
871       872      -23.681326       -46.626373 2024-04-02 05:07:09.136347309

     order_weight     sla_max_delivery_time_brt
871     10.237388 2024-04-02 07:07:09.136347309
2024-04-02 05:07:09.136347309
tem rota aberta
dist order to order é  6.478377717452237 hub em questão 12
dist order to hub é  3.1709832641006206 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
rota em aberto, route_id:  314
rota_escolhida: 314
orders no hub: 1
passou aqui3
passou aqui4
873
     order_id  order_latitude  order_longitude                ordered_at_brt  \
872       873      -23.574533       -46.657564 2024-04-02 05:08:15.074480308

     order_weight     sla_max_delivery_time_brt
872     10.791565 2024-04-02 06:08:15.074480308
2024-04-02 05:08:15.074480308
tem rota aberta
dist order to order é  3.019016042406522 hub em questão 8
dist order to hub é  3.58917072337223 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 313
874
     order_id  order_latitude  order_longitude                ordered_at_brt  \
873       874      -23.717989       -46.687319 2024-04-02 05:08:28.723125589

     order_weight     sla_max_delivery_time_brt
873      7.130839 2024-04-02 07:08:28.723125589
2024-04-02 05:08:28.723125589
tem rota aberta
dist order to order é  2.0025090873715885 hub em questão 5
dist order to hub é  6.00515730081118 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 314
875
     order_id  order_latitude  order_longitude                ordered_at_brt  \
874       875      -23.560265       -46.676643 2024-04-02 05:10:25.997919955

     order_weight     sla_max_delivery_time_brt
874      1.413221 2024-04-02 06:10:25.997919955
2024-04-02 05:10:25.997919955
tem rota aberta
dist order to order é  10.940041841043275 hub em questão 9
dist order to hub é  2.6881414291254995 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 9
passou aqui1
passou aqui5
route_id 317
caiu aqui tb
876
     order_id  order_latitude  order_longitude                ordered_at_brt  \
875       876      -23.661996         -46.7305 2024-04-02 05:10:31.899811956

     order_weight     sla_max_delivery_time_brt
875      5.558853 2024-04-02 06:10:31.899811956
2024-04-02 05:10:31.899811956
tem rota aberta
dist order to order é  2.1978267054384393 hub em questão 9
dist order to hub é  2.9874282908152585 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 315
877
     order_id  order_latitude  order_longitude                ordered_at_brt  \
876       877      -23.688777       -46.541285 2024-04-02 05:11:12.093432041

     order_weight     sla_max_delivery_time_brt
876      6.821551 2024-04-02 06:11:12.093432041
2024-04-02 05:11:12.093432041
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.689968107021473 hub em questão 12
dist order to hub é  4.297755914466083 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 316
878
     order_id  order_latitude  order_longitude                ordered_at_brt  \
877       878      -23.677438       -46.649361 2024-04-02 05:11:19.650895788

     order_weight     sla_max_delivery_time_brt
877      7.262734 2024-04-02 06:11:19.650895788
2024-04-02 05:11:19.650895788
tem rota aberta
dist order to order é  2.3805084383268023 hub em questão 5
dist order to hub é  0.8790075263893277 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 314
879
     order_id  order_latitude  order_longitude                ordered_at_brt  \
878       879      -23.702273       -46.528793 2024-04-02 05:13:45.543687027

     order_weight     sla_max_delivery_time_brt
878      6.926662 2024-04-02 06:13:45.543687027
2024-04-02 05:13:45.543687027
tem rota aberta
dist order to order é  1.9672712026967694 hub em questão 12
dist order to hub é  5.464611006035816 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 316
880
     order_id  order_latitude  order_longitude                ordered_at_brt  \
879       880      -23.751834       -46.651738 2024-04-02 05:15:58.023117462

     order_weight     sla_max_delivery_time_brt
879       7.36369 2024-04-02 06:15:58.023117462
2024-04-02 05:15:58.023117462
tem rota aberta
dist order to order é  12.809931953854639 hub em questão 9
dist order to hub é  4.982454223526004 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 9
passou aqui1
passou aqui5
route_id 318
caiu aqui tb
881
     order_id  order_latitude  order_longitude                ordered_at_brt  \
880       881      -23.609426       -46.728929 2024-04-02 05:16:55.113003680

     order_weight     sla_max_delivery_time_brt
880      4.851043 2024-04-02 08:16:55.113003680
2024-04-02 05:16:55.113003680
tem rota aberta
dist order to order é  3.7564600052053105 hub em questão 9
dist order to hub é  5.150020819219663 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 315
882
     order_id  order_latitude  order_longitude                ordered_at_brt  \
881       882      -23.657908       -46.554935 2024-04-02 05:17:20.132308151

     order_weight     sla_max_delivery_time_brt
881       6.88778 2024-04-02 07:17:20.132308151
2024-04-02 05:17:20.132308151
tem rota aberta
dist order to order é  1.2881956443410287 hub em questão 12
dist order to hub é  2.5873426340332824 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 316
883
     order_id  order_latitude  order_longitude                ordered_at_brt  \
882       883      -23.692148       -46.691004 2024-04-02 05:20:05.058493452

     order_weight     sla_max_delivery_time_brt
882      9.342035 2024-04-02 07:20:05.058493452
2024-04-02 05:20:05.058493452
tem rota aberta
dist order to order é  5.236236621311054 hub em questão 9
dist order to hub é  4.2017668928297365 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 315
884
     order_id  order_latitude  order_longitude                ordered_at_brt  \
883       884      -23.715517       -46.669908 2024-04-02 05:20:54.989328507

     order_weight     sla_max_delivery_time_brt
883      5.030209 2024-04-02 06:20:54.989328507
2024-04-02 05:20:54.989328507
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  4.44166508265163 hub em questão 1
dist order to hub é  4.27793283981856 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 318
885
     order_id  order_latitude  order_longitude                ordered_at_brt  \
884       885      -23.678367       -46.565585 2024-04-02 05:24:05.335187227

     order_weight     sla_max_delivery_time_brt
884      8.821194 2024-04-02 06:24:05.335187227
2024-04-02 05:24:05.335187227
tem rota aberta
dist order to order é  11.397099699016923 hub em questão 1
dist order to hub é  1.6076853075523698 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 1
passou aqui1
passou aqui5
route_id 319
caiu aqui tb
886
     order_id  order_latitude  order_longitude                ordered_at_brt  \
885       886        -23.7128       -46.575074 2024-04-02 05:25:25.643650566

     order_weight     sla_max_delivery_time_brt
885      8.671852 2024-04-02 08:25:25.643650566
2024-04-02 05:25:25.643650566
tem rota aberta
dist order to order é  3.9488572692398973 hub em questão 12
dist order to hub é  1.4154574842321919 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 12
passou aqui1
passou aqui5
route_id 320
caiu aqui tb
887
     order_id  order_latitude  order_longitude                ordered_at_brt  \
886       887      -23.585297       -46.749323 2024-04-02 05:26:55.145749632

     order_weight     sla_max_delivery_time_brt
886      9.992835 2024-04-02 07:26:55.145749632
2024-04-02 05:26:55.145749632
tem rota aberta
dist order to order é  7.912993355583872 hub em questão 4
dist order to hub é  3.3238238658160366 hub em questão 11
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 11
hub_order 4
passou aqui1
passou aqui5
route_id 321
caiu aqui tb
888
     order_id  order_latitude  order_longitude                ordered_at_brt  \
887       888      -23.745039        -46.64796 2024-04-02 05:26:58.614300583

     order_weight     sla_max_delivery_time_brt
887      6.110345 2024-04-02 06:26:58.614300583
2024-04-02 05:26:58.614300583
tem rota aberta
dist order to order é  0.8477173316085459 hub em questão 1
dist order to hub é  4.135381405544978 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 318
889
     order_id  order_latitude  order_longitude                ordered_at_brt  \
888       889      -23.698136        -46.70249 2024-04-02 05:29:02.631480803

     order_weight     sla_max_delivery_time_brt
888      1.360251 2024-04-02 06:29:02.631480803
2024-04-02 05:29:02.631480803
tem rota aberta
dist order to order é  3.839121594555875 hub em questão 1
dist order to hub é  5.089513797218958 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 318
890
     order_id  order_latitude  order_longitude                ordered_at_brt  \
889       890      -23.694376       -46.621056 2024-04-02 05:29:54.446692430

     order_weight     sla_max_delivery_time_brt
889       8.39416 2024-04-02 07:29:54.446692430
2024-04-02 05:29:54.446692430
tem rota aberta
dist order to order é  5.110220607389469 hub em questão 6
dist order to hub é  2.1510412483252734 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 6
passou aqui1
passou aqui5
route_id 322
caiu aqui tb
891
     order_id  order_latitude  order_longitude                ordered_at_brt  \
890       891      -23.626466       -46.557404 2024-04-02 05:30:25.686636186

     order_weight     sla_max_delivery_time_brt
890     12.083855 2024-04-02 07:30:25.686636186
2024-04-02 05:30:25.686636186
tem rota aberta
dist order to order é  5.830911420724923 hub em questão 12
dist order to hub é  2.221933048671186 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 12
passou aqui1
passou aqui5
route_id 323
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

892
     order_id  order_latitude  order_longitude                ordered_at_brt  \
891       892      -23.637537       -46.673887 2024-04-02 05:31:33.961256934

     order_weight     sla_max_delivery_time_brt
891     11.727659 2024-04-02 06:31:33.961256934
2024-04-02 05:31:33.961256934
tem rota aberta
dist order to order é  8.30039641793344 hub em questão 1
dist order to hub é  2.8272123696122327 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 1
passou aqui1
passou aqui5
route_id 324
caiu aqui tb
893
     order_id  order_latitude  order_longitude                ordered_at_brt  \
892       893      -23.657465       -46.573352 2024-04-02 05:32:31.804078265

     order_weight     sla_max_delivery_time_brt
892      9.867721 2024-04-02 07:32:31.804078265
2024-04-02 05:32:31.804078265
tem rota aberta
dist order to order é  2.455076002428185 hub em questão 12
dist order to hub é  1.3234459617563703 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 319
894
     order_id  order_latitude  order_longitude                ordered_at_brt  \
893       894      -23.658837       -46.694445 2024-04-02 05:33:47.941715952

     order_weight     sla_max_delivery_time_brt
893     12.196153 2024-04-02 06:33:47.941715952
2024-04-02 05:33:47.941715952
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.161366821633271 hub em questão 15
dist order to hub é  1.1390152799875644 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 325
caiu aqui tb
895
     order_id  order_latitude  order_longitude                ordered_at_brt  \
894       895      -23.630322       -46.539399 2024-04-02 05:41:34.323963683

     order_weight     sla_max_delivery_time_brt
894      6.026354 2024-04-02 07:41:34.323963683
2024-04-02 05:41:34.323963683
tem rota aberta
dist order to order é  1.883619646057077 hub em questão 3
dist order to hub é  3.9392559271814838 hub em questão 2
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 323
896
     order_id  order_latitude  order_longitude                ordered_at_brt  \
895       896      -23.689997       -46.689295 2024-04-02 05:42:28.702124802

     order_weight     sla_max_delivery_time_brt
895      9.843594 2024-04-02 07:42:28.702124802
2024-04-02 05:42:28.702124802
tem rota aberta
dist order to order é  3.5043762189769225 hub em questão 9
dist order to hub é  3.9296590585633875 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 325
897
     order_id  order_latitude  order_longitude                ordered_at_brt  \
896       897      -23.626042        -46.67118 2024-04-02 05:45:27.386526118

     order_weight     sla_max_delivery_time_brt
896      5.189062 2024-04-02 07:45:27.386526118
2024-04-02 05:45:27.386526118
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  1.3075543864230879 hub em questão 15
dist order to hub é  1.637914368905247 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 324
898
     order_id  order_latitude  order_longitude                ordered_at_brt  \
897       898      -23.716363       -46.633165 2024-04-02 05:47:03.947754267

     order_weight     sla_max_delivery_time_brt
897      5.569484 2024-04-02 08:47:03.947754267
2024-04-02 05:47:03.947754267
tem rota aberta
dist order to order é  2.738107037076913 hub em questão 1
dist order to hub é  0.6685229153360852 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 1
passou aqui1
rota em aberto, route_id:  322
rota_escolhida: 322
orders no hub: 1
passou aqui3
passou aqui4
899
     order_id  order_latitude  order_longitude                ordered_at_brt  \
898       899       -23.62321       -46.718043 2024-04-02 05:51:27.876565290

     order_weight     sla_max_delivery_time_brt
898      8.385047 2024-04-02 06:51:27.876565290
2024-04-02 05:51:27.876565290
tem rota aberta
dist order to order é  4.633712093552306 hub em questão 9
dist order to hub é  3.581073592645707 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 325
900
     order_id  order_latitude  order_longitude                ordered_at_brt  \
899       900      -23.675588       -46.570532 2024-04-02 05:52:20.488389193

     order_weight     sla_max_delivery_time_brt
899      6.048044 2024-04-02 07:52:20.488389193
2024-04-02 05:52:20.488389193
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  0.5909855911180312 hub em questão 12
dist order to hub é  1.0309048926958266 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 319
901
     order_id  order_latitude  order_longitude                ordered_at_brt  \
900       901      -23.593806       -46.701514 2024-04-02 05:52:54.295360326

     order_weight     sla_max_delivery_time_brt
900       4.29385 2024-04-02 06:52:54.295360326
2024-04-02 05:52:54.295360326
tem rota aberta
dist order to order é  3.677784272509013 hub em questão 9
dist order to hub é  2.4934115871720035 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 325
902
     order_id  order_latitude  order_longitude                ordered_at_brt  \
901       902      -23.711393       -46.617315 2024-04-02 05:57:44.615573350

     order_weight     sla_max_delivery_time_brt
901      9.442385 2024-04-02 06:57:44.615573350
2024-04-02 05:57:44.615573350
tem rota aberta
dist order to order é  1.7056352574671858 hub em questão 1
dist order to hub é  1.097181152558972 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 322
903
     order_id  order_latitude  order_longitude                ordered_at_brt  \
902       903        -23.6729       -46.712469 2024-04-02 05:57:49.956810881

     order_weight     sla_max_delivery_time_brt
902      7.646024 2024-04-02 07:57:49.956810881
2024-04-02 05:57:49.956810881
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  5.559237847450936 hub em questão 15
dist order to hub é  2.473789678835722 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 326
caiu aqui tb
904
     order_id  order_latitude  order_longitude                ordered_at_brt  \
903       904      -23.691271       -46.642524 2024-04-02 06:03:51.266673171

     order_weight     sla_max_delivery_time_brt
903     11.290946 2024-04-02 07:03:51.266673171
2024-04-02 06:03:51.266673171
tem rota aberta
dist order to order é  7.409761333669556 hub em questão 9
dist order to hub é  2.5129102884514327 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 9
passou aqui1
passou aqui5
route_id 327
caiu aqui tb
905
     order_id  order_latitude  order_longitude                ordered_at_brt  \
904       905      -23.603214       -46.648539 2024-04-02 06:05:28.808386791

     order_weight     sla_max_delivery_time_brt
904        3.0292 2024-04-02 08:05:28.808386791
2024-04-02 06:05:28.808386791
tem rota aberta
dist order to order é  9.810570443576657 hub em questão 5
dist order to hub é  1.2410028885086166 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 5
passou aqui1
passou aqui5
route_id 328
caiu aqui tb
906
     order_id  order_latitude  order_longitude                ordered_at_brt  \
905       906       -23.72079       -46.667425 2024-04-02 06:06:25.470845764

     order_weight     sla_max_delivery_time_brt
905      5.737841 2024-04-02 08:06:25.470845764
2024-04-02 06:06:25.470845764
tem rota aberta
dist order to order é  4.147497387808156 hub em questão 5
dist order to hub é  4.114026710634532 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 327
907
     order_id  order_latitude  order_longitude                ordered_at_brt  \
906       907      -23.606018       -46.623552 2024-04-02 06:17:02.531282392

     order_weight     sla_max_delivery_time_brt
906      5.448237 2024-04-02 09:17:02.531282392
2024-04-02 06:17:02.531282392
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  2.5650032403203755 hub em questão 8
dist order to hub é  1.4725315286933505 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 328
908
     order_id  order_latitude  order_longitude                ordered_at_brt  \
907       908      -23.627064       -46.703854 2024-04-02 06:17:09.747488776

     order_weight     sla_max_delivery_time_brt
907      6.301968 2024-04-02 08:17:09.747488776
2024-04-02 06:17:09.747488776
tem rota aberta
dist order to order é  5.171723569987176 hub em questão 9
dist order to hub é  2.814691626906999 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 9
passou aqui1
rota em aberto, route_id:  326
rota_escolhida: 326
orders no hub: 1
passou aqui3
passou aqui4
909
     order_id  order_latitude  order_longitude                ordered_at_brt  \
908       909      -23.621927       -46.571919 2024-04-02 06:18:37.003191887

     order_weight     sla_max_delivery_time_brt
908      9.164037 2024-04-02 07:18:37.003191887
2024-04-02 06:18:37.003191887
tem rota aberta
dist order to order é  5.54998203147433 hub em questão 8
dist order to hub é  0.813189828354105 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 8
passou aqui1
passou aqui5
route_id 329
caiu aqui tb
910
     order_id  order_latitude  order_longitude                ordered_at_brt  \
909       910      -23.684633        -46.63789 2024-04-02 06:18:40.794094268

     order_weight     sla_max_delivery_time_brt
909       3.52221 2024-04-02 08:18:40.794094268
2024-04-02 06:18:40.794094268
tem rota aberta
dist order to order é  0.875943717116888 hub em questão 5
dist order to hub é  2.2915746439720803 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 327
911
     order_id  order_latitude  order_longitude                ordered_at_brt  \
910       911      -23.626458       -46.787585 2024-04-02 06:20:22.399065360

     order_weight     sla_max_delivery_time_brt
910       10.2125 2024-04-02 08:20:22.399065360
2024-04-02 06:20:22.399065360
tem rota aberta
dist order to order é  8.53025491186349 hub em questão 9
dist order to hub é  8.049704372997109 hub em questão 11
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 326
912
     order_id  order_latitude  order_longitude                ordered_at_brt  \
911       912      -23.562689       -46.547735 2024-04-02 06:20:46.281759892

     order_weight     sla_max_delivery_time_brt
911      5.503073 2024-04-02 08:20:46.281759892
2024-04-02 06:20:46.281759892
tem rota aberta
dist order to order é  7.032846381512598 hub em questão 3
dist order to hub é  6.515217776843745 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 329
913
     order_id  order_latitude  order_longitude                ordered_at_brt  \
912       913      -23.684791       -46.625377 2024-04-02 06:22:45.903528636

     order_weight     sla_max_delivery_time_brt
912     10.474754 2024-04-02 08:22:45.903528636
2024-04-02 06:22:45.903528636
tem rota aberta
dist order to order é  1.2743396859078568 hub em questão 5
dist order to hub é  3.108763755053438 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 327

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

914
     order_id  order_latitude  order_longitude                ordered_at_brt  \
913       914      -23.637566       -46.570335 2024-04-02 06:30:41.020402346

     order_weight     sla_max_delivery_time_brt
913     11.503166 2024-04-02 07:30:41.020402346
2024-04-02 06:30:41.020402346
tem rota aberta
dist order to order é  1.7464799903745627 hub em questão 3
dist order to hub é  2.518800440003656 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 329
915
     order_id  order_latitude  order_longitude                ordered_at_brt  \
914       915      -23.663379        -46.65686 2024-04-02 06:34:50.459872958

     order_weight     sla_max_delivery_time_brt
914     12.528885 2024-04-02 08:34:50.459872958
2024-04-02 06:34:50.459872958
tem rota aberta
dist order to order é  6.743533212675328 hub em questão 8
dist order to hub é  0.9947083736518582 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 8
passou aqui1
passou aqui5
route_id 330
caiu aqui tb
916
     order_id  order_latitude  order_longitude                ordered_at_brt  \
915       916      -23.705243       -46.761144 2024-04-02 06:36:02.601619567

     order_weight     sla_max_delivery_time_brt
915      3.960222 2024-04-02 08:36:02.601619567
2024-04-02 06:36:02.601619567
tem rota aberta
dist order to order é  11.594641665618425 hub em questão 5
dist order to hub é  8.335707055479665 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

passou aqui5
route_id 331
caiu aqui tb
917
     order_id  order_latitude  order_longitude                ordered_at_brt  \
916       917      -23.691467       -46.668999 2024-04-02 06:38:30.511345047

     order_weight     sla_max_delivery_time_brt
916      5.870717 2024-04-02 08:38:30.511345047
2024-04-02 06:38:30.511345047
tem rota aberta
dist order to order é  3.358919274073828 hub em questão 5
dist order to hub é  2.515688048250147 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 330
918
     order_id  order_latitude  order_longitude                ordered_at_brt  \
917       918      -23.623983       -46.709316 2024-04-02 06:41:30.833873584

     order_weight     sla_max_delivery_time_brt
917      9.242865 2024-04-02 08:41:30.833873584
2024-04-02 06:41:30.833873584
tem rota aberta
dist order to order é  6.909513739996721 hub em questão 5
dist order to hub é  3.2189146673265006 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
rota em aberto, route_id:  331
rota_escolhida: 331
orders no hub: 1
passou aqui3
passou aqui4
919
     order_id  order_latitude  order_longitude                ordered_at_brt  \
918       919      -23.652494       -46.649937 2024-04-02 06:42:52.780214413

     order_weight     sla_max_delivery_time_brt
918      9.830901 2024-04-02 08:42:52.780214413
2024-04-02 06:42:52.780214413
tem rota aberta
dist order to order é  1.4007440472787684 hub em questão 5
dist order to hub é  2.2826837514326392 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 330
920

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
919       920      -23.772871       -46.672149 2024-04-02 06:44:23.009079425

     order_weight     sla_max_delivery_time_brt
919      5.723315 2024-04-02 08:44:23.009079425
2024-04-02 06:44:23.009079425
tem rota aberta
dist order to order é  9.057471525007305 hub em questão 5
dist order to hub é  8.06454062319321 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 330
921
     order_id  order_latitude  order_longitude                ordered_at_brt  \
920       921      -23.623611       -46.637562 2024-04-02 06:44:42.622140685

     order_weight     sla_max_delivery_time_brt
920      9.417334 2024-04-02 08:44:42.622140685
2024-04-02 06:44:42.622140685
tem rota aberta
dist order to order é  6.690122083700592 hub em questão 3
dist order to hub é  1.831509665582857 hub em questão 10
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 10
hub_order 3
passou aqui1
passou aqui5
route_id 332
caiu aqui tb
922
     order_id  order_latitude  order_longitude                ordered_at_brt  \
921       922      -23.666105       -46.736233 2024-04-02 06:45:37.952150353

     order_weight     sla_max_delivery_time_brt
921       7.17056 2024-04-02 08:45:37.952150353
2024-04-02 06:45:37.952150353
tem rota aberta
dist order to order é  5.037221100854165 hub em questão 9
dist order to hub é  3.702607094491398 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 331

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

923
     order_id  order_latitude  order_longitude                ordered_at_brt  \
922       923      -23.604338       -46.645324 2024-04-02 06:45:56.361240368

     order_weight     sla_max_delivery_time_brt
922      5.345925 2024-04-02 09:45:56.361240368
2024-04-02 06:45:56.361240368
tem rota aberta
dist order to order é  2.2842975026063757 hub em questão 10
dist order to hub é  0.9734131619006039 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 332
924
     order_id  order_latitude  order_longitude                ordered_at_brt  \
923       924      -23.682407       -46.670992 2024-04-02 06:48:32.108565682

     order_weight     sla_max_delivery_time_brt
923      5.187435 2024-04-02 08:48:32.108565682
2024-04-02 06:48:32.108565682
tem rota aberta
dist order to order é  6.886847173831482 hub em questão 9
dist order to hub é  1.9047763728587501 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 9
passou aqui1
passou aqui5
route_id 333
caiu aqui tb
925
     order_id  order_latitude  order_longitude                ordered_at_brt  \
924       925      -23.534879       -46.616337 2024-04-02 06:49:49.892405016

     order_weight     sla_max_delivery_time_brt
924     10.704906 2024-04-02 09:49:49.892405016
2024-04-02 06:49:49.892405016
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  8.269221312076176 hub em questão 10
dist order to hub é  7.591509998952369 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 332
926
     order_id  order_latitude  order_longitude                ordered_at_brt  \
925       926      -23.697663       -46.732628 2024-04-02 06:51:01.388476646

     order_weight     sla_max_delivery_time_brt
925      6.690668 2024-04-02 07:51:01.388476646
2024-04-02 06:51:01.388476646
tem rota aberta
dist order to order é  3.0232138971707485 hub em questão 9
dist order to hub é  5.8650060622860885 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 331
927
     order_id  order_latitude  order_longitude                ordered_at_brt  \
926       927      -23.611914       -46.669266 2024-04-02 06:55:21.973160720

     order_weight     sla_max_delivery_time_brt
926      5.893437 2024-04-02 07:55:21.973160720
2024-04-02 06:55:21.973160720
tem rota aberta
dist order to order é  2.580846793051882 hub em questão 10
dist order to hub é  1.0471941460914245 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 10 2
route_id 332
928
     order_id  order_latitude  order_longitude                ordered_at_brt  \
927       928      -23.703998       -46.565093 2024-04-02 06:56:51.969432754

     order_weight     sla_max_delivery_time_brt
927     12.677708 2024-04-02 08:56:51.969432754
2024-04-02 06:56:51.969432754
tem rota aberta
dist order to order é  11.046948689545767 hub em questão 5
dist order to hub é  2.6399222039562646 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 5
passou aqui1

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

passou aqui5
route_id 334
caiu aqui tb
929
     order_id  order_latitude  order_longitude                ordered_at_brt  \
928       929      -23.640478       -46.707066 2024-04-02 06:57:55.100588589

     order_weight     sla_max_delivery_time_brt
928      7.562048 2024-04-02 07:57:55.100588589
2024-04-02 06:57:55.100588589
tem rota aberta
dist order to order é  5.936002116569764 hub em questão 5
dist order to hub é  1.3820578627479354 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 5
passou aqui1
passou aqui5
route_id 335
caiu aqui tb
930
     order_id  order_latitude  order_longitude                ordered_at_brt  \
929       930      -23.707601        -46.61111 2024-04-02 06:58:32.683882714

     order_weight     sla_max_delivery_time_brt
929      3.296938 2024-04-02 08:58:32.683882714
2024-04-02 06:58:32.683882714
tem rota aberta
dist order to order é  4.702235288439593 hub em questão 6
dist order to hub é  1.8091975152231456 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 6
passou aqui1
passou aqui5
route_id 336
caiu aqui tb
931
     order_id  order_latitude  order_longitude                ordered_at_brt  \
930       931      -23.587483       -46.581487 2024-04-02 06:58:41.652264539

     order_weight     sla_max_delivery_time_brt
930      7.315403 2024-04-02 08:58:41.652264539
2024-04-02 06:58:41.652264539
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  13.06312289408589 hub em questão 6
dist order to hub é  3.165291942272701 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 6
passou aqui1
passou aqui5
route_id 337
caiu aqui tb
932
     order_id  order_latitude  order_longitude                ordered_at_brt  \
931       932      -23.651281       -46.648517 2024-04-02 06:59:46.634516381

     order_weight     sla_max_delivery_time_brt
931      6.334482 2024-04-02 08:59:46.634516381
2024-04-02 06:59:46.634516381
tem rota aberta
dist order to order é  4.14949389678143 hub em questão 5
dist order to hub é  2.4534725815771714 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 333
933
     order_id  order_latitude  order_longitude                ordered_at_brt  \
932       933      -23.575487       -46.598587 2024-04-02 06:59:49.765425487

     order_weight     sla_max_delivery_time_brt
932      5.980331 2024-04-02 07:59:49.765425487
2024-04-02 06:59:49.765425487
tem rota aberta
dist order to order é  2.1945471107961576 hub em questão 3
dist order to hub é  4.78113409219606 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 337
934
     order_id  order_latitude  order_longitude                ordered_at_brt  \
933       934       -23.65509       -46.595941 2024-04-02 07:00:31.059453428

     order_weight     sla_max_delivery_time_brt
933      7.928971 2024-04-02 08:00:31.059453428
2024-04-02 07:00:31.059453428
tem rota aberta
dist order to order é  5.371829914468613 hub em questão 5
dist order to hub é  2.4253550417132583 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 5
passou aqui1
passou aqui5
route_id 338
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

935
     order_id  order_latitude  order_longitude                ordered_at_brt  \
934       935      -23.731443       -46.569525 2024-04-02 07:01:55.082367362

     order_weight     sla_max_delivery_time_brt
934      0.204066 2024-04-02 09:01:55.082367362
2024-04-02 07:01:55.082367362
tem rota aberta
dist order to order é  3.0849205921400387 hub em questão 6
dist order to hub é  0.9408696246350581 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 6
passou aqui1
rota em aberto, route_id:  334
rota_escolhida: 334
orders no hub: 1
passou aqui3
passou aqui4
936
     order_id  order_latitude  order_longitude                ordered_at_brt  \
935       936      -23.692381       -46.666404 2024-04-02 07:08:40.613729015

     order_weight     sla_max_delivery_time_brt
935      7.704891 2024-04-02 10:08:40.613729015
2024-04-02 07:08:40.613729015
tem rota aberta
dist order to order é  1.2034377757677728 hub em questão 5
dist order to hub é  2.477524509092079 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 333
937
     order_id  order_latitude  order_longitude                ordered_at_brt  \
936       937      -23.669834       -46.653628 2024-04-02 07:08:54.514613216

     order_weight     sla_max_delivery_time_brt
936      4.008369 2024-04-02 09:08:54.514613216
2024-04-02 07:08:54.514613216
tem rota aberta
dist order to order é  2.1276764358747555 hub em questão 5
dist order to hub é  0.3575857978587906 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 333
938
     order_id  order_latitude  order_longitude                ordered_at_brt  \
937       938       -23.58115       -46.607807 2024-04-02 07:11:08.665092899

     order_weight     sla_max_delivery_time_brt
937      8.591341 2024-04-02 09:11:08.665092899
2024-04-02 07:11:08.665092899
tem rota aberta
dist order to order é  1.1310925594665766 hub em questão 3
dist order to hub é  3.6507911640677766 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 337
939
     order_id  order_latitude  order_longitude                ordered_at_brt  \
938       939      -23.513752       -46.685295 2024-04-02 07:12:31.826524727

     order_weight     sla_max_delivery_time_brt
938      8.711197 2024-04-02 10:12:31.826524727
2024-04-02 07:12:31.826524727
tem rota aberta
dist order to order é  10.888377713365527 hub em questão 3
dist order to hub é  6.586545010330637 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 3
passou aqui1
passou aqui5
route_id 339
caiu aqui tb
940
     order_id  order_latitude  order_longitude                ordered_at_brt  \
939       940      -23.655933        -46.64561 2024-04-02 07:15:31.949416078

     order_weight     sla_max_delivery_time_brt
939          0.01 2024-04-02 09:15:31.949416078
2024-04-02 07:15:31.949416078
tem rota aberta
dist order to order é  5.059794444361912 hub em questão 12
dist order to hub é  2.0985649071237855 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 12
passou aqui1
passou aqui5
route_id 340
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

941
     order_id  order_latitude  order_longitude                ordered_at_brt  \
940       941      -23.634324       -46.682941 2024-04-02 07:15:50.552523306

     order_weight     sla_max_delivery_time_brt
940      8.468641 2024-04-02 08:15:50.552523306
2024-04-02 07:15:50.552523306
tem rota aberta
dist order to order é  2.5509422913267614 hub em questão 9
dist order to hub é  2.8721190933014324 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 335
942
     order_id  order_latitude  order_longitude                ordered_at_brt  \
941       942       -23.58772       -46.764465 2024-04-02 07:16:00.976780352

     order_weight     sla_max_delivery_time_brt
941       8.92558 2024-04-02 09:16:00.976780352
2024-04-02 07:16:00.976780352
tem rota aberta
dist order to order é  8.283374063648878 hub em questão 9
dist order to hub é  3.3260349511189773 hub em questão 11
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 11
hub_order 9
passou aqui1
passou aqui5
route_id 341
caiu aqui tb
943
     order_id  order_latitude  order_longitude                ordered_at_brt  \
942       943      -23.707291       -46.631267 2024-04-02 07:17:02.119677949

     order_weight     sla_max_delivery_time_brt
942      7.699113 2024-04-02 10:17:02.119677949
2024-04-02 07:17:02.119677949
tem rota aberta
dist order to order é  2.0524939261597503 hub em questão 1
dist order to hub é  0.6817001973059309 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 336

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

944
     order_id  order_latitude  order_longitude                ordered_at_brt  \
943       944      -23.666005       -46.562891 2024-04-02 07:20:13.443281915

     order_weight     sla_max_delivery_time_brt
943      4.718105 2024-04-02 10:20:13.443281915
2024-04-02 07:20:13.443281915
tem rota aberta
dist order to order é  3.5781857837065854 hub em questão 12
dist order to hub é  1.5091602787171094 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 12
passou aqui1
rota em aberto, route_id:  338
rota_escolhida: 338
orders no hub: 1
passou aqui3
passou aqui4
945
     order_id  order_latitude  order_longitude                ordered_at_brt  \
944       945      -23.616746       -46.666616 2024-04-02 07:20:38.978320443

     order_weight     sla_max_delivery_time_brt
944     10.730955 2024-04-02 09:20:38.978320443
2024-04-02 07:20:38.978320443
tem rota aberta
dist order to order é  2.5664759289287553 hub em questão 9
dist order to hub é  0.7038401738739934 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 335
946
     order_id  order_latitude  order_longitude                ordered_at_brt  \
945       946      -23.632569       -46.643798 2024-04-02 07:23:34.185279184

     order_weight     sla_max_delivery_time_brt
945      9.550813 2024-04-02 10:23:34.185279184
2024-04-02 07:23:34.185279184
tem rota aberta
dist order to order é  2.604569672575351 hub em questão 5
dist order to hub é  1.9426473284359274 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 340
947
     order_id  order_latitude  order_longitude                ordered_at_brt  \
946       947      -23.654441       -46.670668 2024-04-02 07:24:15.334492530

     order_weight     sla_max_delivery_time_brt
946      4.137592 2024-04-02 09:24:15.334492530

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-02 07:24:15.334492530
tem rota aberta
dist order to order é  2.557572386998888 hub em questão 5
dist order to hub é  2.489241159196725 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 340
948
     order_id  order_latitude  order_longitude                ordered_at_brt  \
947       948      -23.699095       -46.685061 2024-04-02 07:24:44.672573390

     order_weight     sla_max_delivery_time_brt
947      7.399934 2024-04-02 08:24:44.672573390
2024-04-02 07:24:44.672573390
tem rota aberta
dist order to order é  5.177108405590579 hub em questão 5
dist order to hub é  4.207631097523371 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 340
949
     order_id  order_latitude  order_longitude                ordered_at_brt  \
948       949      -23.645016       -46.641208 2024-04-02 07:24:46.695397928

     order_weight     sla_max_delivery_time_brt
948     11.187699 2024-04-02 09:24:46.695397928
2024-04-02 07:24:46.695397928
tem rota aberta
dist order to order é  4.072018103214272 hub em questão 9
dist order to hub é  3.2838824886621856 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 335

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

950
     order_id  order_latitude  order_longitude                ordered_at_brt  \
949       950      -23.614581       -46.594366 2024-04-02 07:25:47.726584005

     order_weight     sla_max_delivery_time_brt
949     10.446498 2024-04-02 08:25:47.726584005
2024-04-02 07:25:47.726584005
tem rota aberta
dist order to order é  3.286578185702473 hub em questão 3
dist order to hub é  1.8467140027957079 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 337
951
     order_id  order_latitude  order_longitude                ordered_at_brt  \
950       951      -23.686146       -46.537221 2024-04-02 07:26:45.300383789

     order_weight     sla_max_delivery_time_brt
950     10.268791 2024-04-02 08:26:45.300383789
2024-04-02 07:26:45.300383789
tem rota aberta
dist order to order é  3.442334958055321 hub em questão 12
dist order to hub é  4.26257616811344 hub em questão 2
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 338
952
     order_id  order_latitude  order_longitude                ordered_at_brt  \
951       952      -23.646501       -46.606689 2024-04-02 07:28:54.526566598

     order_weight     sla_max_delivery_time_brt
951      6.577929 2024-04-02 09:28:54.526566598
2024-04-02 07:28:54.526566598
tem rota aberta
dist order to order é  1.4527370264869122 hub em questão 12
dist order to hub é  2.536286887409937 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 338

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

953
     order_id  order_latitude  order_longitude                ordered_at_brt  \
952       953      -23.545738       -46.696081 2024-04-02 07:29:03.353611575

     order_weight     sla_max_delivery_time_brt
952     10.551756 2024-04-02 10:29:03.353611575
2024-04-02 07:29:03.353611575
tem rota aberta
dist order to order é  3.7228000987971823 hub em questão 4
dist order to hub é  2.8844183601015816 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 339
954
     order_id  order_latitude  order_longitude                ordered_at_brt  \
953       954      -23.626359       -46.719364 2024-04-02 07:29:23.224069074

     order_weight     sla_max_delivery_time_brt
953     11.665605 2024-04-02 09:29:23.224069074
2024-04-02 07:29:23.224069074
tem rota aberta
dist order to order é  6.290997101617944 hub em questão 11
dist order to hub é  3.332224028222338 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 11
passou aqui1
passou aqui5
route_id 342
caiu aqui tb
955
     order_id  order_latitude  order_longitude                ordered_at_brt  \
954       955      -23.620569       -46.582671 2024-04-02 07:29:25.229845086

     order_weight     sla_max_delivery_time_brt
954     13.146954 2024-04-02 09:29:25.229845086
2024-04-02 07:29:25.229845086
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  13.94064433498814 hub em questão 9
dist order to hub é  0.9206592913932168 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 9
passou aqui1
passou aqui5
route_id 343
caiu aqui tb
956
     order_id  order_latitude  order_longitude                ordered_at_brt  \
955       956      -23.702035       -46.632177 2024-04-02 07:29:39.726866140

     order_weight     sla_max_delivery_time_brt
955      9.057804 2024-04-02 08:29:39.726866140
2024-04-02 07:29:39.726866140
tem rota aberta
dist order to order é  10.367249112489247 hub em questão 3
dist order to hub é  1.253910269901158 hub em questão 1
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 1
hub_order 3
passou aqui1
passou aqui5
route_id 344
caiu aqui tb
957
     order_id  order_latitude  order_longitude                ordered_at_brt  \
956       957      -23.677769       -46.678536 2024-04-02 07:31:46.320560591

     order_weight     sla_max_delivery_time_brt
956      8.322078 2024-04-02 08:31:46.320560591
2024-04-02 07:31:46.320560591
tem rota aberta
dist order to order é  5.437232700959818 hub em questão 1
dist order to hub é  2.384123422368272 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 1
passou aqui1
passou aqui5
route_id 345
caiu aqui tb
958
     order_id  order_latitude  order_longitude                ordered_at_brt  \
957       958      -23.666099       -46.700821 2024-04-02 07:32:48.152185839

     order_weight     sla_max_delivery_time_brt
957      8.644178 2024-04-02 08:32:48.152185839
2024-04-02 07:32:48.152185839
tem rota aberta
dist order to order é  2.614341935468692 hub em questão 5
dist order to hub é  1.5445132638821997 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 345

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

959
     order_id  order_latitude  order_longitude                ordered_at_brt  \
958       959      -23.692159       -46.688399 2024-04-02 07:33:34.612934615

     order_weight     sla_max_delivery_time_brt
958       6.74411 2024-04-02 08:33:34.612934615
2024-04-02 07:33:34.612934615
tem rota aberta
dist order to order é  1.889187416347407 hub em questão 5
dist order to hub é  3.979240102000959 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 345
960
     order_id  order_latitude  order_longitude                ordered_at_brt  \
959       960       -23.71068       -46.586342 2024-04-02 07:35:12.562491656

     order_weight     sla_max_delivery_time_brt
959      7.094357 2024-04-02 10:35:12.562491656
2024-04-02 07:35:12.562491656
tem rota aberta
dist order to order é  4.764605906532368 hub em questão 1
dist order to hub é  1.949627918941913 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 1
passou aqui1
passou aqui5
route_id 346
caiu aqui tb
961
     order_id  order_latitude  order_longitude                ordered_at_brt  \
960       961      -23.728514       -46.649131 2024-04-02 07:45:16.149162823

     order_weight     sla_max_delivery_time_brt
960      7.056997 2024-04-02 10:45:16.149162823
2024-04-02 07:45:16.149162823
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  3.412962068643203 hub em questão 1
dist order to hub é  2.7818923487259366 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 344
962
     order_id  order_latitude  order_longitude                ordered_at_brt  \
961       962      -23.660619       -46.718036 2024-04-02 07:48:51.993474965

     order_weight     sla_max_delivery_time_brt
961      5.501054 2024-04-02 08:48:51.993474965
2024-04-02 07:48:51.993474965
tem rota aberta
dist order to order é  1.8561104739175172 hub em questão 5
dist order to hub é  1.7750569351911503 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 345
963
     order_id  order_latitude  order_longitude                ordered_at_brt  \
962       963      -23.608584       -46.604384 2024-04-02 07:51:16.319579025

     order_weight     sla_max_delivery_time_brt
962      6.981411 2024-04-02 09:51:16.319579025
2024-04-02 07:51:16.319579025
tem rota aberta
dist order to order é  2.582554669784289 hub em questão 3
dist order to hub é  1.456598029597261 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 343
964
     order_id  order_latitude  order_longitude                ordered_at_brt  \
963       964      -23.619386       -46.632508 2024-04-02 07:56:16.822923892

     order_weight     sla_max_delivery_time_brt
963      6.521095 2024-04-02 09:56:16.822923892
2024-04-02 07:56:16.822923892
tem rota aberta
dist order to order é  3.1069345080894077 hub em questão 3
dist order to hub é  1.7669823603502692 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 343
965
     order_id  order_latitude  order_longitude                ordered_at_brt  \
964       965      -23.616411       -46.662569 2024-04-02 07:56:21.687656360

     order_weight     sla_max_delivery_time_brt
964      8.351173 2024-04-02 09:56:21.687656360
2024-04-02 07:56:21.687656360
tem rota aberta
dist order to order é  3.0805373700375274 hub em questão 3
dist order to hub é  0.29381348712799443 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 3
passou aqui1
passou aqui5
route_id 347
caiu aqui tb
966
     order_id  order_latitude  order_longitude                ordered_at_brt  \
965       966      -23.604621       -46.617627 2024-04-02 07:56:30.439171939

     order_weight     sla_max_delivery_time_brt
965      6.638503 2024-04-02 09:56:30.439171939
2024-04-02 07:56:30.439171939
tem rota aberta
dist order to order é  1.419494132226417 hub em questão 3
dist order to hub é  1.6634511693771996 hub em questão 13
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 343
967
     order_id  order_latitude  order_longitude                ordered_at_brt  \
966       967      -23.693166       -46.689397 2024-04-02 07:57:47.535094875

     order_weight     sla_max_delivery_time_brt
966      8.156696 2024-04-02 09:57:47.535094875
2024-04-02 07:57:47.535094875
tem rota aberta

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

dist order to order é  5.679275375317001 hub em questão 1
dist order to hub é  4.126120298394819 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 1 2
route_id 344
968
     order_id  order_latitude  order_longitude                ordered_at_brt  \
967       968      -23.684389       -46.599818 2024-04-02 07:58:39.075434787

     order_weight     sla_max_delivery_time_brt
967      8.368279 2024-04-02 08:58:39.075434787
2024-04-02 07:58:39.075434787
tem rota aberta
dist order to order é  3.2294675025102944 hub em questão 6
dist order to hub é  2.8682417939215075 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 346
969
     order_id  order_latitude  order_longitude                ordered_at_brt  \
968       969      -23.662005       -46.719256 2024-04-02 08:04:11.310982480

     order_weight     sla_max_delivery_time_brt
968      7.851197 2024-04-02 10:04:11.310982480
2024-04-02 08:04:11.310982480
tem rota aberta
dist order to order é  7.684101179440774 hub em questão 15
dist order to hub é  1.9621664372909113 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 348
caiu aqui tb
970
     order_id  order_latitude  order_longitude                ordered_at_brt  \
969       970      -23.694788       -46.693185 2024-04-02 08:05:32.010010421

     order_weight     sla_max_delivery_time_brt
969     14.096804 2024-04-02 09:05:32.010010421
2024-04-02 08:05:32.010010421
tem rota aberta
dist order to order é  4.509687491650096 hub em questão 9
dist order to hub é  4.546937259058216 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 348

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

971
     order_id  order_latitude  order_longitude                ordered_at_brt  \
970       971      -23.637742       -46.716857 2024-04-02 08:07:05.101963557

     order_weight     sla_max_delivery_time_brt
970      9.948052 2024-04-02 11:07:05.101963557
2024-04-02 08:07:05.101963557
tem rota aberta
dist order to order é  2.708949810886394 hub em questão 9
dist order to hub é  2.1457138974835606 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 348
972
     order_id  order_latitude  order_longitude                ordered_at_brt  \
971       972      -23.683383       -46.668841 2024-04-02 08:11:35.855285389

     order_weight     sla_max_delivery_time_brt
971      2.253118 2024-04-02 10:11:35.855285389
2024-04-02 08:11:35.855285389
tem rota aberta
dist order to order é  2.7844332406492125 hub em questão 9
dist order to hub é  1.8053163430632322 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 348
973
     order_id  order_latitude  order_longitude                ordered_at_brt  \
972       973      -23.594528       -46.685885 2024-04-02 08:12:46.863790408

     order_weight     sla_max_delivery_time_brt
972      3.194231 2024-04-02 09:12:46.863790408
2024-04-02 08:12:46.863790408
tem rota aberta
dist order to order é  3.4007378861168447 hub em questão 15
dist order to hub é  2.9463354526946888 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 347
974

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
973       974      -23.694118       -46.666145 2024-04-02 08:16:58.365856439

     order_weight     sla_max_delivery_time_brt
973       9.82961 2024-04-02 10:16:58.365856439
2024-04-02 08:16:58.365856439
tem rota aberta
dist order to order é  8.648269182673202 hub em questão 15
dist order to hub é  2.642502860052164 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 15
passou aqui1
passou aqui5
route_id 349
caiu aqui tb
975
     order_id  order_latitude  order_longitude                ordered_at_brt  \
974       975      -23.622098       -46.647774 2024-04-02 08:17:33.462157824

     order_weight     sla_max_delivery_time_brt
974     10.288049 2024-04-02 09:17:33.462157824
2024-04-02 08:17:33.462157824
tem rota aberta
dist order to order é  1.6345902971457262 hub em questão 15
dist order to hub é  0.8166893768767165 hub em questão 10
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 15 2
route_id 347
976
     order_id  order_latitude  order_longitude                ordered_at_brt  \
975       976      -23.566287         -46.6203 2024-04-02 08:18:11.855339786

     order_weight     sla_max_delivery_time_brt
975      6.110959 2024-04-02 09:18:11.855339786
2024-04-02 08:18:11.855339786
tem rota aberta
dist order to order é  6.808159237460533 hub em questão 15
dist order to hub é  4.160500728130561 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 15
passou aqui1
passou aqui5
route_id 350
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

977
     order_id  order_latitude  order_longitude                ordered_at_brt  \
976       977      -23.710987       -46.640686 2024-04-02 08:18:59.619523704

     order_weight     sla_max_delivery_time_brt
976      7.685111 2024-04-02 10:18:59.619523704
2024-04-02 08:18:59.619523704
tem rota aberta
dist order to order é  3.199578906599306 hub em questão 5
dist order to hub é  1.3041342541579086 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 349
978
     order_id  order_latitude  order_longitude                ordered_at_brt  \
977       978      -23.677791        -46.63542 2024-04-02 08:20:34.792670921

     order_weight     sla_max_delivery_time_brt
977      6.864422 2024-04-02 11:20:34.792670921
2024-04-02 08:20:34.792670921
tem rota aberta
dist order to order é  3.617249126179245 hub em questão 5
dist order to hub é  2.1741648345029403 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 349
979
     order_id  order_latitude  order_longitude                ordered_at_brt  \
978       979      -23.688633       -46.567797 2024-04-02 08:21:04.627831673

     order_weight     sla_max_delivery_time_brt
978      6.490096 2024-04-02 10:21:04.627831673
2024-04-02 08:21:04.627831673
tem rota aberta
dist order to order é  6.99082139959967 hub em questão 5
dist order to hub é  2.414898040920299 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 5
passou aqui1
passou aqui5
route_id 351
caiu aqui tb

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

980
     order_id  order_latitude  order_longitude                ordered_at_brt  \
979       980      -23.703239       -46.661337 2024-04-02 08:23:18.188173811

     order_weight     sla_max_delivery_time_brt
979      9.308653 2024-04-02 10:23:18.188173811
2024-04-02 08:23:18.188173811
tem rota aberta
dist order to order é  1.1261777954148104 hub em questão 5
dist order to hub é  3.486428547537447 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 349
981
     order_id  order_latitude  order_longitude                ordered_at_brt  \
980       981      -23.637191        -46.72093 2024-04-02 08:23:36.677315315

     order_weight     sla_max_delivery_time_brt
980      4.034446 2024-04-02 10:23:36.677315315
2024-04-02 08:23:36.677315315
tem rota aberta
dist order to order é  5.937401209444633 hub em questão 15
dist order to hub é  2.4779835070176595 hub em questão 9
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 9
hub_order 15
passou aqui1
passou aqui5
route_id 352
caiu aqui tb
982
     order_id  order_latitude  order_longitude                ordered_at_brt  \
981       982      -23.625209       -46.600444 2024-04-02 08:23:48.536514193

     order_weight     sla_max_delivery_time_brt
981      4.852462 2024-04-02 10:23:48.536514193
2024-04-02 08:23:48.536514193
tem rota aberta
dist order to order é  4.834286180803188 hub em questão 15
dist order to hub é  1.2461110685090986 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 15
passou aqui1
passou aqui5
route_id 353
caiu aqui tb
983

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
982       983      -23.686866       -46.556219 2024-04-02 08:27:53.540140774

     order_weight     sla_max_delivery_time_brt
982      9.065069 2024-04-02 11:27:53.540140774
2024-04-02 08:27:53.540140774
tem rota aberta
dist order to order é  1.195148171019168 hub em questão 12
dist order to hub é  2.949208794124225 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 351
984
     order_id  order_latitude  order_longitude                ordered_at_brt  \
983       984      -23.675849       -46.638648 2024-04-02 08:28:25.979162768

     order_weight     sla_max_delivery_time_brt
983      4.830992 2024-04-02 09:28:25.979162768
2024-04-02 08:28:25.979162768
tem rota aberta
dist order to order é  6.844712282157296 hub em questão 7
dist order to hub é  1.8015137660054705 hub em questão 5
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 5
hub_order 7
passou aqui1
passou aqui5
route_id 354
caiu aqui tb
985
     order_id  order_latitude  order_longitude                ordered_at_brt  \
984       985      -23.638105       -46.606036 2024-04-02 08:29:24.511188783

     order_weight     sla_max_delivery_time_brt
984      7.096745 2024-04-02 10:29:24.511188783
2024-04-02 08:29:24.511188783
tem rota aberta
dist order to order é  1.5429360710268698 hub em questão 7
dist order to hub é  1.7580777390547924 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 353
986
     order_id  order_latitude  order_longitude                ordered_at_brt  \
985       986      -23.634527       -46.680794 2024-04-02 08:31:06.218722203

     order_weight     sla_max_delivery_time_brt
985      8.009104 2024-04-02 11:31:06.218722203
2024-04-02 08:31:06.218722203
tem rota aberta
dist order to order é  4.099250235791406 hub em questão 9
dist order to hub é  2.997705656644734 hub em questão 15
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 352
987
     order_id  order_latitude  order_longitude                ordered_at_brt  \
986       987      -23.705794       -46.638729 2024-04-02 08:32:35.754353357

     order_weight     sla_max_delivery_time_brt
986       0.97196 2024-04-02 10:32:35.754353357
2024-04-02 08:32:35.754353357
tem rota aberta
dist order to order é  3.3296929169671055 hub em questão 5
dist order to hub é  1.3312880019076205 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 354
988
     order_id  order_latitude  order_longitude                ordered_at_brt  \
987       988      -23.535144       -46.616162 2024-04-02 08:32:45.242639504

     order_weight     sla_max_delivery_time_brt
987      9.139321 2024-04-02 09:32:45.242639504
2024-04-02 08:32:45.242639504
tem rota aberta
dist order to order é  3.4886279098371267 hub em questão 8
dist order to hub é  7.568149508349011 hub em questão 8
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 8 2
route_id 350
989
     order_id  order_latitude  order_longitude                ordered_at_brt  \
988       989      -23.661897       -46.629084 2024-04-02 08:36:53.939442791

     order_weight     sla_max_delivery_time_brt
988      6.993411 2024-04-02 09:36:53.939442791

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-02 08:36:53.939442791
tem rota aberta
dist order to order é  1.8318342041796989 hub em questão 5
dist order to hub é  2.9655090096323984 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 354
990
     order_id  order_latitude  order_longitude                ordered_at_brt  \
989       990      -23.645819       -46.674998 2024-04-02 08:42:56.184227702

     order_weight     sla_max_delivery_time_brt
989     12.684295 2024-04-02 10:42:56.184227702
2024-04-02 08:42:56.184227702
tem rota aberta
dist order to order é  1.3875036683339976 hub em questão 9
dist order to hub é  2.955245242808097 hub em questão 9
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 9 2
route_id 352
991
     order_id  order_latitude  order_longitude                ordered_at_brt  \
990       991      -23.681629       -46.566481 2024-04-02 08:46:17.066074493

     order_weight     sla_max_delivery_time_brt
990      14.49683 2024-04-02 09:46:17.066074493
2024-04-02 08:46:17.066074493
tem rota aberta
dist order to order é  0.7902948740032735 hub em questão 12
dist order to hub é  1.8107066607010285 hub em questão 12
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 351
992
     order_id  order_latitude  order_longitude                ordered_at_brt  \
991       992       -23.66316       -46.639372 2024-04-02 08:46:57.121880510

     order_weight     sla_max_delivery_time_brt
991      2.405048 2024-04-02 11:46:57.121880510

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-02 08:46:57.121880510
tem rota aberta
dist order to order é  1.0571587662320692 hub em questão 5
dist order to hub é  1.965619574815866 hub em questão 5
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 5 2
route_id 354
993
     order_id  order_latitude  order_longitude                ordered_at_brt  \
992       993       -23.69544       -46.601503 2024-04-02 08:48:27.176091898

     order_weight     sla_max_delivery_time_brt
992      7.087706 2024-04-02 10:48:27.176091898
2024-04-02 08:48:27.176091898
tem rota aberta
dist order to order é  3.514548638913838 hub em questão 12
dist order to hub é  3.3076884614451143 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 12 2
route_id 351
994
     order_id  order_latitude  order_longitude                ordered_at_brt  \
993       994      -23.568813       -46.627724 2024-04-02 08:49:16.931941828

     order_weight     sla_max_delivery_time_brt
993      5.667831 2024-04-02 10:49:16.931941828
2024-04-02 08:49:16.931941828
tem rota aberta
dist order to order é  6.859445852069724 hub em questão 7
dist order to hub é  3.6455732702191095 hub em questão 8
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 8
hub_order 7
passou aqui1
passou aqui5
route_id 355
caiu aqui tb
995
     order_id  order_latitude  order_longitude                ordered_at_brt  \
994       995      -23.742585       -46.604329 2024-04-02 08:50:54.003981020

     order_weight     sla_max_delivery_time_brt
994      6.632764 2024-04-02 10:50:54.003981020

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

2024-04-02 08:50:54.003981020
tem rota aberta
dist order to order é  11.618952498310266 hub em questão 7
dist order to hub é  3.445072111286321 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 7
passou aqui1
passou aqui5
route_id 356
caiu aqui tb
996
     order_id  order_latitude  order_longitude                ordered_at_brt  \
995       996      -23.659473        -46.60135 2024-04-02 08:58:13.839793951

     order_weight     sla_max_delivery_time_brt
995       3.71815 2024-04-02 10:58:13.839793951
2024-04-02 08:58:13.839793951
tem rota aberta
dist order to order é  9.246611048660885 hub em questão 6
dist order to hub é  2.6496568354656365 hub em questão 12
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 12
hub_order 6
passou aqui1
passou aqui5
route_id 357
caiu aqui tb
997
     order_id  order_latitude  order_longitude                ordered_at_brt  \
996       997       -23.61717       -46.658821 2024-04-02 08:58:58.663961384

     order_weight     sla_max_delivery_time_brt
996      3.636059 2024-04-02 10:58:58.663961384
2024-04-02 08:58:58.663961384
tem rota aberta
dist order to order é  6.241228577258769 hub em questão 8
dist order to hub é  0.19996108016007136 hub em questão 15
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 15
hub_order 8
passou aqui1
passou aqui5
route_id 358
caiu aqui tb
998

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)
C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\3290022937.py:20: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  distance_order_to_order = distances_order_order_df.merge(orders_hub,on='hub_id_waiting',how='left').fillna(0)

     order_id  order_latitude  order_longitude                ordered_at_brt  \
997       998      -23.730086       -46.606329 2024-04-02 09:01:11.266674428

     order_weight     sla_max_delivery_time_brt
997      1.127828 2024-04-02 10:01:11.266674428
2024-04-02 09:01:11.266674428
tem rota aberta
dist order to order é  1.404617465643211 hub em questão 6
dist order to hub é  2.9377779547680403 hub em questão 1
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 356
999
     order_id  order_latitude  order_longitude                ordered_at_brt  \
998       999      -23.627175        -46.53999 2024-04-02 09:01:58.603856277

     order_weight     sla_max_delivery_time_brt
998      4.962055 2024-04-02 10:01:58.603856277
2024-04-02 09:01:58.603856277
tem rota aberta
dist order to order é  7.208572109713375 hub em questão 12
dist order to hub é  3.8543839130709814 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 12
passou aqui1
passou aqui5
route_id 359
caiu aqui tb
1000
     order_id  order_latitude  order_longitude                ordered_at_brt  \
999      1000        -23.5844       -46.548063 2024-04-02 09:04:57.323973383

     order_weight     sla_max_delivery_time_brt
999      8.433094 2024-04-02 11:04:57.323973383
2024-04-02 09:04:57.323973383
tem rota aberta
dist order to order é  4.826922976598122 hub em questão 3
dist order to hub é  4.446370931008322 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 359

dist order to order é  4.542471824870384 hub em questão 3
dist order to hub é  0.8284792548386232 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 3
passou aqui1
rota em aberto, route_id:  83
rota_escolhida: 83
orders no hub: 1
passou aqui3
passou aqui4
249
     order_id  order_latitude  order_longitude      ordered_at_brt
248       249      -23.671942       -46.792164 2024-04-01 20:12:00
2024-04-01 20:12:00
tem rota aberta
dist order to order é  9.683730291823561 hub em questão 4
dist order to hub é  10.241002426778085 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 82
250
     order_id  order_latitude  order_longitude      ordered_at_brt
249       250      -23.689718       -46.661864 2024-04-01 20:15:00
2024-04-01 20:15:00
tem rota aberta
dist order to order é  8.034047685402225 hub em questão 3
dist order to hub é  8.721197320147294 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 83
251
     order_id  order_latitude  order_longitude      ordered_at_brt
250       251      -23.706154       -46.621032 2024-04-01 20:20:00
2024-04-01 20:20:00
tem rota aberta
dist order to order é  4.541465562167398 hub em questão 3
dist order to hub é  8.755520941076911 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 83
252
     order_id  order_latitude  order_longitude      ordered_at_brt
251       252      -23.587347       -46.604245 2024-04-01 20:28:00
2024-04-01 20:28:00
não tem rota aberta
route_id 84
dist pro hub mais próximo é 8.08
hub alocado 16
253
     order_id  order_latitude  order_longitude      ordered_at_brt
252       253      -23.656459       -46.616046 2024-04-01 20:32:00
2024-04-01 20:32:00
tem rota aberta
dist order to order é  7.778388718338883 hub em questão 16
dist order to hub é  10.88916835352286 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 84
254
     order_id  order_latitude  order_longitude      ordered_at_brt
253       254      -23.704651       -46.672136 2024-04-01 20:35:00
2024-04-01 20:35:00
tem rota aberta
dist order to order é  7.83191409626207 hub em questão 16
dist order to hub é  6.959081001335584 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 84
255
     order_id  order_latitude  order_longitude      ordered_at_brt
254       255      -23.660126        -46.67991 2024-04-01 20:39:00
2024-04-01 20:39:00
tem rota aberta
dist order to order é  5.013824239488314 hub em questão 16
dist order to hub é  11.910830043212044 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 84
256
     order_id  order_latitude  order_longitude      ordered_at_brt
255       256      -23.699926       -46.595217 2024-04-01 20:43:00
2024-04-01 20:43:00
não tem rota aberta
route_id 85
dist pro hub mais próximo é 11.07
hub alocado 3
257
     order_id  order_latitude  order_longitude      ordered_at_brt
256       257      -23.564189       -46.549916 2024-04-01 20:47:00
2024-04-01 20:47:00
tem rota aberta
dist order to order é  15.783073623571 hub em questão 3
dist order to hub é  4.990631861755399 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 86
caiu aqui tb
258
     order_id  order_latitude  order_longitude      ordered_at_brt
257       258      -23.623739       -46.639755 2024-04-01 20:51:00
2024-04-01 20:51:00
tem rota aberta
dist order to order é  9.609593573808517 hub em questão 3
dist order to hub é  10.558119854873864 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 85
259
     order_id  order_latitude  order_longitude      ordered_at_brt
258       259      -23.661805       -46.627488 2024-04-01 20:57:00
2024-04-01 20:57:00
tem rota aberta
dist order to order é  4.413323413063264 hub em questão 3
dist order to hub é  12.191563977246393 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 85
260
     order_id  order_latitude  order_longitude      ordered_at_brt
259       260      -23.670374       -46.644148 2024-04-01 20:58:00
2024-04-01 20:58:00
tem rota aberta
dist order to order é  1.9458801942398145 hub em questão 3
dist order to hub é  11.223193150356002 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 85
261
     order_id  order_latitude  order_longitude      ordered_at_brt
260       261      -23.681748       -46.641515 2024-04-01 20:59:00
2024-04-01 20:59:00
tem rota aberta
dist order to order é  16.061103966983996 hub em questão 14
dist order to hub é  10.105148914797846 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 14
passou aqui1
passou aqui5
route_id 87
caiu aqui tb
262
     order_id  order_latitude  order_longitude      ordered_at_brt
261       262      -23.653583        -46.62635 2024-04-01 21:04:00
2024-04-01 21:04:00
tem rota aberta
dist order to order é  3.4918790048479864 hub em questão 3
dist order to hub é  11.628795599640284 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 87
263
     order_id  order_latitude  order_longitude      ordered_at_brt
262       263      -23.657909        -46.70723 2024-04-01 21:09:00
2024-04-01 21:09:00
tem rota aberta
dist order to order é  7.198309203459273 hub em questão 3
dist order to hub é  11.385810934202059 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 87
264
     order_id  order_latitude  order_longitude      ordered_at_brt
263       264       -23.72603       -46.698813 2024-04-01 21:18:00
2024-04-01 21:18:00
tem rota aberta
dist order to order é  7.623025496790589 hub em questão 3
dist order to hub é  5.156851594593669 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 3
passou aqui1
rota em aberto, route_id:  87
rota_escolhida: 87
orders no hub: 3
passou aqui3
passou aqui4
265
     order_id  order_latitude  order_longitude      ordered_at_brt
264       265      -23.681097       -46.612947 2024-04-01 21:26:00
2024-04-01 21:26:00
não tem rota aberta
route_id 88
dist pro hub mais próximo é 11.49
hub alocado 3
266
     order_id  order_latitude  order_longitude      ordered_at_brt
265       266      -23.673144       -46.649819 2024-04-01 21:31:00
2024-04-01 21:31:00
tem rota aberta
dist order to order é  3.857566387545047 hub em questão 3
dist order to hub é  10.774212899304432 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 88
267
     order_id  order_latitude  order_longitude      ordered_at_brt
266       267      -23.723253       -46.647245 2024-04-01 21:34:00
2024-04-01 21:34:00
tem rota aberta
dist order to order é  5.578006934122062 hub em questão 3
dist order to hub é  5.6619875751345505 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 88
268
     order_id  order_latitude  order_longitude      ordered_at_brt
267       268       -23.62777       -46.631568 2024-04-01 21:42:00
2024-04-01 21:42:00
tem rota aberta
dist order to order é  5.376939336908556 hub em questão 3
dist order to hub é  11.073271112417652 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 88
269
     order_id  order_latitude  order_longitude      ordered_at_brt
268       269       -23.69557       -46.639912 2024-04-01 21:47:00
2024-04-01 21:47:00
não tem rota aberta
route_id 89
dist pro hub mais próximo é 8.74
hub alocado 3
271
     order_id  order_latitude  order_longitude      ordered_at_brt
269       271      -23.675814       -46.649684 2024-04-01 21:50:00
2024-04-01 21:50:00
tem rota aberta
dist order to order é  2.4117340839140393 hub em questão 3
dist order to hub é  10.489805545172164 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 89
270
     order_id  order_latitude  order_longitude      ordered_at_brt
270       270      -23.608223       -46.748718 2024-04-01 21:50:00
2024-04-01 21:50:00
tem rota aberta
dist order to order é  12.579765714548309 hub em questão 3
dist order to hub é  11.282649954540823 hub em questão 19
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 89
272
     order_id  order_latitude  order_longitude      ordered_at_brt
271       272      -23.624282       -46.559165 2024-04-01 21:53:00
2024-04-01 21:53:00
tem rota aberta
dist order to order é  10.855523562775433 hub em questão 3
dist order to hub é  4.082486041000679 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 90
caiu aqui tb
273
     order_id  order_latitude  order_longitude      ordered_at_brt
272       273      -23.640406       -46.654396 2024-04-01 21:56:00
2024-04-01 21:56:00
tem rota aberta

dist order to order é  3.966345388215435 hub em questão 3
dist order to hub é  12.338419291813084 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 89
274
     order_id  order_latitude  order_longitude      ordered_at_brt
273       274      -23.648926        -46.70537 2024-04-01 22:00:00
2024-04-01 22:00:00
tem rota aberta
dist order to order é  15.143447309286092 hub em questão 14
dist order to hub é  12.389253787474109 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 14
passou aqui1
passou aqui5
route_id 91
caiu aqui tb
275
     order_id  order_latitude  order_longitude      ordered_at_brt
274       275       -23.61494       -46.652479 2024-04-01 22:08:00
2024-04-01 22:08:00
tem rota aberta
dist order to order é  6.581279484716946 hub em questão 4
dist order to hub é  9.50457297330139 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 91
276
     order_id  order_latitude  order_longitude      ordered_at_brt
275       276      -23.660293       -46.575488 2024-04-01 22:12:00
2024-04-01 22:12:00
tem rota aberta
dist order to order é  4.335736920509542 hub em questão 14
dist order to hub é  8.074413650749358 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 90
277
     order_id  order_latitude  order_longitude      ordered_at_brt
276       277      -23.675262       -46.738927 2024-04-01 22:18:00
2024-04-01 22:18:00
tem rota aberta
dist order to order é  4.50068842674754 hub em questão 4
dist order to hub é  8.773078895661284 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 91
278
     order_id  order_latitude  order_longitude      ordered_at_brt
277       278      -23.642444       -46.650507 2024-04-01 22:23:00
2024-04-01 22:23:00
tem rota aberta
dist order to order é  3.0649117411680558 hub em questão 4
dist order to hub é  12.563853555878783 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 91
279
     order_id  order_latitude  order_longitude      ordered_at_brt
278       279      -23.631693       -46.723483 2024-04-01 22:26:00
2024-04-01 22:26:00
não tem rota aberta
route_id 92
dist pro hub mais próximo é 13.41
hub alocado 7
280
     order_id  order_latitude  order_longitude      ordered_at_brt
279       280      -23.631561       -46.565198 2024-04-01 22:27:00
2024-04-01 22:27:00
tem rota aberta
dist order to order é  16.124542939174372 hub em questão 7
dist order to hub é  5.057884767526305 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 7
passou aqui1
passou aqui5
route_id 93
caiu aqui tb
281
     order_id  order_latitude  order_longitude      ordered_at_brt
280       281      -23.692614       -46.681272 2024-04-01 22:30:00
2024-04-01 22:30:00
tem rota aberta
dist order to order é  8.023103213358464 hub em questão 7
dist order to hub é  8.31100061986875 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 92
282
     order_id  order_latitude  order_longitude      ordered_at_brt
281       282      -23.640377       -46.626639 2024-04-01 22:35:00
2024-04-01 22:35:00
tem rota aberta
dist order to order é  6.335119340244097 hub em questão 14
dist order to hub é  11.02833586671935 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 93
283
     order_id  order_latitude  order_longitude      ordered_at_brt
282       283      -23.731437       -46.716868 2024-04-01 22:39:00
2024-04-01 22:39:00
tem rota aberta
dist order to order é  5.636416848507808 hub em questão 7
dist order to hub é  3.893099714798359 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 92
284
     order_id  order_latitude  order_longitude      ordered_at_brt
283       284      -23.706864       -46.604419 2024-04-01 22:40:00
2024-04-01 22:40:00
tem rota aberta
dist order to order é  7.731637647013246 hub em questão 14
dist order to hub é  9.857647016110908 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 93
285
     order_id  order_latitude  order_longitude      ordered_at_brt
284       285      -23.718554       -46.647279 2024-04-01 22:47:00
2024-04-01 22:47:00
tem rota aberta
dist order to order é  4.505346377292756 hub em questão 7
dist order to hub é  6.116689281870396 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 92
286
     order_id  order_latitude  order_longitude      ordered_at_brt
285       286      -23.644531       -46.591017 2024-04-01 22:50:00
2024-04-01 22:50:00
tem rota aberta
dist order to order é  2.999549060692741 hub em questão 14
dist order to hub é  8.03194656235341 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 93
287
     order_id  order_latitude  order_longitude      ordered_at_brt
286       287      -23.618438       -46.644553 2024-04-01 22:55:00
2024-04-01 22:55:00
não tem rota aberta
route_id 94
dist pro hub mais próximo é 9.92
hub alocado 16
288
     order_id  order_latitude  order_longitude      ordered_at_brt
287       288      -23.632768       -46.663589 2024-04-01 22:58:00
2024-04-01 22:58:00
tem rota aberta
dist order to order é  2.5099578247567944 hub em questão 16
dist order to hub é  11.546565670863176 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 94
289
     order_id  order_latitude  order_longitude      ordered_at_brt
288       289      -23.706957       -46.689876 2024-04-01 23:03:00
2024-04-01 23:03:00
tem rota aberta
dist order to order é  8.672954713230585 hub em questão 16
dist order to hub é  6.854593660360832 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 94
290
     order_id  order_latitude  order_longitude      ordered_at_brt
289       290      -23.611308       -46.695369 2024-04-01 23:07:00
2024-04-01 23:07:00
tem rota aberta
dist order to order é  4.022006911867464 hub em questão 16
dist order to hub é  10.113205350584867 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 94
291
     order_id  order_latitude  order_longitude      ordered_at_brt
290       291      -23.714731       -46.696269 2024-04-01 23:11:00
2024-04-01 23:11:00
não tem rota aberta
route_id 95
dist pro hub mais próximo é 6.2
hub alocado 3
292
     order_id  order_latitude  order_longitude      ordered_at_brt
291       292      -23.682722       -46.626276 2024-04-01 23:16:00
2024-04-01 23:16:00
tem rota aberta
dist order to order é  7.9659653764374125 hub em questão 3
dist order to hub é  10.638571928355143 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 95
293
     order_id  order_latitude  order_longitude      ordered_at_brt
292       293      -23.631302       -46.753088 2024-04-01 23:22:00
2024-04-01 23:22:00
tem rota aberta
dist order to order é  10.933542813383875 hub em questão 3
dist order to hub é  13.647578789872282 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 95
294
     order_id  order_latitude  order_longitude      ordered_at_brt
293       294      -23.645324       -46.633004 2024-04-01 23:23:00
2024-04-01 23:23:00
tem rota aberta
dist order to order é  4.214542999937547 hub em questão 3
dist order to hub é  11.83788405836485 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 95
295
     order_id  order_latitude  order_longitude      ordered_at_brt
294       295      -23.658409       -46.739486 2024-04-01 23:29:00
2024-04-01 23:29:00
não tem rota aberta
route_id 96
dist pro hub mais próximo é 10.64
hub alocado 4
296
     order_id  order_latitude  order_longitude      ordered_at_brt
295       296      -23.681052       -46.617956 2024-04-01 23:32:00
2024-04-01 23:32:00
tem rota aberta
dist order to order é  12.63020065185442 hub em questão 4
dist order to hub é  11.220169023109433 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 96
297
     order_id  order_latitude  order_longitude      ordered_at_brt
296       297      -23.647015       -46.653386 2024-04-01 23:33:00
2024-04-01 23:33:00
tem rota aberta
dist order to order é  5.2292296316489155 hub em questão 4
dist order to hub é  13.071739466546012 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 96
298
     order_id  order_latitude  order_longitude      ordered_at_brt
297       298      -23.652979       -46.584066 2024-04-01 23:40:00
2024-04-01 23:40:00
tem rota aberta

dist order to order é  4.653639529073808 hub em questão 4
dist order to hub é  8.069791160510611 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 96
299
     order_id  order_latitude  order_longitude      ordered_at_brt
298       299      -23.559758       -46.635158 2024-04-01 23:46:00
2024-04-01 23:46:00
não tem rota aberta
route_id 97
dist pro hub mais próximo é 3.79
hub alocado 16
300
     order_id  order_latitude  order_longitude      ordered_at_brt
299       300      -23.701214       -46.567913 2024-04-01 23:51:00
2024-04-01 23:51:00
tem rota aberta
dist order to order é  17.156134877191718 hub em questão 16
dist order to hub é  11.673254334495098 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 98
caiu aqui tb
301
     order_id  order_latitude  order_longitude      ordered_at_brt
300       301      -23.692894       -46.646723 2024-04-01 23:54:00
2024-04-01 23:54:00
tem rota aberta
dist order to order é  8.07750558957929 hub em questão 14
dist order to hub é  8.759498064141082 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 98
302
     order_id  order_latitude  order_longitude      ordered_at_brt
301       302      -23.617604       -46.687361 2024-04-02 00:02:00
2024-04-02 00:02:00
tem rota aberta
dist order to order é  8.346870962476105 hub em questão 16
dist order to hub é  10.439053460026424 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 97
303
     order_id  order_latitude  order_longitude      ordered_at_brt
302       303      -23.695786       -46.542312 2024-04-02 00:06:00
2024-04-02 00:06:00
tem rota aberta
dist order to order é  2.6756018214466057 hub em questão 14
dist order to hub é  10.398760903699305 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 98
304
     order_id  order_latitude  order_longitude      ordered_at_brt
303       304      -23.662167       -46.621016 2024-04-02 00:10:00
2024-04-02 00:10:00
tem rota aberta
dist order to order é  4.304314882133594 hub em questão 14
dist order to hub é  11.661092217373849 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 98
305
     order_id  order_latitude  order_longitude      ordered_at_brt
304       305      -23.583171       -46.662179 2024-04-02 00:17:00
2024-04-02 00:17:00
não tem rota aberta
route_id 99
dist pro hub mais próximo é 6.06
hub alocado 16
306
     order_id  order_latitude  order_longitude      ordered_at_brt
305       306      -23.666651       -46.632567 2024-04-02 00:23:00
2024-04-02 00:23:00
tem rota aberta
dist order to order é  9.760478199352455 hub em questão 16
dist order to hub é  11.997330851747849 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 99
307
     order_id  order_latitude  order_longitude      ordered_at_brt
306       307      -23.694046       -46.631681 2024-04-02 00:27:00
2024-04-02 00:27:00
tem rota aberta
dist order to order é  3.0474494856607395 hub em questão 16
dist order to hub é  9.269107809750514 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 99
308
     order_id  order_latitude  order_longitude      ordered_at_brt
307       308      -23.559272       -46.663618 2024-04-02 00:31:00
2024-04-02 00:31:00
tem rota aberta
dist order to order é  2.661460290350737 hub em questão 16
dist order to hub é  3.5166753105378215 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 99
309
     order_id  order_latitude  order_longitude      ordered_at_brt
308       309      -23.675038       -46.561885 2024-04-02 00:34:00
2024-04-02 00:34:00
não tem rota aberta
route_id 100
dist pro hub mais próximo é 8.75
hub alocado 14
310
     order_id  order_latitude  order_longitude      ordered_at_brt
309       310      -23.677397       -46.649172 2024-04-02 00:38:00
2024-04-02 00:38:00
tem rota aberta
dist order to order é  8.892817703710687 hub em questão 14
dist order to hub é  10.332754788392355 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 100
311
     order_id  order_latitude  order_longitude      ordered_at_brt
310       311      -23.606485       -46.680288 2024-04-02 00:41:00
2024-04-02 00:41:00
tem rota aberta
dist order to order é  8.498309443276797 hub em questão 14
dist order to hub é  9.033600934743156 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 100
312
     order_id  order_latitude  order_longitude      ordered_at_brt
311       312      -23.717373       -46.647385 2024-04-02 00:45:00
2024-04-02 00:45:00
tem rota aberta
dist order to order é  4.448877456992888 hub em questão 14
dist order to hub é  6.228026805524526 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 100
313
     order_id  order_latitude  order_longitude      ordered_at_brt
312       313      -23.590409       -46.729972 2024-04-02 00:50:00
2024-04-02 00:50:00
não tem rota aberta
route_id 101
dist pro hub mais próximo é 9.16
hub alocado 19
314
     order_id  order_latitude  order_longitude      ordered_at_brt
313       314      -23.659543       -46.651613 2024-04-02 00:54:00
2024-04-02 00:54:00
tem rota aberta
dist order to order é  11.082393016538813 hub em questão 19
dist order to hub é  12.209663479089885 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 19 2
route_id 101
315
     order_id  order_latitude  order_longitude      ordered_at_brt
314       315      -23.585196       -46.667437 2024-04-02 01:00:00
2024-04-02 01:00:00
tem rota aberta
dist order to order é  6.398865194090972 hub em questão 19
dist order to hub é  6.391492163516423 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 19 2
route_id 101
316
     order_id  order_latitude  order_longitude      ordered_at_brt
315       316      -23.688903       -46.619955 2024-04-02 01:07:00
2024-04-02 01:07:00
tem rota aberta
dist order to order é  4.58830626595202 hub em questão 19
dist order to hub é  10.372783125354411 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 19 2
route_id 101
317
     order_id  order_latitude  order_longitude      ordered_at_brt
316       317      -23.573022       -46.574015 2024-04-02 01:10:00
2024-04-02 01:10:00
não tem rota aberta
route_id 102
dist pro hub mais próximo é 5.93
hub alocado 14
318
     order_id  order_latitude  order_longitude      ordered_at_brt
317       318      -23.626179       -46.640463 2024-04-02 01:14:00
2024-04-02 01:14:00
tem rota aberta
dist order to order é  8.987793071575718 hub em questão 14
dist order to hub é  10.819413897325681 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 102
319
     order_id  order_latitude  order_longitude      ordered_at_brt
318       319      -23.563754       -46.705053 2024-04-02 01:21:00
2024-04-02 01:21:00
tem rota aberta
dist order to order é  9.565630605745534 hub em questão 14
dist order to hub é  5.667510954632011 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 14
passou aqui1
passou aqui5
route_id 103
caiu aqui tb
320
     order_id  order_latitude  order_longitude      ordered_at_brt
319       320      -23.658278       -46.600112 2024-04-02 01:26:00
2024-04-02 01:26:00
tem rota aberta
dist order to order é  5.443667326373536 hub em questão 14
dist order to hub é  9.69074882703726 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 102
321
     order_id  order_latitude  order_longitude      ordered_at_brt
320       321       -23.62681        -46.55132 2024-04-02 01:34:00
2024-04-02 01:34:00
tem rota aberta
dist order to order é  6.078276035804846 hub em questão 14
dist order to hub é  3.648862365516382 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 14
passou aqui1
rota em aberto, route_id:  102
rota_escolhida: 102
orders no hub: 3
passou aqui3
passou aqui4
322
     order_id  order_latitude  order_longitude      ordered_at_brt
321       322       -23.64641       -46.749682 2024-04-02 01:41:00
2024-04-02 01:41:00
tem rota aberta
dist order to order é  10.254299861211258 hub em questão 7
dist order to hub é  11.954927976681363 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 103

323
     order_id  order_latitude  order_longitude      ordered_at_brt
322       323      -23.598973       -46.589876 2024-04-02 01:47:00
2024-04-02 01:47:00
tem rota aberta
dist order to order é  12.373781485618633 hub em questão 7
dist order to hub é  6.509804452747946 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 7
passou aqui1
passou aqui5
route_id 104
caiu aqui tb
324
     order_id  order_latitude  order_longitude      ordered_at_brt
323       324      -23.655527       -46.684118 2024-04-02 01:51:00
2024-04-02 01:51:00
tem rota aberta
dist order to order é  11.477051412833411 hub em questão 14
dist order to hub é  12.444970075670254 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 104
325
     order_id  order_latitude  order_longitude      ordered_at_brt
324       325      -23.612875        -46.59089 2024-04-02 01:57:00
2024-04-02 01:57:00
tem rota aberta
dist order to order é  1.549209596337605 hub em questão 14
dist order to hub é  6.676641769426437 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 104
326
     order_id  order_latitude  order_longitude      ordered_at_brt
325       326      -23.571983       -46.751418 2024-04-02 02:01:00
2024-04-02 02:01:00
tem rota aberta
dist order to order é  11.54615028190676 hub em questão 14
dist order to hub é  7.400474859163952 hub em questão 19
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 19
hub_order 14
passou aqui1
passou aqui5
route_id 105
caiu aqui tb
327
     order_id  order_latitude  order_longitude      ordered_at_brt
326       327       -23.66648       -46.634251 2024-04-02 02:04:00
2024-04-02 02:04:00
tem rota aberta
dist order to order é  5.222858360402437 hub em questão 14
dist order to hub é  11.953944935643335 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 104
328
     order_id  order_latitude  order_longitude      ordered_at_brt
327       328      -23.498802       -46.663043 2024-04-02 02:11:00
2024-04-02 02:11:00
tem rota aberta
dist order to order é  12.140294123039906 hub em questão 19
dist order to hub é  2.8748134817607136 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 19
passou aqui1
passou aqui5
route_id 106
caiu aqui tb
329
     order_id  order_latitude  order_longitude      ordered_at_brt
328       329       -23.64811       -46.612747 2024-04-02 02:16:00
2024-04-02 02:16:00
tem rota aberta
dist order to order é  16.47053801324662 hub em questão 19
dist order to hub é  10.12188484512135 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 19
passou aqui1
passou aqui5
route_id 107
caiu aqui tb
330
     order_id  order_latitude  order_longitude      ordered_at_brt
329       330      -23.621771       -46.614527 2024-04-02 02:19:00
2024-04-02 02:19:00
tem rota aberta
dist order to order é  2.9343990774230013 hub em questão 14
dist order to hub é  9.229673492816149 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 107
331
     order_id  order_latitude  order_longitude      ordered_at_brt
330       331      -23.652445       -46.703231 2024-04-02 02:22:00
2024-04-02 02:22:00
tem rota aberta
dist order to order é  9.229016021671606 hub em questão 14
dist order to hub é  12.098484212378636 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 107
332
     order_id  order_latitude  order_longitude      ordered_at_brt
331       332      -23.648939       -46.609603 2024-04-02 02:28:00
2024-04-02 02:28:00
tem rota aberta
dist order to order é  0.33320982306554686 hub em questão 14
dist order to hub é  9.890931558739803 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 107
333
     order_id  order_latitude  order_longitude      ordered_at_brt
332       333      -23.572658       -46.668025 2024-04-02 02:32:00
2024-04-02 02:32:00
tem rota aberta
dist order to order é  8.228180442403055 hub em questão 7
dist order to hub é  5.070163643798814 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 7
passou aqui1
passou aqui5
route_id 108
caiu aqui tb
334
     order_id  order_latitude  order_longitude      ordered_at_brt
333       334      -23.727468       -46.705319 2024-04-02 02:36:00
2024-04-02 02:36:00
tem rota aberta
dist order to order é  17.628209402892736 hub em questão 16
dist order to hub é  5.095198475684596 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 16
passou aqui1
passou aqui5
route_id 109
caiu aqui tb
335
     order_id  order_latitude  order_longitude      ordered_at_brt
334       335      -23.653877       -46.599477 2024-04-02 02:38:00
2024-04-02 02:38:00
tem rota aberta
dist order to order é  11.416495190278681 hub em questão 16
dist order to hub é  9.338784383364324 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 110
caiu aqui tb
336
     order_id  order_latitude  order_longitude      ordered_at_brt
335       336      -23.674562       -46.629994 2024-04-02 02:42:00
2024-04-02 02:42:00
tem rota aberta
dist order to order é  3.8665291945187037 hub em questão 14
dist order to hub é  11.287206843926528 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 110
337
     order_id  order_latitude  order_longitude      ordered_at_brt
336       337      -23.652971       -46.566225 2024-04-02 02:44:00
2024-04-02 02:44:00
tem rota aberta
dist order to order é  3.388318769503636 hub em questão 14
dist order to hub é  6.853943800683563 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 110
338
     order_id  order_latitude  order_longitude      ordered_at_brt
337       338      -23.552121       -46.666625 2024-04-02 02:52:00
2024-04-02 02:52:00
tem rota aberta
dist order to order é  2.28805606769893 hub em questão 16
dist order to hub é  2.9226962855271563 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 108
339
     order_id  order_latitude  order_longitude      ordered_at_brt
338       339       -23.63777       -46.643947 2024-04-02 02:54:00
2024-04-02 02:54:00
tem rota aberta
dist order to order é  4.330830581383861 hub em questão 14
dist order to hub é  12.071755268919787 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 110
340
     order_id  order_latitude  order_longitude      ordered_at_brt
339       340      -23.573716       -46.661255 2024-04-02 02:56:00
2024-04-02 02:56:00
tem rota aberta
dist order to order é  0.6999104987248179 hub em questão 16
dist order to hub é  5.008454127715941 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 108
341
     order_id  order_latitude  order_longitude      ordered_at_brt
340       341       -23.66942        -46.63866 2024-04-02 03:02:00
2024-04-02 03:02:00
tem rota aberta
dist order to order é  9.366241752343004 hub em questão 4
dist order to hub é  11.494428804853799 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 109
342
     order_id  order_latitude  order_longitude      ordered_at_brt
341       342      -23.684253       -46.624557 2024-04-02 03:07:00
2024-04-02 03:07:00
não tem rota aberta
route_id 111
dist pro hub mais próximo é 10.57
hub alocado 3
343
     order_id  order_latitude  order_longitude      ordered_at_brt
342       343       -23.72261       -46.652783 2024-04-02 03:12:00
2024-04-02 03:12:00
tem rota aberta
dist order to order é  5.142997336533697 hub em questão 3
dist order to hub é  5.463229312693266 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 111
344
     order_id  order_latitude  order_longitude      ordered_at_brt
343       344      -23.759112       -46.663426 2024-04-02 03:13:00
2024-04-02 03:13:00
tem rota aberta
dist order to order é  4.2009286759587745 hub em questão 3
dist order to hub é  1.5129360100314033 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 3
passou aqui1
rota em aberto, route_id:  111
rota_escolhida: 111
orders no hub: 2
passou aqui3

passou aqui4
345
     order_id  order_latitude  order_longitude      ordered_at_brt
344       345       -23.71901       -46.659566 2024-04-02 03:19:00
2024-04-02 03:19:00
tem rota aberta
dist order to order é  0.7981715957915488 hub em questão 3
dist order to hub é  5.591957112703578 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 111
346
     order_id  order_latitude  order_longitude      ordered_at_brt
345       346        -23.5981       -46.587234 2024-04-02 03:22:00
2024-04-02 03:22:00
não tem rota aberta
route_id 112
dist pro hub mais próximo é 6.25
hub alocado 14
347
     order_id  order_latitude  order_longitude      ordered_at_brt
346       347      -23.624064       -46.663915 2024-04-02 03:27:00
2024-04-02 03:27:00
tem rota aberta
dist order to order é  8.329156551032703 hub em questão 14
dist order to hub é  10.587911658499676 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 112
348
     order_id  order_latitude  order_longitude      ordered_at_brt
347       348      -23.652259       -46.651578 2024-04-02 03:30:00
2024-04-02 03:30:00
tem rota aberta
dist order to order é  3.3776219635227203 hub em questão 14
dist order to hub é  13.005118773713054 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 112
349
     order_id  order_latitude  order_longitude      ordered_at_brt
348       349       -23.65032       -46.602003 2024-04-02 03:36:00
2024-04-02 03:36:00
tem rota aberta
dist order to order é  5.054082534253976 hub em questão 14
dist order to hub é  9.31905986848028 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 112
350
     order_id  order_latitude  order_longitude      ordered_at_brt
349       350      -23.700678        -46.79801 2024-04-02 03:44:00
2024-04-02 03:44:00
não tem rota aberta
route_id 113
dist pro hub mais próximo é 7.92
hub alocado 4
351
     order_id  order_latitude  order_longitude      ordered_at_brt
350       351      -23.606718       -46.648396 2024-04-02 03:46:00
2024-04-02 03:46:00
tem rota aberta
dist order to order é  18.476411606247517 hub em questão 4
dist order to hub é  8.598511908424307 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 4
passou aqui1
passou aqui5
route_id 114
caiu aqui tb
352
     order_id  order_latitude  order_longitude      ordered_at_brt
351       352      -23.735318       -46.610161 2024-04-02 03:51:00
2024-04-02 03:51:00
tem rota aberta
dist order to order é  14.82040641529541 hub em questão 16
dist order to hub é  7.525999968153222 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 115
caiu aqui tb
353
     order_id  order_latitude  order_longitude      ordered_at_brt
352       353      -23.648526       -46.625475 2024-04-02 03:54:00
2024-04-02 03:54:00
tem rota aberta
dist order to order é  5.202394134233365 hub em questão 16
dist order to hub é  11.290215573593882 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 114
354
     order_id  order_latitude  order_longitude      ordered_at_brt
353       354       -23.67166       -46.630924 2024-04-02 04:00:00
2024-04-02 04:00:00
tem rota aberta
dist order to order é  2.6315587564693397 hub em questão 16
dist order to hub é  11.544819011023078 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 114
355
     order_id  order_latitude  order_longitude      ordered_at_brt
354       355      -23.650199       -46.709368 2024-04-02 04:05:00
2024-04-02 04:05:00
tem rota aberta
dist order to order é  7.8713722832394515 hub em questão 16
dist order to hub é  12.12389975843143 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 114
356
     order_id  order_latitude  order_longitude      ordered_at_brt
355       356       -23.62191        -46.66995 2024-04-02 04:10:00
2024-04-02 04:10:00
tem rota aberta
dist order to order é  14.003287702393553 hub em questão 3
dist order to hub é  10.439468675968001 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 116
caiu aqui tb
357
     order_id  order_latitude  order_longitude      ordered_at_brt
356       357      -23.701644       -46.570363 2024-04-02 04:16:00
2024-04-02 04:16:00
tem rota aberta
dist order to order é  5.516829386762643 hub em questão 3
dist order to hub é  11.810606670059476 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 115
358
     order_id  order_latitude  order_longitude      ordered_at_brt
357       358      -23.666283        -46.71655 2024-04-02 04:20:00
2024-04-02 04:20:00
tem rota aberta
dist order to order é  6.846624120996839 hub em questão 16
dist order to hub é  10.197861858451894 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 116
359
     order_id  order_latitude  order_longitude      ordered_at_brt
358       359      -23.651785       -46.680342 2024-04-02 04:26:00
2024-04-02 04:26:00
tem rota aberta
dist order to order é  3.486509068479566 hub em questão 16
dist order to hub é  12.839321838311923 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 116
360
     order_id  order_latitude  order_longitude      ordered_at_brt
359       360      -23.663839       -46.588109 2024-04-02 04:32:00
2024-04-02 04:32:00
tem rota aberta
dist order to order é  9.489133247096104 hub em questão 16
dist order to hub é  9.214413324760294 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 116
361
     order_id  order_latitude  order_longitude      ordered_at_brt
360       361      -23.598268       -46.657917 2024-04-02 04:36:00
2024-04-02 04:36:00
não tem rota aberta
route_id 117
dist pro hub mais próximo é 7.67
hub alocado 16
362
     order_id  order_latitude  order_longitude      ordered_at_brt
361       362      -23.618095       -46.712335 2024-04-02 04:40:00
2024-04-02 04:40:00
tem rota aberta
dist order to order é  5.966758040381381 hub em questão 16
dist order to hub é  11.611331047790792 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 117
363
     order_id  order_latitude  order_longitude      ordered_at_brt
362       363      -23.734078       -46.610377 2024-04-02 04:43:00
2024-04-02 04:43:00
tem rota aberta
dist order to order é  15.858609083281708 hub em questão 16
dist order to hub é  7.572636701237505 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 118
caiu aqui tb
364
     order_id  order_latitude  order_longitude      ordered_at_brt
363       364      -23.557411       -46.618494 2024-04-02 04:50:00
2024-04-02 04:50:00
tem rota aberta
dist order to order é  6.064830088981858 hub em questão 16
dist order to hub é  4.624665168815229 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 117
365
     order_id  order_latitude  order_longitude      ordered_at_brt
364       365      -23.620721       -46.579893 2024-04-02 04:55:00
2024-04-02 04:55:00
tem rota aberta
dist order to order é  8.06423715013783 hub em questão 16
dist order to hub é  5.800575609716269 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 119
caiu aqui tb
366
     order_id  order_latitude  order_longitude      ordered_at_brt
365       366      -23.633645       -46.613659 2024-04-02 04:57:00
2024-04-02 04:57:00
tem rota aberta
dist order to order é  3.728004415240707 hub em questão 14
dist order to hub é  9.524704342499922 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 119
367
     order_id  order_latitude  order_longitude      ordered_at_brt
366       367      -23.669292       -46.694315 2024-04-02 04:59:00
2024-04-02 04:59:00
tem rota aberta
dist order to order é  5.981479522715785 hub em questão 16
dist order to hub é  10.788562525003272 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 117
368
     order_id  order_latitude  order_longitude      ordered_at_brt
367       368      -23.729041       -46.595697 2024-04-02 04:59:00
2024-04-02 04:59:00
tem rota aberta
dist order to order é  1.595874892138294 hub em questão 3
dist order to hub é  9.153902209669056 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 118
369
     order_id  order_latitude  order_longitude      ordered_at_brt
368       369      -23.641758       -46.639524 2024-04-02 05:03:00
2024-04-02 05:03:00
tem rota aberta
dist order to order é  2.7848758230285364 hub em questão 14
dist order to hub é  12.308609443023904 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 119
370
     order_id  order_latitude  order_longitude      ordered_at_brt
369       370       -23.65116       -46.626889 2024-04-02 05:06:00

2024-04-02 05:06:00
tem rota aberta
dist order to order é  1.6580555765324119 hub em questão 14
dist order to hub é  11.550906006550097 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 119
371
     order_id  order_latitude  order_longitude      ordered_at_brt
370       371      -23.670956       -46.675283 2024-04-02 05:12:00
2024-04-02 05:12:00
tem rota aberta
dist order to order é  9.640305446827583 hub em questão 3
dist order to hub é  10.697721597458523 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 118
372
     order_id  order_latitude  order_longitude      ordered_at_brt
371       372      -23.633051       -46.562144 2024-04-02 05:20:00
2024-04-02 05:20:00
não tem rota aberta
route_id 120
dist pro hub mais próximo é 4.93
hub alocado 14
373
     order_id  order_latitude  order_longitude      ordered_at_brt
372       373      -23.673402        -46.66228 2024-04-02 05:23:00
2024-04-02 05:23:00
tem rota aberta
dist order to order é  11.142539201645295 hub em questão 14
dist order to hub é  10.511146221133327 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 120
374
     order_id  order_latitude  order_longitude      ordered_at_brt
373       374      -23.692491       -46.641194 2024-04-02 05:27:00
2024-04-02 05:27:00
tem rota aberta
dist order to order é  3.0193316023750074 hub em questão 14
dist order to hub é  9.004117707423019 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 120
375
     order_id  order_latitude  order_longitude      ordered_at_brt
374       375      -23.765269       -46.598535 2024-04-02 05:30:00
2024-04-02 05:30:00
tem rota aberta
dist order to order é  9.18405603935644 hub em questão 14
dist order to hub é  6.058860445179089 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 14
passou aqui1
passou aqui5
route_id 121
caiu aqui tb
376
     order_id  order_latitude  order_longitude      ordered_at_brt
375       376      -23.679582       -46.630704 2024-04-02 05:35:00
2024-04-02 05:35:00
tem rota aberta
dist order to order é  1.789257584038267 hub em questão 14
dist order to hub é  10.749542451133578 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 120
377
     order_id  order_latitude  order_longitude      ordered_at_brt
376       377      -23.668049       -46.721126 2024-04-02 05:40:00
2024-04-02 05:40:00
tem rota aberta
dist order to order é  16.51132754514685 hub em questão 6
dist order to hub é  9.879891591338236 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 6
passou aqui1
passou aqui5
route_id 122
caiu aqui tb
378
     order_id  order_latitude  order_longitude      ordered_at_brt
377       378      -23.683676       -46.658384 2024-04-02 05:46:00
2024-04-02 05:46:00
tem rota aberta
dist order to order é  6.621493438083667 hub em questão 4
dist order to hub é  9.443761012919719 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 122
379
     order_id  order_latitude  order_longitude      ordered_at_brt
378       379      -23.663874        -46.62494 2024-04-02 05:46:00
2024-04-02 05:46:00
tem rota aberta
dist order to order é  4.055585570085131 hub em questão 4
dist order to hub é  12.098782253146263 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 122
380
     order_id  order_latitude  order_longitude      ordered_at_brt
379       380      -23.683188       -46.684473 2024-04-02 05:53:00
2024-04-02 05:53:00
tem rota aberta
dist order to order é  2.6572519924157385 hub em questão 4
dist order to hub é  9.383129142583286 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 122
381
     order_id  order_latitude  order_longitude      ordered_at_brt
380       381      -23.728607       -46.607284 2024-04-02 05:57:00
2024-04-02 05:57:00
tem rota aberta
dist order to order é  4.172849153377808 hub em questão 6
dist order to hub é  8.152250848559897 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 121
382
     order_id  order_latitude  order_longitude      ordered_at_brt
381       382      -23.598959       -46.658091 2024-04-02 06:03:00
2024-04-02 06:03:00
não tem rota aberta
route_id 123
dist pro hub mais próximo é 7.75
hub alocado 16
383
     order_id  order_latitude  order_longitude      ordered_at_brt
382       383      -23.661521       -46.565898 2024-04-02 06:08:00
2024-04-02 06:08:00
tem rota aberta
dist order to order é  11.687667159162528 hub em questão 16
dist order to hub é  7.621064605621874 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 124
caiu aqui tb
384
     order_id  order_latitude  order_longitude      ordered_at_brt
383       384      -23.730876       -46.758648 2024-04-02 06:11:00
2024-04-02 06:11:00
tem rota aberta
dist order to order é  17.889829776161058 hub em questão 16
dist order to hub é  2.852988329802822 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 16
passou aqui1
passou aqui5
route_id 125
caiu aqui tb
385
     order_id  order_latitude  order_longitude      ordered_at_brt
384       385      -23.660068       -46.680361 2024-04-02 06:16:00
2024-04-02 06:16:00
tem rota aberta
dist order to order é  7.1637040466293636 hub em questão 16
dist order to hub é  11.919121101699066 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 123
386
     order_id  order_latitude  order_longitude      ordered_at_brt
385       386      -23.712453       -46.605005 2024-04-02 06:21:00
2024-04-02 06:21:00
tem rota aberta
dist order to order é  6.923297012394605 hub em questão 14
dist order to hub é  9.40020666681095 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 124
387
     order_id  order_latitude  order_longitude      ordered_at_brt
386       387      -23.714537       -46.586946 2024-04-02 06:25:00
2024-04-02 06:25:00
tem rota aberta
dist order to order é  1.8531148938011852 hub em questão 14
dist order to hub é  10.738854129483704 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 124
388
     order_id  order_latitude  order_longitude      ordered_at_brt
387       388      -23.608122       -46.686834 2024-04-02 06:26:00
2024-04-02 06:26:00
tem rota aberta
dist order to order é  3.100838792033889 hub em questão 16
dist order to hub é  9.435960569131902 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 123
389
     order_id  order_latitude  order_longitude      ordered_at_brt
388       389      -23.668891       -46.623244 2024-04-02 06:30:00
2024-04-02 06:30:00
tem rota aberta
dist order to order é  5.187728147423507 hub em questão 14
dist order to hub é  12.149527712841461 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 124
390
     order_id  order_latitude  order_longitude      ordered_at_brt
389       390      -23.574702       -46.613782 2024-04-02 06:34:00
2024-04-02 06:34:00
tem rota aberta
dist order to order é  22.78781813518304 hub em questão 4
dist order to hub é  6.368133328202252 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 4
passou aqui1
passou aqui5
route_id 126
caiu aqui tb
391
     order_id  order_latitude  order_longitude      ordered_at_brt
390       391      -23.661336       -46.566906 2024-04-02 06:38:00
2024-04-02 06:38:00
tem rota aberta
dist order to order é  10.752117726896751 hub em questão 16
dist order to hub é  7.658745596648151 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 127
caiu aqui tb
392
     order_id  order_latitude  order_longitude      ordered_at_brt
391       392      -23.692374       -46.696395 2024-04-02 06:40:00
2024-04-02 06:40:00
tem rota aberta
dist order to order é  7.648370536066235 hub em questão 4
dist order to hub é  8.514877456934451 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 125
393
     order_id  order_latitude  order_longitude      ordered_at_brt
392       393      -23.670736       -46.540765 2024-04-02 06:43:00
2024-04-02 06:43:00
tem rota aberta
dist order to order é  2.8600797322250675 hub em questão 14
dist order to hub é  7.628762823519814 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 127
394
     order_id  order_latitude  order_longitude      ordered_at_brt
393       394      -23.633731        -46.58815 2024-04-02 06:46:00
2024-04-02 06:46:00
tem rota aberta
dist order to order é  3.755594036978011 hub em questão 14
dist order to hub é  7.156137825006175 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 127
395
     order_id  order_latitude  order_longitude      ordered_at_brt
394       395      -23.651847       -46.705226 2024-04-02 06:49:00
2024-04-02 06:49:00
tem rota aberta
dist order to order é  12.094502320191928 hub em questão 14
dist order to hub é  12.088861685913633 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 127
396
     order_id  order_latitude  order_longitude      ordered_at_brt
395       396      -23.683591       -46.678915 2024-04-02 06:54:00
2024-04-02 06:54:00
tem rota aberta

dist order to order é  13.806839367461903 hub em questão 16
dist order to hub é  9.299636152396559 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 128
caiu aqui tb
397
     order_id  order_latitude  order_longitude      ordered_at_brt
396       397      -23.667445        -46.65353 2024-04-02 07:01:00
2024-04-02 07:01:00
tem rota aberta
dist order to order é  3.1474547405520847 hub em questão 3
dist order to hub é  11.309707341893485 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 128
398
     order_id  order_latitude  order_longitude      ordered_at_brt
397       398      -23.739902       -46.643424 2024-04-02 07:06:00
2024-04-02 07:06:00
tem rota aberta
dist order to order é  7.22920969210719 hub em questão 3
dist order to hub é  4.448216036707756 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 3
passou aqui1
rota em aberto, route_id:  128
rota_escolhida: 128
orders no hub: 2
passou aqui3
passou aqui4
399
     order_id  order_latitude  order_longitude      ordered_at_brt
398       399      -23.718646        -46.62023 2024-04-02 07:10:00
2024-04-02 07:10:00
tem rota aberta
dist order to order é  3.3407591184344487 hub em questão 3
dist order to hub é  7.7877425730593215 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 128
400
     order_id  order_latitude  order_longitude      ordered_at_brt
399       400      -23.694223        -46.69455 2024-04-02 07:14:00
2024-04-02 07:14:00
não tem rota aberta
route_id 129
dist pro hub mais próximo é 8.34
hub alocado 3
401
     order_id  order_latitude  order_longitude      ordered_at_brt
400       401       -23.67364       -46.656089 2024-04-02 07:15:00
2024-04-02 07:15:00
tem rota aberta
dist order to order é  4.536205404078604 hub em questão 3
dist order to hub é  10.58375792040804 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 129
402
     order_id  order_latitude  order_longitude      ordered_at_brt
401       402      -23.655018       -46.646785 2024-04-02 07:17:00
2024-04-02 07:17:00
tem rota aberta
dist order to order é  2.277064257197944 hub em questão 3
dist order to hub é  12.805954263130774 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 129
403
     order_id  order_latitude  order_longitude      ordered_at_brt
402       403      -23.657516       -46.697695 2024-04-02 07:19:00
2024-04-02 07:19:00
tem rota aberta
dist order to order é  4.094083385709275 hub em questão 3
dist order to hub é  11.799245834518201 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 129
404
     order_id  order_latitude  order_longitude      ordered_at_brt
403       404      -23.620236       -46.652314 2024-04-02 07:23:00
2024-04-02 07:23:00
não tem rota aberta
route_id 130
dist pro hub mais próximo é 10.09
hub alocado 16
405
     order_id  order_latitude  order_longitude      ordered_at_brt
404       405      -23.564329       -46.549167 2024-04-02 07:30:00
2024-04-02 07:30:00
tem rota aberta
dist order to order é  12.211653428949374 hub em questão 16
dist order to hub é  4.940359678268274 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 131
caiu aqui tb
406
     order_id  order_latitude  order_longitude      ordered_at_brt
405       406      -23.602788       -46.559814 2024-04-02 07:34:00
2024-04-02 07:34:00
tem rota aberta
dist order to order é  4.412003260249024 hub em questão 14
dist order to hub é  3.4284660196478467 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 131
407
     order_id  order_latitude  order_longitude      ordered_at_brt
406       407      -23.686844       -46.621741 2024-04-02 07:42:00
2024-04-02 07:42:00
tem rota aberta
dist order to order é  8.03450854310622 hub em questão 16
dist order to hub é  10.469605060374203 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 130
408
     order_id  order_latitude  order_longitude      ordered_at_brt
407       408      -23.637013       -46.612077 2024-04-02 07:46:00
2024-04-02 07:46:00
tem rota aberta
dist order to order é  4.503634555839256 hub em questão 16
dist order to hub é  9.514492085572122 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 130
409
     order_id  order_latitude  order_longitude      ordered_at_brt
408       409      -23.724905       -46.675894 2024-04-02 07:51:00
2024-04-02 07:51:00
tem rota aberta
dist order to order é  6.950523546615212 hub em questão 16
dist order to hub é  4.699165481461072 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 132
caiu aqui tb
410
     order_id  order_latitude  order_longitude      ordered_at_brt
409       410      -23.626265       -46.668642 2024-04-02 07:54:00
2024-04-02 07:54:00
tem rota aberta
dist order to order é  10.99311743352799 hub em questão 3
dist order to hub é  10.89516196061444 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 132
411
     order_id  order_latitude  order_longitude      ordered_at_brt
410       411      -23.612641       -46.733492 2024-04-02 07:57:00
2024-04-02 07:57:00
tem rota aberta
dist order to order é  6.77842965379441 hub em questão 3
dist order to hub é  11.637461719737185 hub em questão 19
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 132
412
     order_id  order_latitude  order_longitude      ordered_at_brt
411       412      -23.754987       -46.654221 2024-04-02 08:02:00
2024-04-02 08:02:00
tem rota aberta
dist order to order é  4.006881315784977 hub em questão 3
dist order to hub é  2.5463033015595316 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 132
413
     order_id  order_latitude  order_longitude      ordered_at_brt
412       413      -23.762733        -46.65399 2024-04-02 08:09:00
2024-04-02 08:09:00
não tem rota aberta
route_id 133
dist pro hub mais próximo é 2.23
hub alocado 3
414
     order_id  order_latitude  order_longitude      ordered_at_brt
413       414      -23.644519       -46.576121 2024-04-02 08:17:00
2024-04-02 08:17:00
tem rota aberta
dist order to order é  15.350572467347314 hub em questão 3
dist order to hub é  6.837609804620774 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 134
caiu aqui tb
415
     order_id  order_latitude  order_longitude      ordered_at_brt
414       415      -23.612178       -46.622995 2024-04-02 08:23:00
2024-04-02 08:23:00
tem rota aberta
dist order to order é  5.977906643819103 hub em questão 14
dist order to hub é  9.663684572262994 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 134
416
     order_id  order_latitude  order_longitude      ordered_at_brt
415       416      -23.578359       -46.696491 2024-04-02 08:28:00
2024-04-02 08:28:00
tem rota aberta
dist order to order é  8.380272304298668 hub em questão 14
dist order to hub é  6.967859602445613 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 134
417
     order_id  order_latitude  order_longitude      ordered_at_brt
416       417      -23.655526       -46.593401 2024-04-02 08:31:00
2024-04-02 08:31:00
tem rota aberta
dist order to order é  2.1437412222989964 hub em questão 14
dist order to hub é  8.968880414506579 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 134
418
     order_id  order_latitude  order_longitude      ordered_at_brt
417       418      -23.648962       -46.753001 2024-04-02 08:34:00
2024-04-02 08:34:00
tem rota aberta
dist order to order é  16.175903368201787 hub em questão 3
dist order to hub é  11.686364357731549 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 3
passou aqui1
passou aqui5
route_id 135
caiu aqui tb
419
     order_id  order_latitude  order_longitude      ordered_at_brt
418       419      -23.648384       -46.695149 2024-04-02 08:41:00
2024-04-02 08:41:00
tem rota aberta
dist order to order é  5.893009458621224 hub em questão 4
dist order to hub é  12.831457477368156 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 135
420
     order_id  order_latitude  order_longitude      ordered_at_brt
419       420      -23.584507       -46.652115 2024-04-02 08:44:00
2024-04-02 08:44:00
tem rota aberta

dist order to order é  8.3469764540898 hub em questão 4
dist order to hub é  6.12055383777269 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 4
passou aqui1
passou aqui5
route_id 136
caiu aqui tb
421
     order_id  order_latitude  order_longitude      ordered_at_brt
420       421       -23.71312       -46.599923 2024-04-02 08:50:00
2024-04-02 08:50:00
tem rota aberta
dist order to order é  12.07683082830989 hub em questão 4
dist order to hub é  9.754395441318845 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 4
passou aqui1
passou aqui5
route_id 137
caiu aqui tb
422
     order_id  order_latitude  order_longitude      ordered_at_brt
421       422      -23.665639       -46.687575 2024-04-02 08:54:00
2024-04-02 08:54:00
tem rota aberta
dist order to order é  2.0680193950342054 hub em questão 4
dist order to hub é  11.356691242382205 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 135
423
     order_id  order_latitude  order_longitude      ordered_at_brt
422       423      -23.734695       -46.582608 2024-04-02 09:02:00
2024-04-02 09:02:00
tem rota aberta
dist order to order é  2.9768922575936934 hub em questão 3
dist order to hub é  9.595521460706529 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 137
424
     order_id  order_latitude  order_longitude      ordered_at_brt
423       424      -23.765834       -46.596961 2024-04-02 09:09:00
2024-04-02 09:09:00
tem rota aberta
dist order to order é  3.758009284575158 hub em questão 3
dist order to hub é  6.145777117900488 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 137
425
     order_id  order_latitude  order_longitude      ordered_at_brt
424       425      -23.507889       -46.581207 2024-04-02 09:15:00
2024-04-02 09:15:00
tem rota aberta
dist order to order é  22.900238208043735 hub em questão 3
dist order to hub é  4.684780741813514 hub em questão 17
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 17
hub_order 3
passou aqui1
passou aqui5
route_id 138
caiu aqui tb
426
     order_id  order_latitude  order_longitude      ordered_at_brt
425       426      -23.675518        -46.68921 2024-04-02 09:19:00
2024-04-02 09:19:00
tem rota aberta
dist order to order é  10.006737113013841 hub em questão 3
dist order to hub é  10.286919385545199 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 137
427
     order_id  order_latitude  order_longitude      ordered_at_brt
426       427       -23.56223       -46.647907 2024-04-02 09:27:00
2024-04-02 09:27:00
tem rota aberta
dist order to order é  9.096575670184292 hub em questão 17
dist order to hub é  3.668360904820202 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 17
passou aqui1
passou aqui5
route_id 139
caiu aqui tb
428
     order_id  order_latitude  order_longitude      ordered_at_brt
427       428      -23.676541       -46.689951 2024-04-02 09:37:00
2024-04-02 09:37:00
tem rota aberta
dist order to order é  13.413086465529231 hub em questão 16
dist order to hub é  10.18492345247224 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 140
caiu aqui tb
429
     order_id  order_latitude  order_longitude      ordered_at_brt
428       429      -23.613059       -46.615597 2024-04-02 09:44:00
2024-04-02 09:44:00
tem rota aberta
dist order to order é  6.541066796122055 hub em questão 16
dist order to hub é  9.173686271395624 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 139
430
     order_id  order_latitude  order_longitude      ordered_at_brt
429       430      -23.640446       -46.751052 2024-04-02 09:48:00
2024-04-02 09:48:00
tem rota aberta
dist order to order é  7.405135108429563 hub em questão 3
dist order to hub é  12.622475748755372 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 140
431
     order_id  order_latitude  order_longitude      ordered_at_brt
430       431       -23.66551       -46.596977 2024-04-02 09:51:00
2024-04-02 09:51:00
tem rota aberta
dist order to order é  6.132972819220123 hub em questão 16
dist order to hub é  9.98259644499611 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 139
432
     order_id  order_latitude  order_longitude      ordered_at_brt
431       432      -23.681279       -46.592289 2024-04-02 09:57:00
2024-04-02 09:57:00
tem rota aberta
dist order to order é  9.959169290061139 hub em questão 3
dist order to hub é  10.96639722354852 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 140
433
     order_id  order_latitude  order_longitude      ordered_at_brt
432       433      -23.687636       -46.580484 2024-04-02 10:02:00
2024-04-02 10:02:00
tem rota aberta
dist order to order é  1.3944955123765976 hub em questão 3
dist order to hub é  10.874080799541034 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 140
434
     order_id  order_latitude  order_longitude      ordered_at_brt
433       434      -23.638732       -46.592932 2024-04-02 10:12:00
2024-04-02 10:12:00
não tem rota aberta
route_id 141
dist pro hub mais próximo é 7.85
hub alocado 14
435
     order_id  order_latitude  order_longitude      ordered_at_brt
434       435      -23.581222       -46.693838 2024-04-02 10:18:00
2024-04-02 10:18:00
tem rota aberta
dist order to order é  12.1075234456816 hub em questão 14
dist order to hub é  7.157493357178214 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 142
caiu aqui tb
436
     order_id  order_latitude  order_longitude      ordered_at_brt
435       436      -23.603878       -46.615909 2024-04-02 10:28:00
2024-04-02 10:28:00
tem rota aberta
dist order to order é  4.527624577780158 hub em questão 14
dist order to hub é  9.059126937847351 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 141
437
     order_id  order_latitude  order_longitude      ordered_at_brt
436       437      -23.648505        -46.62692 2024-04-02 10:32:00
2024-04-02 10:32:00
tem rota aberta
dist order to order é  3.628589267149281 hub em questão 14
dist order to hub é  11.42123936732948 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 141
438
     order_id  order_latitude  order_longitude      ordered_at_brt
437       438      -23.651434       -46.681006 2024-04-02 10:40:00
2024-04-02 10:40:00
tem rota aberta
dist order to order é  5.518651489991982 hub em questão 14
dist order to hub é  12.881107985062739 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 141
439
     order_id  order_latitude  order_longitude      ordered_at_brt
438       439      -23.671852       -46.715922 2024-04-02 10:50:00
2024-04-02 10:50:00
não tem rota aberta
route_id 143
dist pro hub mais próximo é 9.63
hub alocado 4
440
     order_id  order_latitude  order_longitude      ordered_at_brt
439       440      -23.661951       -46.701355 2024-04-02 10:54:00
2024-04-02 10:54:00
tem rota aberta
dist order to order é  1.847472307687156 hub em questão 4
dist order to hub é  11.196220740005986 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 143
441
     order_id  order_latitude  order_longitude      ordered_at_brt
440       441      -23.634219       -46.717474 2024-04-02 11:00:00
2024-04-02 11:00:00
tem rota aberta
dist order to order é  3.493436831817709 hub em questão 4
dist order to hub é  13.419326732736936 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 143
442
     order_id  order_latitude  order_longitude      ordered_at_brt
441       442      -23.773926       -46.702982 2024-04-02 11:03:00
2024-04-02 11:03:00
tem rota aberta
dist order to order é  11.426320633264805 hub em questão 4
dist order to hub é  2.904747750452474 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 4
passou aqui1
passou aqui5
route_id 144
caiu aqui tb
443
     order_id  order_latitude  order_longitude      ordered_at_brt
442       443      -23.581897        -46.71292 2024-04-02 11:10:00
2024-04-02 11:10:00
tem rota aberta
dist order to order é  5.8364277196267205 hub em questão 4
dist order to hub é  7.837868883039697 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 143
444
     order_id  order_latitude  order_longitude      ordered_at_brt
443       444      -23.621108       -46.673708 2024-04-02 11:14:00
2024-04-02 11:14:00
tem rota aberta

dist order to order é  17.252030490289183 hub em questão 3
dist order to hub é  10.425807654458662 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 145
caiu aqui tb
445
     order_id  order_latitude  order_longitude      ordered_at_brt
444       445      -23.676306       -46.680886 2024-04-02 11:18:00
2024-04-02 11:18:00
tem rota aberta
dist order to order é  6.181177586352637 hub em questão 16
dist order to hub é  10.118187456880044 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 145
446
     order_id  order_latitude  order_longitude      ordered_at_brt
445       446      -23.662399       -46.687092 2024-04-02 11:24:00
2024-04-02 11:24:00
tem rota aberta
dist order to order é  1.6705614110654854 hub em questão 16
dist order to hub é  11.709756254739377 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 145
447
     order_id  order_latitude  order_longitude      ordered_at_brt
446       447      -23.665675       -46.715416 2024-04-02 11:26:00
2024-04-02 11:26:00
tem rota aberta
dist order to order é  2.9075826021950673 hub em questão 16
dist order to hub é  10.297020064427542 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 145
448
     order_id  order_latitude  order_longitude      ordered_at_brt
447       448      -23.561956       -46.677211 2024-04-02 11:30:00
2024-04-02 11:30:00
tem rota aberta
dist order to order é  23.71565777226145 hub em questão 3
dist order to hub é  4.428340990933407 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 146
caiu aqui tb
449
     order_id  order_latitude  order_longitude      ordered_at_brt
448       449      -23.712694       -46.645344 2024-04-02 11:33:00
2024-04-02 11:33:00
tem rota aberta
dist order to order é  17.072779964037228 hub em questão 16
dist order to hub é  6.78593754969657 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 147
caiu aqui tb
450
     order_id  order_latitude  order_longitude      ordered_at_brt
449       450      -23.614146       -46.708294 2024-04-02 11:41:00
2024-04-02 11:41:00
tem rota aberta
dist order to order é  6.611338227056354 hub em questão 16
dist order to hub é  11.02149932203142 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 146
451
     order_id  order_latitude  order_longitude      ordered_at_brt
450       451      -23.554451       -46.646839 2024-04-02 11:47:00
2024-04-02 11:47:00
tem rota aberta
dist order to order é  3.2062484852101734 hub em questão 16
dist order to hub é  2.8295793063510213 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 146
452
     order_id  order_latitude  order_longitude      ordered_at_brt
451       452      -23.714711       -46.686683 2024-04-02 11:50:00
2024-04-02 11:50:00
tem rota aberta
dist order to order é  4.214582740040776 hub em questão 3
dist order to hub é  5.944239377612631 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 147
453
     order_id  order_latitude  order_longitude      ordered_at_brt
452       453      -23.622905       -46.602596 2024-04-02 11:57:00
2024-04-02 11:57:00
tem rota aberta
dist order to order é  8.846882251300475 hub em questão 16
dist order to hub é  8.081320993799393 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 146
454
     order_id  order_latitude  order_longitude      ordered_at_brt
453       454      -23.624857       -46.578625 2024-04-02 12:01:00
2024-04-02 12:01:00
tem rota aberta
dist order to order é  11.898060382204017 hub em questão 3
dist order to hub é  5.850403948516732 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 148
caiu aqui tb
455
     order_id  order_latitude  order_longitude      ordered_at_brt
454       455      -23.563777       -46.688566 2024-04-02 12:05:00
2024-04-02 12:05:00
tem rota aberta
dist order to order é  13.100871131997124 hub em questão 14
dist order to hub é  5.241896292917101 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 14
passou aqui1
passou aqui5
route_id 149
caiu aqui tb
456
     order_id  order_latitude  order_longitude      ordered_at_brt
455       456      -23.633725       -46.771182 2024-04-02 12:07:00
2024-04-02 12:07:00
tem rota aberta
dist order to order é  11.461274359233954 hub em questão 7
dist order to hub é  13.599787599698535 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 149
457
     order_id  order_latitude  order_longitude      ordered_at_brt
456       457      -23.544939       -46.668567 2024-04-02 12:11:00
2024-04-02 12:11:00
tem rota aberta
dist order to order é  2.922863108329885 hub em questão 7
dist order to hub é  2.4045522867514473 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 149
458
     order_id  order_latitude  order_longitude      ordered_at_brt
457       458      -23.731369       -46.623277 2024-04-02 12:14:00
2024-04-02 12:14:00
tem rota aberta
dist order to order é  12.68644787839728 hub em questão 14
dist order to hub é  6.632955640115198 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 14
passou aqui1
passou aqui5
route_id 150
caiu aqui tb
459
     order_id  order_latitude  order_longitude      ordered_at_brt
458       459      -23.687577        -46.68295 2024-04-02 12:19:00
2024-04-02 12:19:00
tem rota aberta
dist order to order é  7.785948330894773 hub em questão 3
dist order to hub é  8.882846431085992 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 150
460
     order_id  order_latitude  order_longitude      ordered_at_brt
459       460      -23.674831       -46.765936 2024-04-02 12:25:00
2024-04-02 12:25:00
tem rota aberta
dist order to order é  4.601915574291788 hub em questão 7
dist order to hub é  9.015635246589488 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 149
461
     order_id  order_latitude  order_longitude      ordered_at_brt
460       461      -23.642023       -46.709113 2024-04-02 12:28:00
2024-04-02 12:28:00
tem rota aberta
dist order to order é  5.723452173038338 hub em questão 3
dist order to hub é  12.999007919422896 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 150
462
     order_id  order_latitude  order_longitude      ordered_at_brt
461       462      -23.755158       -46.641661 2024-04-02 12:34:00
2024-04-02 12:34:00
tem rota aberta
dist order to order é  3.2401916934074513 hub em questão 3
dist order to hub é  3.68494503275798 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 150
463
     order_id  order_latitude  order_longitude      ordered_at_brt
462       463      -23.613733        -46.64156 2024-04-02 12:43:00
2024-04-02 12:43:00
não tem rota aberta
route_id 151
dist pro hub mais próximo é 9.43
hub alocado 16
464
     order_id  order_latitude  order_longitude      ordered_at_brt
463       464      -23.612895       -46.648477 2024-04-02 12:47:00
2024-04-02 12:47:00
tem rota aberta
dist order to order é  0.7108920699718297 hub em questão 16
dist order to hub é  9.284421581878151 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 151
465
     order_id  order_latitude  order_longitude      ordered_at_brt
464       465      -23.744426       -46.664977 2024-04-02 12:55:00
2024-04-02 12:55:00
tem rota aberta
dist order to order é  14.721830937547022 hub em questão 16
dist order to hub é  2.7422237158671248 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 152
caiu aqui tb
466
     order_id  order_latitude  order_longitude      ordered_at_brt
465       466      -23.705967       -46.568495 2024-04-02 13:02:00
2024-04-02 13:02:00
tem rota aberta
dist order to order é  10.712226556949268 hub em questão 3
dist order to hub é  12.187836137054063 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 152
467
     order_id  order_latitude  order_longitude      ordered_at_brt
466       467      -23.625487       -46.665126 2024-04-02 13:07:00
2024-04-02 13:07:00
tem rota aberta
dist order to order é  2.1994710671653097 hub em questão 16
dist order to hub é  10.759616053432318 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 151
468
     order_id  order_latitude  order_longitude      ordered_at_brt
467       468      -23.597742       -46.608365 2024-04-02 13:12:00
2024-04-02 13:12:00
tem rota aberta
dist order to order é  3.821136553398036 hub em questão 16
dist order to hub é  8.398758199879856 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 151
469
     order_id  order_latitude  order_longitude      ordered_at_brt
468       469      -23.705501       -46.578874 2024-04-02 13:15:00
2024-04-02 13:15:00
tem rota aberta

dist order to order é  1.0579849501596266 hub em questão 3
dist order to hub é  11.982019180309072 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 152
470
     order_id  order_latitude  order_longitude      ordered_at_brt
469       470      -23.698515       -46.634824 2024-04-02 13:17:00
2024-04-02 13:17:00
tem rota aberta
dist order to order é  5.749331449578812 hub em questão 3
dist order to hub é  8.679668329044459 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 152
471
     order_id  order_latitude  order_longitude      ordered_at_brt
470       471      -23.588415       -46.705164 2024-04-02 13:20:00
2024-04-02 13:20:00
não tem rota aberta
route_id 153
dist pro hub mais próximo é 8.26
hub alocado 7
472
     order_id  order_latitude  order_longitude      ordered_at_brt
471       472      -23.689171       -46.610094 2024-04-02 13:27:00
2024-04-02 13:27:00
tem rota aberta
dist order to order é  14.808909196039428 hub em questão 7
dist order to hub é  10.927852866188541 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 7
passou aqui1
passou aqui5
route_id 154
caiu aqui tb
473
     order_id  order_latitude  order_longitude      ordered_at_brt
472       473      -23.598601        -46.71625 2024-04-02 13:37:00
2024-04-02 13:37:00
tem rota aberta
dist order to order é  1.599717904805201 hub em questão 7
dist order to hub é  9.690371961843645 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 153
474
     order_id  order_latitude  order_longitude      ordered_at_brt
473       474      -23.616464       -46.638189 2024-04-02 13:45:00
2024-04-02 13:45:00
tem rota aberta
dist order to order é  7.5031454927573025 hub em questão 7
dist order to hub é  9.777172289001447 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 153
475
     order_id  order_latitude  order_longitude      ordered_at_brt
474       475      -23.693183        -46.55873 2024-04-02 13:54:00
2024-04-02 13:54:00
tem rota aberta
dist order to order é  5.249110199150143 hub em questão 3
dist order to hub é  10.515105805927831 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 154
476
     order_id  order_latitude  order_longitude      ordered_at_brt
475       476      -23.658268       -46.650788 2024-04-02 14:03:00
2024-04-02 14:03:00
não tem rota aberta
route_id 155
dist pro hub mais próximo é 12.37
hub alocado 3
477
     order_id  order_latitude  order_longitude      ordered_at_brt
476       477      -23.657932       -46.659442 2024-04-02 14:04:00
2024-04-02 14:04:00
tem rota aberta
dist order to order é  0.8822093562547211 hub em questão 3
dist order to hub é  12.254260375175631 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 155
478
     order_id  order_latitude  order_longitude      ordered_at_brt
477       478      -23.675045       -46.650003 2024-04-02 14:09:00
2024-04-02 14:09:00
tem rota aberta
dist order to order é  1.8671644109801857 hub em questão 3
dist order to hub é  10.564646245592867 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 155
479
     order_id  order_latitude  order_longitude      ordered_at_brt
478       479      -23.573729       -46.651125 2024-04-02 14:14:00
2024-04-02 14:14:00
tem rota aberta
dist order to order é  9.400391626402703 hub em questão 3
dist order to hub é  4.9231065686113435 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 156
caiu aqui tb
480
     order_id  order_latitude  order_longitude      ordered_at_brt
479       480      -23.642088       -46.673267 2024-04-02 14:17:00
2024-04-02 14:17:00
tem rota aberta
dist order to order é  2.255403243579503 hub em questão 3
dist order to hub é  12.707787789830642 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 155
481
     order_id  order_latitude  order_longitude      ordered_at_brt
480       481      -23.711312       -46.645455 2024-04-02 14:20:00
2024-04-02 14:20:00
tem rota aberta
dist order to order é  15.30936659461371 hub em questão 16
dist order to hub é  6.918525365312528 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 157
caiu aqui tb
482
     order_id  order_latitude  order_longitude      ordered_at_brt
481       482      -23.766245       -46.612256 2024-04-02 14:22:00
2024-04-02 14:22:00
tem rota aberta
dist order to order é  6.9807502243044395 hub em questão 3
dist order to hub é  4.968579296048255 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 3
passou aqui1
passou aqui5
route_id 158
caiu aqui tb
483
     order_id  order_latitude  order_longitude      ordered_at_brt
482       483      -23.606378       -46.657466 2024-04-02 14:28:00
2024-04-02 14:28:00
tem rota aberta
dist order to order é  3.687465028895354 hub em questão 16
dist order to hub é  8.570036099897267 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 156
484
     order_id  order_latitude  order_longitude      ordered_at_brt
483       484      -23.685447        -46.69598 2024-04-02 14:32:00
2024-04-02 14:32:00
tem rota aberta
dist order to order é  5.893662987277595 hub em questão 3
dist order to hub é  9.168603406931933 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 157
485
     order_id  order_latitude  order_longitude      ordered_at_brt
484       485      -23.712793       -46.728621 2024-04-02 14:33:00
2024-04-02 14:33:00
tem rota aberta
dist order to order é  4.504592339985021 hub em questão 3
dist order to hub é  4.907241160292944 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 157
486
     order_id  order_latitude  order_longitude      ordered_at_brt
485       486      -23.715623       -46.655867 2024-04-02 14:38:00
2024-04-02 14:38:00
tem rota aberta
dist order to order é  1.1633198619451435 hub em questão 3
dist order to hub é  6.0664521727134915 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 157
487
     order_id  order_latitude  order_longitude      ordered_at_brt
486       487      -23.656307       -46.618566 2024-04-02 14:43:00
2024-04-02 14:43:00
tem rota aberta
dist order to order é  6.821000217989134 hub em questão 16
dist order to hub é  11.096897043122484 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 156
488
     order_id  order_latitude  order_longitude      ordered_at_brt
487       488      -23.661658       -46.717138 2024-04-02 14:49:00
2024-04-02 14:49:00
tem rota aberta
dist order to order é  15.787876118229105 hub em questão 6
dist order to hub é  10.673346789683777 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 6
passou aqui1
passou aqui5
route_id 159
caiu aqui tb
489
     order_id  order_latitude  order_longitude      ordered_at_brt
488       489      -23.639355        -46.69079 2024-04-02 14:55:00
2024-04-02 14:55:00
tem rota aberta
dist order to order é  3.6541141993391513 hub em questão 4
dist order to hub é  12.839992484773328 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 159
490
     order_id  order_latitude  order_longitude      ordered_at_brt
489       490       -23.67259       -46.645067 2024-04-02 15:00:00
2024-04-02 15:00:00
tem rota aberta
dist order to order é  5.945124539264669 hub em questão 4
dist order to hub é  10.960389662744442 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 159
491
     order_id  order_latitude  order_longitude      ordered_at_brt
490       491      -23.626955       -46.635643 2024-04-02 15:05:00
2024-04-02 15:05:00
tem rota aberta
dist order to order é  5.164332121180695 hub em questão 4
dist order to hub é  10.969455994805385 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 159
492
     order_id  order_latitude  order_longitude      ordered_at_brt
491       492      -23.602104       -46.720913 2024-04-02 15:10:00
2024-04-02 15:10:00
não tem rota aberta
route_id 160
dist pro hub mais próximo é 10.23
hub alocado 7
493
     order_id  order_latitude  order_longitude      ordered_at_brt
492       493      -23.619349       -46.649738 2024-04-02 15:12:00
2024-04-02 15:12:00
tem rota aberta
dist order to order é  7.501016093936064 hub em questão 7
dist order to hub é  9.997726531335987 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 160
494
     order_id  order_latitude  order_longitude      ordered_at_brt
493       494      -23.728161       -46.567995 2024-04-02 15:18:00
2024-04-02 15:18:00
tem rota aberta
dist order to order é  14.686425644304395 hub em questão 7
dist order to hub é  11.141307555910018 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 7
passou aqui1
passou aqui5
route_id 161
caiu aqui tb
495
     order_id  order_latitude  order_longitude      ordered_at_brt
494       495      -23.689822       -46.623545 2024-04-02 15:24:00
2024-04-02 15:24:00
tem rota aberta

dist order to order é  7.082292989444821 hub em questão 6
dist order to hub é  10.091255803568666 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 161
496
     order_id  order_latitude  order_longitude      ordered_at_brt
495       496      -23.479638       -46.663967 2024-04-02 15:33:00
2024-04-02 15:33:00
tem rota aberta
dist order to order é  14.80335893782621 hub em questão 7
dist order to hub é  3.5485703245393045 hub em questão 13
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 13
hub_order 7
passou aqui1
passou aqui5
route_id 162
caiu aqui tb
497
     order_id  order_latitude  order_longitude      ordered_at_brt
496       497      -23.657697        -46.67841 2024-04-02 15:40:00
2024-04-02 15:40:00
tem rota aberta
dist order to order é  6.631661848282304 hub em questão 6
dist order to hub é  12.175887586655822 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 161
498
     order_id  order_latitude  order_longitude      ordered_at_brt
497       498      -23.654932       -46.688228 2024-04-02 15:46:00
2024-04-02 15:46:00
tem rota aberta
dist order to order é  1.0461918600598146 hub em questão 6
dist order to hub é  12.486667160643272 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 161
499
     order_id  order_latitude  order_longitude      ordered_at_brt
498       499      -23.763198       -46.590641 2024-04-02 15:48:00
2024-04-02 15:48:00
tem rota aberta
dist order to order é  32.40331780378841 hub em questão 13
dist order to hub é  6.836135961339304 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 13
passou aqui1
passou aqui5
route_id 163
caiu aqui tb
500
     order_id  order_latitude  order_longitude      ordered_at_brt
499       500      -23.707499        -46.66722 2024-04-02 15:51:00
2024-04-02 15:51:00
tem rota aberta
dist order to order é  9.955828661922505 hub em questão 6
dist order to hub é  6.686495874255401 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 6
passou aqui1
passou aqui5
route_id 164
caiu aqui tb
501
     order_id  order_latitude  order_longitude      ordered_at_brt
500       501      -23.595766       -46.524644 2024-04-02 15:55:00
2024-04-02 15:55:00
tem rota aberta
dist order to order é  19.111542259388802 hub em questão 3
dist order to hub é  0.8678702575892985 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 165
caiu aqui tb
502
     order_id  order_latitude  order_longitude      ordered_at_brt
501       502      -23.615762       -46.583466 2024-04-02 15:59:00
2024-04-02 15:59:00
tem rota aberta
dist order to order é  6.392592557009391 hub em questão 14
dist order to hub é  5.995918328069698 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 165
503
     order_id  order_latitude  order_longitude      ordered_at_brt
502       503      -23.600051       -46.579339 2024-04-02 16:05:00
2024-04-02 16:05:00
tem rota aberta
dist order to order é  1.7968850371929435 hub em questão 14
dist order to hub é  5.43025052592728 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 165
504
     order_id  order_latitude  order_longitude      ordered_at_brt
503       504      -23.720251       -46.626486 2024-04-02 16:12:00
2024-04-02 16:12:00
tem rota aberta
dist order to order é  4.382618535974046 hub em questão 3
dist order to hub é  7.211599406776163 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 164
505
     order_id  order_latitude  order_longitude      ordered_at_brt
504       505      -23.632138        -46.66557 2024-04-02 16:16:00
2024-04-02 16:16:00
tem rota aberta
dist order to order é  8.38147444539891 hub em questão 3
dist order to hub é  11.49923967012528 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 164
506
     order_id  order_latitude  order_longitude      ordered_at_brt
505       506      -23.595357       -46.742618 2024-04-02 16:20:00
2024-04-02 16:20:00
tem rota aberta
dist order to order é  8.851548934915586 hub em questão 3
dist order to hub é  9.780277795990038 hub em questão 19
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 164
507
     order_id  order_latitude  order_longitude      ordered_at_brt
506       507      -23.733112       -46.612517 2024-04-02 16:22:00
2024-04-02 16:22:00
tem rota aberta
dist order to order é  13.379937697552451 hub em questão 14
dist order to hub é  7.4371266440056605 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 14
passou aqui1
passou aqui5
route_id 166
caiu aqui tb
508
     order_id  order_latitude  order_longitude      ordered_at_brt
507       508      -23.671608       -46.554033 2024-04-02 16:26:00
2024-04-02 16:26:00
tem rota aberta
dist order to order é  9.068020055517241 hub em questão 3
dist order to hub é  8.093363245392048 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 166
509
     order_id  order_latitude  order_longitude      ordered_at_brt
508       509      -23.643513       -46.647052 2024-04-02 16:31:00
2024-04-02 16:31:00
tem rota aberta
dist order to order é  9.975791214818345 hub em questão 3
dist order to hub é  12.692155594416814 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 166
510
     order_id  order_latitude  order_longitude      ordered_at_brt
509       510      -23.629651       -46.559273 2024-04-02 16:37:00
2024-04-02 16:37:00
tem rota aberta
dist order to order é  4.695846142149126 hub em questão 3
dist order to hub é  4.456883655180407 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 166
511
     order_id  order_latitude  order_longitude      ordered_at_brt
510       511      -23.610629       -46.686001 2024-04-02 16:43:00
2024-04-02 16:43:00
não tem rota aberta
route_id 167
dist pro hub mais próximo é 9.66
hub alocado 16
512
     order_id  order_latitude  order_longitude      ordered_at_brt
511       512      -23.695298       -46.711538 2024-04-02 16:47:00
2024-04-02 16:47:00
tem rota aberta
dist order to order é  9.767475984132043 hub em questão 16
dist order to hub é  7.4093203052338685 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 16
passou aqui1
passou aqui5
route_id 168
caiu aqui tb
513
     order_id  order_latitude  order_longitude      ordered_at_brt
512       513      -23.647115       -46.594248 2024-04-02 16:48:00
2024-04-02 16:48:00
tem rota aberta
dist order to order é  10.189571210359372 hub em questão 16
dist order to hub é  8.466229976025435 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 167
514
     order_id  order_latitude  order_longitude      ordered_at_brt
513       514      -23.613472       -46.700896 2024-04-02 16:54:00
2024-04-02 16:54:00
tem rota aberta
dist order to order é  1.5501615427091482 hub em questão 16
dist order to hub é  10.583021170156275 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 167
515
     order_id  order_latitude  order_longitude      ordered_at_brt
514       515      -23.632151       -46.580499 2024-04-02 16:58:00
2024-04-02 16:58:00
tem rota aberta
dist order to order é  2.174918936159714 hub em questão 16
dist order to hub é  6.3892427697294645 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 167
516
     order_id  order_latitude  order_longitude      ordered_at_brt
515       516      -23.667972       -46.568635 2024-04-02 17:02:00
2024-04-02 17:02:00
tem rota aberta
dist order to order é  14.865869300994733 hub em questão 4
dist order to hub é  8.378088791915951 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 4
passou aqui1
passou aqui5
route_id 169
caiu aqui tb
517
     order_id  order_latitude  order_longitude      ordered_at_brt
516       517      -23.679379       -46.617685 2024-04-02 17:06:00
2024-04-02 17:06:00
tem rota aberta
dist order to order é  5.1536939373711705 hub em questão 14
dist order to hub é  11.393512644305696 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 169
518
     order_id  order_latitude  order_longitude      ordered_at_brt
517       518      -23.671563        -46.63739 2024-04-02 17:13:00
2024-04-02 17:13:00
tem rota aberta
dist order to order é  2.18676088976872 hub em questão 14
dist order to hub é  11.312951542226294 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 169

519
     order_id  order_latitude  order_longitude      ordered_at_brt
518       519      -23.562068       -46.639275 2024-04-02 17:19:00
2024-04-02 17:19:00
tem rota aberta
dist order to order é  12.176839259389643 hub em questão 14
dist order to hub é  3.8537264349113127 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 170
caiu aqui tb
520
     order_id  order_latitude  order_longitude      ordered_at_brt
519       520      -23.725266       -46.598423 2024-04-02 17:20:00
2024-04-02 17:20:00
tem rota aberta
dist order to order é  5.466319726059488 hub em questão 14
dist order to hub é  9.116234216014597 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 169
521
     order_id  order_latitude  order_longitude      ordered_at_brt
520       521      -23.659574       -46.703498 2024-04-02 17:22:00
2024-04-02 17:22:00
tem rota aberta
dist order to order é  12.663751986550414 hub em questão 16
dist order to hub é  11.352570842732913 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 170
522
     order_id  order_latitude  order_longitude      ordered_at_brt
521       522      -23.644538         -46.6767 2024-04-02 17:27:00
2024-04-02 17:27:00
tem rota aberta
dist order to order é  3.2009329161645637 hub em questão 16
dist order to hub é  13.039085375744548 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 170
523
     order_id  order_latitude  order_longitude      ordered_at_brt
522       523      -23.751581       -46.681736 2024-04-02 17:34:00
2024-04-02 17:34:00
tem rota aberta
dist order to order é  10.46785485996333 hub em questão 16
dist order to hub é  1.8484001892874324 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 171
caiu aqui tb
524
     order_id  order_latitude  order_longitude      ordered_at_brt
523       524      -23.726592        -46.66049 2024-04-02 17:37:00
2024-04-02 17:37:00
tem rota aberta
dist order to order é  3.5210153050273836 hub em questão 3
dist order to hub é  4.760100403990912 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 171
525
     order_id  order_latitude  order_longitude      ordered_at_brt
524       525      -23.559046       -46.709914 2024-04-02 17:40:00
2024-04-02 17:40:00
tem rota aberta
dist order to order é  7.207760747945524 hub em questão 16
dist order to hub é  5.421662844012821 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 170
526
     order_id  order_latitude  order_longitude      ordered_at_brt
525       526      -23.592286       -46.713412 2024-04-02 17:43:00
2024-04-02 17:43:00
tem rota aberta
dist order to order é  15.877082984373905 hub em questão 3
dist order to hub é  8.931473978735998 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 3
passou aqui1
passou aqui5
route_id 172
caiu aqui tb
527
     order_id  order_latitude  order_longitude      ordered_at_brt
526       527      -23.668559       -46.656454 2024-04-02 17:51:00
2024-04-02 17:51:00
tem rota aberta
dist order to order é  6.466008570235807 hub em questão 3
dist order to hub é  11.13282927276355 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 171
528
     order_id  order_latitude  order_longitude      ordered_at_brt
527       528      -23.645914       -46.629497 2024-04-02 17:53:00
2024-04-02 17:53:00
tem rota aberta
dist order to order é  3.725381204727369 hub em questão 3
dist order to hub é  11.536941330857985 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 171
529
     order_id  order_latitude  order_longitude      ordered_at_brt
528       529      -23.708477       -46.677942 2024-04-02 17:59:00
2024-04-02 17:59:00
tem rota aberta
dist order to order é  13.415553540100001 hub em questão 7
dist order to hub é  6.530655012885221 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 7
passou aqui1
passou aqui5
route_id 173
caiu aqui tb
530
     order_id  order_latitude  order_longitude      ordered_at_brt
529       530       -23.67171       -46.673894 2024-04-02 18:03:00
2024-04-02 18:03:00
tem rota aberta
dist order to order é  4.10905233715706 hub em questão 3
dist order to hub é  10.615014803166314 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 173
531
     order_id  order_latitude  order_longitude      ordered_at_brt
530       531      -23.597573       -46.655548 2024-04-02 18:06:00
2024-04-02 18:06:00
tem rota aberta
dist order to order é  5.925519287730009 hub em questão 7
dist order to hub é  7.581623068180786 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 172
532
     order_id  order_latitude  order_longitude      ordered_at_brt
531       532      -23.699219       -46.567791 2024-04-02 18:11:00
2024-04-02 18:11:00
tem rota aberta
dist order to order é  11.22894738396531 hub em questão 3
dist order to hub é  11.462391246502584 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 173
533
     order_id  order_latitude  order_longitude      ordered_at_brt
532       533      -23.666204       -46.571252 2024-04-02 18:13:00
2024-04-02 18:13:00
tem rota aberta
dist order to order é  3.6879751756345134 hub em questão 3
dist order to hub é  8.353955557982058 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 173
534
     order_id  order_latitude  order_longitude      ordered_at_brt
533       534      -23.616734       -46.701505 2024-04-02 18:23:00
2024-04-02 18:23:00
não tem rota aberta
route_id 174
dist pro hub mais próximo é 10.93
hub alocado 16
535
     order_id  order_latitude  order_longitude      ordered_at_brt
534       535      -23.649231       -46.683005 2024-04-02 18:26:00
2024-04-02 18:26:00
tem rota aberta
dist order to order é  4.075424595184062 hub em questão 16
dist order to hub é  13.136297822961852 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 174
537
     order_id  order_latitude  order_longitude      ordered_at_brt
535       537      -23.671617        -46.73795 2024-04-02 18:31:00
2024-04-02 18:31:00
tem rota aberta
dist order to order é  6.124639087969182 hub em questão 16
dist order to hub é  9.18564613632095 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 174
536
     order_id  order_latitude  order_longitude      ordered_at_brt
536       536      -23.578508        -46.56794 2024-04-02 18:31:00
2024-04-02 18:31:00
tem rota aberta
dist order to order é  14.116676058696978 hub em questão 16
dist order to hub é  5.079506537831653 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 175
caiu aqui tb
538
     order_id  order_latitude  order_longitude      ordered_at_brt
537       538      -23.591565       -46.714212 2024-04-02 18:37:00
2024-04-02 18:37:00
tem rota aberta
dist order to order é  3.083535191849786 hub em questão 16
dist order to hub é  8.885010220349947 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 174
539
     order_id  order_latitude  order_longitude      ordered_at_brt
538       539      -23.659959         -46.6135 2024-04-02 18:44:00
2024-04-02 18:44:00
tem rota aberta
dist order to order é  10.177058839170442 hub em questão 14
dist order to hub é  10.891658508074118 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 175
540
     order_id  order_latitude  order_longitude      ordered_at_brt
539       540      -23.648431       -46.634717 2024-04-02 18:51:00
2024-04-02 18:51:00
tem rota aberta
dist order to order é  2.5125789428425307 hub em questão 14
dist order to hub é  12.136690628463095 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 175
541
     order_id  order_latitude  order_longitude      ordered_at_brt
540       541      -23.707317       -46.644983 2024-04-02 18:56:00
2024-04-02 18:56:00
tem rota aberta
dist order to order é  6.165141045212715 hub em questão 14
dist order to hub é  7.3400414165928956 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 175
542
     order_id  order_latitude  order_longitude      ordered_at_brt
541       542      -23.616214       -46.673915 2024-04-02 19:07:00
2024-04-02 19:07:00
não tem rota aberta
route_id 176

dist pro hub mais próximo é 9.9
hub alocado 16
543
     order_id  order_latitude  order_longitude      ordered_at_brt
542       543      -23.674466        -46.70489 2024-04-02 19:10:00
2024-04-02 19:10:00
tem rota aberta
dist order to order é  7.204861825181336 hub em questão 16
dist order to hub é  9.781698883262322 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 176
544
     order_id  order_latitude  order_longitude      ordered_at_brt
543       544      -23.663957       -46.540115 2024-04-02 19:15:00
2024-04-02 19:15:00
tem rota aberta
dist order to order é  14.626844449434266 hub em questão 16
dist order to hub é  6.876973210032621 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 177
caiu aqui tb
545
     order_id  order_latitude  order_longitude      ordered_at_brt
544       545       -23.64783       -46.627755 2024-04-02 19:21:00
2024-04-02 19:21:00
tem rota aberta
dist order to order é  5.871218452184625 hub em questão 16
dist order to hub é  11.465317379411868 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 176
546
     order_id  order_latitude  order_longitude      ordered_at_brt
545       546      -23.631219       -46.693381 2024-04-02 19:27:00
2024-04-02 19:27:00
tem rota aberta
dist order to order é  2.5916175201889904 hub em questão 16
dist order to hub é  12.071725923432835 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 176
547
     order_id  order_latitude  order_longitude      ordered_at_brt
546       547      -23.649883       -46.674734 2024-04-02 19:30:00
2024-04-02 19:30:00
tem rota aberta
dist order to order é  13.80004006516007 hub em questão 14
dist order to hub é  13.041125811501393 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 177
548
     order_id  order_latitude  order_longitude      ordered_at_brt
547       548      -23.617487       -46.593211 2024-04-02 19:37:00
2024-04-02 19:37:00
tem rota aberta
dist order to order é  7.480110921160757 hub em questão 14
dist order to hub é  7.006427417541957 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 177
549
     order_id  order_latitude  order_longitude      ordered_at_brt
548       549      -23.694347       -46.612127 2024-04-02 19:41:00
2024-04-02 19:41:00
tem rota aberta
dist order to order é  8.0681620602866 hub em questão 14
dist order to hub é  10.346792157893848 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 177
550
     order_id  order_latitude  order_longitude      ordered_at_brt
549       550      -23.656079       -46.643616 2024-04-02 19:46:00
2024-04-02 19:46:00
não tem rota aberta
route_id 178
dist pro hub mais próximo é 12.77
hub alocado 3
551
     order_id  order_latitude  order_longitude      ordered_at_brt
550       551      -23.621047       -46.606048 2024-04-02 19:50:00
2024-04-02 19:50:00
tem rota aberta
dist order to order é  5.460638887260442 hub em questão 3
dist order to hub é  8.370063922792365 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 178
552
     order_id  order_latitude  order_longitude      ordered_at_brt
551       552      -23.667831       -46.709085 2024-04-02 19:57:00
2024-04-02 19:57:00
tem rota aberta
dist order to order é  6.794687836672407 hub em questão 3
dist order to hub é  10.288048976482317 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 178
553
     order_id  order_latitude  order_longitude      ordered_at_brt
552       553      -23.710899       -46.616639 2024-04-02 20:00:00
2024-04-02 20:00:00
tem rota aberta
dist order to order é  6.686088209865723 hub em questão 3
dist order to hub é  8.656053824553851 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 178
554
     order_id  order_latitude  order_longitude      ordered_at_brt
553       554      -23.617984       -46.666389 2024-04-02 20:05:00
2024-04-02 20:05:00
não tem rota aberta
route_id 179
dist pro hub mais próximo é 9.95
hub alocado 16
555
     order_id  order_latitude  order_longitude      ordered_at_brt
554       555      -23.657857       -46.714166 2024-04-02 20:08:00
2024-04-02 20:08:00
tem rota aberta
dist order to order é  6.583540947664377 hub em questão 16
dist order to hub é  11.164766972000988 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 179
556
     order_id  order_latitude  order_longitude      ordered_at_brt
555       556      -23.774895       -46.646708 2024-04-02 20:13:00
2024-04-02 20:13:00
tem rota aberta
dist order to order é  14.714871370556263 hub em questão 16
dist order to hub é  2.7451746401697 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 16
passou aqui1
passou aqui5
route_id 180
caiu aqui tb
557
     order_id  order_latitude  order_longitude      ordered_at_brt
556       557      -23.700631       -46.614068 2024-04-02 20:16:00
2024-04-02 20:16:00
tem rota aberta
dist order to order é  8.900999887071581 hub em questão 6
dist order to hub é  9.680866209076324 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 180
558
     order_id  order_latitude  order_longitude      ordered_at_brt
557       558      -23.786081       -46.582415 2024-04-02 20:19:00
2024-04-02 20:19:00
tem rota aberta
dist order to order é  6.659278626998493 hub em questão 6
dist order to hub é  6.52516359850124 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 180
559
     order_id  order_latitude  order_longitude      ordered_at_brt
558       559      -23.593973        -46.68837 2024-04-02 20:26:00
2024-04-02 20:26:00
tem rota aberta
dist order to order é  3.4848914629032826 hub em questão 16
dist order to hub é  8.07010335412393 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 179
560
     order_id  order_latitude  order_longitude      ordered_at_brt
559       560      -23.677826       -46.553546 2024-04-02 20:29:00
2024-04-02 20:29:00
tem rota aberta
dist order to order é  6.66405389789439 hub em questão 6
dist order to hub é  8.728251831586114 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 180
561
     order_id  order_latitude  order_longitude      ordered_at_brt
560       561       -23.64569       -46.695465 2024-04-02 20:32:00
2024-04-02 20:32:00
tem rota aberta
dist order to order é  2.3362926478109136 hub em questão 16
dist order to hub é  13.093087870166606 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 179
562
     order_id  order_latitude  order_longitude      ordered_at_brt
561       562      -23.714847        -46.71973 2024-04-02 20:38:00
2024-04-02 20:38:00
não tem rota aberta
route_id 181
dist pro hub mais próximo é 5.11
hub alocado 4
563
     order_id  order_latitude  order_longitude      ordered_at_brt
562       563       -23.66303       -46.612221 2024-04-02 20:45:00
2024-04-02 20:45:00
tem rota aberta
dist order to order é  12.370887016841253 hub em questão 4
dist order to hub é  10.98795260765867 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 181
564
     order_id  order_latitude  order_longitude      ordered_at_brt
563       564      -23.585137       -46.543074 2024-04-02 20:51:00
2024-04-02 20:51:00
tem rota aberta
dist order to order é  11.164338972356637 hub em questão 4
dist order to hub é  2.6663023485449093 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 4
passou aqui1
passou aqui5
route_id 182
caiu aqui tb
565
     order_id  order_latitude  order_longitude      ordered_at_brt
564       565      -23.624118       -46.637462 2024-04-02 20:54:00
2024-04-02 20:54:00
tem rota aberta
dist order to order é  5.0331210073284725 hub em questão 4
dist order to hub é  10.630131883695455 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 181
566
     order_id  order_latitude  order_longitude      ordered_at_brt
565       566      -23.574445       -46.604251 2024-04-02 20:58:00
2024-04-02 20:58:00
tem rota aberta
dist order to order é  6.346952656502486 hub em questão 14
dist order to hub é  6.985549774836994 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 182
567
     order_id  order_latitude  order_longitude      ordered_at_brt
566       567      -23.624067       -46.660987 2024-04-02 21:03:00
2024-04-02 21:03:00
tem rota aberta
dist order to order é  2.3966576400744377 hub em questão 4
dist order to hub é  10.558428543380591 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 181
568
     order_id  order_latitude  order_longitude      ordered_at_brt
567       568       -23.58615       -46.757111 2024-04-02 21:09:00
2024-04-02 21:09:00
tem rota aberta
dist order to order é  15.632219262721515 hub em questão 14
dist order to hub é  9.075407831139557 hub em questão 19
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 19
hub_order 14
passou aqui1
passou aqui5
route_id 183
caiu aqui tb
569
     order_id  order_latitude  order_longitude      ordered_at_brt
568       569       -23.63922       -46.654063 2024-04-02 21:11:00
2024-04-02 21:11:00
tem rota aberta

dist order to order é  8.811148186890964 hub em questão 14
dist order to hub é  12.205979704608884 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 182
570
     order_id  order_latitude  order_longitude      ordered_at_brt
569       570      -23.599733       -46.644087 2024-04-02 21:18:00
2024-04-02 21:18:00
tem rota aberta
dist order to order é  4.506852881364849 hub em questão 14
dist order to hub é  7.856050986814664 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 182
571
     order_id  order_latitude  order_longitude      ordered_at_brt
570       571      -23.662982       -46.696285 2024-04-02 21:20:00
2024-04-02 21:20:00
tem rota aberta
dist order to order é  10.554046851309694 hub em questão 19
dist order to hub é  11.314016305320289 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 19 2
route_id 183
572
     order_id  order_latitude  order_longitude      ordered_at_brt
571       572      -23.712588       -46.641794 2024-04-02 21:26:00
2024-04-02 21:26:00
tem rota aberta
dist order to order é  7.823889538811863 hub em questão 19
dist order to hub é  6.966647841840512 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 19 2
route_id 183
573
     order_id  order_latitude  order_longitude      ordered_at_brt
572       573       -23.68817        -46.74253 2024-04-02 21:32:00
2024-04-02 21:32:00
tem rota aberta
dist order to order é  5.479378004423294 hub em questão 19
dist order to hub é  7.315979049169097 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 19 2
route_id 183
574
     order_id  order_latitude  order_longitude      ordered_at_brt
573       574      -23.639282       -46.693008 2024-04-02 21:37:00
2024-04-02 21:37:00
não tem rota aberta
route_id 184
dist pro hub mais próximo é 12.9
hub alocado 16
575
     order_id  order_latitude  order_longitude      ordered_at_brt
574       575      -23.634915       -46.738098 2024-04-02 21:44:00
2024-04-02 21:44:00
tem rota aberta
dist order to order é  4.618778812871998 hub em questão 16
dist order to hub é  13.253854270446737 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 184
576
     order_id  order_latitude  order_longitude      ordered_at_brt
575       576      -23.536621       -46.615954 2024-04-02 21:47:00
2024-04-02 21:47:00
tem rota aberta
dist order to order é  13.85524847302558 hub em questão 16
dist order to hub é  3.769162361316899 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 16
passou aqui1
rota em aberto, route_id:  184
rota_escolhida: 184
orders no hub: 2
passou aqui3
passou aqui4
577
     order_id  order_latitude  order_longitude      ordered_at_brt
576       577      -23.627662       -46.645929 2024-04-02 21:53:00
2024-04-02 21:53:00
tem rota aberta
dist order to order é  4.966845087727328 hub em questão 16
dist order to hub é  10.93727187371569 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 184
578
     order_id  order_latitude  order_longitude      ordered_at_brt
577       578      -23.653686       -46.636774 2024-04-02 21:59:00
2024-04-02 21:59:00
não tem rota aberta
route_id 185
dist pro hub mais próximo é 12.58
hub alocado 14
579
     order_id  order_latitude  order_longitude      ordered_at_brt
578       579      -23.603552       -46.681885 2024-04-02 22:10:00
2024-04-02 22:10:00
tem rota aberta
dist order to order é  7.224711373318873 hub em questão 14
dist order to hub é  8.779995216911253 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 185
580
     order_id  order_latitude  order_longitude      ordered_at_brt
579       580      -23.664341       -46.649743 2024-04-02 22:11:00
2024-04-02 22:11:00
tem rota aberta
dist order to order é  1.7744136003575532 hub em questão 14
dist order to hub é  11.728138980334423 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 185
581
     order_id  order_latitude  order_longitude      ordered_at_brt
580       581      -23.590026       -46.645931 2024-04-02 22:19:00
2024-04-02 22:19:00
tem rota aberta
dist order to order é  3.9602971066637616 hub em questão 14
dist order to hub é  6.763439485527397 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 185
582
     order_id  order_latitude  order_longitude      ordered_at_brt
581       582      -23.658271       -46.662706 2024-04-02 22:24:00
2024-04-02 22:24:00
não tem rota aberta
route_id 186
dist pro hub mais próximo é 12.18
hub alocado 3
583
     order_id  order_latitude  order_longitude      ordered_at_brt
582       583      -23.621861       -46.677315 2024-04-02 22:28:00
2024-04-02 22:28:00
tem rota aberta
dist order to order é  4.313442008976946 hub em questão 3
dist order to hub é  10.590822255173563 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 186
584
     order_id  order_latitude  order_longitude      ordered_at_brt
583       584      -23.637402       -46.647946 2024-04-02 22:35:00
2024-04-02 22:35:00
tem rota aberta
dist order to order é  2.7650374432272327 hub em questão 3
dist order to hub é  12.009598424602206 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 186
585
     order_id  order_latitude  order_longitude      ordered_at_brt
584       585      -23.611704       -46.669655 2024-04-02 22:39:00
2024-04-02 22:39:00
tem rota aberta
dist order to order é  1.3728335232204478 hub em questão 3
dist order to hub é  9.318211616955203 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 186
586
     order_id  order_latitude  order_longitude      ordered_at_brt
585       586      -23.621913       -46.630082 2024-04-02 22:44:00
2024-04-02 22:44:00
não tem rota aberta
route_id 187
dist pro hub mais próximo é 10.52
hub alocado 16
587
     order_id  order_latitude  order_longitude      ordered_at_brt
586       587      -23.609795       -46.703928 2024-04-02 22:48:00
2024-04-02 22:48:00
tem rota aberta
dist order to order é  7.643330396077256 hub em questão 16
dist order to hub é  10.377773529432945 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 187
588
     order_id  order_latitude  order_longitude      ordered_at_brt
587       588      -23.561532       -46.649678 2024-04-02 22:49:00
2024-04-02 22:49:00
tem rota aberta
dist order to order é  7.004768164221325 hub em questão 16
dist order to hub é  3.574273461547497 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 16
passou aqui1
rota em aberto, route_id:  187
rota_escolhida: 187
orders no hub: 2
passou aqui3
passou aqui4
589
     order_id  order_latitude  order_longitude      ordered_at_brt
588       589      -23.678901       -46.655438 2024-04-02 22:57:00
2024-04-02 22:57:00
tem rota aberta
dist order to order é  6.842906858611745 hub em questão 16
dist order to hub é  10.02265509533412 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 187
590
     order_id  order_latitude  order_longitude      ordered_at_brt
589       590      -23.643485       -46.696895 2024-04-02 23:00:00
2024-04-02 23:00:00
não tem rota aberta
route_id 188
dist pro hub mais próximo é 13.26
hub alocado 4
591
     order_id  order_latitude  order_longitude      ordered_at_brt
590       591      -23.629143       -46.700069 2024-04-02 23:03:00
2024-04-02 23:03:00
tem rota aberta
dist order to order é  1.6270960942918806 hub em questão 4
dist order to hub é  12.114376796753813 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 188
592
     order_id  order_latitude  order_longitude      ordered_at_brt
591       592      -23.568352       -46.578747 2024-04-02 23:09:00
2024-04-02 23:09:00
tem rota aberta
dist order to order é  14.089644758308145 hub em questão 4
dist order to hub é  6.62781623028288 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 4
passou aqui1
passou aqui5
route_id 189
caiu aqui tb
593
     order_id  order_latitude  order_longitude      ordered_at_brt
592       593      -23.569818       -46.582739 2024-04-02 23:17:00
2024-04-02 23:17:00
tem rota aberta

dist order to order é  0.43828385102837647 hub em questão 14
dist order to hub é  6.8707118645494 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 189
594
     order_id  order_latitude  order_longitude      ordered_at_brt
593       594      -23.616719        -46.74091 2024-04-02 23:20:00
2024-04-02 23:20:00
tem rota aberta
dist order to order é  4.3841516528591695 hub em questão 4
dist order to hub é  12.127545486102234 hub em questão 19
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 188
595
     order_id  order_latitude  order_longitude      ordered_at_brt
594       595      -23.539495       -46.613418 2024-04-02 23:22:00
2024-04-02 23:22:00
tem rota aberta
dist order to order é  4.598652151321292 hub em questão 14
dist order to hub é  4.0974644945545515 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 189
596
     order_id  order_latitude  order_longitude      ordered_at_brt
595       596      -23.681107       -46.616782 2024-04-02 23:28:00
2024-04-02 23:28:00
tem rota aberta
dist order to order é  9.16927676837633 hub em questão 4
dist order to hub é  11.277687067558018 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 188
597
     order_id  order_latitude  order_longitude      ordered_at_brt
596       597      -23.619081       -46.663337 2024-04-02 23:33:00
2024-04-02 23:33:00
tem rota aberta
dist order to order é  9.872136951348924 hub em questão 14
dist order to hub é  10.030727964057352 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 189
598
     order_id  order_latitude  order_longitude      ordered_at_brt
597       598      -23.619677       -46.670615 2024-04-02 23:37:00
2024-04-02 23:37:00
não tem rota aberta
route_id 190
dist pro hub mais próximo é 10.21
hub alocado 16
599
     order_id  order_latitude  order_longitude      ordered_at_brt
598       599      -23.602481       -46.728719 2024-04-02 23:42:00
2024-04-02 23:42:00
tem rota aberta
dist order to order é  6.221206722529707 hub em questão 16
dist order to hub é  10.509462159382682 hub em questão 19
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 190
600
     order_id  order_latitude  order_longitude      ordered_at_brt
599       600      -23.664444       -46.774438 2024-04-02 23:45:00
2024-04-02 23:45:00
tem rota aberta
dist order to order é  8.316442437122808 hub em questão 16
dist order to hub é  10.35089520783831 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 190
601
     order_id  order_latitude  order_longitude      ordered_at_brt
600       601      -23.604705       -46.654501 2024-04-02 23:51:00
2024-04-02 23:51:00
tem rota aberta
dist order to order é  2.338083431779686 hub em questão 16
dist order to hub é  8.370101843509937 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 190
602
     order_id  order_latitude  order_longitude      ordered_at_brt
601       602      -23.644304       -46.578038 2024-04-02 23:56:00
2024-04-02 23:56:00
não tem rota aberta
route_id 191
dist pro hub mais próximo é 6.97
hub alocado 14
603
     order_id  order_latitude  order_longitude ordered_at_brt
602       603       -23.57031       -46.650723     2024-04-03
2024-04-03 00:00:00
tem rota aberta
dist order to order é  11.069925955722193 hub em questão 14
dist order to hub é  4.544017328539441 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 192
caiu aqui tb
604
     order_id  order_latitude  order_longitude      ordered_at_brt
603       604      -23.619221       -46.566781 2024-04-03 00:07:00
2024-04-03 00:07:00
tem rota aberta
dist order to order é  3.015669802861273 hub em questão 14
dist order to hub é  4.493861868221388 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 191
605
     order_id  order_latitude  order_longitude      ordered_at_brt
604       605      -23.742059       -46.758557 2024-04-03 00:09:00
2024-04-03 00:09:00
tem rota aberta
dist order to order é  21.35441557126468 hub em questão 14
dist order to hub é  1.8170649981924503 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 14
passou aqui1
passou aqui5
route_id 193
caiu aqui tb
606
     order_id  order_latitude  order_longitude      ordered_at_brt
605       606      -23.604845       -46.574465 2024-04-03 00:15:00
2024-04-03 00:15:00
tem rota aberta
dist order to order é  1.7799649472369918 hub em questão 14
dist order to hub é  4.922881631134251 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 191
607
     order_id  order_latitude  order_longitude      ordered_at_brt
606       607      -23.609252       -46.643633 2024-04-03 00:23:00
2024-04-03 00:23:00
tem rota aberta
dist order to order é  4.3900414523148985 hub em questão 16
dist order to hub é  8.913852920164539 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 192
608
     order_id  order_latitude  order_longitude      ordered_at_brt
607       608      -23.566247       -46.572869 2024-04-03 00:29:00
2024-04-03 00:29:00
tem rota aberta
dist order to order é  7.947649289978099 hub em questão 16
dist order to hub é  6.30478623593029 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 192
609
     order_id  order_latitude  order_longitude      ordered_at_brt
608       609      -23.676089       -46.642907 2024-04-03 00:34:00
2024-04-03 00:34:00
tem rota aberta
dist order to order é  13.872470684712242 hub em questão 4
dist order to hub é  10.653903637666708 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 4
passou aqui1
passou aqui5
route_id 194
caiu aqui tb
610
     order_id  order_latitude  order_longitude      ordered_at_brt
609       610      -23.626457       -46.602992 2024-04-03 00:40:00
2024-04-03 00:40:00
tem rota aberta
dist order to order é  6.854599136901028 hub em questão 3
dist order to hub é  8.234177571325997 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 194
611
     order_id  order_latitude  order_longitude      ordered_at_brt
610       611      -23.611802       -46.693739 2024-04-03 00:46:00
2024-04-03 00:46:00
tem rota aberta
dist order to order é  8.82661499592863 hub em questão 3
dist order to hub é  10.091578922318252 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 194
612
     order_id  order_latitude  order_longitude      ordered_at_brt
611       612      -23.812536       -46.578298 2024-04-03 00:51:00
2024-04-03 00:51:00
tem rota aberta
dist order to order é  16.53612032787698 hub em questão 3
dist order to hub é  6.922676705039228 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 3
passou aqui1
passou aqui5
route_id 195
caiu aqui tb
613
     order_id  order_latitude  order_longitude      ordered_at_brt
612       613       -23.65636       -46.628041 2024-04-03 00:53:00
2024-04-03 00:53:00
tem rota aberta
dist order to order é  2.6654475992736533 hub em questão 3
dist order to hub é  11.929429773207664 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 194
614
     order_id  order_latitude  order_longitude      ordered_at_brt
613       614      -23.630962        -46.67685 2024-04-03 00:59:00
2024-04-03 00:59:00
tem rota aberta
dist order to order é  22.545407164372303 hub em questão 6
dist order to hub é  11.564721073574985 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 6
passou aqui1
passou aqui5
route_id 196
caiu aqui tb
615
     order_id  order_latitude  order_longitude      ordered_at_brt
614       615      -23.603113       -46.704983 2024-04-03 01:03:00
2024-04-03 01:03:00
tem rota aberta
dist order to order é  4.219578577176489 hub em questão 16
dist order to hub é  9.804393288437653 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 196
616
     order_id  order_latitude  order_longitude      ordered_at_brt
615       616       -23.73015       -46.652464 2024-04-03 01:11:00
2024-04-03 01:11:00
tem rota aberta

dist order to order é  11.305312550103476 hub em questão 16
dist order to hub é  4.732173143599834 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 197
caiu aqui tb
617
     order_id  order_latitude  order_longitude      ordered_at_brt
616       617      -23.730926       -46.593222 2024-04-03 01:15:00
2024-04-03 01:15:00
tem rota aberta
dist order to order é  6.031027237797464 hub em questão 3
dist order to hub é  9.261651031550853 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 197
618
     order_id  order_latitude  order_longitude      ordered_at_brt
617       618      -23.649292       -46.635854 2024-04-03 01:18:00
2024-04-03 01:18:00
tem rota aberta
dist order to order é  4.646831387304733 hub em questão 16
dist order to hub é  12.281731652482316 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 196
619
     order_id  order_latitude  order_longitude      ordered_at_brt
618       619      -23.678981       -46.690943 2024-04-03 01:24:00
2024-04-03 01:24:00
tem rota aberta
dist order to order é  5.528982321523812 hub em questão 16
dist order to hub é  9.932125763273667 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 196
620
     order_id  order_latitude  order_longitude      ordered_at_brt
619       620      -23.697109       -46.694291 2024-04-03 01:30:00
2024-04-03 01:30:00
tem rota aberta
dist order to order é  5.624219453027551 hub em questão 3
dist order to hub é  8.023307314338487 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 197
621
     order_id  order_latitude  order_longitude      ordered_at_brt
620       621      -23.593099       -46.668046 2024-04-03 01:35:00
2024-04-03 01:35:00
tem rota aberta
dist order to order é  11.870359921711659 hub em questão 3
dist order to hub é  7.260320643979274 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 198
caiu aqui tb
622
     order_id  order_latitude  order_longitude      ordered_at_brt
621       622      -23.650975        -46.68292 2024-04-03 01:36:00
2024-04-03 01:36:00
tem rota aberta
dist order to order é  5.258955193328108 hub em questão 3
dist order to hub é  12.942198010753069 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 197
623
     order_id  order_latitude  order_longitude      ordered_at_brt
622       623       -23.60306       -46.732528 2024-04-03 01:38:00
2024-04-03 01:38:00
tem rota aberta
dist order to order é  6.66319319168929 hub em questão 16
dist order to hub é  10.5708025622442 hub em questão 19
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 198
624
     order_id  order_latitude  order_longitude      ordered_at_brt
623       624      -23.657918       -46.681281 2024-04-03 01:43:00
2024-04-03 01:43:00
tem rota aberta
dist order to order é  7.33267243894349 hub em questão 16
dist order to hub é  12.162184359389418 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 198
625
     order_id  order_latitude  order_longitude      ordered_at_brt
624       625      -23.610495       -46.648568 2024-04-03 01:48:00
2024-04-03 01:48:00
tem rota aberta
dist order to order é  2.771408362510714 hub em questão 16
dist order to hub é  9.01741236096452 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 198
626
     order_id  order_latitude  order_longitude      ordered_at_brt
625       626      -23.651207       -46.656796 2024-04-03 01:57:00
2024-04-03 01:57:00
não tem rota aberta
route_id 199
dist pro hub mais próximo é 13.03
hub alocado 3
627
     order_id  order_latitude  order_longitude      ordered_at_brt
626       627      -23.685524       -46.591432 2024-04-03 02:04:00
2024-04-03 02:04:00
tem rota aberta
dist order to order é  7.672991416041015 hub em questão 3
dist order to hub é  11.291025227014467 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 199
628
     order_id  order_latitude  order_longitude      ordered_at_brt
627       628      -23.575989       -46.639978 2024-04-03 02:13:00
2024-04-03 02:13:00
tem rota aberta
dist order to order é  8.537615996135639 hub em questão 3
dist order to hub é  5.31866201762212 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 200
caiu aqui tb
629
     order_id  order_latitude  order_longitude      ordered_at_brt
628       629      -23.675453       -46.619038 2024-04-03 02:17:00
2024-04-03 02:17:00
tem rota aberta
dist order to order é  3.0260691002734936 hub em questão 3
dist order to hub é  11.701541300515526 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 199
630
     order_id  order_latitude  order_longitude      ordered_at_brt
629       630      -23.665478       -46.638606 2024-04-03 02:21:00
2024-04-03 02:21:00
tem rota aberta
dist order to order é  2.280677710743708 hub em questão 3
dist order to hub é  11.911526049087769 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 199
631
     order_id  order_latitude  order_longitude      ordered_at_brt
630       631      -23.655717       -46.721299 2024-04-03 02:25:00
2024-04-03 02:25:00
tem rota aberta
dist order to order é  12.134208580303495 hub em questão 16
dist order to hub é  11.206092630811373 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 200
632
     order_id  order_latitude  order_longitude      ordered_at_brt
631       632      -23.648817       -46.686332 2024-04-03 02:30:00
2024-04-03 02:30:00
tem rota aberta
dist order to order é  3.643251062739305 hub em questão 16
dist order to hub é  13.178076966543866 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 200
633
     order_id  order_latitude  order_longitude      ordered_at_brt
632       633      -23.564957        -46.67676 2024-04-03 02:42:00
2024-04-03 02:42:00
tem rota aberta
dist order to order é  3.944285575755024 hub em questão 16
dist order to hub é  4.679649491802485 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 200
635
     order_id  order_latitude  order_longitude      ordered_at_brt
633       635      -23.644215       -46.673021 2024-04-03 02:49:00
2024-04-03 02:49:00
não tem rota aberta
route_id 201
dist pro hub mais próximo é 12.94
hub alocado 16
634
     order_id  order_latitude  order_longitude      ordered_at_brt
634       634      -23.643874       -46.646731 2024-04-03 02:49:00
2024-04-03 02:49:00
tem rota aberta
dist order to order é  2.6781811228471106 hub em questão 16
dist order to hub é  12.733589698501483 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 201
636
     order_id  order_latitude  order_longitude      ordered_at_brt
635       636      -23.701156       -46.594565 2024-04-03 02:52:00
2024-04-03 02:52:00
tem rota aberta
dist order to order é  8.294153340265328 hub em questão 16
dist order to hub é  11.026917723530069 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 201
637
     order_id  order_latitude  order_longitude      ordered_at_brt
636       637      -23.601458       -46.640144 2024-04-03 02:59:00
2024-04-03 02:59:00
tem rota aberta
dist order to order é  4.763933490134758 hub em questão 16
dist order to hub é  8.097536543871124 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 201
638
     order_id  order_latitude  order_longitude      ordered_at_brt
637       638      -23.605603       -46.655489 2024-04-03 03:05:00
2024-04-03 03:05:00
não tem rota aberta
route_id 202
dist pro hub mais próximo é 8.47
hub alocado 16
639
     order_id  order_latitude  order_longitude      ordered_at_brt
638       639      -23.685655       -46.700606 2024-04-03 03:10:00
2024-04-03 03:10:00
tem rota aberta
dist order to order é  10.017724900842907 hub em questão 16
dist order to hub é  8.894674906052586 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 202
640
     order_id  order_latitude  order_longitude      ordered_at_brt
639       640      -23.671587       -46.647531 2024-04-03 03:18:00
2024-04-03 03:18:00
tem rota aberta
dist order to order é  5.626712367977644 hub em questão 16
dist order to hub é  11.00006385300528 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 202
641
     order_id  order_latitude  order_longitude      ordered_at_brt
640       641       -23.65703       -46.685774 2024-04-03 03:22:00
2024-04-03 03:22:00
tem rota aberta

dist order to order é  3.523189480252366 hub em questão 16
dist order to hub é  12.291601030663577 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 202
642
     order_id  order_latitude  order_longitude      ordered_at_brt
641       642      -23.673854       -46.562175 2024-04-03 03:24:00
2024-04-03 03:24:00
não tem rota aberta
route_id 203
dist pro hub mais próximo é 8.65
hub alocado 14
643
     order_id  order_latitude  order_longitude      ordered_at_brt
642       643      -23.612911       -46.706387 2024-04-03 03:30:00
2024-04-03 03:30:00
tem rota aberta
dist order to order é  16.177346490477248 hub em questão 14
dist order to hub é  10.803655832095272 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 204
caiu aqui tb
644
     order_id  order_latitude  order_longitude      ordered_at_brt
643       644      -23.719204       -46.663063 2024-04-03 03:40:00
2024-04-03 03:40:00
tem rota aberta
dist order to order é  11.443412779661404 hub em questão 14
dist order to hub é  5.478904709486048 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 14
passou aqui1
passou aqui5
route_id 205
caiu aqui tb
645
     order_id  order_latitude  order_longitude      ordered_at_brt
644       645      -23.683946       -46.672934 2024-04-03 03:43:00
2024-04-03 03:43:00
tem rota aberta
dist order to order é  4.047241923847411 hub em questão 3
dist order to hub é  9.256732364230785 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 205
646
     order_id  order_latitude  order_longitude      ordered_at_brt
645       646      -23.569733       -46.690995 2024-04-03 03:48:00
2024-04-03 03:48:00
tem rota aberta
dist order to order é  5.0508746897873396 hub em questão 16
dist order to hub é  5.929089690421074 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 204
647
     order_id  order_latitude  order_longitude      ordered_at_brt
646       647      -23.611522        -46.68581 2024-04-03 03:52:00
2024-04-03 03:52:00
tem rota aberta
dist order to order é  2.102225055320576 hub em questão 16
dist order to hub é  9.750106567620055 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 204
648
     order_id  order_latitude  order_longitude      ordered_at_brt
647       648      -23.578607       -46.579783 2024-04-03 03:57:00
2024-04-03 03:57:00
tem rota aberta
dist order to order é  11.376994215467429 hub em questão 16
dist order to hub é  6.12129939520242 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 206
caiu aqui tb
649
     order_id  order_latitude  order_longitude      ordered_at_brt
648       649      -23.609085       -46.640642 2024-04-03 04:02:00
2024-04-03 04:02:00
tem rota aberta
dist order to order é  7.067133457130209 hub em questão 14
dist order to hub é  8.930095689321217 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 206
650
     order_id  order_latitude  order_longitude      ordered_at_brt
649       650      -23.719003       -46.663695 2024-04-03 04:04:00
2024-04-03 04:04:00
tem rota aberta
dist order to order é  0.06809600452935433 hub em questão 3
dist order to hub é  5.486386171722631 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 205
651
     order_id  order_latitude  order_longitude      ordered_at_brt
650       651      -23.624235       -46.543534 2024-04-03 04:13:00
2024-04-03 04:13:00
tem rota aberta
dist order to order é  6.275701763690156 hub em questão 14
dist order to hub é  2.910891542061655 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 14
passou aqui1
rota em aberto, route_id:  206
rota_escolhida: 206
orders no hub: 2
passou aqui3
passou aqui4
652
     order_id  order_latitude  order_longitude      ordered_at_brt
651       652      -23.702772       -46.617476 2024-04-03 04:16:00
2024-04-03 04:16:00
tem rota aberta
dist order to order é  10.68140219874154 hub em questão 14
dist order to hub é  9.275870653699723 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 206
653
     order_id  order_latitude  order_longitude      ordered_at_brt
652       653       -23.66907       -46.631012 2024-04-03 04:20:00
2024-04-03 04:20:00
não tem rota aberta
route_id 207
dist pro hub mais próximo é 11.81
hub alocado 3
654
     order_id  order_latitude  order_longitude      ordered_at_brt
653       654      -23.663348       -46.649883 2024-04-03 04:25:00
2024-04-03 04:25:00
tem rota aberta
dist order to order é  2.0245246659877507 hub em questão 3
dist order to hub é  11.832682607049964 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 207
655
     order_id  order_latitude  order_longitude      ordered_at_brt
654       655      -23.611691       -46.681871 2024-04-03 04:32:00
2024-04-03 04:32:00
tem rota aberta
dist order to order é  6.60390614920761 hub em questão 3
dist order to hub é  9.633787737278995 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 207
656
     order_id  order_latitude  order_longitude      ordered_at_brt
655       656      -23.670053       -46.622162 2024-04-03 04:37:00
2024-04-03 04:37:00
tem rota aberta
dist order to order é  0.9078451670998391 hub em questão 3
dist order to hub é  12.082478606380162 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 207
657
     order_id  order_latitude  order_longitude      ordered_at_brt
656       657      -23.676527        -46.61152 2024-04-03 04:44:00
2024-04-03 04:44:00
não tem rota aberta
route_id 208
dist pro hub mais próximo é 11.9
hub alocado 14
658
     order_id  order_latitude  order_longitude      ordered_at_brt
657       658      -23.683406       -46.697164 2024-04-03 04:50:00
2024-04-03 04:50:00
tem rota aberta
dist order to order é  8.754866368216986 hub em questão 14
dist order to hub é  9.292545616264 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 208
659
     order_id  order_latitude  order_longitude      ordered_at_brt
658       659      -23.579379       -46.693502 2024-04-03 04:53:00
2024-04-03 04:53:00
tem rota aberta
dist order to order é  11.573292178729748 hub em questão 14
dist order to hub é  6.97295013683582 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 209
caiu aqui tb
660
     order_id  order_latitude  order_longitude      ordered_at_brt
659       660      -23.619412       -46.623738 2024-04-03 04:55:00
2024-04-03 04:55:00
tem rota aberta
dist order to order é  6.471708919275098 hub em questão 14
dist order to hub é  10.097762832221607 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 208
661
     order_id  order_latitude  order_longitude      ordered_at_brt
660       661      -23.715751       -46.653504 2024-04-03 05:01:00
2024-04-03 05:01:00
tem rota aberta
dist order to order é  5.718097925308569 hub em questão 14
dist order to hub é  6.136229334679701 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 208
662
     order_id  order_latitude  order_longitude      ordered_at_brt
661       662      -23.709989       -46.553364 2024-04-03 05:06:00
2024-04-03 05:06:00
tem rota aberta
dist order to order é  20.363834376997854 hub em questão 16
dist order to hub é  12.166667663074834 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 210
caiu aqui tb
663
     order_id  order_latitude  order_longitude      ordered_at_brt
662       663      -23.602631       -46.628575 2024-04-03 05:11:00
2024-04-03 05:11:00
tem rota aberta
dist order to order é  7.103456644237371 hub em questão 16
dist order to hub é  8.481580565222627 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 209
664
     order_id  order_latitude  order_longitude      ordered_at_brt
663       664      -23.635963       -46.758139 2024-04-03 05:20:00

2024-04-03 05:20:00
tem rota aberta
dist order to order é  9.108265265327447 hub em questão 16
dist order to hub é  13.167362105212902 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 209
665
     order_id  order_latitude  order_longitude      ordered_at_brt
664       665      -23.587393       -46.611419 2024-04-03 05:26:00
2024-04-03 05:26:00
tem rota aberta
dist order to order é  14.85938025587484 hub em questão 14
dist order to hub é  7.660235852967347 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 211
caiu aqui tb
666
     order_id  order_latitude  order_longitude      ordered_at_brt
665       666      -23.595555       -46.688337 2024-04-03 05:30:00
2024-04-03 05:30:00
tem rota aberta
dist order to order é  7.890481515482404 hub em questão 16
dist order to hub é  8.225311289890323 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 211
667
     order_id  order_latitude  order_longitude      ordered_at_brt
666       667      -23.694018       -46.584814 2024-04-03 05:42:00
2024-04-03 05:42:00
tem rota aberta
dist order to order é  12.16200062216265 hub em questão 16
dist order to hub é  11.70936207363673 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 211
668
     order_id  order_latitude  order_longitude      ordered_at_brt
667       668      -23.570904       -46.679438 2024-04-03 05:46:00
2024-04-03 05:46:00
tem rota aberta
dist order to order é  2.887216451969153 hub em questão 16
dist order to hub é  5.3854536989833415 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 211
669
     order_id  order_latitude  order_longitude      ordered_at_brt
668       669      -23.616215       -46.586587 2024-04-03 05:50:00
2024-04-03 05:50:00
não tem rota aberta
route_id 212
dist pro hub mais próximo é 6.32
hub alocado 14
670
     order_id  order_latitude  order_longitude      ordered_at_brt
669       670      -23.662983       -46.660524 2024-04-03 05:52:00
2024-04-03 05:52:00
tem rota aberta
dist order to order é  9.152437228878908 hub em questão 14
dist order to hub é  11.68308528837421 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 212
671
     order_id  order_latitude  order_longitude      ordered_at_brt
670       671      -23.610095       -46.545511 2024-04-03 05:58:00
2024-04-03 05:58:00
tem rota aberta
dist order to order é  4.2400102736329774 hub em questão 14
dist order to hub é  2.1044609281973905 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 14
passou aqui1
rota em aberto, route_id:  212
rota_escolhida: 212
orders no hub: 2
passou aqui3
passou aqui4
672
     order_id  order_latitude  order_longitude      ordered_at_brt
671       672      -23.700945       -46.608744 2024-04-03 06:04:00
2024-04-03 06:04:00
tem rota aberta
dist order to order é  6.7543602801895615 hub em questão 14
dist order to hub é  10.013297694524878 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 212
673
     order_id  order_latitude  order_longitude      ordered_at_brt
672       673      -23.661323       -46.617877 2024-04-03 06:09:00
2024-04-03 06:09:00
não tem rota aberta
route_id 213
dist pro hub mais próximo é 11.34
hub alocado 14
674
     order_id  order_latitude  order_longitude      ordered_at_brt
673       674      -23.567947       -46.671827 2024-04-03 06:19:00
2024-04-03 06:19:00
tem rota aberta
dist order to order é  11.748161715281428 hub em questão 14
dist order to hub é  4.72842045587428 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 214
caiu aqui tb
675
     order_id  order_latitude  order_longitude      ordered_at_brt
674       675      -23.597671       -46.701254 2024-04-03 06:21:00
2024-04-03 06:21:00
tem rota aberta
dist order to order é  4.462842772946619 hub em questão 16
dist order to hub é  9.090026891164687 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 214
676
     order_id  order_latitude  order_longitude      ordered_at_brt
675       676      -23.663337       -46.681195 2024-04-03 06:25:00
2024-04-03 06:25:00
tem rota aberta
dist order to order é  6.452618748268677 hub em questão 14
dist order to hub é  11.559959564758856 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 213
677
     order_id  order_latitude  order_longitude      ordered_at_brt
676       677      -23.582163       -46.683379 2024-04-03 06:27:00
2024-04-03 06:27:00
tem rota aberta
dist order to order é  1.9710267645291117 hub em questão 16
dist order to hub é  6.671492508249764 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 214
678
     order_id  order_latitude  order_longitude      ordered_at_brt
677       678      -23.664577       -46.626207 2024-04-03 06:33:00
2024-04-03 06:33:00
tem rota aberta
dist order to order é  0.922261683837087 hub em questão 14
dist order to hub é  12.24943101944372 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 213
679
     order_id  order_latitude  order_longitude      ordered_at_brt
678       679      -23.660392       -46.610326 2024-04-03 06:41:00
2024-04-03 06:41:00
tem rota aberta
dist order to order é  11.448088872430631 hub em questão 16
dist order to hub é  10.65774579169646 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 214
680
     order_id  order_latitude  order_longitude      ordered_at_brt
679       680      -23.601948       -46.617999 2024-04-03 06:43:00
2024-04-03 06:43:00
não tem rota aberta
route_id 215
dist pro hub mais próximo é 8.78
hub alocado 16
681
     order_id  order_latitude  order_longitude      ordered_at_brt
680       681      -23.664737       -46.621182 2024-04-03 06:48:00
2024-04-03 06:48:00
tem rota aberta
dist order to order é  6.989425337434768 hub em questão 16
dist order to hub é  11.837254125775129 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 215
682
     order_id  order_latitude  order_longitude      ordered_at_brt
681       682      -23.645422       -46.647867 2024-04-03 06:54:00
2024-04-03 06:54:00
tem rota aberta
dist order to order é  3.4641210567715053 hub em questão 16
dist order to hub é  12.901229635477174 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 215
683
     order_id  order_latitude  order_longitude      ordered_at_brt
682       683      -23.650665       -46.607321 2024-04-03 06:59:00
2024-04-03 06:59:00
tem rota aberta
dist order to order é  2.1074679441359776 hub em questão 16
dist order to hub é  9.7933608454095 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 215
684
     order_id  order_latitude  order_longitude      ordered_at_brt
683       684      -23.649304        -46.67469 2024-04-03 07:10:00
2024-04-03 07:10:00
não tem rota aberta
route_id 216
dist pro hub mais próximo é 13.11
hub alocado 3
685
     order_id  order_latitude  order_longitude      ordered_at_brt
684       685      -23.660649       -46.671098 2024-04-03 07:17:00
2024-04-03 07:17:00
tem rota aberta
dist order to order é  1.3135617812557974 hub em questão 3
dist order to hub é  11.85196987770267 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 216
686
     order_id  order_latitude  order_longitude      ordered_at_brt
685       686      -23.625091       -46.588327 2024-04-03 07:20:00
2024-04-03 07:20:00
tem rota aberta
dist order to order é  9.200249895476732 hub em questão 3
dist order to hub é  6.774430777995956 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 217
caiu aqui tb
687
     order_id  order_latitude  order_longitude      ordered_at_brt
686       687      -23.529498       -46.633054 2024-04-03 07:31:00
2024-04-03 07:31:00
tem rota aberta

dist order to order é  11.565563098005033 hub em questão 14
dist order to hub é  1.9409777886823756 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 218
caiu aqui tb
688
     order_id  order_latitude  order_longitude      ordered_at_brt
687       688       -23.60944       -46.564758 2024-04-03 07:34:00
2024-04-03 07:34:00
tem rota aberta
dist order to order é  2.965523842943066 hub em questão 14
dist order to hub é  3.9874898626605524 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 217
689
     order_id  order_latitude  order_longitude      ordered_at_brt
688       689      -23.603671       -46.581601 2024-04-03 07:41:00
2024-04-03 07:41:00
tem rota aberta
dist order to order é  1.8320996685374618 hub em questão 14
dist order to hub é  5.6476187208054265 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 217
690
     order_id  order_latitude  order_longitude      ordered_at_brt
689       690      -23.676481       -46.643408 2024-04-03 07:44:00
2024-04-03 07:44:00
tem rota aberta
dist order to order é  8.00810707044677 hub em questão 14
dist order to hub é  10.596598976454374 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 217
691
     order_id  order_latitude  order_longitude      ordered_at_brt
690       691      -23.670855       -46.609981 2024-04-03 07:49:00
2024-04-03 07:49:00
tem rota aberta
dist order to order é  15.893004716722645 hub em questão 16
dist order to hub é  11.360816922168109 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 219
caiu aqui tb
692
     order_id  order_latitude  order_longitude      ordered_at_brt
691       692      -23.660967       -46.663579 2024-04-03 07:51:00
2024-04-03 07:51:00
tem rota aberta
dist order to order é  5.568245549839044 hub em questão 14
dist order to hub é  11.869741864855825 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 219
693
     order_id  order_latitude  order_longitude      ordered_at_brt
692       693      -23.771028       -46.694854 2024-04-03 07:57:00
2024-04-03 07:57:00
tem rota aberta
dist order to order é  12.645637838304491 hub em questão 14
dist order to hub é  2.0247379898346107 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 14
passou aqui1
passou aqui5
route_id 220
caiu aqui tb
694
     order_id  order_latitude  order_longitude      ordered_at_brt
693       694        -23.7249       -46.583267 2024-04-03 07:58:00
2024-04-03 07:58:00
tem rota aberta
dist order to order é  6.5964209549666455 hub em questão 14
dist order to hub é  10.398151632417536 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 219
695
     order_id  order_latitude  order_longitude      ordered_at_brt
694       695      -23.722188       -46.622776 2024-04-03 08:01:00
2024-04-03 08:01:00
tem rota aberta
dist order to order é  4.033296323524318 hub em questão 14
dist order to hub é  7.328706632913321 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 219
696
     order_id  order_latitude  order_longitude      ordered_at_brt
695       696        -23.6381       -46.623225 2024-04-03 08:12:00
2024-04-03 08:12:00
tem rota aberta
dist order to order é  16.482170037456267 hub em questão 3
dist order to hub é  10.611901140339347 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 221
caiu aqui tb
697
     order_id  order_latitude  order_longitude      ordered_at_brt
696       697      -23.595758       -46.675949 2024-04-03 08:16:00
2024-04-03 08:16:00
tem rota aberta
dist order to order é  7.142879914659244 hub em questão 14
dist order to hub é  7.7623388667710085 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 221
698
     order_id  order_latitude  order_longitude      ordered_at_brt
697       698      -23.656297       -46.691966 2024-04-03 08:19:00
2024-04-03 08:19:00
tem rota aberta
dist order to order é  6.926571777417537 hub em questão 14
dist order to hub é  12.175805759730192 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 221
699
     order_id  order_latitude  order_longitude      ordered_at_brt
698       699      -23.579455       -46.718161 2024-04-03 08:24:00
2024-04-03 08:24:00
tem rota aberta
dist order to order é  4.668009460714365 hub em questão 14
dist order to hub é  7.816907503845609 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 221
700
     order_id  order_latitude  order_longitude      ordered_at_brt
699       700      -23.635534       -46.592463 2024-04-03 08:32:00
2024-04-03 08:32:00
não tem rota aberta
route_id 222
dist pro hub mais próximo é 7.64
hub alocado 14
701
     order_id  order_latitude  order_longitude      ordered_at_brt
700       701      -23.623995       -46.696221 2024-04-03 08:36:00
2024-04-03 08:36:00
tem rota aberta
dist order to order é  10.647584072513405 hub em questão 14
dist order to hub é  11.43305837369668 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 222
702
     order_id  order_latitude  order_longitude      ordered_at_brt
701       702      -23.692559       -46.747324 2024-04-03 08:39:00
2024-04-03 08:39:00
tem rota aberta
dist order to order é  9.231232528477642 hub em questão 14
dist order to hub é  6.819147440595165 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 14
passou aqui1
passou aqui5
route_id 223
caiu aqui tb
703
     order_id  order_latitude  order_longitude      ordered_at_brt
702       703      -23.599345       -46.637307 2024-04-03 08:41:00
2024-04-03 08:41:00
tem rota aberta
dist order to order é  6.088292425894841 hub em questão 14
dist order to hub é  7.915192769836143 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 222
704
     order_id  order_latitude  order_longitude      ordered_at_brt
703       704      -23.732747       -46.660183 2024-04-03 08:45:00
2024-04-03 08:45:00
tem rota aberta
dist order to order é  9.933483224340915 hub em questão 4
dist order to hub é  4.128879833961426 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 4
passou aqui1
passou aqui5
route_id 224
caiu aqui tb
705
     order_id  order_latitude  order_longitude      ordered_at_brt
704       705      -23.665383       -46.588821 2024-04-03 08:56:00
2024-04-03 08:56:00
tem rota aberta
dist order to order é  3.339759082099573 hub em questão 14
dist order to hub é  9.38952201553783 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 222
706
     order_id  order_latitude  order_longitude      ordered_at_brt
705       706      -23.596959       -46.658317 2024-04-03 08:59:00
2024-04-03 08:59:00
tem rota aberta
dist order to order é  13.97131275301306 hub em questão 4
dist order to hub é  7.531960388136876 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 4
passou aqui1
passou aqui5
route_id 225
caiu aqui tb
707
     order_id  order_latitude  order_longitude      ordered_at_brt
706       707      -23.640873       -46.533056 2024-04-03 09:04:00
2024-04-03 09:04:00
tem rota aberta
dist order to order é  13.663976380697825 hub em questão 16
dist order to hub é  4.220581076389285 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 226
caiu aqui tb
708
     order_id  order_latitude  order_longitude      ordered_at_brt
707       708      -23.739549       -46.641932 2024-04-03 09:12:00
2024-04-03 09:12:00
tem rota aberta
dist order to order é  2.005783073272528 hub em questão 3
dist order to hub é  4.5866875459154794 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 224

709
     order_id  order_latitude  order_longitude      ordered_at_brt
708       709      -23.544806       -46.646984 2024-04-03 09:13:00
2024-04-03 09:13:00
tem rota aberta
dist order to order é  5.91312464566448 hub em questão 16
dist order to hub é  1.7836911320842987 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 16
passou aqui1
rota em aberto, route_id:  225
rota_escolhida: 225
orders no hub: 1
passou aqui3
passou aqui4
710
     order_id  order_latitude  order_longitude      ordered_at_brt
709       710      -23.654295       -46.646549 2024-04-03 09:16:00
2024-04-03 09:16:00
tem rota aberta
dist order to order é  6.487185193703538 hub em questão 16
dist order to hub é  12.88975264812359 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 225
711
     order_id  order_latitude  order_longitude      ordered_at_brt
710       711      -23.579599       -46.669244 2024-04-03 09:24:00
2024-04-03 09:24:00
tem rota aberta
dist order to order é  2.228522615112626 hub em questão 16
dist order to hub é  5.842516568706091 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 225
712
     order_id  order_latitude  order_longitude      ordered_at_brt
711       712      -23.675618       -46.711759 2024-04-03 09:29:00
2024-04-03 09:29:00
tem rota aberta
dist order to order é  18.60638248598728 hub em questão 14
dist order to hub é  9.382910325094734 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 14
passou aqui1
passou aqui5
route_id 227
caiu aqui tb
713
     order_id  order_latitude  order_longitude      ordered_at_brt
712       713      -23.643001       -46.707102 2024-04-03 09:34:00
2024-04-03 09:34:00
tem rota aberta
dist order to order é  3.6577329778610204 hub em questão 4
dist order to hub é  12.95650215439394 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 227
714
     order_id  order_latitude  order_longitude      ordered_at_brt
713       714      -23.714995       -46.738885 2024-04-03 09:45:00
2024-04-03 09:45:00
tem rota aberta
dist order to order é  5.17690163565061 hub em questão 4
dist order to hub é  4.38759413447496 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 227
715
     order_id  order_latitude  order_longitude      ordered_at_brt
714       715      -23.673882       -46.736267 2024-04-03 09:51:00
2024-04-03 09:51:00
tem rota aberta
dist order to order é  2.503335222126263 hub em questão 4
dist order to hub é  8.952624557975609 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 227
716
     order_id  order_latitude  order_longitude      ordered_at_brt
715       716      -23.641715       -46.700285 2024-04-03 09:55:00
2024-04-03 09:55:00
não tem rota aberta
route_id 228
dist pro hub mais próximo é 13.32
hub alocado 4
717
     order_id  order_latitude  order_longitude      ordered_at_brt
716       717      -23.628886       -46.666696 2024-04-03 10:00:00
2024-04-03 10:00:00
tem rota aberta
dist order to order é  3.7071077870443467 hub em questão 4
dist order to hub é  11.154976870244026 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 228
718
     order_id  order_latitude  order_longitude      ordered_at_brt
717       718      -23.558914       -46.671129 2024-04-03 10:04:00
2024-04-03 10:04:00
tem rota aberta
dist order to order é  7.793654151141024 hub em questão 4
dist order to hub é  3.806468967996331 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 4
passou aqui1
passou aqui5
route_id 229
caiu aqui tb
719
     order_id  order_latitude  order_longitude      ordered_at_brt
718       719      -23.560498        -46.67453 2024-04-03 10:09:00
2024-04-03 10:09:00
tem rota aberta
dist order to order é  0.38890095045087475 hub em questão 16
dist order to hub é  4.140025343512194 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 229
720
     order_id  order_latitude  order_longitude      ordered_at_brt
719       720      -23.692248       -46.648463 2024-04-03 10:12:00
2024-04-03 10:12:00
tem rota aberta
dist order to order é  7.286230173804716 hub em questão 4
dist order to hub é  8.770190505837434 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 228
721
     order_id  order_latitude  order_longitude      ordered_at_brt
720       721      -23.633071       -46.624756 2024-04-03 10:15:00
2024-04-03 10:15:00
tem rota aberta
dist order to order é  4.297752744050732 hub em questão 4
dist order to hub é  10.570088015789114 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 228
722
     order_id  order_latitude  order_longitude      ordered_at_brt
721       722      -23.568603       -46.662694 2024-04-03 10:22:00
2024-04-03 10:22:00
tem rota aberta
dist order to order é  1.3783274214101653 hub em questão 16
dist order to hub é  4.484280353097229 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 229
723
     order_id  order_latitude  order_longitude      ordered_at_brt
722       723      -23.679646       -46.623663 2024-04-03 10:28:00
2024-04-03 10:28:00
tem rota aberta
dist order to order é  12.971928819869396 hub em questão 16
dist order to hub é  11.065754745617632 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 229
724
     order_id  order_latitude  order_longitude      ordered_at_brt
723       724      -23.691764       -46.662988 2024-04-03 10:29:00
2024-04-03 10:29:00
não tem rota aberta
route_id 230
dist pro hub mais próximo é 8.48
hub alocado 3
725
     order_id  order_latitude  order_longitude      ordered_at_brt
724       725      -23.792832       -46.620914 2024-04-03 10:36:00
2024-04-03 10:36:00
tem rota aberta
dist order to order é  12.026570137483143 hub em questão 3
dist order to hub é  2.545652141949617 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 3
passou aqui1
passou aqui5
route_id 231
caiu aqui tb
726
     order_id  order_latitude  order_longitude      ordered_at_brt
725       726      -23.693293       -46.612313 2024-04-03 10:44:00
2024-04-03 10:44:00
tem rota aberta
dist order to order é  5.162719515972371 hub em questão 3
dist order to hub é  10.42710975129898 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 230
727
     order_id  order_latitude  order_longitude      ordered_at_brt
726       727       -23.66372       -46.591919 2024-04-03 10:46:00
2024-04-03 10:46:00
tem rota aberta
dist order to order é  3.8891765770020057 hub em questão 3
dist order to hub é  9.475145826169477 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 230
728
     order_id  order_latitude  order_longitude      ordered_at_brt
727       728      -23.699735        -46.56497 2024-04-03 10:55:00
2024-04-03 10:55:00
tem rota aberta
dist order to order é  4.854695627401769 hub em questão 3
dist order to hub é  11.41305992694034 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 230
729
     order_id  order_latitude  order_longitude      ordered_at_brt
728       729      -23.650986       -46.681467 2024-04-03 11:00:00
2024-04-03 11:00:00
tem rota aberta
dist order to order é  16.934389005632 hub em questão 6
dist order to hub é  12.933081685530668 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 6
passou aqui1
passou aqui5
route_id 232
caiu aqui tb
730
     order_id  order_latitude  order_longitude      ordered_at_brt
729       730      -23.655576       -46.688366 2024-04-03 11:06:00
2024-04-03 11:06:00
tem rota aberta
dist order to order é  0.8685229570208186 hub em questão 3
dist order to hub é  12.416976677989094 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 232
731
     order_id  order_latitude  order_longitude      ordered_at_brt
730       731      -23.734652       -46.666163 2024-04-03 11:11:00
2024-04-03 11:11:00
tem rota aberta
dist order to order é  9.07879331133237 hub em questão 3
dist order to hub é  3.73563157825349 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 3
passou aqui1
rota em aberto, route_id:  232
rota_escolhida: 232
orders no hub: 2
passou aqui3
passou aqui4
732
     order_id  order_latitude  order_longitude      ordered_at_brt
731       732      -23.639112       -46.651282 2024-04-03 11:16:00
2024-04-03 11:16:00
tem rota aberta
dist order to order é  3.3461770145242378 hub em questão 3
dist order to hub é  12.192616127888737 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 232
733
     order_id  order_latitude  order_longitude      ordered_at_brt
732       733      -23.647707       -46.656445 2024-04-03 11:21:00
2024-04-03 11:21:00
não tem rota aberta
route_id 233
dist pro hub mais próximo é 13.16
hub alocado 16
734
     order_id  order_latitude  order_longitude      ordered_at_brt
733       734       -23.66839        -46.65465 2024-04-03 11:23:00
2024-04-03 11:23:00
tem rota aberta
dist order to order é  2.307090340339804 hub em questão 16
dist order to hub é  11.184606586601454 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 233
735
     order_id  order_latitude  order_longitude      ordered_at_brt
734       735        -23.6592       -46.648591 2024-04-03 11:32:00
2024-04-03 11:32:00
tem rota aberta
dist order to order é  1.193762312534244 hub em questão 16
dist order to hub é  12.311581169177012 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 233

736
     order_id  order_latitude  order_longitude      ordered_at_brt
735       736      -23.736475       -46.639725 2024-04-03 11:34:00
2024-04-03 11:34:00
tem rota aberta
dist order to order é  7.721745566629916 hub em questão 16
dist order to hub é  4.983483256707123 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 234
caiu aqui tb
737
     order_id  order_latitude  order_longitude      ordered_at_brt
736       737      -23.661381       -46.658538 2024-04-03 11:39:00
2024-04-03 11:39:00
tem rota aberta
dist order to order é  0.8741429558324296 hub em questão 16
dist order to hub é  11.887204065795682 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 233
738
     order_id  order_latitude  order_longitude      ordered_at_brt
737       738      -23.688856       -46.670938 2024-04-03 11:43:00
2024-04-03 11:43:00
tem rota aberta
dist order to order é  6.175338755892842 hub em questão 3
dist order to hub é  8.719263339830254 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 234
739
     order_id  order_latitude  order_longitude      ordered_at_brt
738       739      -23.687502       -46.701978 2024-04-03 11:48:00
2024-04-03 11:48:00
tem rota aberta
dist order to order é  3.1642451099421716 hub em questão 3
dist order to hub é  8.646641088100477 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 234
740
     order_id  order_latitude  order_longitude      ordered_at_brt
739       740      -23.615479       -46.619753 2024-04-03 11:57:00
2024-04-03 11:57:00
tem rota aberta
dist order to order é  9.682547893994373 hub em questão 3
dist order to hub é  9.627964812144238 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 234
741
     order_id  order_latitude  order_longitude      ordered_at_brt
740       741      -23.704776       -46.556357 2024-04-03 12:05:00
2024-04-03 12:05:00
não tem rota aberta
route_id 235
dist pro hub mais próximo é 11.68
hub alocado 14
742
     order_id  order_latitude  order_longitude      ordered_at_brt
741       742      -23.708984       -46.724104 2024-04-03 12:08:00
2024-04-03 12:08:00
tem rota aberta
dist order to order é  17.08495514937373 hub em questão 14
dist order to hub é  5.47634969497852 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 14
passou aqui1
passou aqui5
route_id 236
caiu aqui tb
743
     order_id  order_latitude  order_longitude      ordered_at_brt
742       743      -23.551249       -46.621813 2024-04-03 12:16:00
2024-04-03 12:16:00
tem rota aberta
dist order to order é  18.32755565869592 hub em questão 14
dist order to hub é  3.923748858260406 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 237
caiu aqui tb
744
     order_id  order_latitude  order_longitude      ordered_at_brt
743       744      -23.678598       -46.615576 2024-04-03 12:23:00
2024-04-03 12:23:00
tem rota aberta
dist order to order é  6.695709473975665 hub em questão 14
dist order to hub é  11.57951384860039 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 235
745
     order_id  order_latitude  order_longitude      ordered_at_brt
744       745      -23.543492       -46.684109 2024-04-03 12:26:00
2024-04-03 12:26:00
tem rota aberta
dist order to order é  6.408492320669764 hub em questão 16
dist order to hub é  2.958990824771868 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 16
passou aqui1
passou aqui5
route_id 238
caiu aqui tb
746
     order_id  order_latitude  order_longitude      ordered_at_brt
745       746      -23.632979       -46.668192 2024-04-03 12:29:00
2024-04-03 12:29:00
tem rota aberta
dist order to order é  7.379061487022632 hub em questão 14
dist order to hub é  11.626752572234833 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 235
747
     order_id  order_latitude  order_longitude      ordered_at_brt
746       747      -23.621972       -46.696641 2024-04-03 12:31:00
2024-04-03 12:31:00
tem rota aberta
dist order to order é  3.145983802204441 hub em questão 14
dist order to hub é  11.243821742527004 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 235
748
     order_id  order_latitude  order_longitude      ordered_at_brt
747       748      -23.665513       -46.623402 2024-04-03 12:37:00
2024-04-03 12:37:00
tem rota aberta
dist order to order é  11.33635282661961 hub em questão 4
dist order to hub é  12.071980840842501 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 236
749
     order_id  order_latitude  order_longitude      ordered_at_brt
748       749      -23.715934       -46.656083 2024-04-03 12:39:00
2024-04-03 12:39:00
tem rota aberta
dist order to order é  18.641928600033562 hub em questão 16
dist order to hub é  6.026562328703527 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 239
caiu aqui tb
750
     order_id  order_latitude  order_longitude      ordered_at_brt
749       750      -23.580909       -46.676052 2024-04-03 12:46:00
2024-04-03 12:46:00
tem rota aberta
dist order to order é  4.240866968650639 hub em questão 7
dist order to hub é  6.219976697712198 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 238
751
     order_id  order_latitude  order_longitude      ordered_at_brt
750       751      -23.640286       -46.639304 2024-04-03 12:49:00
2024-04-03 12:49:00
tem rota aberta
dist order to order é  7.590127310513543 hub em questão 7
dist order to hub é  12.231850361839685 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 238
752
     order_id  order_latitude  order_longitude      ordered_at_brt
751       752      -23.638084       -46.623782 2024-04-03 12:52:00
2024-04-03 12:52:00
tem rota aberta
dist order to order é  1.5999803015436915 hub em questão 7
dist order to hub é  10.66410991586993 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 238
753
     order_id  order_latitude  order_longitude      ordered_at_brt
752       753      -23.630297       -46.656596 2024-04-03 13:02:00
2024-04-03 13:02:00
tem rota aberta
dist order to order é  9.52254168881473 hub em questão 3
dist order to hub é  11.221567804302888 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 239
754
     order_id  order_latitude  order_longitude      ordered_at_brt
753       754       -23.72088       -46.647299 2024-04-03 13:12:00
2024-04-03 13:12:00
não tem rota aberta
route_id 240
dist pro hub mais próximo é 5.89
hub alocado 3
755
     order_id  order_latitude  order_longitude      ordered_at_brt
754       755      -23.749899       -46.743589 2024-04-03 13:21:00
2024-04-03 13:21:00
tem rota aberta
dist order to order é  10.318783969881851 hub em questão 3
dist order to hub é  0.5174938229065993 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 3
passou aqui1
passou aqui5
route_id 241
caiu aqui tb
756
     order_id  order_latitude  order_longitude      ordered_at_brt
755       756       -23.59764       -46.687077 2024-04-03 13:29:00
2024-04-03 13:29:00
tem rota aberta
dist order to order é  14.290020422943808 hub em questão 3
dist order to hub é  8.377555319972254 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 242
caiu aqui tb
757
     order_id  order_latitude  order_longitude      ordered_at_brt
756       757      -23.627053       -46.614576 2024-04-03 13:31:00
2024-04-03 13:31:00
tem rota aberta
dist order to order é  8.078495357016712 hub em questão 16
dist order to hub é  9.38146721578225 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 242
758
     order_id  order_latitude  order_longitude      ordered_at_brt
757       758      -23.604654       -46.548662 2024-04-03 13:35:00
2024-04-03 13:35:00
tem rota aberta
dist order to order é  7.162531747904906 hub em questão 16
dist order to hub é  2.2952486757786015 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 243
caiu aqui tb
759
     order_id  order_latitude  order_longitude      ordered_at_brt
758       759      -23.651401       -46.682154 2024-04-03 13:39:00
2024-04-03 13:39:00
tem rota aberta
dist order to order é  5.9990438271922875 hub em questão 16
dist order to hub é  12.890440923458442 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 242
760
     order_id  order_latitude  order_longitude      ordered_at_brt
759       760      -23.662406        -46.69318 2024-04-03 13:47:00
2024-04-03 13:47:00
tem rota aberta
dist order to order é  1.660843369188748 hub em questão 16
dist order to hub é  11.516121261165152 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 242
761
     order_id  order_latitude  order_longitude      ordered_at_brt
760       761      -23.609024       -46.546682 2024-04-03 13:49:00

2024-04-03 13:49:00
tem rota aberta
dist order to order é  0.5261439784782266 hub em questão 14
dist order to hub é  2.1797552852546227 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 243
762
     order_id  order_latitude  order_longitude      ordered_at_brt
761       762      -23.599695       -46.615158 2024-04-03 13:51:00
2024-04-03 13:51:00
tem rota aberta
dist order to order é  6.797878039503078 hub em questão 14
dist order to hub é  8.669409259156634 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 243
763
     order_id  order_latitude  order_longitude      ordered_at_brt
762       763       -23.62612       -46.680338 2024-04-03 13:57:00
2024-04-03 13:57:00
tem rota aberta
dist order to order é  7.261866387887461 hub em questão 14
dist order to hub é  11.126541060591705 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 243
764
     order_id  order_latitude  order_longitude      ordered_at_brt
763       764      -23.605068       -46.600997 2024-04-03 14:02:00
2024-04-03 14:02:00
não tem rota aberta
route_id 244
dist pro hub mais próximo é 7.63
hub alocado 14
765
     order_id  order_latitude  order_longitude      ordered_at_brt
764       765      -23.664465       -46.624995 2024-04-03 14:10:00
2024-04-03 14:10:00
tem rota aberta
dist order to order é  7.042594549690102 hub em questão 14
dist order to hub é  12.140004783140922 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 244
766
     order_id  order_latitude  order_longitude      ordered_at_brt
765       766      -23.683377       -46.621583 2024-04-03 14:17:00
2024-04-03 14:17:00
tem rota aberta
dist order to order é  2.1313890821385892 hub em questão 14
dist order to hub é  10.808574936185108 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 244
767
     order_id  order_latitude  order_longitude      ordered_at_brt
766       767      -23.615767       -46.643469 2024-04-03 14:22:00
2024-04-03 14:22:00
tem rota aberta
dist order to order é  4.48793241178299 hub em questão 14
dist order to hub é  9.636690735473437 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 244
768
     order_id  order_latitude  order_longitude      ordered_at_brt
767       768      -23.638613       -46.626967 2024-04-03 14:26:00
2024-04-03 14:26:00
não tem rota aberta
route_id 245
dist pro hub mais próximo é 10.99
hub alocado 14
769
     order_id  order_latitude  order_longitude      ordered_at_brt
768       769      -23.679798       -46.689791 2024-04-03 14:32:00
2024-04-03 14:32:00
tem rota aberta
dist order to order é  7.868575958823253 hub em questão 14
dist order to hub é  9.82421940188564 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 245
770
     order_id  order_latitude  order_longitude      ordered_at_brt
769       770      -23.648669       -46.640515 2024-04-03 14:41:00
2024-04-03 14:41:00
tem rota aberta
dist order to order é  1.7761803668270586 hub em questão 14
dist order to hub é  12.687659842154767 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 245
771
     order_id  order_latitude  order_longitude      ordered_at_brt
770       771      -23.620141       -46.559511 2024-04-03 14:48:00
2024-04-03 14:48:00
tem rota aberta
dist order to order é  7.172320885476032 hub em questão 14
dist order to hub é  3.870909450542256 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 14
passou aqui1
rota em aberto, route_id:  245
rota_escolhida: 245
orders no hub: 3
passou aqui3
passou aqui4
772
     order_id  order_latitude  order_longitude      ordered_at_brt
771       772      -23.650698       -46.700768 2024-04-03 14:51:00
2024-04-03 14:51:00
não tem rota aberta
route_id 246
dist pro hub mais próximo é 12.37
hub alocado 4
773
     order_id  order_latitude  order_longitude      ordered_at_brt
772       773      -23.708609       -46.692495 2024-04-03 14:58:00
2024-04-03 14:58:00
tem rota aberta
dist order to order é  6.494339739489827 hub em questão 4
dist order to hub é  6.739121283091085 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 246
774
     order_id  order_latitude  order_longitude      ordered_at_brt
773       774      -23.686801       -46.676304 2024-04-03 15:00:00
2024-04-03 15:00:00
tem rota aberta
dist order to order é  2.932270780657204 hub em questão 4
dist order to hub é  8.936322184958298 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 246
775
     order_id  order_latitude  order_longitude      ordered_at_brt
774       775      -23.678339       -46.559449 2024-04-03 15:06:00
2024-04-03 15:06:00
tem rota aberta
dist order to order é  11.936569609997036 hub em questão 4
dist order to hub é  8.991325670285152 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 4
passou aqui1
passou aqui5
route_id 247
caiu aqui tb
776
     order_id  order_latitude  order_longitude      ordered_at_brt
775       776      -23.629824       -46.606657 2024-04-03 15:09:00
2024-04-03 15:09:00
tem rota aberta
dist order to order é  7.22650018593389 hub em questão 14
dist order to hub é  8.708698157360516 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 247
777
     order_id  order_latitude  order_longitude      ordered_at_brt
776       777      -23.697257       -46.708665 2024-04-03 15:15:00
2024-04-03 15:15:00
tem rota aberta
dist order to order é  2.074599414823307 hub em questão 4
dist order to hub é  7.366047430321484 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 246
778
     order_id  order_latitude  order_longitude      ordered_at_brt
777       778      -23.646863       -46.652839 2024-04-03 15:20:00
2024-04-03 15:20:00
tem rota aberta
dist order to order é  5.071503003649785 hub em questão 14
dist order to hub é  13.054457316744976 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 247
779
     order_id  order_latitude  order_longitude      ordered_at_brt
778       779      -23.655942       -46.692889 2024-04-03 15:30:00
2024-04-03 15:30:00
tem rota aberta
dist order to order é  4.202340706510031 hub em questão 14
dist order to hub é  12.16881475219887 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 247
780
     order_id  order_latitude  order_longitude      ordered_at_brt
779       780      -23.760162       -46.642531 2024-04-03 15:35:00
2024-04-03 15:35:00
não tem rota aberta
route_id 248
dist pro hub mais próximo é 3.44
hub alocado 3
781
     order_id  order_latitude  order_longitude      ordered_at_brt
780       781      -23.660724       -46.590211 2024-04-03 15:38:00
2024-04-03 15:38:00
tem rota aberta
dist order to order é  12.27318751195657 hub em questão 3
dist order to hub é  9.117195383500205 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 3
passou aqui1
passou aqui5
route_id 249
caiu aqui tb
782
     order_id  order_latitude  order_longitude      ordered_at_brt
781       782       -23.63217       -46.641414 2024-04-03 15:45:00
2024-04-03 15:45:00
tem rota aberta
dist order to order é  6.105948617597463 hub em questão 14
dist order to hub é  11.472149318431441 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 249
783
     order_id  order_latitude  order_longitude      ordered_at_brt
782       783      -23.581353       -46.648157 2024-04-03 15:47:00
2024-04-03 15:47:00
tem rota aberta
dist order to order é  5.692191948041724 hub em questão 14
dist order to hub é  5.783771647419401 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 249
784
     order_id  order_latitude  order_longitude      ordered_at_brt
783       784      -23.678318        -46.62362 2024-04-03 15:58:00
2024-04-03 15:58:00
tem rota aberta
dist order to order é  3.924803962706812 hub em questão 14
dist order to hub é  11.197919839264603 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 249
785
     order_id  order_latitude  order_longitude      ordered_at_brt
784       785      -23.690554       -46.721825 2024-04-03 16:03:00
2024-04-03 16:03:00
tem rota aberta

dist order to order é  11.183258245264406 hub em questão 3
dist order to hub é  7.46649202700305 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 3
passou aqui1
passou aqui5
route_id 250
caiu aqui tb
786
     order_id  order_latitude  order_longitude      ordered_at_brt
785       786      -23.600837       -46.616749 2024-04-03 16:08:00
2024-04-03 16:08:00
tem rota aberta
dist order to order é  14.631454510957663 hub em questão 4
dist order to hub é  8.715597752556265 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 4
passou aqui1
passou aqui5
route_id 251
caiu aqui tb
787
     order_id  order_latitude  order_longitude      ordered_at_brt
786       787      -23.736914       -46.690764 2024-04-03 16:13:00
2024-04-03 16:13:00
tem rota aberta
dist order to order é  6.047549850502601 hub em questão 4
dist order to hub é  3.7088527622330054 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 4
passou aqui1
passou aqui5
route_id 252
caiu aqui tb
788
     order_id  order_latitude  order_longitude      ordered_at_brt
787       788      -23.725004       -46.575913 2024-04-03 16:22:00
2024-04-03 16:22:00
tem rota aberta
dist order to order é  11.765878843927432 hub em questão 3
dist order to hub é  10.856774471363405 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 252
789
     order_id  order_latitude  order_longitude      ordered_at_brt
788       789        -23.6409       -46.656957 2024-04-03 16:29:00
2024-04-03 16:29:00
tem rota aberta
dist order to order é  6.051937718574858 hub em questão 16
dist order to hub é  12.401085018741858 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 251
790
     order_id  order_latitude  order_longitude      ordered_at_brt
789       790      -23.628175       -46.739046 2024-04-03 16:32:00
2024-04-03 16:32:00
tem rota aberta
dist order to order é  7.154562035069043 hub em questão 4
dist order to hub é  13.385418349809907 hub em questão 19
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 250
791
     order_id  order_latitude  order_longitude      ordered_at_brt
790       791      -23.683857       -46.755102 2024-04-03 16:38:00
2024-04-03 16:38:00
tem rota aberta
dist order to order é  8.815361328957863 hub em questão 3
dist order to hub é  7.838129928411481 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 252
792
     order_id  order_latitude  order_longitude      ordered_at_brt
791       792      -23.608135       -46.671082 2024-04-03 16:41:00
2024-04-03 16:41:00
tem rota aberta
dist order to order é  12.00574306084188 hub em questão 3
dist order to hub é  8.959364131431272 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 253
caiu aqui tb
793
     order_id  order_latitude  order_longitude      ordered_at_brt
792       793      -23.710792       -46.528177 2024-04-03 16:43:00
2024-04-03 16:43:00
tem rota aberta
dist order to order é  18.49708326667703 hub em questão 16
dist order to hub é  11.938408723064766 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 254
caiu aqui tb
794
     order_id  order_latitude  order_longitude      ordered_at_brt
793       794      -23.631105       -46.709725 2024-04-03 16:50:00
2024-04-03 16:50:00
tem rota aberta
dist order to order é  4.692898902471664 hub em questão 16
dist order to hub é  12.737001701494641 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 253
795
     order_id  order_latitude  order_longitude      ordered_at_brt
794       795      -23.745392       -46.679904 2024-04-03 16:55:00
2024-04-03 16:55:00
tem rota aberta
dist order to order é  13.065967356468711 hub em questão 16
dist order to hub é  2.4636350503932984 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 255
caiu aqui tb
796
     order_id  order_latitude  order_longitude      ordered_at_brt
795       796      -23.629707       -46.602342 2024-04-03 17:01:00
2024-04-03 17:01:00
tem rota aberta
dist order to order é  7.402640692265211 hub em questão 16
dist order to hub é  8.291455797266785 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 253
797
     order_id  order_latitude  order_longitude      ordered_at_brt
796       797      -23.690642       -46.605248 2024-04-03 17:05:00
2024-04-03 17:05:00
tem rota aberta
dist order to order é  6.782162146511693 hub em questão 16
dist order to hub é  11.109010804281043 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 253
798
     order_id  order_latitude  order_longitude      ordered_at_brt
797       798      -23.614269       -46.690306 2024-04-03 17:06:00
2024-04-03 17:06:00
tem rota aberta
dist order to order é  14.618655502375805 hub em questão 3
dist order to hub é  10.202573578778471 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 256
caiu aqui tb
799
     order_id  order_latitude  order_longitude      ordered_at_brt
798       799      -23.618755       -46.645772 2024-04-03 17:09:00
2024-04-03 17:09:00
tem rota aberta
dist order to order é  4.564534713181046 hub em questão 16
dist order to hub é  9.949644024536962 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 256
800
     order_id  order_latitude  order_longitude      ordered_at_brt
799       800       -23.66997       -46.632016 2024-04-03 17:20:00
2024-04-03 17:20:00
tem rota aberta
dist order to order é  5.864727502768364 hub em questão 16
dist order to hub é  11.675429806080164 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 256
801
     order_id  order_latitude  order_longitude      ordered_at_brt
800       801      -23.732456       -46.722739 2024-04-03 17:25:00
2024-04-03 17:25:00
tem rota aberta
dist order to order é  11.558526954074662 hub em questão 16
dist order to hub é  3.374784243912343 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 16
passou aqui1
passou aqui5
route_id 257
caiu aqui tb
802
     order_id  order_latitude  order_longitude      ordered_at_brt
801       802      -23.698259       -46.699018 2024-04-03 17:29:00
2024-04-03 17:29:00
tem rota aberta
dist order to order é  4.504559214256679 hub em questão 4
dist order to hub é  7.8321593017767395 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 257
803
     order_id  order_latitude  order_longitude      ordered_at_brt
802       803      -23.590484       -46.604598 2024-04-03 17:31:00
2024-04-03 17:31:00
tem rota aberta
dist order to order é  5.242461347813409 hub em questão 16
dist order to hub é  8.120047520389704 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 256
804
     order_id  order_latitude  order_longitude      ordered_at_brt
803       804      -23.723378       -46.584317 2024-04-03 17:32:00
2024-04-03 17:32:00
tem rota aberta
dist order to order é  12.00700362193929 hub em questão 4
dist order to hub é  10.470435628734743 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 257
805
     order_id  order_latitude  order_longitude      ordered_at_brt
804       805       -23.69397       -46.664024 2024-04-03 17:36:00
2024-04-03 17:36:00
tem rota aberta
dist order to order é  3.59494948698006 hub em questão 4
dist order to hub é  8.220898761602026 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 257
806
     order_id  order_latitude  order_longitude      ordered_at_brt
805       806      -23.657138       -46.637711 2024-04-03 17:42:00
2024-04-03 17:42:00
não tem rota aberta
route_id 258
dist pro hub mais próximo é 12.82
hub alocado 3
807
     order_id  order_latitude  order_longitude      ordered_at_brt
806       807      -23.710459       -46.605675 2024-04-03 17:50:00
2024-04-03 17:50:00
tem rota aberta
dist order to order é  6.767316279135083 hub em questão 3
dist order to hub é  9.494159676880859 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 258
808
     order_id  order_latitude  order_longitude      ordered_at_brt
807       808       -23.69311       -46.649242 2024-04-03 17:56:00
2024-04-03 17:56:00
tem rota aberta
dist order to order é  4.168765421669037 hub em questão 3
dist order to hub é  8.654468141606342 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 258
809
     order_id  order_latitude  order_longitude      ordered_at_brt
808       809      -23.650831       -46.702497 2024-04-03 18:04:00
2024-04-03 18:04:00
tem rota aberta

dist order to order é  6.6358354985461006 hub em questão 3
dist order to hub é  12.292850360999138 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 258
810
     order_id  order_latitude  order_longitude      ordered_at_brt
809       810      -23.640743       -46.611485 2024-04-03 18:08:00
2024-04-03 18:08:00
não tem rota aberta
route_id 259
dist pro hub mais próximo é 9.63
hub alocado 14
811
     order_id  order_latitude  order_longitude      ordered_at_brt
810       811       -23.62364        -46.66801 2024-04-03 18:12:00
2024-04-03 18:12:00
tem rota aberta
dist order to order é  6.064111608579918 hub em questão 14
dist order to hub é  10.596878116726945 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 259
812
     order_id  order_latitude  order_longitude      ordered_at_brt
811       812      -23.623166       -46.614851 2024-04-03 18:15:00
2024-04-03 18:15:00
tem rota aberta
dist order to order é  1.9843411183468276 hub em questão 14
dist order to hub é  9.2971678869469 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 259
813
     order_id  order_latitude  order_longitude      ordered_at_brt
812       813      -23.672384       -46.642958 2024-04-03 18:20:00
2024-04-03 18:20:00
tem rota aberta
dist order to order é  4.75963004795671 hub em questão 14
dist order to hub é  11.044693843692363 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 259
814
     order_id  order_latitude  order_longitude      ordered_at_brt
813       814      -23.586335       -46.683344 2024-04-03 18:27:00
2024-04-03 18:27:00
não tem rota aberta
route_id 260
dist pro hub mais próximo é 7.08
hub alocado 16
815
     order_id  order_latitude  order_longitude      ordered_at_brt
814       815      -23.684355       -46.544606 2024-04-03 18:28:00
2024-04-03 18:28:00
tem rota aberta
dist order to order é  17.84755550654843 hub em questão 16
dist order to hub é  9.190753514972537 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 261
caiu aqui tb
816
     order_id  order_latitude  order_longitude      ordered_at_brt
815       816      -23.641169       -46.558829 2024-04-03 18:35:00
2024-04-03 18:35:00
tem rota aberta
dist order to order é  5.015794343823182 hub em questão 14
dist order to hub é  5.353902044304307 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 261
817
     order_id  order_latitude  order_longitude      ordered_at_brt
816       817       -23.62944       -46.680086 2024-04-03 18:39:00
2024-04-03 18:39:00
tem rota aberta
dist order to order é  4.804530545955135 hub em questão 16
dist order to hub é  11.477050919293369 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 260
818
     order_id  order_latitude  order_longitude      ordered_at_brt
817       818      -23.714282        -46.58939 2024-04-03 18:47:00
2024-04-03 18:47:00
tem rota aberta
dist order to order é  5.64496398371951 hub em questão 14
dist order to hub é  10.546883272304436 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 261
819
     order_id  order_latitude  order_longitude      ordered_at_brt
818       819      -23.658004       -46.579959 2024-04-03 18:50:00
2024-04-03 18:50:00
tem rota aberta
dist order to order é  2.8525019398868814 hub em questão 14
dist order to hub é  8.17484957397298 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 261
820
     order_id  order_latitude  order_longitude      ordered_at_brt
819       820       -23.78785       -46.744701 2024-04-03 18:55:00
2024-04-03 18:55:00
tem rota aberta
dist order to order é  18.80281043167145 hub em questão 16
dist order to hub é  3.7808394208923577 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 16
passou aqui1
passou aqui5
route_id 262
caiu aqui tb
821
     order_id  order_latitude  order_longitude      ordered_at_brt
820       821      -23.645772        -46.66073 2024-04-03 18:59:00
2024-04-03 18:59:00
tem rota aberta
dist order to order é  17.96291154853344 hub em questão 4
dist order to hub é  12.962867184242686 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 4
passou aqui1
passou aqui5
route_id 263
caiu aqui tb
822
     order_id  order_latitude  order_longitude      ordered_at_brt
821       822      -23.633636       -46.628241 2024-04-03 19:01:00
2024-04-03 19:01:00
tem rota aberta
dist order to order é  3.574045892556244 hub em questão 16
dist order to hub é  10.927147459728644 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 263
823
     order_id  order_latitude  order_longitude      ordered_at_brt
822       823      -23.683835       -46.636005 2024-04-03 19:09:00
2024-04-03 19:09:00
tem rota aberta
dist order to order é  4.924862815210827 hub em questão 16
dist order to hub é  10.096708093523763 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 263
824
     order_id  order_latitude  order_longitude      ordered_at_brt
823       824      -23.677154       -46.613049 2024-04-03 19:12:00
2024-04-03 19:12:00
tem rota aberta
dist order to order é  2.452867936340846 hub em questão 16
dist order to hub é  11.852196983807834 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 263
825
     order_id  order_latitude  order_longitude      ordered_at_brt
824       825      -23.650958       -46.626653 2024-04-03 19:18:00
2024-04-03 19:18:00
tem rota aberta
dist order to order é  19.39387153227025 hub em questão 4
dist order to hub é  11.519274947163613 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 4
passou aqui1
passou aqui5
route_id 264
caiu aqui tb
826
     order_id  order_latitude  order_longitude      ordered_at_brt
825       826      -23.700723       -46.629373 2024-04-03 19:23:00
2024-04-03 19:23:00
tem rota aberta
dist order to order é  5.5405837072321855 hub em questão 14
dist order to hub é  8.748725555888155 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 264
827
     order_id  order_latitude  order_longitude      ordered_at_brt
826       827      -23.647947       -46.612556 2024-04-03 19:24:00
2024-04-03 19:24:00
tem rota aberta
dist order to order é  1.474454287465294 hub em questão 14
dist order to hub é  10.096061556269412 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 264
828
     order_id  order_latitude  order_longitude      ordered_at_brt
827       828      -23.624931       -46.656871 2024-04-03 19:32:00
2024-04-03 19:32:00
tem rota aberta
dist order to order é  4.224904611180369 hub em questão 14
dist order to hub é  10.626712442569174 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 264
829
     order_id  order_latitude  order_longitude      ordered_at_brt
828       829      -23.621384       -46.633208 2024-04-03 19:39:00
2024-04-03 19:39:00
não tem rota aberta
route_id 265
dist pro hub mais próximo é 10.4
hub alocado 16
830
     order_id  order_latitude  order_longitude      ordered_at_brt
829       830      -23.677476       -46.612157 2024-04-03 19:45:00
2024-04-03 19:45:00
tem rota aberta
dist order to order é  6.595442499885638 hub em questão 16
dist order to hub é  11.87091790878622 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 265
831
     order_id  order_latitude  order_longitude      ordered_at_brt
830       831      -23.615065       -46.640192 2024-04-03 19:50:00
2024-04-03 19:50:00
tem rota aberta
dist order to order é  1.0000184168889539 hub em questão 16
dist order to hub é  9.595360461911557 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 265
832
     order_id  order_latitude  order_longitude      ordered_at_brt
831       832      -23.536772       -46.672095 2024-04-03 20:00:00
2024-04-03 20:00:00
tem rota aberta
dist order to order é  9.293113120473473 hub em questão 16
dist order to hub é  2.19512698080371 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 16
passou aqui1
rota em aberto, route_id:  265
rota_escolhida: 265
orders no hub: 3
passou aqui3

passou aqui4
833
     order_id  order_latitude  order_longitude      ordered_at_brt
832       833      -23.644394       -46.645097 2024-04-03 20:07:00
2024-04-03 20:07:00
não tem rota aberta
route_id 266
dist pro hub mais próximo é 12.8
hub alocado 16
834
     order_id  order_latitude  order_longitude      ordered_at_brt
833       834      -23.661762       -46.633902 2024-04-03 20:13:00
2024-04-03 20:13:00
tem rota aberta
dist order to order é  2.2427414475230294 hub em questão 16
dist order to hub é  12.458662119097626 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 266
835
     order_id  order_latitude  order_longitude      ordered_at_brt
834       835      -23.681642        -46.59446 2024-04-03 20:20:00
2024-04-03 20:20:00
tem rota aberta
dist order to order é  4.584887821339029 hub em questão 16
dist order to hub é  11.13511650987908 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 266
836
     order_id  order_latitude  order_longitude      ordered_at_brt
835       836       -23.66716       -46.693749 2024-04-03 20:26:00
2024-04-03 20:26:00
tem rota aberta
dist order to order é  5.564472459339268 hub em questão 16
dist order to hub é  11.023734853655558 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 266
837
     order_id  order_latitude  order_longitude      ordered_at_brt
836       837      -23.648388       -46.654666 2024-04-03 20:37:00
2024-04-03 20:37:00
não tem rota aberta
route_id 267
dist pro hub mais próximo é 13.23
hub alocado 16
838
     order_id  order_latitude  order_longitude      ordered_at_brt
837       838      -23.632361       -46.713252 2024-04-03 20:53:00
2024-04-03 20:53:00
tem rota aberta
dist order to order é  6.2282077125410344 hub em questão 16
dist order to hub é  13.02911320653865 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 267
839
     order_id  order_latitude  order_longitude      ordered_at_brt
838       839      -23.731254       -46.725293 2024-04-03 20:59:00
2024-04-03 20:59:00
tem rota aberta
dist order to order é  11.064591634507742 hub em questão 16
dist order to hub é  3.2967283501987565 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 16
passou aqui1
passou aqui5
route_id 268
caiu aqui tb
840
     order_id  order_latitude  order_longitude      ordered_at_brt
839       840      -23.686517       -46.584078 2024-04-03 21:07:00
2024-04-03 21:07:00
tem rota aberta
dist order to order é  15.213356609747489 hub em questão 4
dist order to hub é  10.95974805114454 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 4
passou aqui1
passou aqui5
route_id 269
caiu aqui tb
841
     order_id  order_latitude  order_longitude      ordered_at_brt
840       841      -23.591655        -46.61076 2024-04-03 21:09:00
2024-04-03 21:09:00
tem rota aberta
dist order to order é  10.892740254739374 hub em questão 14
dist order to hub é  8.09751522267249 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 270
caiu aqui tb
842
     order_id  order_latitude  order_longitude      ordered_at_brt
841       842      -23.635893       -46.628735 2024-04-03 21:20:00
2024-04-03 21:20:00
tem rota aberta
dist order to order é  5.248974978633449 hub em questão 16
dist order to hub é  11.054306637808441 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 270
843
     order_id  order_latitude  order_longitude      ordered_at_brt
842       843      -23.653194       -46.671769 2024-04-03 21:20:00
2024-04-03 21:20:00
tem rota aberta
dist order to order é  4.786992406068219 hub em questão 16
dist order to hub é  12.678273986209822 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 270
844
     order_id  order_latitude  order_longitude      ordered_at_brt
843       844      -23.590168       -46.648433 2024-04-03 21:31:00
2024-04-03 21:31:00
tem rota aberta
dist order to order é  3.8425061739707562 hub em questão 16
dist order to hub é  6.760350930117433 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 270
845
     order_id  order_latitude  order_longitude      ordered_at_brt
844       845      -23.678817       -46.684077 2024-04-03 21:37:00
2024-04-03 21:37:00
não tem rota aberta
route_id 271
dist pro hub mais próximo é 9.86
hub alocado 3
846
     order_id  order_latitude  order_longitude      ordered_at_brt
845       846      -23.598745       -46.677207 2024-04-03 21:43:00
2024-04-03 21:43:00
tem rota aberta
dist order to order é  8.931071102086547 hub em questão 3
dist order to hub é  8.11791655235753 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 271
847
     order_id  order_latitude  order_longitude      ordered_at_brt
846       847      -23.684787       -46.665611 2024-04-03 21:48:00
2024-04-03 21:48:00
tem rota aberta
dist order to order é  1.994181194841062 hub em questão 3
dist order to hub é  9.213977151678835 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 271
848
     order_id  order_latitude  order_longitude      ordered_at_brt
847       848      -23.627818       -46.687479 2024-04-03 21:51:00
2024-04-03 21:51:00
tem rota aberta
dist order to order é  3.3979203475682147 hub em questão 3
dist order to hub é  11.515763521116023 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 271
849
     order_id  order_latitude  order_longitude      ordered_at_brt
848       849      -23.595711        -46.63982 2024-04-03 21:54:00
2024-04-03 21:54:00
não tem rota aberta
route_id 272
dist pro hub mais próximo é 7.47
hub alocado 16
850
     order_id  order_latitude  order_longitude      ordered_at_brt
849       850      -23.649569       -46.662302 2024-04-03 21:59:00
2024-04-03 21:59:00
tem rota aberta
dist order to order é  6.411779363402388 hub em questão 16
dist order to hub é  13.143817628684438 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 272
851
     order_id  order_latitude  order_longitude      ordered_at_brt
850       851      -23.624527       -46.569456 2024-04-03 22:02:00
2024-04-03 22:02:00
tem rota aberta
dist order to order é  7.852629662888868 hub em questão 16
dist order to hub é  4.994177113798094 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 273
caiu aqui tb
852
     order_id  order_latitude  order_longitude      ordered_at_brt
851       852      -23.647482       -46.545796 2024-04-03 22:03:00
2024-04-03 22:03:00
tem rota aberta
dist order to order é  3.5105508082717707 hub em questão 14
dist order to hub é  5.289109531178188 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 273
853
     order_id  order_latitude  order_longitude      ordered_at_brt
852       853      -23.550627        -46.71568 2024-04-03 22:08:00
2024-04-03 22:08:00
tem rota aberta
dist order to order é  9.214452537057856 hub em questão 16
dist order to hub é  5.004557847365387 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 16
passou aqui1
passou aqui5
route_id 274
caiu aqui tb
854
     order_id  order_latitude  order_longitude      ordered_at_brt
853       854      -23.603206       -46.679971 2024-04-03 22:13:00
2024-04-03 22:13:00
tem rota aberta
dist order to order é  4.175267102370417 hub em questão 16
dist order to hub é  8.678176303325362 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 272
855
     order_id  order_latitude  order_longitude      ordered_at_brt
854       855      -23.686887       -46.690393 2024-04-03 22:17:00
2024-04-03 22:17:00
tem rota aberta
dist order to order é  5.040182578613321 hub em questão 16
dist order to hub é  9.055663137102798 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 272
856
     order_id  order_latitude  order_longitude      ordered_at_brt
855       856      -23.608914       -46.588062 2024-04-03 22:21:00
2024-04-03 22:21:00
tem rota aberta
dist order to order é  2.5704713112667177 hub em questão 14
dist order to hub é  6.335062780455999 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 273

857
     order_id  order_latitude  order_longitude      ordered_at_brt
856       857      -23.684111       -46.618257 2024-04-03 22:25:00
2024-04-03 22:25:00
tem rota aberta
dist order to order é  8.282674744834997 hub em questão 14
dist order to hub é  10.914886370752905 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 273
858
     order_id  order_latitude  order_longitude      ordered_at_brt
857       858      -23.640551       -46.618769 2024-04-03 22:31:00
2024-04-03 22:31:00
tem rota aberta
dist order to order é  14.053492852729416 hub em questão 7
dist order to hub é  10.296308253788352 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 7
passou aqui1
passou aqui5
route_id 275
caiu aqui tb
859
     order_id  order_latitude  order_longitude      ordered_at_brt
858       859       -23.57361       -46.630743 2024-04-03 22:32:00
2024-04-03 22:32:00
tem rota aberta
dist order to order é  7.542837891130633 hub em questão 14
dist order to hub é  5.3696484682600065 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 276
caiu aqui tb
860
     order_id  order_latitude  order_longitude      ordered_at_brt
859       860      -23.659921       -46.740422 2024-04-03 22:36:00
2024-04-03 22:36:00
tem rota aberta
dist order to order é  12.41162101255329 hub em questão 7
dist order to hub é  10.46415391642935 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 274
861
     order_id  order_latitude  order_longitude      ordered_at_brt
860       861      -23.656757       -46.629183 2024-04-03 22:44:00
2024-04-03 22:44:00
tem rota aberta
dist order to order é  2.0909961091294345 hub em questão 14
dist order to hub é  12.052405144881362 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 275
862
     order_id  order_latitude  order_longitude      ordered_at_brt
861       862      -23.688835       -46.693926 2024-04-03 22:45:00
2024-04-03 22:45:00
tem rota aberta
dist order to order é  7.496300593344651 hub em questão 14
dist order to hub é  8.911314289471589 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 275
863
     order_id  order_latitude  order_longitude      ordered_at_brt
862       863       -23.59359       -46.642384 2024-04-03 22:50:00
2024-04-03 22:50:00
tem rota aberta
dist order to order é  2.5186035958333477 hub em questão 16
dist order to hub é  7.198891688558178 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 276
864
     order_id  order_latitude  order_longitude      ordered_at_brt
863       864      -23.547549       -46.690473 2024-04-03 22:53:00
2024-04-03 22:53:00
tem rota aberta
dist order to order é  6.742591172211195 hub em questão 16
dist order to hub é  3.4887229195688767 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 16
passou aqui1
passou aqui5
route_id 277
caiu aqui tb
865
     order_id  order_latitude  order_longitude      ordered_at_brt
864       865       -23.67092       -46.718498 2024-04-03 22:55:00
2024-04-03 22:55:00
tem rota aberta
dist order to order é  3.1983932662110894 hub em questão 14
dist order to hub é  9.646670741536708 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 275
866
     order_id  order_latitude  order_longitude      ordered_at_brt
865       866      -23.643032       -46.705086 2024-04-03 23:03:00
2024-04-03 23:03:00
tem rota aberta
dist order to order é  10.721157443597503 hub em questão 7
dist order to hub é  13.01773554529546 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 277
867
     order_id  order_latitude  order_longitude      ordered_at_brt
866       867       -23.75831       -46.611787 2024-04-03 23:04:00
2024-04-03 23:04:00
tem rota aberta
dist order to order é  15.954590862274502 hub em questão 7
dist order to hub é  5.684635706112381 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 7
passou aqui1
passou aqui5
route_id 278
caiu aqui tb
868
     order_id  order_latitude  order_longitude      ordered_at_brt
867       868      -23.677232       -46.698744 2024-04-03 23:09:00
2024-04-03 23:09:00
tem rota aberta
dist order to order é  3.8572578332164524 hub em questão 7
dist order to hub é  9.798095019533175 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 277
869
     order_id  order_latitude  order_longitude      ordered_at_brt
868       869      -23.684698       -46.633864 2024-04-03 23:15:00
2024-04-03 23:15:00
tem rota aberta
dist order to order é  6.6587477973544305 hub em questão 7
dist order to hub é  10.098023512526686 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 277
870
     order_id  order_latitude  order_longitude      ordered_at_brt
869       870      -23.638171       -46.622373 2024-04-03 23:17:00
2024-04-03 23:17:00
tem rota aberta
dist order to order é  13.402271921499407 hub em questão 6
dist order to hub é  10.533917309384591 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 6
passou aqui1
passou aqui5
route_id 279
caiu aqui tb
871
     order_id  order_latitude  order_longitude      ordered_at_brt
870       871      -23.643373       -46.694046 2024-04-03 23:20:00
2024-04-03 23:20:00
tem rota aberta
dist order to order é  7.323761589187969 hub em questão 14
dist order to hub é  13.368207339420199 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 279
872
     order_id  order_latitude  order_longitude      ordered_at_brt
871       872      -23.629235       -46.674687 2024-04-03 23:24:00
2024-04-03 23:24:00
tem rota aberta
dist order to order é  2.5219667403448027 hub em questão 14
dist order to hub é  11.330490224097034 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 279
873
     order_id  order_latitude  order_longitude      ordered_at_brt
872       873      -23.647652       -46.659667 2024-04-03 23:35:00
2024-04-03 23:35:00
tem rota aberta
dist order to order é  2.5563721637439003 hub em questão 14
dist order to hub é  13.164620340012826 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 279
874
     order_id  order_latitude  order_longitude      ordered_at_brt
873       874      -23.610934       -46.630187 2024-04-03 23:38:00
2024-04-03 23:38:00
não tem rota aberta
route_id 280
dist pro hub mais próximo é 9.33
hub alocado 16
875
     order_id  order_latitude  order_longitude      ordered_at_brt
874       875      -23.713844        -46.64902 2024-04-03 23:45:00
2024-04-03 23:45:00
tem rota aberta
dist order to order é  11.602750198679546 hub em questão 16
dist order to hub é  6.508934663766319 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 281
caiu aqui tb
876
     order_id  order_latitude  order_longitude      ordered_at_brt
875       876      -23.608598       -46.687634 2024-04-03 23:52:00
2024-04-03 23:52:00
tem rota aberta
dist order to order é  5.858883605727676 hub em questão 16
dist order to hub é  9.515747482127024 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 280
877
     order_id  order_latitude  order_longitude      ordered_at_brt
876       877      -23.730698        -46.58514 2024-04-03 23:55:00
2024-04-03 23:55:00
tem rota aberta
dist order to order é  6.767690564819697 hub em questão 3
dist order to hub é  9.771605319342507 hub em questão 6
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 281
878
     order_id  order_latitude  order_longitude      ordered_at_brt
877       878      -23.684216       -46.638608 2024-04-03 23:58:00
2024-04-03 23:58:00
tem rota aberta
dist order to order é  3.4609075206867463 hub em questão 3
dist order to hub é  9.95518552991432 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 281
879
     order_id  order_latitude  order_longitude      ordered_at_brt
878       879      -23.572839       -46.585842 2024-04-04 00:03:00
2024-04-04 00:03:00
tem rota aberta
dist order to order é  6.193844057777487 hub em questão 16
dist order to hub é  6.9679558855566714 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 280
880
     order_id  order_latitude  order_longitude      ordered_at_brt
879       880      -23.647566       -46.670145 2024-04-04 00:08:00
2024-04-04 00:08:00
tem rota aberta
dist order to order é  5.1888657783642005 hub em questão 3
dist order to hub é  13.260652015803489 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 281
881
     order_id  order_latitude  order_longitude      ordered_at_brt
880       881      -23.628811       -46.644471 2024-04-04 00:11:00

2024-04-04 00:11:00
não tem rota aberta
route_id 282
dist pro hub mais próximo é 11.07
hub alocado 16
882
     order_id  order_latitude  order_longitude      ordered_at_brt
881       882      -23.594323       -46.729679 2024-04-04 00:15:00
2024-04-04 00:15:00
tem rota aberta
dist order to order é  9.490807396820244 hub em questão 16
dist order to hub é  9.6003389783956 hub em questão 19
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 282
883
     order_id  order_latitude  order_longitude      ordered_at_brt
882       883      -23.567384       -46.608996 2024-04-04 00:20:00
2024-04-04 00:20:00
tem rota aberta
dist order to order é  7.7279216079227435 hub em questão 16
dist order to hub é  6.089144459941869 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 282
884
     order_id  order_latitude  order_longitude      ordered_at_brt
883       884      -23.710372        -46.64597 2024-04-04 00:26:00
2024-04-04 00:26:00
tem rota aberta
dist order to order é  9.070446084668465 hub em questão 16
dist order to hub é  6.989903699890886 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 283
caiu aqui tb
885
     order_id  order_latitude  order_longitude      ordered_at_brt
884       885      -23.682478       -46.630951 2024-04-04 00:31:00
2024-04-04 00:31:00
tem rota aberta
dist order to order é  3.458102459535049 hub em questão 3
dist order to hub é  10.447740799135177 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 283
886
     order_id  order_latitude  order_longitude      ordered_at_brt
885       886      -23.572434       -46.595488 2024-04-04 00:34:00
2024-04-04 00:34:00
tem rota aberta
dist order to order é  1.4868909697553727 hub em questão 16
dist order to hub é  7.491471592332242 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 282
887
     order_id  order_latitude  order_longitude      ordered_at_brt
886       887      -23.720892       -46.611893 2024-04-04 00:38:00
2024-04-04 00:38:00
tem rota aberta
dist order to order é  3.6611393651303623 hub em questão 3
dist order to hub é  8.262497524505825 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 283
888
     order_id  order_latitude  order_longitude      ordered_at_brt
887       888      -23.601629       -46.717087 2024-04-04 00:44:00
2024-04-04 00:44:00
tem rota aberta
dist order to order é  12.561961858771234 hub em questão 3
dist order to hub é  10.035815665023327 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 3
passou aqui1
passou aqui5
route_id 284
caiu aqui tb
889
     order_id  order_latitude  order_longitude      ordered_at_brt
888       889      -23.679433       -46.680997 2024-04-04 00:51:00
2024-04-04 00:51:00
tem rota aberta
dist order to order é  4.955335706184996 hub em questão 3
dist order to hub é  9.7717830811288 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 283
890
     order_id  order_latitude  order_longitude      ordered_at_brt
889       890      -23.663679       -46.601739 2024-04-04 00:56:00
2024-04-04 00:56:00
tem rota aberta
dist order to order é  13.626285092262206 hub em questão 7
dist order to hub é  10.203742578261846 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 7
passou aqui1
passou aqui5
route_id 285
caiu aqui tb
891
     order_id  order_latitude  order_longitude      ordered_at_brt
890       891      -23.606672       -46.686059 2024-04-04 01:00:00
2024-04-04 01:00:00
tem rota aberta
dist order to order é  3.210787889075761 hub em questão 7
dist order to hub é  9.25687981754251 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 284
892
     order_id  order_latitude  order_longitude      ordered_at_brt
891       892      -23.660223       -46.647014 2024-04-04 01:12:00
2024-04-04 01:12:00
tem rota aberta
dist order to order é  4.6271050609546265 hub em questão 14
dist order to hub é  12.237581011198815 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 285
893
     order_id  order_latitude  order_longitude      ordered_at_brt
892       893      -23.587037       -46.660826 2024-04-04 01:18:00
2024-04-04 01:18:00
tem rota aberta
dist order to order é  8.258662213698603 hub em questão 14
dist order to hub é  6.463466000716849 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 285
894
     order_id  order_latitude  order_longitude      ordered_at_brt
893       894      -23.641614       -46.722376 2024-04-04 01:23:00
2024-04-04 01:23:00
tem rota aberta
dist order to order é  7.950038574969688 hub em questão 14
dist order to hub é  12.717126392261711 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 285
895
     order_id  order_latitude  order_longitude      ordered_at_brt
894       895      -23.652127       -46.676745 2024-04-04 01:24:00
2024-04-04 01:24:00
não tem rota aberta
route_id 286
dist pro hub mais próximo é 12.79
hub alocado 3
896
     order_id  order_latitude  order_longitude      ordered_at_brt
895       896      -23.644087          -46.672 2024-04-04 01:28:00
2024-04-04 01:28:00
tem rota aberta
dist order to order é  1.0163703664240276 hub em questão 3
dist order to hub é  12.905956866904175 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 286
897
     order_id  order_latitude  order_longitude      ordered_at_brt
896       897      -23.591245       -46.693921 2024-04-04 01:33:00
2024-04-04 01:33:00
tem rota aberta
dist order to order é  6.285847675214351 hub em questão 3
dist order to hub é  8.08521607267461 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 286
898
     order_id  order_latitude  order_longitude      ordered_at_brt
897       898      -23.623296        -46.66946 2024-04-04 01:35:00
2024-04-04 01:35:00
tem rota aberta
dist order to order é  2.3262427640456185 hub em questão 3
dist order to hub é  10.582772581041135 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 286
899
     order_id  order_latitude  order_longitude      ordered_at_brt
898       899      -23.638582       -46.591034 2024-04-04 01:36:00
2024-04-04 01:36:00
não tem rota aberta
route_id 287
dist pro hub mais próximo é 7.68
hub alocado 14
900
     order_id  order_latitude  order_longitude      ordered_at_brt
899       900      -23.620167       -46.633336 2024-04-04 01:42:00
2024-04-04 01:42:00
tem rota aberta
dist order to order é  4.771154412655289 hub em questão 14
dist order to hub é  10.26529275081873 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 287
901
     order_id  order_latitude  order_longitude      ordered_at_brt
900       901      -23.536158       -46.651224 2024-04-04 01:47:00
2024-04-04 01:47:00
tem rota aberta
dist order to order é  9.517560721232423 hub em questão 14
dist order to hub é  0.7496478464675954 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 288
caiu aqui tb
902
     order_id  order_latitude  order_longitude      ordered_at_brt
901       902       -23.71859       -46.709788 2024-04-04 01:54:00
2024-04-04 01:54:00
tem rota aberta
dist order to order é  13.431223381829613 hub em questão 14
dist order to hub é  5.3992918498718945 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 14
passou aqui1
passou aqui5
route_id 289
caiu aqui tb
903
     order_id  order_latitude  order_longitude      ordered_at_brt
902       903      -23.690207        -46.68393 2024-04-04 01:59:00
2024-04-04 01:59:00
tem rota aberta
dist order to order é  4.109987165328279 hub em questão 4
dist order to hub é  8.600971178506828 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 289
904
     order_id  order_latitude  order_longitude      ordered_at_brt
903       904       -23.69981       -46.583154 2024-04-04 02:00:00
2024-04-04 02:00:00
tem rota aberta
dist order to order é  6.855338866222693 hub em questão 14
dist order to hub é  12.01162412126108 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 287
905
     order_id  order_latitude  order_longitude      ordered_at_brt
904       905       -23.61249       -46.632192 2024-04-04 02:02:00
2024-04-04 02:02:00
tem rota aberta

dist order to order é  0.8615246484505282 hub em questão 14
dist order to hub é  9.45230434927428 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 287
906
     order_id  order_latitude  order_longitude      ordered_at_brt
905       906      -23.746995        -46.62897 2024-04-04 02:08:00
2024-04-04 02:08:00
tem rota aberta
dist order to order é  8.436757563218029 hub em questão 4
dist order to hub é  5.231437862799061 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 4
passou aqui1
passou aqui5
route_id 290
caiu aqui tb
907
     order_id  order_latitude  order_longitude      ordered_at_brt
906       907      -23.688445        -46.63451 2024-04-04 02:10:00
2024-04-04 02:10:00
tem rota aberta
dist order to order é  5.036045657403426 hub em questão 4
dist order to hub é  9.692850355007463 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 289
908
     order_id  order_latitude  order_longitude      ordered_at_brt
907       908        -23.7271       -46.709403 2024-04-04 02:14:00
2024-04-04 02:14:00
tem rota aberta
dist order to order é  0.947035281670054 hub em questão 4
dist order to hub é  4.786851463404908 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 289
909
     order_id  order_latitude  order_longitude      ordered_at_brt
908       909      -23.598448       -46.657755 2024-04-04 02:21:00
2024-04-04 02:21:00
tem rota aberta
dist order to order é  16.77579398629919 hub em questão 3
dist order to hub é  7.692412208136379 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 291
caiu aqui tb
910
     order_id  order_latitude  order_longitude      ordered_at_brt
909       910      -23.631521       -46.621501 2024-04-04 02:28:00
2024-04-04 02:28:00
tem rota aberta
dist order to order é  5.2122355136337255 hub em questão 16
dist order to hub é  10.201462553809952 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 291
911
     order_id  order_latitude  order_longitude      ordered_at_brt
910       911       -23.65447       -46.668007 2024-04-04 02:33:00
2024-04-04 02:33:00
tem rota aberta
dist order to order é  5.380864134936289 hub em questão 16
dist order to hub é  12.553531083173077 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 291
912
     order_id  order_latitude  order_longitude      ordered_at_brt
911       912      -23.693381       -46.674403 2024-04-04 02:36:00
2024-04-04 02:36:00
tem rota aberta
dist order to order é  4.375472190927984 hub em questão 16
dist order to hub é  8.20480634899847 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 291
913
     order_id  order_latitude  order_longitude      ordered_at_brt
912       913      -23.623073       -46.671357 2024-04-04 02:40:00
2024-04-04 02:40:00
não tem rota aberta
route_id 292
dist pro hub mais próximo é 10.59
hub alocado 16
914
     order_id  order_latitude  order_longitude      ordered_at_brt
913       914      -23.660808       -46.652585 2024-04-04 02:46:00
2024-04-04 02:46:00
tem rota aberta
dist order to order é  4.611093808152001 hub em questão 16
dist order to hub é  12.052308800678624 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 292
915
     order_id  order_latitude  order_longitude      ordered_at_brt
914       915      -23.598691       -46.695593 2024-04-04 02:49:00
2024-04-04 02:49:00
tem rota aberta
dist order to order é  3.6671860178243323 hub em questão 16
dist order to hub é  8.883254970203637 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 292
916
     order_id  order_latitude  order_longitude      ordered_at_brt
915       916      -23.633856       -46.665326 2024-04-04 02:52:00
2024-04-04 02:52:00
tem rota aberta
dist order to order é  1.3471992685616219 hub em questão 16
dist order to hub é  11.68593935263833 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 292
917
     order_id  order_latitude  order_longitude      ordered_at_brt
916       917      -23.606464       -46.686031 2024-04-04 02:55:00
2024-04-04 02:55:00
não tem rota aberta
route_id 293
dist pro hub mais próximo é 9.23
hub alocado 16
918
     order_id  order_latitude  order_longitude      ordered_at_brt
917       918      -23.663727       -46.711157 2024-04-04 02:57:00
2024-04-04 02:57:00
tem rota aberta
dist order to order é  6.862580824771002 hub em questão 16
dist order to hub é  10.641113163393126 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 293
919
     order_id  order_latitude  order_longitude      ordered_at_brt
918       919      -23.672684       -46.536593 2024-04-04 03:00:00
2024-04-04 03:00:00
tem rota aberta
dist order to order é  16.909801022490374 hub em questão 16
dist order to hub é  7.772009472052153 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 294
caiu aqui tb
920
     order_id  order_latitude  order_longitude      ordered_at_brt
919       920      -23.672122       -46.613556 2024-04-04 03:07:00
2024-04-04 03:07:00
tem rota aberta
dist order to order é  7.838095560210139 hub em questão 14
dist order to hub é  11.728214614391486 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 294
921
     order_id  order_latitude  order_longitude      ordered_at_brt
920       921      -23.772122         -46.7246 2024-04-04 03:12:00
2024-04-04 03:12:00
tem rota aberta
dist order to order é  12.130434857524225 hub em questão 16
dist order to hub é  2.9933202307496507 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 16
passou aqui1
passou aqui5
route_id 295
caiu aqui tb
922
     order_id  order_latitude  order_longitude      ordered_at_brt
921       922      -23.676151       -46.682929 2024-04-04 03:17:00
2024-04-04 03:17:00
tem rota aberta
dist order to order é  3.1895455941150668 hub em questão 16
dist order to hub é  10.148986183900492 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 293
923
     order_id  order_latitude  order_longitude      ordered_at_brt
922       923      -23.616179       -46.691636 2024-04-04 03:21:00
2024-04-04 03:21:00
tem rota aberta
dist order to order é  1.2219987167984654 hub em questão 16
dist order to hub é  10.450710789283985 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 293
924
     order_id  order_latitude  order_longitude      ordered_at_brt
923       924      -23.731743       -46.605912 2024-04-04 03:27:00
2024-04-04 03:27:00
tem rota aberta
dist order to order é  6.675163848679296 hub em questão 14
dist order to hub é  8.096044558614812 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 294
925
     order_id  order_latitude  order_longitude      ordered_at_brt
924       925      -23.594445       -46.697796 2024-04-04 03:28:00
2024-04-04 03:28:00
tem rota aberta
dist order to order é  12.175572577319748 hub em questão 14
dist order to hub é  8.597036663612215 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 14
passou aqui1
passou aqui5
route_id 296
caiu aqui tb
926
     order_id  order_latitude  order_longitude      ordered_at_brt
925       926      -23.609571       -46.686577 2024-04-04 03:31:00
2024-04-04 03:31:00
tem rota aberta
dist order to order é  2.0336407038931883 hub em questão 16
dist order to hub é  9.57581574810315 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 296
927
     order_id  order_latitude  order_longitude      ordered_at_brt
926       927       -23.65693       -46.635847 2024-04-04 03:36:00
2024-04-04 03:36:00
tem rota aberta

dist order to order é  7.378312707864984 hub em questão 16
dist order to hub é  12.656903359131435 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 296
928
     order_id  order_latitude  order_longitude      ordered_at_brt
927       928      -23.638653       -46.684818 2024-04-04 03:40:00
2024-04-04 03:40:00
tem rota aberta
dist order to order é  3.23879258854466 hub em questão 16
dist order to hub é  12.59104010687251 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 296
929
     order_id  order_latitude  order_longitude      ordered_at_brt
928       929      -23.646824       -46.637905 2024-04-04 03:44:00
2024-04-04 03:44:00
não tem rota aberta
route_id 297
dist pro hub mais próximo é 12.36
hub alocado 14
930
     order_id  order_latitude  order_longitude      ordered_at_brt
929       930      -23.620664       -46.669563 2024-04-04 03:47:00
2024-04-04 03:47:00
tem rota aberta
dist order to order é  4.343059025019759 hub em questão 14
dist order to hub é  10.296116232282774 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 297
931
     order_id  order_latitude  order_longitude      ordered_at_brt
930       931      -23.704094       -46.711198 2024-04-04 03:54:00
2024-04-04 03:54:00
tem rota aberta
dist order to order é  9.81134209034003 hub em questão 14
dist order to hub é  6.584617298528019 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 14
passou aqui1
passou aqui5
route_id 298
caiu aqui tb
932
     order_id  order_latitude  order_longitude      ordered_at_brt
931       932      -23.671953       -46.660297 2024-04-04 04:02:00
2024-04-04 04:02:00
tem rota aberta
dist order to order é  3.6066752189638414 hub em questão 14
dist order to hub é  10.698172721526456 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 297
933
     order_id  order_latitude  order_longitude      ordered_at_brt
932       933      -23.580859       -46.641038 2024-04-04 04:05:00
2024-04-04 04:05:00
tem rota aberta
dist order to order é  5.295071011491888 hub em questão 14
dist order to hub é  5.824957787290646 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 297
934
     order_id  order_latitude  order_longitude      ordered_at_brt
933       934      -23.731088       -46.699334 2024-04-04 04:09:00
2024-04-04 04:09:00
tem rota aberta
dist order to order é  3.2354177492597196 hub em questão 4
dist order to hub é  4.692555336980893 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 298
935
     order_id  order_latitude  order_longitude      ordered_at_brt
934       935      -23.669432       -46.648238 2024-04-04 04:14:00
2024-04-04 04:14:00
tem rota aberta
dist order to order é  7.480478199466192 hub em questão 4
dist order to hub é  11.213794749199874 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 298
936
     order_id  order_latitude  order_longitude      ordered_at_brt
935       936      -23.706722       -46.631581 2024-04-04 04:21:00
2024-04-04 04:21:00
tem rota aberta
dist order to order é  4.4799373995957374 hub em questão 4
dist order to hub é  8.06677061068733 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 298
937
     order_id  order_latitude  order_longitude      ordered_at_brt
936       937      -23.589409       -46.694154 2024-04-04 04:27:00
2024-04-04 04:27:00
não tem rota aberta
route_id 299
dist pro hub mais próximo é 7.93
hub alocado 16
938
     order_id  order_latitude  order_longitude      ordered_at_brt
937       938      -23.724219       -46.666273 2024-04-04 04:32:00
2024-04-04 04:32:00
tem rota aberta
dist order to order é  15.256826991869714 hub em questão 16
dist order to hub é  4.864868459845316 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 300
caiu aqui tb
939
     order_id  order_latitude  order_longitude      ordered_at_brt
938       939      -23.672729       -46.735661 2024-04-04 04:39:00
2024-04-04 04:39:00
tem rota aberta
dist order to order é  9.093750603348287 hub em questão 3
dist order to hub é  9.087166779608037 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 300
940
     order_id  order_latitude  order_longitude      ordered_at_brt
939       940      -23.642189       -46.671146 2024-04-04 04:45:00
2024-04-04 04:45:00
tem rota aberta
dist order to order é  6.319691621421875 hub em questão 16
dist order to hub é  12.68401229232362 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 299
941
     order_id  order_latitude  order_longitude      ordered_at_brt
940       941      -23.654186        -46.68525 2024-04-04 04:48:00
2024-04-04 04:48:00
tem rota aberta
dist order to order é  1.960456120864726 hub em questão 16
dist order to hub é  12.602429932897477 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 299
942
     order_id  order_latitude  order_longitude      ordered_at_brt
941       942      -23.625685       -46.613884 2024-04-04 04:51:00
2024-04-04 04:51:00
tem rota aberta
dist order to order é  6.115091680716128 hub em questão 16
dist order to hub é  9.272089612006122 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 299
943
     order_id  order_latitude  order_longitude      ordered_at_brt
942       943      -23.675204        -46.59036 2024-04-04 04:54:00
2024-04-04 04:54:00
tem rota aberta
dist order to order é  9.45758234828824 hub em questão 3
dist order to hub é  10.316028195333557 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 300
944
     order_id  order_latitude  order_longitude      ordered_at_brt
943       944      -23.633085       -46.577875 2024-04-04 04:58:00
2024-04-04 04:58:00
tem rota aberta
dist order to order é  4.8530009674329 hub em questão 3
dist order to hub é  6.213567528877919 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 300
945
     order_id  order_latitude  order_longitude      ordered_at_brt
944       945      -23.674397        -46.65627 2024-04-04 05:05:00
2024-04-04 05:05:00
não tem rota aberta
route_id 301
dist pro hub mais próximo é 10.5
hub alocado 3
946
     order_id  order_latitude  order_longitude      ordered_at_brt
945       946      -23.647418       -46.643731 2024-04-04 05:08:00
2024-04-04 05:08:00
tem rota aberta
dist order to order é  3.260427999961689 hub em questão 3
dist order to hub é  12.935938923404285 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 301
947
     order_id  order_latitude  order_longitude      ordered_at_brt
946       947      -23.657116       -46.614096 2024-04-04 05:10:00
2024-04-04 05:10:00
tem rota aberta
dist order to order é  3.205375308771999 hub em questão 3
dist order to hub é  10.762924758411275 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 301
948
     order_id  order_latitude  order_longitude      ordered_at_brt
947       948      -23.700379         -46.7003 2024-04-04 05:12:00
2024-04-04 05:12:00
tem rota aberta
dist order to order é  5.333663052278425 hub em questão 3
dist order to hub é  7.565985522518304 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 301
949
     order_id  order_latitude  order_longitude      ordered_at_brt
948       949      -23.624793       -46.604924 2024-04-04 05:14:00
2024-04-04 05:14:00
não tem rota aberta
route_id 302
dist pro hub mais próximo é 8.37
hub alocado 14
950
     order_id  order_latitude  order_longitude      ordered_at_brt
949       950       -23.62914       -46.763258 2024-04-04 05:22:00
2024-04-04 05:22:00
tem rota aberta
dist order to order é  16.13738561620116 hub em questão 14
dist order to hub é  13.855063443761265 hub em questão 19
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 19
hub_order 14
passou aqui1
passou aqui5
route_id 303
caiu aqui tb
951
     order_id  order_latitude  order_longitude      ordered_at_brt
950       951      -23.693383       -46.676385 2024-04-04 05:24:00
2024-04-04 05:24:00
tem rota aberta
dist order to order é  10.542384224613786 hub em questão 14
dist order to hub é  8.204616415892755 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 14
passou aqui1
passou aqui5
route_id 304
caiu aqui tb
952
     order_id  order_latitude  order_longitude      ordered_at_brt
951       952       -23.55003       -46.580774 2024-04-04 05:28:00
2024-04-04 05:28:00
tem rota aberta
dist order to order é  8.669929446522044 hub em questão 14
dist order to hub é  5.7984238195639985 hub em questão 17
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 17
hub_order 14
passou aqui1
passou aqui5
route_id 305
caiu aqui tb
953
     order_id  order_latitude  order_longitude      ordered_at_brt
952       953      -23.556346        -46.58076 2024-04-04 05:37:00
2024-04-04 05:37:00
tem rota aberta
dist order to order é  0.7023077378957264 hub em questão 17
dist order to hub é  6.261210421015034 hub em questão 17
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 17 2
route_id 305
954
     order_id  order_latitude  order_longitude      ordered_at_brt
953       954      -23.653591         -46.6225 2024-04-04 05:46:00

2024-04-04 05:46:00
tem rota aberta
dist order to order é  7.049209349127003 hub em questão 3
dist order to hub é  11.286583465502428 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 304
955
     order_id  order_latitude  order_longitude      ordered_at_brt
954       955      -23.625654       -46.608367 2024-04-04 05:55:00
2024-04-04 05:55:00
tem rota aberta
dist order to order é  8.204141568323788 hub em questão 17
dist order to hub é  8.730742703072126 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 17 2
route_id 305
956
     order_id  order_latitude  order_longitude      ordered_at_brt
955       956      -23.636605       -46.624299 2024-04-04 06:01:00
2024-04-04 06:01:00
não tem rota aberta
route_id 306
dist pro hub mais próximo é 10.66
hub alocado 14
957
     order_id  order_latitude  order_longitude      ordered_at_brt
956       957      -23.603023        -46.61193 2024-04-04 06:05:00
2024-04-04 06:05:00
tem rota aberta
dist order to order é  3.9410386594388487 hub em questão 14
dist order to hub é  8.738034699748505 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 306
958
     order_id  order_latitude  order_longitude      ordered_at_brt
957       958      -23.632538       -46.633259 2024-04-04 06:10:00
2024-04-04 06:10:00
tem rota aberta
dist order to order é  1.018603818963638 hub em questão 14
dist order to hub é  11.379491004818421 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 306
959
     order_id  order_latitude  order_longitude      ordered_at_brt
958       959      -23.643039       -46.544243 2024-04-04 06:18:00
2024-04-04 06:18:00
tem rota aberta
dist order to order é  8.186185753236181 hub em questão 14
dist order to hub é  4.772188307376975 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 14
passou aqui1
rota em aberto, route_id:  306
rota_escolhida: 306
orders no hub: 3
passou aqui3
passou aqui4
960
     order_id  order_latitude  order_longitude      ordered_at_brt
959       960       -23.59307       -46.735521 2024-04-04 06:19:00
2024-04-04 06:19:00
não tem rota aberta
route_id 307
dist pro hub mais próximo é 9.47
hub alocado 19
961
     order_id  order_latitude  order_longitude      ordered_at_brt
960       961      -23.591118       -46.644594 2024-04-04 06:21:00
2024-04-04 06:21:00
tem rota aberta
dist order to order é  9.268095291354738 hub em questão 19
dist order to hub é  6.898122629053403 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 19
passou aqui1
passou aqui5
route_id 308
caiu aqui tb
962
     order_id  order_latitude  order_longitude      ordered_at_brt
961       962      -23.648919       -46.657072 2024-04-04 06:28:00
2024-04-04 06:28:00
tem rota aberta
dist order to order é  6.55168230891336 hub em questão 16
dist order to hub é  13.280103331139411 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 308
963
     order_id  order_latitude  order_longitude      ordered_at_brt
962       963      -23.550015       -46.599058 2024-04-04 06:36:00
2024-04-04 06:36:00
tem rota aberta
dist order to order é  6.513625489160766 hub em questão 16
dist order to hub é  5.869554946443051 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 308
964
     order_id  order_latitude  order_longitude      ordered_at_brt
963       964      -23.638336       -46.700494 2024-04-04 06:38:00
2024-04-04 06:38:00
tem rota aberta
dist order to order é  4.576826994683906 hub em questão 16
dist order to hub é  13.072300906431641 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 308
965
     order_id  order_latitude  order_longitude      ordered_at_brt
964       965      -23.655121       -46.632229 2024-04-04 06:43:00
2024-04-04 06:43:00
tem rota aberta
dist order to order é  12.583389844434114 hub em questão 19
dist order to hub é  12.237131761531238 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 19 2
route_id 307
966
     order_id  order_latitude  order_longitude      ordered_at_brt
965       966      -23.638455       -46.612425 2024-04-04 06:49:00
2024-04-04 06:49:00
não tem rota aberta
route_id 309
dist pro hub mais próximo é 9.61
hub alocado 14
967
     order_id  order_latitude  order_longitude      ordered_at_brt
966       967      -23.600017       -46.590613 2024-04-04 06:52:00
2024-04-04 06:52:00
tem rota aberta
dist order to order é  4.817273715084686 hub em questão 14
dist order to hub é  6.576983379443678 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 309
968
     order_id  order_latitude  order_longitude      ordered_at_brt
967       968      -23.740808         -46.5981 2024-04-04 06:55:00
2024-04-04 06:55:00
tem rota aberta
dist order to order é  11.474268429995934 hub em questão 14
dist order to hub é  8.077852332203422 hub em questão 6
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 6
hub_order 14
passou aqui1
passou aqui5
route_id 310
caiu aqui tb
969
     order_id  order_latitude  order_longitude      ordered_at_brt
968       969      -23.666243         -46.7061 2024-04-04 06:59:00
2024-04-04 06:59:00
tem rota aberta
dist order to order é  10.029080171092835 hub em questão 14
dist order to hub é  10.566212125800622 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 309
970
     order_id  order_latitude  order_longitude      ordered_at_brt
969       970      -23.696112       -46.620834 2024-04-04 07:05:00
2024-04-04 07:05:00
tem rota aberta
dist order to order é  5.482468648838419 hub em questão 6
dist order to hub é  9.658261766284593 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 310
971
     order_id  order_latitude  order_longitude      ordered_at_brt
970       971      -23.691168       -46.633727 2024-04-04 07:08:00
2024-04-04 07:08:00
tem rota aberta
dist order to order é  1.423218681476062 hub em questão 6
dist order to hub é  9.455712976606572 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 310
972
     order_id  order_latitude  order_longitude      ordered_at_brt
971       972      -23.617327       -46.592497 2024-04-04 07:13:00
2024-04-04 07:13:00
tem rota aberta
dist order to order é  1.9344140124302565 hub em questão 14
dist order to hub é  6.9315838238347975 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 309
973
     order_id  order_latitude  order_longitude      ordered_at_brt
972       973      -23.686594       -46.665131 2024-04-04 07:16:00
2024-04-04 07:16:00
tem rota aberta
dist order to order é  3.2378564977764057 hub em questão 6
dist order to hub é  9.019802198597674 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 6 2
route_id 310
974
     order_id  order_latitude  order_longitude      ordered_at_brt
973       974      -23.563788       -46.633548 2024-04-04 07:24:00
2024-04-04 07:24:00
não tem rota aberta
route_id 311
dist pro hub mais próximo é 4.26
hub alocado 16
975
     order_id  order_latitude  order_longitude      ordered_at_brt
974       975      -23.526278       -46.680879 2024-04-04 07:32:00
2024-04-04 07:32:00
tem rota aberta
dist order to order é  6.377676981815683 hub em questão 16
dist order to hub é  1.0694211974821264 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 16
passou aqui1
passou aqui5
route_id 312
caiu aqui tb
976
     order_id  order_latitude  order_longitude      ordered_at_brt
975       976      -23.619077       -46.655176 2024-04-04 07:41:00
2024-04-04 07:41:00
tem rota aberta
dist order to order é  6.530967505050124 hub em questão 16
dist order to hub é  9.969488449477648 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 311
977
     order_id  order_latitude  order_longitude      ordered_at_brt
976       977      -23.562522       -46.620944 2024-04-04 07:41:00
2024-04-04 07:41:00
tem rota aberta
dist order to order é  1.2923370085737964 hub em questão 16
dist order to hub é  4.8573711451100605 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 311
978
     order_id  order_latitude  order_longitude      ordered_at_brt
977       978      -23.737715       -46.696199 2024-04-04 07:45:00
2024-04-04 07:45:00
tem rota aberta

dist order to order é  13.837650294696918 hub em questão 16
dist order to hub é  3.898586384673261 hub em questão 3
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 3
hub_order 16
passou aqui1
passou aqui5
route_id 313
caiu aqui tb
979
     order_id  order_latitude  order_longitude      ordered_at_brt
978       979      -23.690755       -46.632647 2024-04-04 07:48:00
2024-04-04 07:48:00
tem rota aberta
dist order to order é  8.294010769901957 hub em questão 16
dist order to hub é  9.546422430057946 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 311
980
     order_id  order_latitude  order_longitude      ordered_at_brt
979       980      -23.611327       -46.640843 2024-04-04 07:51:00
2024-04-04 07:51:00
tem rota aberta
dist order to order é  10.299818793099444 hub em questão 7
dist order to hub é  9.174731438467525 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 312
981
     order_id  order_latitude  order_longitude      ordered_at_brt
980       981      -23.634908       -46.631383 2024-04-04 07:58:00
2024-04-04 07:58:00
tem rota aberta
dist order to order é  2.7935915623564154 hub em questão 7
dist order to hub é  11.275252752903793 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 312
982
     order_id  order_latitude  order_longitude      ordered_at_brt
981       982      -23.647391       -46.681119 2024-04-04 08:02:00
2024-04-04 08:02:00
tem rota aberta
dist order to order é  10.160331854409497 hub em questão 3
dist order to hub é  13.330802240114426 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 313
983
     order_id  order_latitude  order_longitude      ordered_at_brt
982       983      -23.713357       -46.685079 2024-04-04 08:09:00
2024-04-04 08:09:00
tem rota aberta
dist order to order é  2.9355554751582127 hub em questão 3
dist order to hub é  6.063407328324746 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 313
984
     order_id  order_latitude  order_longitude      ordered_at_brt
983       984       -23.65371       -46.622082 2024-04-04 08:10:00
2024-04-04 08:10:00
tem rota aberta
dist order to order é  6.054122708134944 hub em questão 3
dist order to hub é  11.25623827973633 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 313
985
     order_id  order_latitude  order_longitude      ordered_at_brt
984       985      -23.663721       -46.683522 2024-04-04 08:18:00
2024-04-04 08:18:00
não tem rota aberta
route_id 314
dist pro hub mais próximo é 11.53
hub alocado 3
986
     order_id  order_latitude  order_longitude      ordered_at_brt
985       986      -23.644502        -46.64717 2024-04-04 08:24:00
2024-04-04 08:24:00
tem rota aberta
dist order to order é  4.274990909216853 hub em questão 3
dist order to hub é  12.801546566270579 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 314
987
     order_id  order_latitude  order_longitude      ordered_at_brt
986       987      -23.703313       -46.640843 2024-04-04 08:28:00
2024-04-04 08:28:00
tem rota aberta
dist order to order é  6.186203584616424 hub em questão 3
dist order to hub é  7.923853665452077 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 314
988
     order_id  order_latitude  order_longitude      ordered_at_brt
987       988      -23.563105       -46.681432 2024-04-04 08:39:00
2024-04-04 08:39:00
tem rota aberta
dist order to order é  9.7009291394414 hub em questão 3
dist order to hub é  4.789334424107837 hub em questão 16
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 16
hub_order 3
passou aqui1
passou aqui5
route_id 315
caiu aqui tb
989
     order_id  order_latitude  order_longitude      ordered_at_brt
988       989      -23.653521       -46.672697 2024-04-04 08:44:00
2024-04-04 08:44:00
tem rota aberta
dist order to order é  1.5817271195125266 hub em questão 3
dist order to hub é  12.63948004495201 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 3 2
route_id 314
990
     order_id  order_latitude  order_longitude      ordered_at_brt
989       990      -23.678475       -46.582461 2024-04-04 08:49:00
2024-04-04 08:49:00
tem rota aberta
dist order to order é  16.316893547269128 hub em questão 16
dist order to hub é  10.123305206690986 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 16
passou aqui1
passou aqui5
route_id 316
caiu aqui tb
991
     order_id  order_latitude  order_longitude      ordered_at_brt
990       991      -23.639453       -46.729576 2024-04-04 08:56:00
2024-04-04 08:56:00
tem rota aberta
dist order to order é  9.804977515014816 hub em questão 16
dist order to hub é  12.835819741325349 hub em questão 4
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 16 2
route_id 315
992
     order_id  order_latitude  order_longitude      ordered_at_brt
991       992      -23.604541       -46.585923 2024-04-04 09:01:00
2024-04-04 09:01:00
tem rota aberta
dist order to order é  8.228662745224355 hub em questão 14
dist order to hub é  6.08912621573971 hub em questão 14
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 14
hub_order 14
passou aqui1
rota em aberto, route_id:  316
rota_escolhida: 316
orders no hub: 1
passou aqui3
passou aqui4
993
     order_id  order_latitude  order_longitude      ordered_at_brt
992       993      -23.681987       -46.630234 2024-04-04 09:03:00
2024-04-04 09:03:00
tem rota aberta
dist order to order é  4.880449670634688 hub em questão 14
dist order to hub é  10.528640375964175 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 316
994
     order_id  order_latitude  order_longitude      ordered_at_brt
993       994      -23.523818       -46.670135 2024-04-04 09:07:00
2024-04-04 09:07:00
tem rota aberta
dist order to order é  4.517669984853188 hub em questão 16
dist order to hub é  1.5369206667544801 hub em questão 7
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 7
hub_order 16
passou aqui1
passou aqui5
route_id 317
caiu aqui tb
995
     order_id  order_latitude  order_longitude      ordered_at_brt
994       995      -23.593699       -46.666777 2024-04-04 09:15:00
2024-04-04 09:15:00
tem rota aberta
dist order to order é  7.777950338831797 hub em questão 7
dist order to hub é  7.297806978008803 hub em questão 16
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 317
996
     order_id  order_latitude  order_longitude      ordered_at_brt
995       996      -23.621374       -46.547824 2024-04-04 09:18:00
2024-04-04 09:18:00
tem rota aberta
dist order to order é  4.309375629861049 hub em questão 14
dist order to hub é  2.9733417611253077 hub em questão 14
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 14 2
route_id 316
997
     order_id  order_latitude  order_longitude      ordered_at_brt
996       997      -23.602095       -46.710131 2024-04-04 09:23:00
2024-04-04 09:23:00
tem rota aberta
dist order to order é  4.515187318255313 hub em questão 7
dist order to hub é  9.863938241014022 hub em questão 7
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 7 2
route_id 317
998
     order_id  order_latitude  order_longitude      ordered_at_brt
997       998      -23.697909        -46.70916 2024-04-04 09:27:00
2024-04-04 09:27:00
tem rota aberta
dist order to order é  10.654568428837122 hub em questão 7
dist order to hub é  7.277928194017601 hub em questão 4
distancia pro pedido maior que distancia pro hub + 2 km
hub alocado 4
hub_order 7
passou aqui1
passou aqui5
route_id 318
caiu aqui tb
999
     order_id  order_latitude  order_longitude      ordered_at_brt
998       999      -23.687929       -46.676961 2024-04-04 09:30:00
2024-04-04 09:30:00
tem rota aberta
dist order to order é  3.4613273510889564 hub em questão 4
dist order to hub é  8.811918252491132 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 318
1000
     order_id  order_latitude  order_longitude      ordered_at_brt
999      1000      -23.680222       -46.651947 2024-04-04 09:38:00
2024-04-04 09:38:00
tem rota aberta
dist order to order é  2.6873703888005958 hub em questão 4
dist order to hub é  9.958162658824854 hub em questão 3
distancia pro pedido menor que distancia pro hub + 2 km
hub alocado 4 2
route_id 318

In [434]:
order_allocated_hub['route_id'].nunique()

359

In [435]:
order_allocated_hub.groupby(['route_id'])['order_id'].count().sort_values()

route_id
358    1
357    1
27     1
23     1
29     1
      ..
327    4
330    4
21     4
22     4
1      4
Name: order_id, Length: 359, dtype: int64

In [436]:
order_allocated_hub

    route_id order_id hub_id
0          1        1     13
1          2        2      4
2          3        3      1
3          1        4     13
4          4        5      9
..       ...      ...    ...
995      357      996     12
996      358      997     15
997      356      998      6
998      359      999      3
999      359     1000      3

[1000 rows x 3 columns]

# Roteirização

In [437]:
order_allocated_hub = order_allocated_hub.rename(columns={'route_id':'route_id_new_model','hub_id':'hub_id_new_model'})
order_allocated_hub

    route_id_new_model order_id hub_id_new_model
0                    1        1               13
1                    2        2                4
2                    3        3                1
3                    1        4               13
4                    4        5                9
..                 ...      ...              ...
995                357      996               12
996                358      997               15
997                356      998                6
998                359      999                3
999                359     1000                3

[1000 rows x 3 columns]

In [438]:
df_routes = hubs_with_both_routes.merge(order_allocated_hub,on='order_id')
df_routes

,order_id,order_longitude,order_latitude,ordered_at_brt,sla_hours,sla_max_delivery_time_brt,order_weight,hub_id,hub_longitude,hub_latitude,distance,route_id_moving_window,route_id_fixed_interval,route_id_new_model,hub_id_new_model
0,3,-46.607296,-23.715624,2024-04-01 00:03:37.661456595,2,2024-04-01 02:03:37.661456595,2.240132,1,-46.628005,-23.712645,2.13,1.0,1.0,3,1
1,6,-46.655737,-23.739572,2024-04-01 00:04:51.534203198,3,2024-04-01 03:04:51.534203198,5.795681,1,-46.628005,-23.712645,4.12,1.0,1.0,3,1
2,18,-46.635742,-23.711039,2024-04-01 00:21:44.105305969,3,2024-04-01 03:21:44.105305969,3.578536,1,-46.628005,-23.712645,0.81,1.0,1.0,3,1
3,27,-46.701407,-23.732633,2024-04-01 00:44:34.473570777,3,2024-04-01 03:44:34.473570777,6.392867,1,-46.628005,-23.712645,7.80,2.0,2.0,11,5
4,28,-46.651847,-23.718389,2024-04-01 00:44:39.254116151,1,2024-04-01 01:44:39.254116151,5.822331,1,-46.628005,-23.712645,2.51,2.0,2.0,11,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,927,-46.669266,-23.611914,2024-04-02 06:55:21.973160720,1,2024-04-02 07:55:21.973160720,5.893437,15,-46.659818,-23.615621,1.05,576.0,660.0,332,10
996,945,-46.666616,-23.616746,2024-04-02 07:20:38.978320443,2,2024-04-02 09:20:38.978320443,10.730955,15,-46.659818,-23.615621,0.70,576.0,661.0,335,9
997,965,-46.662569,-23.616411,2024-04-02 07:56:21.687656360,2,2024-04-02 09:56:21.687656360,8.351173,15,-46.659818,-23.615621,0.29,577.0,662.0,347,15
998,986,-46.680794,-23.634527,2024-04-02 08:31:06.218722203,3,2024-04-02 11:31:06.218722203,8.009104,15,-46.659818,-23.615621,3.00,578.0,663.0,352,9
999,997,-46.658821,-23.617170,2024-04-02 08:58:58.663961384,2,2024-04-02 10:58:58.663961384,3.636059,15,-46.659818,-23.615621,0.20,578.0,663.0,358,15

In [439]:
n_routes = len(df_routes.drop_duplicates(subset=['route_id_new_model']))
route_id_counter = 1.0
fact_route_order = pd.DataFrame(columns=['route_id_new_model', 'order_id', 
                                        'order_id_delivery_order','route_total_distance',
                                        'order_partial_distance'])

In [440]:
for _ in range(n_routes):
    #print(route_id_counter)
    one_route_df = filter_one_route(df_routes,'route_id_new_model','hub_id_new_model',n_routes,route_id_counter)
    distance_matrix = get_distance_matrix(one_route_df)
    tour, total_distance, partial_distances = solve_tsp_brute_force_without_return(distance_matrix)
    route_indexed_df = get_route_reindexed_df(one_route_df,'route_id_new_model',tour,total_distance,partial_distances)
    fact_route_order = pd.concat([fact_route_order,route_indexed_df],ignore_index=True)
    route_id_counter = route_id_counter+1

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\262065342.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  fact_route_order = pd.concat([fact_route_order,route_indexed_df],ignore_index=True)

In [441]:
fact_route_order_new = fact_route_order.copy()

In [442]:
fact_route_order_new['order_partial_distance'].sum()
#20099.992870707087

np.float64(2697.813842769152)

In [443]:
fact_route_order_new['route_id_new_model'].nunique()

359

In [444]:
fact_route_order_new

,route_id_new_model,order_id,order_id_delivery_order,route_total_distance,order_partial_distance
0,1,1,1,16.916255,3.702519
1,1,11,2,16.916255,4.184342
2,1,4,3,16.916255,2.990904
3,1,10,4,16.916255,6.038490
4,2,2,1,6.670006,3.702425
...,...,...,...,...,...
995,356,995,2,4.342395,1.404617
996,357,996,1,2.649657,2.649657
997,358,997,1,0.199961,0.199961
998,359,999,1,8.300755,3.854384
999,359,1000,2,8.300755,4.446371

# Current models

In [445]:
import itertools

df_routes_current_fixed_window = df_routes.copy()

n_routes_fixed_window = len(df_routes_current_fixed_window.drop_duplicates(subset=['route_id_fixed_interval']))
route_id_counter_fixed_window = 1.0
fact_route_order_fixed_window = pd.DataFrame(columns=['route_id_fixed_interval', 'order_id', 
                                        'order_id_delivery_order','route_total_distance',
                                        'order_partial_distance'])

In [446]:
for _ in range(n_routes_fixed_window):
    #print(route_id_counter)
    one_route_df = filter_one_route(df_routes_current_fixed_window,'route_id_fixed_interval','hub_id',n_routes_fixed_window,route_id_counter_fixed_window)
    distance_matrix = get_distance_matrix(one_route_df)
    tour, total_distance, partial_distances = solve_tsp_brute_force_without_return(distance_matrix)
    route_indexed_df = get_route_reindexed_df(one_route_df,'route_id_fixed_interval',tour,total_distance,partial_distances)
    fact_route_order_fixed_window = pd.concat([fact_route_order_fixed_window,route_indexed_df],ignore_index=True)
    route_id_counter_fixed_window = route_id_counter_fixed_window+1

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\1188770579.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  fact_route_order_fixed_window = pd.concat([fact_route_order_fixed_window,route_indexed_df],ignore_index=True)

In [447]:
fact_route_order_fixed_window

,route_id_fixed_interval,order_id,order_id_delivery_order,route_total_distance,order_partial_distance
0,1.0,3,1,6.711418,2.134217
1,1.0,18,2,6.711418,0.807629
2,1.0,6,3,6.711418,3.769572
3,2.0,28,1,7.797674,2.509842
4,2.0,27,2,7.797674,5.287832
...,...,...,...,...,...
995,660.0,927,1,1.047194,1.047194
996,661.0,945,1,0.703840,0.703840
997,662.0,965,1,0.293813,0.293813
998,663.0,997,1,3.155656,0.199961
999,663.0,986,2,3.155656,2.955695

In [448]:
df_routes_current_moving_window = df_routes.copy()
n_routes_moving_window = len(df_routes_current_moving_window.drop_duplicates(subset=['route_id_moving_window']))
route_id_counter_moving_window = 1.0
fact_route_order_moving_window = pd.DataFrame(columns=['route_id_moving_window', 'order_id', 
                                        'order_id_delivery_order','route_total_distance',
                                        'order_partial_distance'])

for _ in range(n_routes_moving_window):
    #print(route_id_counter)
    one_route_df = filter_one_route(df_routes_current_moving_window,'route_id_moving_window','hub_id',n_routes_moving_window,route_id_counter_moving_window)
    distance_matrix = get_distance_matrix(one_route_df)
    tour, total_distance, partial_distances = solve_tsp_brute_force_without_return(distance_matrix)
    route_indexed_df = get_route_reindexed_df(one_route_df,'route_id_moving_window',tour,total_distance,partial_distances)
    fact_route_order_moving_window = pd.concat([fact_route_order_moving_window,route_indexed_df],ignore_index=True)
    route_id_counter_moving_window = route_id_counter_moving_window+1

C:\Users\EduardoMontez\AppData\Local\Temp\ipykernel_12808\1807010926.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  fact_route_order_moving_window = pd.concat([fact_route_order_moving_window,route_indexed_df],ignore_index=True)

In [449]:
fact_route_order_moving_window

,route_id_moving_window,order_id,order_id_delivery_order,route_total_distance,order_partial_distance
0,1.0,3,1,6.711418,2.134217
1,1.0,18,2,6.711418,0.807629
2,1.0,6,3,6.711418,3.769572
3,2.0,28,1,7.797674,2.509842
4,2.0,27,2,7.797674,5.287832
...,...,...,...,...,...
995,576.0,945,1,1.305139,0.703840
996,576.0,927,2,1.305139,0.601298
997,577.0,965,1,0.293813,0.293813
998,578.0,997,1,3.155656,0.199961
999,578.0,986,2,3.155656,2.955695

In [450]:
fator_correct = 1.5
percorrido_real_janelas_fixas = fact_route_order_fixed_window['order_partial_distance'].sum()*fator_correct
percorrido_real_janelas_moveis = fact_route_order_moving_window['order_partial_distance'].sum()*fator_correct
percorrido_real_rotas_abertas = fact_route_order_new['order_partial_distance'].sum()*fator_correct

percorrido_real_janelas_fixas,percorrido_real_janelas_moveis,percorrido_real_rotas_abertas

(np.float64(3861.3222610110715),
 np.float64(3753.0023583570837),
 np.float64(4046.720764153728))

In [451]:
custo_rota = 6
custo_km_add = 1.15
custo_parada = 1

In [452]:
n_rotas_janela_fixa = fact_route_order_fixed_window['route_id_fixed_interval'].nunique()
n_rotas_janela_movel = fact_route_order_moving_window['route_id_moving_window'].nunique()
n_rotas_rotas_aberto = fact_route_order_new['route_id_new_model'].nunique()
n_pedidos = fact_route_order['order_id'].nunique()

In [453]:
custo_janela_fixa = custo_rota*n_rotas_janela_fixa+(percorrido_real_janelas_fixas-n_rotas_janela_fixa)*custo_km_add+(n_pedidos-n_rotas_janela_fixa)*custo_parada
custo_janela_movel = custo_rota*n_rotas_janela_movel+(percorrido_real_janelas_moveis-n_rotas_janela_movel)*custo_km_add+(n_pedidos-n_rotas_janela_movel)*custo_parada
custo_rotas_aberto = custo_rota*n_rotas_rotas_aberto+(percorrido_real_rotas_abertas-n_rotas_rotas_aberto)*custo_km_add+(n_pedidos-n_rotas_rotas_aberto)*custo_parada

In [454]:
custo_janela_fixa,custo_janela_movel,custo_rotas_aberto

(np.float64(7993.070600162731),
 np.float64(7541.252712110646),
 np.float64(7035.878878776787))

In [455]:
print("p.p de redução de custo do modelo de janelas fixas para janelas móveis de ",round((custo_janela_movel - custo_janela_fixa)/custo_janela_fixa*100,2))
print("p.p de redução de custo do modelo de janelas fixas para rotas em aberto de ",round((custo_rotas_aberto - custo_janela_fixa)/custo_janela_fixa*100,2))

p.p de redução de custo do modelo de janelas fixas para janelas móveis de  -5.65
p.p de redução de custo do modelo de janelas fixas para rotas em aberto de  -11.98

In [456]:
fact_route_order_fixed_window

,route_id_fixed_interval,order_id,order_id_delivery_order,route_total_distance,order_partial_distance
0,1.0,3,1,6.711418,2.134217
1,1.0,18,2,6.711418,0.807629
2,1.0,6,3,6.711418,3.769572
3,2.0,28,1,7.797674,2.509842
4,2.0,27,2,7.797674,5.287832
...,...,...,...,...,...
995,660.0,927,1,1.047194,1.047194
996,661.0,945,1,0.703840,0.703840
997,662.0,965,1,0.293813,0.293813
998,663.0,997,1,3.155656,0.199961
999,663.0,986,2,3.155656,2.955695

In [457]:
fact_route_order_fixed_window['order_id'] = fact_route_order_fixed_window['order_id'].astype(int)
fact_route_order_fixed_window = fact_route_order_fixed_window.rename(columns={'order_id_delivery_order':'order_id_delivery_order_fixed_window','order_partial_distance':'order_partial_distance_fixed_window'})
fact_route_order_moving_window['order_id'] = fact_route_order_moving_window['order_id'].astype(int)
fact_route_order_moving_window = fact_route_order_moving_window.rename(columns={'order_id_delivery_order':'order_id_delivery_order_moving_window','order_partial_distance':'order_partial_distance_moving_window'})

df_full = hubs_with_both_routes\
    .merge(fact_route_order_fixed_window[['order_id','order_id_delivery_order_fixed_window','order_partial_distance_fixed_window']],on=['order_id'],how='left')\
    .merge(fact_route_order_moving_window[['order_id','order_id_delivery_order_moving_window','order_partial_distance_moving_window']],on=['order_id'],how='left')
def next_fixed_window(dt):
    minute = dt.minute
    if minute < 30:
        return dt.replace(minute=30, second=0, microsecond=0)
    else:
        return (dt + timedelta(hours=1)).replace(minute=0, second=0, microsecond=0)

df_full['adensing_is_finished_fixed_window'] = df_full['ordered_at_brt'].apply(next_fixed_window)
df_full['time_adensing_fixed_window'] = (df_full['adensing_is_finished_fixed_window'] - df_full['ordered_at_brt']).dt.total_seconds() / 60

# Time to dispatch moving window is always 30 minutes
df_full['adensing_is_finished_moving_window'] = (
    df_full.groupby('route_id_moving_window')['ordered_at_brt']
    .transform('min') + pd.Timedelta(minutes=30)
)

df_full['time_adensing_moving_window'] = (
    df_full['adensing_is_finished_moving_window'] - df_full['ordered_at_brt']
).dt.total_seconds() / 60

df_full['time_to_dispatch_order_fixed_window'] = generate_normal_distribution(
    mean=15, std_dev=5, n=len(df_full), min_val=1
)

df_full['time_to_dispatch_order_moving_window'] = df_full['time_to_dispatch_order_fixed_window']

df_full

,order_id,order_longitude,order_latitude,ordered_at_brt,sla_hours,sla_max_delivery_time_brt,order_weight,hub_id,hub_longitude,hub_latitude,...,order_id_delivery_order_fixed_window,order_partial_distance_fixed_window,order_id_delivery_order_moving_window,order_partial_distance_moving_window,adensing_is_finished_fixed_window,time_adensing_fixed_window,adensing_is_finished_moving_window,time_adensing_moving_window,time_to_dispatch_order_fixed_window,time_to_dispatch_order_moving_window
0,3,-46.607296,-23.715624,2024-04-01 00:03:37.661456595,2,2024-04-01 02:03:37.661456595,2.240132,1,-46.628005,-23.712645,...,1,2.134217,1,2.134217,2024-04-01 00:30:00.000000595,26.372309,2024-04-01 00:33:37.661456595,30.000000,16.225002,16.225002
1,6,-46.655737,-23.739572,2024-04-01 00:04:51.534203198,3,2024-04-01 03:04:51.534203198,5.795681,1,-46.628005,-23.712645,...,3,3.769572,3,3.769572,2024-04-01 00:30:00.000000198,25.141097,2024-04-01 00:33:37.661456595,28.768788,20.251762,20.251762
2,18,-46.635742,-23.711039,2024-04-01 00:21:44.105305969,3,2024-04-01 03:21:44.105305969,3.578536,1,-46.628005,-23.712645,...,2,0.807629,2,0.807629,2024-04-01 00:30:00.000000969,8.264912,2024-04-01 00:33:37.661456595,11.892603,14.514803,14.514803
3,27,-46.701407,-23.732633,2024-04-01 00:44:34.473570777,3,2024-04-01 03:44:34.473570777,6.392867,1,-46.628005,-23.712645,...,2,5.287832,2,5.287832,2024-04-01 01:00:00.000000777,15.425441,2024-04-01 01:14:34.473570777,30.000000,7.120926,7.120926
4,28,-46.651847,-23.718389,2024-04-01 00:44:39.254116151,1,2024-04-01 01:44:39.254116151,5.822331,1,-46.628005,-23.712645,...,1,2.509842,1,2.509842,2024-04-01 01:00:00.000000151,15.345765,2024-04-01 01:14:34.473570777,29.920324,16.605085,16.605085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,927,-46.669266,-23.611914,2024-04-02 06:55:21.973160720,1,2024-04-02 07:55:21.973160720,5.893437,15,-46.659818,-23.615621,...,1,1.047194,2,0.601298,2024-04-02 07:00:00.000000720,4.633781,2024-04-02 07:25:21.973160720,30.000000,16.806014,16.806014
996,945,-46.666616,-23.616746,2024-04-02 07:20:38.978320443,2,2024-04-02 09:20:38.978320443,10.730955,15,-46.659818,-23.615621,...,1,0.703840,1,0.703840,2024-04-02 07:30:00.000000443,9.350361,2024-04-02 07:25:21.973160720,4.716581,21.739928,21.739928
997,965,-46.662569,-23.616411,2024-04-02 07:56:21.687656360,2,2024-04-02 09:56:21.687656360,8.351173,15,-46.659818,-23.615621,...,1,0.293813,1,0.293813,2024-04-02 08:00:00.000000360,3.638539,2024-04-02 08:26:21.687656360,30.000000,10.114681,10.114681
998,986,-46.680794,-23.634527,2024-04-02 08:31:06.218722203,3,2024-04-02 11:31:06.218722203,8.009104,15,-46.659818,-23.615621,...,2,2.955695,2,2.955695,2024-04-02 09:00:00.000000203,28.896355,2024-04-02 09:01:06.218722203,30.000000,9.650155,9.650155
999,997,-46.658821,-23.617170,2024-04-02 08:58:58.663961384,2,2024-04-02 10:58:58.663961384,3.636059,15,-46.659818,-23.615621,...,1,0.199961,1,0.199961,2024-04-02 09:00:00.000000384,1.022267,2024-04-02 09:01:06.218722203,2.125913,11.507381,11.507381

In [458]:
# Função generalista para calcular tempo em rota com base em parâmetros de coluna
def calcular_time_in_route(df, route_col, order_col, distance_col, output_col, seed=1):
    rng = np.random.default_rng(seed)  # gerador com seed fixa
    df_sorted = df.sort_values(by=[route_col, order_col]).copy()
    df_sorted[output_col] = 0.0

    for route_id, group in df_sorted.groupby(route_col):
        total_time = 0
        times = []
        for idx, row in group.iterrows():
            dist = row[distance_col]
            travel_time = rng.normal(loc=4 * dist, scale=2 * dist)
            travel_time = max(travel_time, 1)  # mínimo de 1 minuto
            stop_delay = 5 * (row[order_col] - 1)
            total_time += travel_time + (5 if row[order_col] > 1 else 0)
            times.append(total_time)
        df_sorted.loc[group.index, output_col] = times

    return df_sorted[output_col]


# Aplicar a função para ambas as estratégias
df_full['time_in_route_moving'] = calcular_time_in_route(
    df_full,
    route_col='route_id_moving_window',
    order_col='order_id_delivery_order_moving_window',
    distance_col='order_partial_distance_moving_window',
    output_col='time_in_route_moving',
    seed=seed
)

df_full['time_in_route_fixed'] = calcular_time_in_route(
    df_full,
    route_col='route_id_fixed_interval',
    order_col='order_id_delivery_order_fixed_window',
    distance_col='order_partial_distance_fixed_window',
    output_col='time_in_route_fixed',
    seed=seed
)

In [459]:
# Calcular horários de entrega para janela fixa e janela móvel
df_full['delivered_at_brt_fixed_window'] = (
    df_full['ordered_at_brt'] +
    pd.to_timedelta(df_full['time_adensing_fixed_window'], unit='m')+
    pd.to_timedelta(df_full['time_to_dispatch_order_fixed_window'], unit='m')+
    pd.to_timedelta(df_full['time_in_route_fixed'], unit='m')
)

df_full['delivered_at_brt_moving_window'] = (
    df_full['ordered_at_brt'] +
    pd.to_timedelta(df_full['time_adensing_moving_window'], unit='m')+
    pd.to_timedelta(df_full['time_to_dispatch_order_moving_window'], unit='m')+
    pd.to_timedelta(df_full['time_in_route_moving'], unit='m')
)

# Calcular se o SLA foi cumprido em cada caso
df_full['total_time_to_fullfill_customer_fixed'] = df_full['time_adensing_fixed_window'] + df_full['time_to_dispatch_order_fixed_window'] + df_full['time_in_route_fixed']
df_full['total_time_to_fullfill_customer_moving'] = df_full['time_adensing_moving_window'] + df_full['time_to_dispatch_order_moving_window'] + df_full['time_in_route_moving']

df_full['achieve_sla_fixed'] = df_full['delivered_at_brt_fixed_window'] < df_full['sla_max_delivery_time_brt']
df_full['achieve_sla_moving'] = df_full['delivered_at_brt_moving_window'] < df_full['sla_max_delivery_time_brt']
df_full

,order_id,order_longitude,order_latitude,ordered_at_brt,sla_hours,sla_max_delivery_time_brt,order_weight,hub_id,hub_longitude,hub_latitude,...,time_to_dispatch_order_fixed_window,time_to_dispatch_order_moving_window,time_in_route_moving,time_in_route_fixed,delivered_at_brt_fixed_window,delivered_at_brt_moving_window,total_time_to_fullfill_customer_fixed,total_time_to_fullfill_customer_moving,achieve_sla_fixed,achieve_sla_moving
0,3,-46.607296,-23.715624,2024-04-01 00:03:37.661456595,2,2024-04-01 02:03:37.661456595,2.240132,1,-46.628005,-23.712645,...,16.225002,16.225002,10.011973,10.011973,2024-04-01 00:56:14.218545315,2024-04-01 00:59:51.880001313,52.609285,56.236976,True,True
1,6,-46.655737,-23.739572,2024-04-01 00:04:51.534203198,3,2024-04-01 03:04:51.534203198,5.795681,1,-46.628005,-23.712645,...,20.251762,20.251762,42.139112,42.139112,2024-04-01 01:32:23.452423784,2024-04-01 01:36:01.113880178,87.531970,91.159661,True,True
2,18,-46.635742,-23.711039,2024-04-01 00:21:44.105305969,3,2024-04-01 03:21:44.105305969,3.578536,1,-46.628005,-23.712645,...,14.514803,14.514803,19.569613,19.569613,2024-04-01 01:04:05.064990119,2024-04-01 01:07:42.726445746,42.349328,45.977019,True,True
3,27,-46.701407,-23.732633,2024-04-01 00:44:34.473570777,3,2024-04-01 03:44:34.473570777,6.392867,1,-46.628005,-23.712645,...,7.120926,7.120926,39.223999,39.223999,2024-04-01 01:46:20.695485261,2024-04-01 02:00:55.169055261,61.770365,76.344925,True,True
4,28,-46.651847,-23.718389,2024-04-01 00:44:39.254116151,1,2024-04-01 01:44:39.254116151,5.822331,1,-46.628005,-23.712645,...,16.605085,16.605085,3.497930,3.497930,2024-04-01 01:20:06.180942185,2024-04-01 01:34:40.654512815,35.448780,50.023340,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,927,-46.669266,-23.611914,2024-04-02 06:55:21.973160720,1,2024-04-02 07:55:21.973160720,5.893437,15,-46.659818,-23.615621,...,16.806014,16.806014,8.338460,3.479230,2024-04-02 07:20:17.114611532,2024-04-02 07:50:30.641592188,24.919024,55.144474,True,True
996,945,-46.666616,-23.616746,2024-04-02 07:20:38.978320443,2,2024-04-02 09:20:38.978320443,10.730955,15,-46.659818,-23.615621,...,21.739928,21.739928,2.338460,1.000000,2024-04-02 07:52:44.395677591,2024-04-02 07:49:26.676434883,32.090289,28.794969,True,True
997,965,-46.662569,-23.616411,2024-04-02 07:56:21.687656360,2,2024-04-02 09:56:21.687656360,8.351173,15,-46.659818,-23.615621,...,10.114681,10.114681,1.130477,1.130477,2024-04-02 08:11:14.709473444,2024-04-02 08:37:36.397129442,14.883697,41.245158,True,True
998,986,-46.680794,-23.634527,2024-04-02 08:31:06.218722203,3,2024-04-02 11:31:06.218722203,8.009104,15,-46.659818,-23.615621,...,9.650155,9.650155,19.448153,19.448153,2024-04-02 09:29:05.898462765,2024-04-02 09:30:12.117184767,57.994662,59.098308,True,True
999,997,-46.658821,-23.617170,2024-04-02 08:58:58.663961384,2,2024-04-02 10:58:58.663961384,3.636059,15,-46.659818,-23.615621,...,11.507381,11.507381,1.000000,1.000000,2024-04-02 09:12:30.442879244,2024-04-02 09:13:36.661601060,13.529649,14.633294,True,True

In [460]:
df_full['achieve_sla_moving'].sum()/df_full['order_id'].count(),df_full['achieve_sla_fixed'].sum()/df_full['order_id'].count()

(np.float64(0.912), np.float64(0.942))

In [461]:
df_full['total_time_to_fullfill_customer_moving'].mean(),df_full['total_time_to_fullfill_customer_fixed'].mean()

(np.float64(56.458449478234066), np.float64(45.504215929130716))

In [318]:
unique_hubs['icon']='home'

In [248]:
unique_hubs.to_csv('hubs_simula.csv')

In [249]:
df_orders.to_csv('pedidos_simula.csv')